kubernetes/org

- OWNERS_ALIASES
- kubernetes/org.yaml
- kubernetes/sig-contributor-experience/OWNERS
- kubernetes/sig-contributor-experience/org.yaml
This updates the meta org as follows:
- Pull a copy of the OWNERS_ALIASES from k/community
- Updates membership as of 7/16
- Adds a folder of team members for sig-contributor-experience. Example of what it would look like to have sig-responsible teams.
> Update meta org

- .github/ISSUE_TEMPLATE/general-support.md
- .github/ISSUE_TEMPLATE/integrations.md
- .github/ISSUE_TEMPLATE/membership.md
- .github/ISSUE_TEMPLATE/repo-archive.md
- .github/ISSUE_TEMPLATE/repo-create.md
This adds issue templates to allow users to submit common kinds of requests.
> Add issue templates

- .github/ISSUE_TEMPLATE/membership.md
In the current issue template for membership, the last few points are not displayed in "List of contributions": https://github.com/kubernetes/org/blob/master/.github/ISSUE_TEMPLATE/membership.md#list-of-contributions-to-the-kubernetes-project. I think it's because the points are listed in angle brackets (`<Issues responded to>`), which markdown treats as html.
/assign cblecker
> ISSUE_TEMPLATE/membership: fix markdown rendering

- config/kubernetes-incubator/org.yaml
There were some users in kubernetes/org#16 that didn't end up getting PR'd and didn't accept their invite right away. This adds them to the config so they don't get deleted as soon as they accept their invite.
> Add additional users to kubernetes-incubator

- config/config_test.go
/assign @cblecker @spiffxp @nikhiljindal 
a) Do we want to enforce this (we already enforce the absence of duplicates)
b) Do we want to enforce case sensitive sorting?
> Require org members to be sorted

- .github/ISSUE_TEMPLATE/repo-create.md
These are questions I find myself guessing the answer to or
having to ask as followup requests to the initial create
I'm also adding "staging" as an option since we tend to
create a bunch of those and they have slightly different
requirements from new or migrated repos
/cc @cblecker @calebamiles
Since you've also handled repo creation in the past
> Update the repo-create template with more questions

- .github/ISSUE_TEMPLATE/general-support.md
- .github/ISSUE_TEMPLATE/integrations.md
- .github/ISSUE_TEMPLATE/membership.md
- .github/ISSUE_TEMPLATE/repo-archive.md
- .github/ISSUE_TEMPLATE/repo-create.md
GitHub now allows you to specify titles and labels by default as a part of the template. Update our templates to use this.
ref: https://help.github.com/articles/creating-issue-templates-for-your-repository/
> Update GitHub template metadata

- config/kubernetes-sigs/org.yaml
- Add @adelina-t to kubernetes-sigs so she can be given permissions to kubernetes-sigs/windows-testing.
- Add @krousey and @kris-nova to kubernetes-sigs so they can be given permissions to kubernetes-sigs/cluster-api via a group (as opposed to outside collab access)
All three are members of @kubernetes.
> Add members to kubernetes-sigs

- OWNERS_ALIASES
- admin/BUILD.bazel
- config/BUILD.bazel
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-api-machinery/OWNERS
- config/kubernetes/sig-api-machinery/teams.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
🙊!
This might actually work.
fixes #336
/assign @fejta @spiffxp 
/hold
> Enable team management for peribolos

- config/kubernetes/org.yaml
Aaron added these two members to the team yesterday. This syncs the config for them.
/assign @spiffxp 
/approve
> Add members to cncf-conformance-wg

- Gopkg.lock
- config/BUILD.bazel
- config/config_test.go
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
This would be useful to fail early if someone who is added as a team maintainer or member is not an org member. See https://github.com/kubernetes/org/pull/346#pullrequestreview-191923294 for an example.
This PR also validates:
- a user is not mentioned as both an org admin and org member
- a user is not mentioned as both a team maintainer and member
- no duplicates exist in the list of team maintainers and members
/assign @cblecker @fejta
> Add a test to check if team members are org members

- config/config_test.go
- config/kubernetes/sig-release/teams.yaml
Org admins are always listed as team maintainers in the API. This ensures that an org admin is never listed as just a member.. they can either be a maintainer, or not on the team at all.
> Add test to ensure that org admins are never team members

- config/kubernetes/sig-release/teams.yaml
- Add dims and liggitt as SIG Release-designated milestone maintainers
- Prune `kubernetes-release-managers` team
- Add 1.14 RT to `sig-release` team
- Prune `sig-release-admins`
Closes: kubernetes/sig-release#353
/assign @calebamiles @tpepper @cblecker
> Update SIG Release teams

- config/config_test.go
The `List()` method creates a sorted list. :neutral_face: 
https://github.com/kubernetes/org/blob/45f511fb4217606e29cb01fa3f27e91d194cb5e5/config/config_test.go#L83-L91
This was introduced in https://github.com/kubernetes/org/pull/350, so this PR reverts the change to the `isSorted` function.
/kind bug
/assign @cblecker @fejta
> Fix isSorted function in tests

- config/kubernetes/org.yaml
Following https://github.com/kubernetes/org/pull/353 as an example, I would like to help in sig-instrumentation. Hence being added here would be great.
Let me know if this is the wrong way to approach this.
//CC @brancz
> config/kubernetes: Add mxinden to sig-instrumentation

- config/kubernetes/sig-release/teams.yaml
As 1.14 enhancements lead I think I should be able to add milestones to issues in the enhancements repo 
@spiffxp @justaugustus lmk if this isn't something I should have access to do
> add claurence to milestone-maintainers

- config/kubernetes/sig-release/teams.yaml
Add 1.14 release team members to the kubernetes/milestone-maintainers team
- I expect that at a minimum everyone in the 1.14 release team roles should have /milestone privileges.
- Role shadows I am willing to let roles decide for themselves.
Add 1.14 release team lead + shadows to the kubernetes/kubernetes-release-managers team:
- solely for "just in case" purposes, and you can totally convince me we should be revoked down the line, just following the description of the team
- provide coverage in case branch manager doesn't have availability
Also, having just gone through the exercise of doing a commit per user, I did not enjoy it. I know that's the process we use for adjusting org membership, but it doesn't feel like it scales very well. But I did it this time just to try it out
> Add 1.14 release team members to sig-release github teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-azure/OWNERS
- config/kubernetes-sigs/sig-azure/teams.yaml
- config/kubernetes/sig-azure/teams.yaml
Fixes: kubernetes-sigs/cluster-api-provider-azure#48
/assign @cblecker @dstrebel @khenidak @feiskyer 
For visibility:
/cc @lachie83 @tariq1890 @soggiest
> Update SIG Azure teams

- config/kubernetes/org.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
This PR also moves the `community-maintainers` and `community-admins` team from `org.yaml` to `sig-contributor-experience/teams.yaml`.
I wish to be added to this team so that I can help manage the [contribex project board](https://github.com/orgs/kubernetes/projects/1). I am a technical lead for sig-contribex.
/cc @cblecker @parispittman @Phillels 
> Add nikhita to community-maintainers team

- config/kubernetes/sig-cli/teams.yaml
This updates sig-cli teams based on who's currently leading the SIG. 
/assign @cblecker 
/cc @pwittrock @seans3
> Update sig-cli teams

- OWNERS
- admin/BUILD.bazel
- config/kubernetes-client/OWNERS
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/OWNERS
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/OWNERS
- config/kubernetes-incubator/org.yaml
- config/kubernetes-retired/OWNERS
- config/kubernetes-retired/org.yaml
- config/kubernetes-sigs/OWNERS
- config/kubernetes-sigs/org.yaml
- config/kubernetes/OWNERS
- config/kubernetes/org.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
- config/kubernetes/sig-pm/teams.yaml
- config/kubernetes/sig-release/teams.yaml
awaiting steering committee approval, ref: https://github.com/kubernetes/community/pull/3148
/hold
/assign @spiffxp
> Promote nikhita to GitHub Administration Team

- config/kubernetes/org.yaml
Updating groups to reflect our [OWNER_ALIASES](https://github.com/kubernetes/dashboard/blob/master/OWNERS_ALIASES) accurately and the [sigs.yaml ](https://github.com/kubernetes/community/blob/master/sigs.yaml#L1989) changes. 
Let me know if I did something wrong. :) 
/sig ui
> Update SIG-UI (Dashboard) groups 

- config/kubernetes/org.yaml
I wanted to explictly at-mention the code of conduct committee in https://github.com/kubernetes/community/pull/3194 but found that there was no such team.
We already have a team for the steering committee (which is pretty useful for at-mentioning). I think it'd be useful to have this team as well.
Members of the team are the members of the CoC mentioned here: https://github.com/kubernetes/community/tree/master/committee-code-of-conduct
/cc @Bradamant3 @carolynvs @eparis @jdumars @parispittman
> Add code-of-conduct-committee team

- config/kubernetes-sigs/org.yaml
I'm already a member of the Kubernetes org.
It would be handy to be able to express opinions in e.g. kubernetes-sigs/kind without the bot [yelling at everyone involved](https://github.com/kubernetes-sigs/kind/pull/285).
> Add Katharine to kubernetes-sigs

- config/kubernetes-csi/org.yaml
For CSI development we need to tag all developers in PRs and issues. IMO, we don't need separate csi-pr-reviews and csi-bugs teams, everybody does everything, `@csi-misc` in any `kubernetes-csi` repo should be enough.
Do we need the same team in `kubernetes/` repos?
/hold
for discussion in sig-storage first.
@chakri-nelluri @davidz627 @gnufied @lpabon @pohly @rootfs @sbezverk @vladimirvivien @xing-yang @saad-ali  @childsb , PTAL. Feel free to suggest other members or remove yourself.
> Add csi-misc team to tag all developers

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
I incorrect added @jichenjc to the @kubernetes-sigs org instead of @kubernetes org in PR #400.
This PR reverts the commit: https://github.com/kubernetes/org/pull/400/commits/492582a6d75a4442a0c4e71218f6141686bdeed1 and correctly adds @jichenjc to the @kubernetes org. 
I double checked that the other membership requests in that PR were processed correctly. 
ref: https://github.com/kubernetes/org/issues/389#issuecomment-463019923
Sorry about that @jichenjc :(
> Correct jichenjc membership

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-api-machinery/teams.yaml
Follow up of #505 
https://github.com/kubernetes-sigs/structured-merge-diff and https://github.com/kubernetes-sigs/yaml are apimachinery subprojects.
Ref: https://github.com/kubernetes/community/tree/master/sig-api-machinery#subprojects
> Move structured-merge-diff and yaml teams to api-machinery dir

- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/org.yaml
- config/kubernetes-retired/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
The bot formerly known as k8s-merge-robot is going to do more things in more orgs
ref: https://github.com/kubernetes/test-infra/issues/11402
> Add k8s-github-robot alongside k8s-ci-robot in all orgs

- config/kubernetes-csi/org.yaml
Adds teams for providing admin access and write access for https://github.com/kubernetes/org/issues/486.
> Add teams for kubernetes-csi/csi-driver-image-populator

- config/kubernetes/sig-pm/teams.yaml
This cleans up the enhancements-maintainers team to only include SIG PM maintainers.
Ref: https://github.com/kubernetes/enhancements/issues/590#issuecomment-464413261
/assign @calebamiles @idvoretskyi @jdumars
> sig-pm: Update `enhancements-maintainers` team

- config/kubernetes-csi/org.yaml
Ref: https://github.com/kubernetes/org/issues/519
Currently, @lpabon has direct collaborator admin access and @saad-ali has direct collaborator write access to https://github.com/kubernetes-csi/kubernetes-csi.github.io.
This PR creates a team consisting of @lpabon and @saad-ali to provide admin access to the repo.
Once this gets merged, the postsubmit runs and the GitHub team gets created, I'll remove direct collaborator access and give the team admin access.
> Add team for kubernetes-csi.github.io

- config/kubernetes/sig-release/teams.yaml
Add note about team now having write access to k/enhancements
ref: https://github.com/kubernetes/enhancements/issues/590#issuecomment-466560650
/assign @spiffxp @calebamiles @tpepper
> sig-release: Update kubernetes-milestone-maintainers description

- config/kubernetes/sig-release/teams.yaml
All CI signal team members create issues for failing tests and flakes on the sig-release dashboards. Adding them as milestone maintainers allows them to assign the respective issues to the 1.14 release milestone, which means we can be more effective with keeping track of fixes expected to land by the release date.
cc @alejandrox1 @smourapina @mortent @kacole2 
/assign @spiffxp
> Add 1.14 CI Signal team as milestone maintainers

- config/kubernetes/sig-testing/teams.yaml
ref: https://github.com/kubernetes/test-infra/issues/11465
These were individual commits, but probably not needed, so:
- Drop test-infra-reviewers in favor of sig-testing-pr-reviews
- Demote all sig-testing team maintainers to members
- ... except those who are GitHub Owners because GitHub, apparently
- Add akutz
- Fix Katharine's case
- Update team descriptions
- test-infra-admins ~= kubernetes/test-infra/OWNERS
- test-infra-maintainers ~= kubernetes/test-infra/OWNERS
- sig-testing-pr-reviews contains test-infra-admins
> prune sig-testing teams

- config/kubernetes/sig-cloud-provider/teams.yaml
Admins are based on people in the [OWNERS](https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/master/OWNERS) file.
> add admins for cloud-provider-alibaba repo

- config/kubernetes/sig-release/teams.yaml
As CI Signal team member, I need to have the ability to assign issues created to the 1.14 release milestone, and so will need to be added as milestone maintainer.
cc @mariantalla
> Add smourapina (CI Signal 1.14) as milestone maintainer

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-release/teams.yaml
ref: https://github.com/kubernetes/org/issues/551
All members I'm adding to kubernetes-sigs to satisfy the repo migration request are already members of kubernetes, so I opted to handle in this PR instead of asking for issues to be filed
> Setup teams and org membership for k8s-container-image-promoter

- .gitignore
- config/kubernetes/sig-docs/teams.yaml
PR is adding the Italian localization teams. The members are already in the appropriate OWNERS files => [kubernetes/website/OWNERS_ALIASES](https://github.com/kubernetes/website/blob/12036aa614ff0e4ac5bdfce102642b7e5e4cb2b5/OWNERS_ALIASES#L166)
Next to that some small improvements
- Ignoring `.idea` files when opening the project with a Jetbrains editor
- Swapped `sig-docs-fr-reviews` and `sig-docs-fr-owners` to follow the rest of the file: first owners, then review teams
- Fixed indentation for `sig-docs-ko-reviews`
> Add sig docs it teams and update fr teams

- config/kubernetes/sig-release/teams.yaml
Fixes https://github.com/kubernetes/org/issues/564
/assign @justaugustus @spiffxp 
/hold
I'd like a lgtm from a SIG Release lead or the release team lead
@soggiest your GitHub username in https://github.com/kubernetes/sig-release/blob/master/releases/release-1.14/release_team.md is slightly incorrect :P
> Add soggiest to milestone-maintainers team

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-azure/teams.yaml
ref: #344
Only adding @andyzhangx, as he's the only one listed in the repo OWNERS file. Additional manual write access can be provided at a later time. Once the repo moves over, using the bots and labels to merge things is the standardized way to do thing
> Add teams for Azure CSI repo migrations

- config/kubernetes/sig-release/teams.yaml
Adds a team so that we can use it to cc folks for reviews/issues related to the publishing-bot.
Ref: https://github.com/kubernetes/publishing-bot/blob/master/OWNERS
/cc @sttts @dims @mfojtik @caesarxuchao
> Add publishing-bot-reviewers team

- config/kubernetes-sigs/org.yaml
Adding Andy Goldstein (ncdc) to the `cluster-api-maintainers` and `cluster-api-provider-aws-maintainers` groups for `kubernetes-sigs` to allow for issue management and milestone management ACLs for the `cluster-api` and `cluster-api-provider-aws` projects.
> add ncdc to cluster-api-maintaners and cluster-api-provider-aws-maintainers

- config/kubernetes-csi/org.yaml
Fixes https://github.com/kubernetes/org/issues/571
> Add brad as resizer repo admin

- config/kubernetes-sigs/org.yaml
Add @randomvariable to cluster-api-provider-aws-maintainers to be able to do Milestone management
> Add randomvariable to cluster-api-provider-aws-maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-auth/OWNERS
- config/kubernetes-sigs/sig-auth/teams.yaml
Ref: https://github.com/kubernetes/org/issues/528
Adds teams to provide write access and admin access to https://github.com/kubernetes-sigs/multi-tenancy.
> Add teams for k-sigs/multi-tenancy

- config/config_test.go
- config/kubernetes-incubator/org.yaml
Peribolos [fails](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-org-peribolos/201) with a 403 when it tries to update memberships for certain teams in kubernetes-incubator. This temporarily unblocks peribolos so other changes can be synced.
```
{"client":"github","component":"peribolos","level":"info","msg":"UpdateTeamMembership(2113629, euank, false)","time":"2019-03-11T03:17:04Z"}
{"component":"peribolos","error":"is the account using at least one of the following oauth scopes?: admin:org, repo","level":"warning","msg":"UpdateTeamMembership(2113629, euank, false) failed","time":"2019-03-11T03:17:07Z"}
{"component":"peribolos","level":"fatal","msg":"Configuration failed: failed to configure kubernetes-incubator teams: failed to update maintainers-rktlet members: 1 errors: [is …
```
> Revert migrate maintainers to members for kubernetes-incubator

- config/kubernetes/sig-testing/teams.yaml
Create a dummy team to test prow project plugin to add issues/PRs to github projects (https://github.com/kubernetes/test-infra/pull/10982). No ACL is needed. 
FYI @stevekuznetsov @spiffxp
> Add dummy team for testing prow project plugin

- OWNERS_ALIASES
- config/kubernetes/wg-lts/OWNERS
- config/kubernetes/wg-lts/teams.yaml
Added the WG_LTS chairs/organizers to the leads alias
https://github.com/kubernetes/community/tree/master/wg-lts
> Add wg-lts leads owner alias and wg-lts team

- config/kubernetes-sigs/sig-auth/teams.yaml
@tashimi (Tasha Drew) from VMware is lead of kubernetes-wg-multitenancy.
> Add tashimi to multi-tenancy sub-project teams

- config/kubernetes-incubator/org.yaml
The [GitHub Admin team](https://github.com/kubernetes/community/tree/master/github-management#github-administration-team) is responsible for having admin privileges across all Kubernetes orgs.
/assign @idvoretskyi @spiffxp
> Remove owners team in kubernetes-incubator org

- config/kubernetes/sig-pm/teams.yaml
- Following discussions at Open Source Leadership Summit this week with @jdumars and I, @lachie83 has stepped up to help us out with SIG PM. Adding him to the relevant teams.
- @idvoretskyi has been working with SIG ContribEx on their project mgmt needs (https://github.com/kubernetes/community/issues/3079). Adding him to `project-board-maintainers`.
- @mattfarina has offered his assistance in grooming (https://github.com/kubernetes/community/issues/3267#issuecomment-466419304). Adding him to `project-board-maintainers`.
/assign @calebamiles @idvoretskyi @jdumars
> sig-pm: Update teams

- config/kubernetes-client/org.yaml
Created the missing teams for the kubernetes-client repos (#615). 
Added a description to the python-base-admins team as well.
@nikhita can you assign the repository permissions to the teams?
@brendandburns is this sufficient for you to setup the CI/CD pipelines?
> Add client go teams

- config/kubernetes/sig-contributor-experience/teams.yaml
For https://github.com/kubernetes/community/issues/3443
This team will have the power to use the `/milestone` command in the community repo. Membership in this team requires an entry in an OWNERS file (reviewer or approver) for a contribex subproject in the community repo.
Once this merges and the team is created, I'll add the team here: https://github.com/kubernetes/test-infra/blob/b9778912cf2e162c9f2b005cdff2a48be7f4a593/prow/plugins.yaml#L214.
/hold
/assign @parispittman
> Add community-milestone-maintainers team

- config/kubernetes/sig-release/teams.yaml
we had a discussion today about this in the kubeadm office hours meeting and i got approval from a SIG chair (@timothysc) and a tech lead (@fabriziopandini).
i have read the details about the milestone maintainers role:
https://github.com/kubernetes/sig-release/blob/master/release-team/README.md#milestone-maintainers
this is a primary "super power" i'm interested in, because our k/e items descriptions need update:
> Milestone maintainers also have write access to kubernetes/enhancements, which allows them to keep enhancement tracking issue descriptions up-to-date.
---
> for SIGs: Request approval from a SIG Chair or Technical Lead
/assign @timothysc @fabriziopandini 
> Once your request is approved by the appropriate group, you can now assign to the PR to a SIG Release Chair for final …
> add neolit123 to kubernetes-milestone-maintainers

- config/kubernetes/sig-docs/teams.yaml
For https://github.com/kubernetes/test-infra/issues/11687#issuecomment-474388190.
This PR specifies who can use `/milestone` in the website repo. Membership in the team milestone requires an entry in a sig-docs-**-owners alias for a localization project in k/website. (See kubernetes/website#13287)
Reboot of https://github.com/kubernetes/org/pull/628#issuecomment-475772806 for clean commit history.
/sig docs
This PR also updates sig-docs team membership based on `k/website/OWNERS_ALIASES`.
> Add milestone team for SIG Docs

- config/kubernetes/sig-release/teams.yaml
Shift the patch release team out from under the release management team.
This gives the community an easy single place to GitHub @ on the
multiple issues, master pull requests, and branch cherry picks that are
involved in stable branch management.
Signed-off-by: Tim Pepper <tpepper@vmware.com>
> team add: kubernetes-patch-release-team

- config/kubernetes-sigs/org.yaml
Hey, this is the necessary follow up of https://github.com/kubernetes-sigs/cri-o/pull/2149 and adds me to the list of cri-o maintainers.
> Add saschagrunert to cri-o-maintainers team

- config/kubernetes-incubator/org.yaml
@tengqm is one of the primary maintainers of the ref doc generation code. This gives him Write access to the reference-docs repo.
> Add tengqm to reference-docs maintainers.

- config/kubernetes/sig-docs/teams.yaml
Using the same description format for all localization teams now.
/cc @zacharysarah 
/sig docs
> Updated descriptions for sig-docs-[de|en]-owners

- OWNERS_ALIASES
This PR updates SIG Docs leads by removing @chenopis and adding @jaredbhatti. 
See also: https://github.com/kubernetes/community/pull/3523
/assign @Bradamant3 @chenopis @jaredbhatti 
/sig docs
> Remove chenopis, add jaredbhatti

- config/kubernetes/sig-release/teams.yaml
We're thinking we'll do at least one last build here to clear the
pending cherry picks and potentially also to deliver packages that have
a fixup around runtime dependencies' metadata.
Signed-off-by: Tim Pepper <tpepper@vmware.com>
> patch-release-team: re-add @foxish for 1.11.10

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-contributor-experience/OWNERS
- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
Ref: https://github.com/kubernetes/org/issues/663
Also reorganize teams for sig-contribex.
/cc @Katharine @jeefy @mrbobbytables
> Add slack-infra-admins team

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cli/OWNERS
- config/kubernetes-sigs/sig-cli/teams.yaml
Ref: https://github.com/kubernetes/org/issues/662
Also reorganize teams for sig-cli.
/assign @pwittrock
> Add teams for cli-experimental

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cli/teams.yaml
Ref: https://github.com/kubernetes/org/issues/599
Some members of the team [sig-cli-maintainers ](https://github.com/kubernetes/org/blob/94ded1dc4a1cf58aab6ab2e332058da1f1f347dc/config/kubernetes/sig-cli/teams.yaml#L41-L53) were not members of kubernetes-sigs so I've added them to the org (all kubernetes org members are implcitly eligible for kubernetes-sigs membership)
/assign @ahmetb @soltysh @juanvallejo
> Add teams for krew and krew-index

- OWNERS_ALIASES
Ref: https://github.com/kubernetes/community/pull/3539
/cc @brendandburns
> Correct github handle for Brendan Burns in OWNERS_ALIASES

- config/kubernetes/sig-docs/teams.yaml
Due to time constraints @lledru asked to step down from sig-docs.
Many thanks for your sig-docs contributions @lledru 🎉 
/cc @lledru 
/assign @bradamant3
ref. https://github.com/kubernetes/website/pull/13596
> Removed lledru from sig-docs

- config/kubernetes/org.yaml
OWNERS files don't support regex right now, which means we can't require dep-approvers to be able to approve `go.mod` and `go.sum` changes. Ref: https://github.com/kubernetes/kubernetes/pull/76167
Add a team for it so that it's easier to cc them for a review, before cc'ing a root approver.
Ref: https://github.com/kubernetes/kubernetes/blob/06150f798e271ec048cd03fef98908b7a23c4486/OWNERS_ALIASES#L290-L297
/cc @cblecker @liggitt @sttts @BenTheElder @dims
> Add team for dep-approvers

- config/kubernetes/sig-docs/teams.yaml
Owners and reviewers for the Spanish translation team joined at https://github.com/kubernetes/website/pull/13543
> Add sig-docs-es members

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/wg-component-standard/OWNERS
- config/kubernetes-sigs/wg-component-standard/teams.yaml
Ref: https://github.com/kubernetes/org/issues/683
@sttts and @mtaufen were not part of k-sigs, so I've added them in this PR. They are members of @kubernetes and are implicitly eligible for members to @kubernetes-sigs. 
/assign @sttts
> Add teams for legacyflag

- config/kubernetes/sig-release/teams.yaml
@mrbobbytables and @craiglpeters added to the kubernetes-milestone-maintainers team. They are both members of the Kubernetes Org already. They are Enhancement shadows for the 1.15 cycle and will need the ability to change milestones and apply labels.
Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>
/sig release
/assign justaugustus
/assign claurence
> Add 1.15 Enhancement Shadows to Milestone Maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cloud-provider/OWNERS
- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Ref: https://github.com/kubernetes/org/issues/715
@cheftako and @anfernee are members of Kubernetes but were not members of Kubernetes SIGs so I've added them as members in this PR (members of Kubernetes are implicitly eligible for membership to Kubernetes SIGs).
/assign @cheftako @andrewsykim
> Add teams for apiserver-network-proxy

- config/kubernetes-sigs/org.yaml
The repo has moved to the cri-o GitHub org: https://github.com/cri-o/cri-o
Ref: https://github.com/kubernetes/org/issues/675
> Remove teams for cri-o

- config/kubernetes/sig-docs/teams.yaml
As per https://github.com/kubernetes/website/pull/13822#issuecomment-483588039 , we have to update the sig-docs team for init Indonesian translation doc.
/assign @zacharysarah 
Co-authored-by: Giri Kuncoro girikuncoro@gmail.com
Co-authored-by: Irvi Firqotul Aini irvifa@gmail.com
> Add sig-docs-id members to the team

- config/kubernetes/sig-release/teams.yaml
Updated kubernetes-milestone-maintainers as follows:
- drop all 1.14 release team members and shadows
- add all 1.15 release team role leads
- add 1.15 release team role shadows for:
- lead
- enhancements
- ci-signal
- bug-triage
Updated kubernetes-release-managers as follows:
- drop 1.14 release team members
- add 1.15 release team members
> Update github teams for release-team 1.14 to 1.15 transition

- config/kubernetes/sig-docs/teams.yaml
Hi @rlenferink
please have a look at this PR as requested
Cheers
Felipe
> Add sig-docs-id PT speaking members to the team

- config/kubernetes/sig-docs/teams.yaml
Fixes #754 
This PR creates a GitHub team for the Kubernetes blog.
> Add a team for the K8s blog

- config/kubernetes-sigs/org.yaml
Ref: https://github.com/kubernetes/org/issues/738
/assign @dims @jdumars
> Remove teams for architecture-tracking repo

- config/kubernetes/org.yaml
This person removed themselves from the GitHub org and we immediately re-invited them. This removes that invitation.
> Remove XiaoningDing from kubernetes

- config/kubernetes/sig-instrumentation/teams.yaml
This PR adds @andyxning to the sig-instrumentation team.
It seems that names are sorted by alphabet, so i added myself to the beginning since it starts with `a`. :)
/cc @brancz @piosz
> add andyxning to sig-instrumentation

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-release/OWNERS
- config/kubernetes-sigs/sig-release/teams.yaml
Ref: https://github.com/kubernetes/org/issues/801
@marpaia was not a member of k-sigs, so I've added him in this PR. Since he is a member of @kubernetes, he is implicitly eligible for membership to @kubernetes-sigs. 
@jeefy you mentioned that release-engineering should also have write access to this repo. I'm not entirely sure if we have it codified somewhere who comes under release-engineering? Could you add them as a follow-up?
/assign @jeefy @justaugustus
> Add teams for release-notes

- config/kubernetes/sig-docs/teams.yaml
Add owners and reviewers for the Hindi team.
* https://github.com/kubernetes/org/issues/747
* https://github.com/kubernetes/website/pull/13910
> Add sig-docs-hi members

- config/kubernetes/sig-release/teams.yaml
So that @k8s-release-robot can add milestone for the publishing bot issue. See https://github.com/kubernetes/kubernetes/issues/77871#issuecomment-492299856 and https://github.com/kubernetes/release/pull/711 for more details.
> Add k8s-release-robot to milestone-maintainers team

- config/config_test.go
- config/kubernetes-incubator/org.yaml
- config/kubernetes/sig-release/teams.yaml
This is a manual revert of https://github.com/kubernetes/org/pull/591, and a retake of https://github.com/kubernetes/org/pull/592
If this looks good, I'll do a manual peribolos run to fix any weird errors that arise.
> Enforce non-admins shouldn't be team maintainers

- config/kubernetes/sig-release/teams.yaml
This removes nesting for the kubernetes-release-manager and patch-release-team teams. This ensures clarity over who has/needs active permissions to push branches.
> Remove nesting from release manager teams

- config/kubernetes/org.yaml
The publishing-bot requires admin to access to be able to push to protected branches. Also see https://github.com/orgs/kubernetes/teams/stage-bots/repositories.
This confused me for a second while assigning access to a new staging repo.
> Fix description for stage-bots team

- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Cleaning description of the teams

- config/kubernetes-sigs/sig-service-catalog/OWNERS
- config/kubernetes-sigs/sig-service-catalog/teams.yaml
- config/kubernetes/sig-service-catalog/teams.yaml
> Update service catalog teams

- config/kubernetes-sigs/org.yaml
I'm already the member of the @kubernetes org and I need to join the @kubernetes-sigs because the Service Catalog project (to which I contribute) will be moved there soon.
> Add mszostok to the kubernetes-sigs org

- config/kubernetes-incubator/org.yaml
red #882
service-catalog has moved! We can clean up the old teams from incubator
> Remove service-catalog teams from incubator

- config/kubernetes-incubator/org.yaml
I believe the following teams are not used anymore.
The repo has transferred away from [kubernetes-incubator/cri-containerd](https://github.com/kubernetes-incubator/cri-containerd) to the containerd org.
> Removed cri-containerd teams

- config/kubernetes/sig-release/teams.yaml
Kubernetes Build Admins are the current set of Googlers with access
to publish packages (debs/rpms) on behalf of the Kubernetes project.
This team is a notification-only group, which includes the
SIG Release Chairs for continuity.
/assign @tpepper @calebamiles 
/cc @kubernetes/patch-release-team @kubernetes/release-engineering @kubernetes/release-managers 
cc: @sumitranr @aleksandra-malinowska @listx
> sig-release: Add build-admins team

- config/kubernetes-sigs/sig-service-catalog/teams.yaml
- config/kubernetes/sig-service-catalog/teams.yaml
making these teams represent current membership of the sig.
-removing defunct members
-readding mhbauer who got dropped during the incubator -> sigs transition
-add new maintainer mszostok
> cleanup sig-service-catalog teams

- config/kubernetes/org.yaml
The kube-state-metrics portion is very outdated.
i) Removing ghodss and fabxc as they are no longer active.
ii) Adding brancz and andyxing as admins since they are the Security Contacts of kube-state-metrics.
iii) Adding the listed `approvers` of `kube-state-metrics` as maintainers.
Reference:
i) https://github.com/kubernetes/kube-state-metrics/blob/master/OWNERS
ii) https://github.com/kubernetes/kube-state-metrics/blob/master/SECURITY_CONTACTS
cc @brancz @mxinden @andyxning
> update kube-state-metrics admins and maintainers

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Add Leigh and Daniel to help with project logistics.
Daniel has been helping with meeting logistics since the start. Leigh has written quite a bit of code and contributed design and ideas.
It'd be good to add us to maintainers, so we can e.g. add and drive a project board for [the issues](https://github.com/kubernetes-sigs/addon-operators/issues?q=is%3Aopen+sort%3Acreated-asc).
> add Leigh and Daniel as cluster addons operator maintainers

- config/kubernetes/sig-release/teams.yaml
- I was removed from `patch-release-team` in [this PR][pr], I am not sure why. Re-adding myself again.
- I think I also need to be on `release-managers` to be able to actually cut a patch.
If there are good reasons why I have been removed in the first place, please let me know.
/cc @kubernetes/patch-release-team 
/cc @kubernetes/release-managers 
/cc @cblecker 
[pr]: https://github.com/kubernetes/org/pull/849
> Add /me to the patch release and release managers team

- config/kubernetes/sig-release/teams.yaml
/assign @calebamiles @tpepper @lachie83 
/cc @kubernetes/owners @kubernetes/release-team-leads @kubernetes/release-team
> Initial update to SIG Release teams for 1.16

- config/kubernetes/org.yaml
The user doesn't exist anymore, probably moved to @yoojinl.
@yoojinl can you confirm that @rustyrobot was your old username and it was renamed to @yoojinl? Will readd you after that.
This should fix peribolos.
> Remove rustyrobot from Kubernetes org

- config/kubernetes/sig-release/teams.yaml
to include folks from:
- Build Admins
- Patch Release Team
- Branch Managers
- Release Manager Associates
xref: https://github.com/kubernetes/sig-release/pull/702
/cc @kubernetes/release-managers 
> added members to release-engineering team

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/wg-lts/teams.yaml
These teams don't need to be secret. If the `privacy` field is not included for a team, they are secret by default.
For `wg-lts` and `release-notes-maintainers` teams, it looks like we just missed adding the `privacy` field.
> Fix visibility of secret teams

- config/kubernetes/org.yaml
- config/kubernetes/sig-release/teams.yaml
ref: https://groups.google.com/d/topic/kubernetes-release-managers-private/eunbbd2WN_E/discussion, https://groups.google.com/d/topic/kubernetes-release-managers-private/V9ZHE6iHbvU/discussion
/cc @kubernetes/owners
> Remove k8s-release-robot from all teams

- config/kubernetes/org.yaml
- config/kubernetes/sig-release/teams.yaml
This reverts commit 18c15544dce0ee2b89a080cb0ddb006829ebd47a.
/cc @kubernetes/owners @kubernetes/sig-release-admins 
/assign @cblecker @nikhita 
ref: #980, https://groups.google.com/d/topic/kubernetes-release-managers-private/eunbbd2WN_E/discussion, https://groups.google.com/d/topic/kubernetes-release-managers-private/V9ZHE6iHbvU/discussion
> Revert "Remove k8s-release-robot from all teams"

- config/kubernetes/sig-release/teams.yaml
Adding rbitia and evillgenius75 as team members. Updated mariantalla role and moved mrbobbytables to the member and not maintainer section
Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>
/sig release
/assign justaugustus
/assign lachie83
> Add 1.16 Enhancement Shadows

- config/kubernetes/sig-release/teams.yaml
I overlooked Maria as a milestone maintainer as 1.16 Enhancement Shadow. She needs the powers.
Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>
> Add Maria as Milestone Maintainer

- config/kubernetes/org.yaml
- config/kubernetes/sig-docs/teams.yaml
This PR updates K8s blog team info by removing deprecated teams.
Instead of org-level teams, a Prow/OWNERS group in [k/website](https://github.com/kubernetes/website/blob/master/content/en/blog/OWNERS) handles blog maintenance.
/assign @kbarnard10 @mrbobbytables 
/sig docs
/area github-permissions
> Update blog team members

- config/kubernetes-sigs/org.yaml
This PR adds missing members from the [CNDT owners file in the contributor playground](https://github.com/kubernetes-sigs/contributor-playground/blob/master/cndt-2019/OWNERS) to the kubernetes-sigs org. All members are members of the kubernetes org already.
ref: https://github.com/kubernetes-sigs/contributor-playground/pull/354
ref: https://kubernetes.slack.com/archives/C1TU9EB9S/p1563272182237200
ref: https://kubernetes.slack.com/archives/C1TU9EB9S/p1563703645003300
> Add members to kubernetes-sigs for CloudNativeDays Tokyo Workshop

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-aws/OWNERS
- config/kubernetes-sigs/sig-azure/OWNERS
- config/kubernetes-sigs/sig-ibmcloud/OWNERS
- config/kubernetes-sigs/sig-vmware/OWNERS
- config/kubernetes/sig-aws/OWNERS
- config/kubernetes/sig-aws/teams.yaml
- config/kubernetes/sig-azure/OWNERS
- config/kubernetes/sig-azure/teams.yaml
- config/kubernetes/sig-gcp/OWNERS
- config/kubernetes/sig-gcp/teams.yaml
- config/kubernetes/sig-ibmcloud/OWNERS
- config/kubernetes/sig-ibmcloud/teams.yaml
- config/kubernetes/sig-openstack/OWNERS
- config/kubernetes/sig-openstack/teams.yaml
- OWNERS: Update OWNER_ALIASES from k/community
- sig-cloud-provider: Update OWNER_ALIASES for consolidated SIGs
- sig-cloud-provider: Update GitHub teams for consolidated SIGs
Ref: [kubernetes/community#3941](https://github.com/kubernetes/community/pull/3941), [kubernetes/community#3895](https://github.com/kubernetes/community/pull/3895), #1051
/assign @andrewsykim @nikhita
> sig-cloud-provider: Rename OWNERS_ALIASES & GitHub teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-usability/OWNERS
- config/kubernetes-sigs/sig-usability/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1047
This PR:
- Adds team for sig-usability
- Adds @hpandeycodeit @Rajakavitha1 @vllry to k-sigs org, since they are already members of the kubernetes org.
- ~~Adds `sig-usability-leads` to `OWNERS_ALIASES`. Ideally we should just do a sync of the OWNERS_ALIASES file in k/community but that removes aliases for cloud providers sigs (sig-azure, etc). I'd prefer to clean those up in a follow-up (https://github.com/kubernetes/org/issues/1051)~~
> Add team for sig-usability

- config/kubernetes-csi/org.yaml
Ref: https://github.com/kubernetes/org/issues/1060
Also adds @PatrickLang to kubernetes-csi since he is already a member of @kubernetes and @kubernetes-sigs. 
/cc @ddebroy @msau42 @PatrickLang
> Add teams for csi-proxy

- config/kubernetes/sig-docs/teams.yaml
Matching k8s/website PR: https://github.com/kubernetes/website/pull/15850
Mattia is helping out with our Italian localization efforts.
/cc @micheleberardi @mattiaperi 
> Added mattiaperi to sig-docs-it-* teams

- config/kubernetes/sig-release/teams.yaml
I'll be doing some branch management tasks which require superpowers e.g., `branchff`
/area release-eng
/sig release
/cc @kubernetes/release-engineering 
/assign @tpepper @calebamiles
> sig-release: Add justaugustus to Release Managers team

- config/kubernetes/sig-docs/teams.yaml
Adding @danninov and @phanama as additional reviewers for Indonesian localization as they have demonstrated consistent contribution with the localization effort for Bahasa Indonesia for the past months.
Co-authored-by: Giri Kuncoro girikuncoro@gmail.com
Co-authored-by: Irvi Firqotul Aini irvifa@gmail.com
> Add danninov and phanama as docs-id reviewers

- config/kubernetes-sigs/sig-service-catalog/teams.yaml
**Description**
I'm one of the Service Catalog chair: https://github.com/kubernetes/community/tree/master/sig-service-catalog#chairs 
During the repo configuration, we overlooked that entry.
/cc @jberkhahn
> Add mszostok to the Service Catalog repo admin

- OWNERS_ALIASES
- config/kubernetes/sig-docs/teams.yaml
This PR updates teams for SIG Docs.
@jimangel 👋 I'm happy to close this in deference to your own PR.
> Update SIG Docs teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Adds @CecileRobertMichon to k-sigs (implicitly qualifies through kubernetes org membership) and
fixes #1153
/assign @cblecker @mrbobbytables
> New members (190903)

- config/kubernetes-sigs/sig-cli/teams.yaml
Hey there, among the active maintainers of sigs.k8s.io/krew there is only @ahmetb who has sufficient rights to do a release of a new krew version (see https://github.com/kubernetes-sigs/krew/issues/324). We would like to reduce the truck factor here, so that there are at least two of the maintainers with the appropriate rights. In particular, I need the right to create tags manually.
So I was digging into this and I found this config file where @ahmetb is listed in `krew-maintainers`, who apparently have write access to the repository. Is it appropriate to add me there as well (I have been krew maintainer for just a few months only)? If so, is there a particular process that needs to be followed?
Thanks in advance!
Also see the discussion here …
> Add corneliusweig to krew-maintainers

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Signed-off-by: Vince Prignano <vincepri@vmware.com>
> Add vincepri to Cluster API GCP repo admin / update maintainers

- config/kubernetes-sigs/org.yaml
Both `aveshagarwal` and `ravisantoshgudimetla` are already members of the kubernetes org.
Adding as a prerequisite to migrating the descheduler repo from kubernetes-incubator to kubernetes-sigs. 
ref:  https://github.com/kubernetes/org/issues/1176
> Add members to k-sigs for descheduler repo migration

- config/kubernetes-sigs/org.yaml
Adding as a prerequisite to migrating the descheduler repo from kubernetes-incubator to kubernetes-sigs. 
ref:  https://github.com/kubernetes/org/issues/1176
/hold
holding for https://github.com/kubernetes/org/pull/1179
> Add descheduler teams to kubernetes-sigs

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Requesting access to be able to create releases and branches for the CAPO project
> Add sbueringer to cluster-api-openstack maintainer

- config/kubernetes-client/org.yaml
Add @roycaihw to the admin groups in 
- kubernetes-client/python
- kubernetes-client/python-base
- kubernetes-client/go
- kubernetes-client/go-base
since I already have admin access to these repos. I maintain the python client repo and do [releases](https://github.com/kubernetes-client/python/releases) regularly.
Also add myself to the admin group in
- kubernetes-client/gen
per conversation in https://github.com/kubernetes-client/gen/pull/97#issuecomment-530034348.
> Add roycaihw to admin groups in kubernetes-client gen, python and go repos

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-network/OWNERS
- config/kubernetes-sigs/sig-network/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1154
Also add @bowei @dnardo and @MrHohn to @kubernetes-sigs since they are already members of the @kubernetes org.
> Add team for ip-masq-agent in k-sigs

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- Add ~SIG Release Chairs~ Release Engineering subproject owners as maintainers for CIP
- Promote cpanato to Branch Manager
- Add ps882 to Build Admins
- Remove inactive Release Manager Associates
- Update `milestone-maintainers` (compared w/ current SIG Chairs/TLs)
- Remove ixdy from `release-engineering`
- Remove 1.15 team from `release-team`
- Rotate `release-team-leads`
- Update `sig-release` GH team
(This also syncs up `OWNERS_ALIASES` w/ k/community)
/hold
/sig release
/area release-eng release-team
/assign @tpepper @calebamiles @mrbobbytables @nikhita @cblecker 
cc: @kubernetes/release-engineering @kubernetes/release-team @kubernetes/milestone-maintainers
> Quarterly SIG Release teams update

- OWNERS_ALIASES
- config/kubernetes/org.yaml
- config/kubernetes/sig-openstack/teams.yaml
- config/kubernetes/sig-release/teams.yaml
@lingxiankong has taken over the leadership for the cloud-provider-openstack from @hogepodge.
> Add lingxiankong to cloud-provider-openstack team

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
ref #1158 
Adds @bradtopol @jimangel @kbarnard10 @kbhawkey @steveperry-53 @tengqm and @zparnold to the kubernetes-sigs org (admins, maintainers, and owners) as a prerequisite. All are current kubernetes org members.
> Migrate reference docs teams to kubernetes-sigs

- config/kubernetes/sig-release/teams.yaml
Adds @annajung, @jeremyrickard, @kcmartin, and @palnabarun to milestone maintainers for the 1.17 release.
/hold 
holding for #1236 and sign off from sig release/release team leads.
> Add Enhancements shadows for 1.17 Release Team.

- config/kubernetes/org.yaml
- config/kubernetes/sig-openstack/teams.yaml
Cleaning up the SIG-OpenStack owners files to reflect new leadership
changes over the last year.
> Cleaning up SIG-OpenStack owners

- config/kubernetes-sigs/org.yaml
Adds sig-usability-reviewer team, initially populated with the admin/maintainer members and @raelga as a reviewer.
Closes #1243 
/cc @tashimi
> Add @raelga to kubernetes-sigs/org

- config/kubernetes/sig-contributor-experience/teams.yaml
added all the current members in https://git.k8s.io/community/sig-contributor-experience/role-handbooks/apac-coordinator.md#team
... as per today's meeting.
ref: https://kubernetes.slack.com/archives/C1TU9EB9S/p1569473474129900?thread_ts=1569473351.128100&cid=C1TU9EB9S
/assign @nikhita @parispittman
> added APAC Coordinator team in SIG ContribEx

- .bazelrc
- BUILD.bazel
- WORKSPACE
- load.bzl
- repos.bzl
Needs https://github.com/kubernetes/test-infra/pull/14646
* Reuses some repo-loading logic from repo-infra.
* Adds RBE support when using `--config=remote`
* Adds a stub `--config=ci` that does nearly nothing
Next:
* Update CI to use `--config=ci` and make this config use RBE
* Replace hack scripts with common repo-infra versions.
/assign
> Use repo-infra to bootstrap go rules

- config/kubernetes/sig-docs/teams.yaml
This PR add 1.17 doc lead @daminisatya to @kubernetes/website-milestone-maintainers
> add daminisatya to milestone maintainers

- config/kubernetes/sig-docs/teams.yaml
I've been involved with the kubernetes community for a long time (more than 1 year), and I've become reviewer/approver for zh docs.
As a matter of fact, I am assisting in the management of zh related tasks ( such as https://github.com/kubernetes/website/pull/16755).
This PR adds myself(SataQiu) to sig-docs-zh teams, then I can better participate in the contribution and management work related to zh docs.
Looking forward to your support @zacharysarah @zhangxiaoyu-zidif @markthink @chenrui333 :)
> Add SataQiu to sig-docs-zh teams

- config/kubernetes/sig-docs/teams.yaml
This PR removes @markthink from a team with write access to k/website.
This is in response to https://github.com/kubernetes/website/pull/16708#issuecomment-541201579, where @markthink manually merged his own PR containing architectural site changes to k/website.
The @kubernetes/sig-docs-l10n-admins team exists so that localization teams can create branches and assign milestones to localization projects. Any use of write permissions beyond localization work is an abuse of trust and [does not demonstrate sound technical judgment](https://github.com/kubernetes/community/blob/master/community-membership.md#responsibilities-and-privileges-2). 
There's a longer conversation here, but this PR needs to merge ASAP to establish safety first.
> Isolate permissions for user markthink

- config/kubernetes/org.yaml
```
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership\"}","file":"external/io_k8s_test_infra/prow/cmd/peribolos/main.go:441","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(kubernetes, kylix3511, false) failed","time":"2019-10-14T22:25:57Z"}
```
> Remove kylix3511 from kubernetes

- config/kubernetes-sigs/sig-vmware/teams.yaml
Divyen is in the repo OWNERS file as an approver, and will be managing
driver releases in the future. He needs the ability to push tags.
/assign @frapposelli
> Add divyenpatel to vsphere-csi-driver-maintainers

- config/kubernetes/sig-docs/teams.yaml
Owners and reviewers for the Vietnamese translation team
joined at kubernetes/website#16965
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
> Adding sig-docs-vi members

- config/kubernetes-sigs/org.yaml
I'm adding myself to kubernetes-sigs and kubernetes-incubator org to ease contributing for projects under this org. I'm already kubernetes org member.
> Add girikuncoro to kubernetes-sigs and kubernetes-incubator org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- config/kubernetes/sig-cluster-lifecycle/teams.yaml
I am interested in the projects around `kubeadm`, and would like to actively participate in them.
So far, I have been involved in the releated contributions about one year.
Happily, I have been honored as a `kubeadm` reviewer and a `cluster-api-bootstrap-provider-kubeadm` maintainer.
This PR put myself(SataQiu) into the proper teams to get better involved in the community.
Ref: 
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/master/OWNERS_ALIASES#L20
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/OWNERS#L21
/cc @chuckha @neolit123
> Add SataQiu into cluster-api-bootstrap-provider-kubeadm-maintainers and sig-cluster-lifecycle teams

- config/kubernetes/sig-release/teams.yaml
Adding milestone maintainer role for lead and shadows on 1.17 bug triage team.
@kikisdeliveryservice @markyjackson-taulia @smourapina @ttousai
> Milestone Maintainer role for 1.17 bug triage team

- config/kubernetes-csi/org.yaml
Note that I'm already a member of the Kubernetes org
Fixes https://github.com/kubernetes-csi/external-provisioner/issues/375
/cc @msau42
> Add verult to kubernetes-csi org

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1286
`linki` is a kubernetes org member and is automatically eligible for membership to kubernetes-sigs. All others mentioned in the issue are only kubernetes-incubator members, so they'll need to apply for membership to kubernetes-sigs.
> Update teams for external-dns

- config/kubernetes-sigs/sig-network/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1328
Repo has been migrated: https://github.com/kubernetes-sigs/ingress-controller-conformance
`rhs` and `alexgervais` are not kubernetes/kubernetes-sigs members yet.
> Add teams for ingress-controller-conformance

- config/kubernetes/org.yaml
This PR updates the list of people with admin access to the k/website repo as part of [OWNERS cleanup](https://groups.google.com/d/msg/kubernetes-dev/4160VsBL7OI/BsBRZSqpCQAJ). 
I've pruned the list of people from SIG Docs to its current chairs:
```
- Bradamant3
- jimangel
- zacharysarah
```
A couple of questions:
1. Is there a compelling reason for these folks to continue with admin permissions for k/website?
```
- Kashomon
- lavalamp
- pwittrock
- sebgoa
- thockin
```
2. Are there folks whom we should add instead? 
I'm thinking it might be good to add one or two people from steering.
> Update list of folks with admin access to the website repo

- config/kubernetes-sigs/sig-network/teams.yaml
ref: #1292 
Adds teams for [kubernetes-sigs/service-apis](https://github.com/kubernetes-sigs/service-apis) repo.
> Add service-apis teams

- config/kubernetes-sigs/sig-network/teams.yaml
After joining the kubernetes-sigs I'd request admin access for the other owners:
- @Raffo
- @hjacobs
- @njuettner
/cc @nikhita 
/cc @mrbobbytables 
Signed-off-by: njuettner <nick@zalando.de>
> Adding more owners to external-dns

- config/kubernetes-sigs/sig-network/teams.yaml
`maintainers-` and `admins-` are only used as prefixes in the kubernetes-incubator org, and suffixes in kubernetes and kubernetes-sigs orgs.
> sig-network: fix team names in k-sigs

- config/kubernetes-incubator/org.yaml
- config/kubernetes/org.yaml
https://github.com/vaikas-google doesn't exist anymore, peribolos is broken right now: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-org-peribolos/1191287543132327936
> Remove vaikas-google from kubernetes orgs

- config/kubernetes-client/org.yaml
Adding myself as as pointed out by the following issues since I am already a @kubernetes org member I think its ok to add my self.
* https://github.com/kubernetes-client/javascript/issues/359 
* https://github.com/kubernetes-client/ruby/issues/49
cc/ @brendandburns
> Add drubin to the kubernetes-client org

- config/kubernetes-incubator/org.yaml
/assign @brancz 
Adding myself as owner for MetricsServer as discussed with @brancz.
@mrbobbytables I will handle migrating MetricsServer to Kubernetes SIGs
> Add serathius to kubernetes-incubator org

- config/kubernetes/sig-release/teams.yaml
- Temporarily grant Sascha access to `release-managers` team
Sascha will be cutting the `1.17.0-beta.1` release, so we're granting him
temporary write access to `kubernetes/kubernetes`.
- Add new Release Manager Associates to `release-engineering`
- Kendrick Coleman - @kacole2 
- Sascha Grunert - @saschagrunert 
- Seth McCombs - @sethmccombs 
- Marko Mudrinić - @xmudrii 
- Taylor Dolezal - @onlydole 
- Paul Bouwer - @paulbouwer 
- Jim Angel - @jimangel
> sig-release: Update Release Managers teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-instrumentation/OWNERS
- config/kubernetes-sigs/sig-instrumentation/teams.yaml
ref: https://github.com/kubernetes/org/issues/1382
Adds members and teams for metrics-server migration to kubernetes-sigs.
@s-urbaniak, @serathius, and @kawych are all members of the kubernetes org and implicitly permitted to join other orgs.
@kawych is not a part of the teams, but is being added as the [primary approver for the repo](https://github.com/kubernetes/org/issues/1382).
> Add metrics server members and teams to kubernetes-sigs

- config/kubernetes/sig-release/teams.yaml
We granted Sascha temporary access to cut the 1.17.0-beta.1 release.
Revoking it here.
For the record, @idealhack was right [here](https://github.com/kubernetes/org/pull/1383#discussion_r342386023):
> correct me if I'm wrong: it seems this is only needed for branch fast-forwarding?
We didn't need to actually grant this, so oversight on my part.
/assign @tpepper @calebamiles @saschagrunert
cc: @kubernetes/release-engineering
> releng: Revoke Sascha's temporary access to release-managers team

- config/kubernetes-sigs/org.yaml
Add three contribex folks to kubernetes-sigs for administering the playground repo.
All three of these folks are already members of @kubernetes.
> Add members to kubernetes-sigs for contributor playground

- config/kubernetes/sig-release/teams.yaml
Request to be added as a milestone maintainer for sig instrumentation.
/cc @brancz
> Add RainbowMango as a milestone maintainer for sig instrumentation

- config/kubernetes/sig-release/teams.yaml
@oxddr is SIG-Scalability member and part of our oncall. He should be in milestone-maintainers to flag potential release-blocking scalability regressions, e.g. see https://github.com/kubernetes/kubernetes/issues/84910#issuecomment-551021607
> Add oxddr@ to milestone-maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
ref: https://github.com/kubernetes/org/issues/1305
EDIT:Adds @aaronlevy and the bootkube teams to the kubernetes-sigs org.
aaronlevy is implicitly allowed to join k-sigs as they are a member of the kubernetes org.
> Add bootkube teams to kubernetes-sigs.

- config/kubernetes/sig-release/teams.yaml
This will make it easier to contact the CI signal team within the big amount of issues we're supposed to be looking after.
> Add CI signal github team

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
ref: https://github.com/kubernetes/community/issues/3178
Following up on slack convo for establishing teams for the aws-iam-authenticator repo.
@nckturner is a member of the kubernetes org and is implicitly allowed membership to kubernetes-sigs.
/cc @nckturner 
/assign @andrewsykim 
/hold
for sign off
> Adds teams for the aws-iam-authenticator repo.

- config/kubernetes/org.yaml
@l-korbes changed their username from `ellenkorbes` to `l-korbes` and got removed from the org as a result (https://github.com/kubernetes/org/pull/1420).
This adds them back! :)
/assign @cblecker @mrbobbytables
> Add l-korbes to kubernetes org

- config/kubernetes/sig-docs/teams.yaml
I hope to join the sig-docs-zh team
*  I've become reviewer/approver for zh docs.
* I worked for website repo for 15 months.
* Merged and approve pr 179 [link](https://github.com/kubernetes/website/pulls/assigned/xichengliudui)
* Personal create includes merged pr 225 [link](https://github.com/kubernetes/website/pulls/xichengliudui)
Next, I will work in zh docs for a long time, so that I can manage and approve it more conveniently! So I created this pr
/cc @zacharysarah  @chenrui333
> add xichengliudui to sig-docs-zh team

- config/kubernetes/sig-docs/teams.yaml
Updated `teams.yaml` according to OWNER_ALIAS on k/website.
https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L117
> Update Japanese l10n owners and reviewers

- config/kubernetes/org.yaml
- config/kubernetes/sig-docs/teams.yaml
Based on [this #sig-release Slack discussion](https://kubernetes.slack.com/archives/C2C40FMNF/p1572534834092200), this PR changes the team name of `sig-docs-l10n-admins` to `kubernetes-website-write` and adds comments for why each team member has write access.
This PR also freshens team membership to the [current SIG Docs chairs](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES#L39-L42).
Many thanks to @justaugustus for the guidance!
/sig docs
> Clarify who has website write access and why

- config/kubernetes/org.yaml
Add the following users as Kops maintainers:
granular-ryanbonham
rdrgmnzs
rifelpet
/assign @justinsb
> Add members to Kops Maintainers list.

- config/kubernetes-sigs/sig-cli/teams.yaml
It appears like during 732ea009 we have added a set of people do not
directly work on krew and krew-index as admins/maintainers. This fixes that.
Additionally, this moves juanvallejo out of admins/maintainers and promotes
corneliusweig as such, since Juan hasn't been active in this repo.
/assign @soltysh
/cc @corneliusweig
> Update admins and approvers for -sigs/krew repos

- config/kubernetes/sig-release/teams.yaml
Accompanying GitHub team membership changes to https://github.com/kubernetes/sig-release/pull/868.
- Add Stephen Augustus
- Promote Sascha Grunert (@saschagrunert)
- Remove Cheryl Fong (@Bubblemelon)
Remove inactive associates:
- Nikhil Manchanda (@SlickNik)
- Dhawal Yogesh Bhanushali (@imkin)
- Nikhita Raghunath (@nikhita)
- Javier B Perez (@javier-b-perez)
- Giri Kuncoro (@girikuncoro)
- Peter Swica (@pswica)
**On hold until https://github.com/kubernetes/sig-release/pull/868 merges**
/hold
/assign @tpepper @calebamiles 
@kubernetes/sig-release-admins @kubernetes/release-engineering @kubernetes/release-managers 
/milestone v1.18
/priority important-longterm
/kind feature cleanup
> releng: Update Release Managers

- config/kubernetes-sigs/sig-cli/teams.yaml
ref: https://github.com/kubernetes-sigs/kustomize/issues/1708
Removes the `kustomize-contributors` team (no longer used)
Updates `kustomize-admins` and `kustomize-maintainers` teams with the current individually granted rights -- should be a noop permissions wise.
/assign @pwittrock
> Update kustomize teams.

- config/kubernetes/sig-pm/teams.yaml
We don't currently have a SIG PM team w/ admin access to k/enhancements.
Creating this team to address https://github.com/kubernetes/enhancements/issues/1195.
cc: @cjwagner
> sig-pm: Add enhancement-admins team to grant admin to k/enhancements

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-scheduling/OWNERS
- config/kubernetes-sigs/sig-scheduling/teams.yaml
- Adds @ahg-g and @deepak-vij to kubernetes-sigs org (both are members of kubernetes)
- Breaks out sig-scheduling teams into their own directory and updates current teams.
- Adds teams for the poseidon repo.
ref: https://github.com/kubernetes-sigs/poseidon/issues/178
/assign @ahg-g @k82cn 
/cc @deepak-vij 
/hold
> Update kubernetes-sigs scheduling teams.

- config/kubernetes/sig-docs/teams.yaml
This PR removes permissions from approvers/reviewers who are no longer active in SIG Docs.
/assign @jimangel @Bradamant3 
/cc @kbarnard10 @bradtopol
> Prune outdated SIG Docs permissions

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1449
@brendandburns @khenidak @lachie83 were not part of the kubernetes-sigs org, but are part of the kubernetes org so this PR adds them to k-sigs.
> Add teams for blobfuse-csi-driver

- config/kubernetes/sig-docs/teams.yaml
This PR removes approval/write access for @tengqm pending review of recent actions:
- https://github.com/kubernetes/website/pull/16135#issuecomment-562714349
- https://github.com/kubernetes/website/pull/17888#issuecomment-562071814
- https://github.com/kubernetes/website/pull/17894#issuecomment-562713120
/sig docs
> Remove SIG Docs approver permissions

- config/kubernetes-csi/org.yaml
In practice I've been the one who has prepared all of the recent
releases, so it makes sense that I also do the last step with tagging
it.
> kubernetes-csi: add pohly as csi-test maintainer

- config/kubernetes/sig-docs/teams.yaml
Per https://github.com/kubernetes/org/issues/1436#issuecomment-563327863, this PR removes the `sig-docs-maintainers` team because it's no longer required.
/assign @jimangel @nikhita 
/sig docs
> Prune sig-docs-maintainers

- config/kubernetes-csi/org.yaml
I've been managing and doing releases of the external-snapshotter repo.
> Add xing-yang as external-snapshotter admin

- config/kubernetes-sigs/org.yaml
I am already a member of the kubernetes org, I'd like to join kubernetes-sigs as well.
Some context: https://github.com/kubernetes-sigs/windows-testing/pull/120, https://github.com/kubernetes/org/issues/1489.
> Add pjh to kubernetes-sigs org

- config/kubernetes/sig-release/teams.yaml
Added alejandrox1 as releate team lead and daminisatya and mrbobbytables
as release team shadows for 1.18.
xref: https://github.com/kubernetes/sig-release/issues/933
Signed-off-by: alejandrox1 <alarcj137@gmail.com>
> Updated release team leads

- config/kubernetes/sig-contributor-experience/teams.yaml
- Remove inactive folks from community-admins/maintainers
- Rename -misc team to just "sig-contributor-experience"
- Add -leads team
- Remove stale/unused teams
- Move remaining teams as subteams
/hold
for comment
> Update ContribEx Teams

- config/kubernetes/sig-contributor-experience/teams.yaml
Update SIG Contributor Experience `teams.yaml` with the newest moderators. 
Thanks @nikhita, @mrbobbytables, and @castrojo for helping with this!
> Add nzoueidi, markyjackson-taulia, and onlydole to the YouTube admin section

- config/kubernetes-sigs/org.yaml
Joining kubernetes-sigs to work on service-apis.
Fixes: https://github.com/kubernetes/org/issues/1522
/cc @mrbobbytables
> Adding robscott as kubernetes-sigs member

- config/kubernetes-sigs/org.yaml
Add aledbf to the kubernetes-sigs org so that I can work on https://github.com/kubernetes-sigs/service-apis.
> Add aledbf to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-scheduling/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1564
Also adds @Huang-Wei to k-sigs since they are already a member of the @kubernetes github org.
> Add teams for scheduler-plugins

- config/kubernetes-sigs/org.yaml
Add Sh4d1 to the kubernetes-sigs org so that I can work on https://github.com/kubernetes-sigs/apiserver-network-proxy
> Add Sh4d1 to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
Ref: https://github.com/kubernetes/org/issues/1519
/assign @spiffxp @mrbobbytables
> Remove teams for testing_frameworks

- config/kubernetes/org.yaml
This fixes https://github.com/kubernetes/org/issues/1584
I was originally going to suggest that this person PR themselves into the relevant repo's admin team only to discover it does not exist. So here are the teams, populated with the member requesting addition, along with the individual who already had collaborator access
> Add teams to manage kubernetes/kube-openapi

- config/kubernetes-sigs/provider-azure/teams.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
(Also, moves capz teams under SIG Cluster Lifecycle approval.)
/assign @neolit123 @timothysc @fabriziopandini @justinsb 
cc: @CecileRobertMichon @soggiest @awesomenix
> Reconcile capz GitHub team membership w/ repo OWNERS

- config/kubernetes/sig-release/teams.yaml
- Adds two 1.18 Bug Triage team members as milestone maintainers;
- Removes one team member from past cycle.
> Updates Milestone Maintainer role for the 1.18 Bug Triage team

- config/kubernetes/sig-docs/teams.yaml
disabling simplytunde as an approver due to inactivity
Always welcome to come back if able to become
active again
Signed-off-by: Brad Topol <btopol@us.ibm.com>
> disable simplytunde as an approver due to inactivity.

- config/kubernetes/sig-release/teams.yaml
Processing k/org updates for https://github.com/kubernetes/sig-release/issues/978.
- Add hasheddan as a Release Manager Associate
- Temporarily grant @hasheddan release-managers access to cut release `v1.18.0-alpha.4`
I'll send an accompanying PR to process the removal of `release-managers` access (to be held until after the `v1.18.0-alpha.4` release) shortly.
/assign @tpepper @calebamiles 
/cc @hoegaarden @saschagrunert @cpanato
> Promote hasheddan to Release Manager Associate + temp Branch Manager access

- config/kubernetes/org.yaml
The user (https://github.com/l-korbes) is no longer present, which breaks peribolos.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-org-peribolos/1227356355153629184
> Replace l-korbes with ellenkorbes

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- Add cluster-api-provider-azure-pms team to manage capz boards
- Remove @soggiest from maintainers (ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/387)
/assign @neolit123 @timothysc
> cluster-lifecycle: Update capz GitHub teams

- config/kubernetes/sig-release/teams.yaml
Reverts the temporary Branch Manager access granted to @hasheddan in https://github.com/kubernetes/org/pull/1620.
/hold until https://github.com/kubernetes/org/pull/1620 merges AND `v.1.18.0-alpha.4` has been released
/assign @tpepper @calebamiles 
/cc @hoegaarden @saschagrunert @cpanato
> releng: Remove hasheddan's temporary Branch Manager access

- config/kubernetes-sigs/org.yaml
Closes https://github.com/kubernetes/org/issues/1645
I’m a k org member but need to also be a k-sigs member for https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/174 which adds me to the OWNERS file for the image promotor tool.
Signed-off-by: Bart Smykla <bartek@smykla.com>
> Added bartsmykla to k-sigs org

- config/kubernetes-csi/org.yaml
Ref: https://github.com/kubernetes/org/issues/1648
Also adds @NickrenREN to @kubernetes-csi org, since they are already a member of the @kubernetes org.
> Add teams for external-health-monitor

- config/kubernetes-csi/org.yaml
* @jsafrane and @msau42 are sig-storage tech leads.
* @saad-ali and @xing-yang are sig-storage co-chairs.
* And remove @childsb.
See https://github.com/kubernetes/community/tree/master/sig-storage
> Add sig-storage tech leads and co-chairs

- config/kubernetes/sig-storage/teams.yaml
* @jsafrane and @msau42 are sig-storage tech leads.
* @saad-ali and @xing-yang are sig-storage co-chairs.
* And remove @childsb.
See https://github.com/kubernetes/community/tree/master/sig-storage
> Add sig-storage co-chair

- config/kubernetes/sig-instrumentation/teams.yaml
I wasn't aware loburm was on parental leave for 10w within the last half a year, so adding him back and we'll reassess in some time. Sorry!
Removing mxinden due to inactivity. Thanks Max for everything you've done and contributed!
> sig-instrumentation: Re-add loburm, remove mxinden

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Remove stale invites for kubernetes-sigs org.
2019-01-22 19:18:14 -0800  68) - bryk
2019-10-15 22:46:33 +0100 146) - grayluck
2019-10-30 21:13:57 -0400 123) - dtoledo67
2019-12-06 12:16:09 +0530  67) - brendandburns
2019-07-16 16:18:43 -0400 289) - openstacker
> Remote stale invites for kubernetes-sigs

- config/kubernetes-sigs/org.yaml
I'm a member of the kubernetes org, but more of my projects are moving to kubernetes-sigs
> Add craiglpeters to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
I'm already member of `kubernetes` org and this PR is to request access to `kubernetes-sig` I've been working in some `cluster-api` projects.
/cc @justaugustus @detiber
> Add cpanato to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1691
Also adds @RainbowMango and @kevin-wangzefeng to the kubernetes-sigs org since they are already members of the @kubernetes org.
> Add GitHub teams for cloud-provider-huaweicloud

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1688
Also adds @caseydavenport @danwinship @dcbw to the @kubernetes-sigs org, since they are already members of the @kubernetes org.
> Add GitHub teams for iptables-wrappers

- config/kubernetes-sigs/sig-windows/teams.yaml
So we are planning to use GitHub actions to maintain the [Windows kube-proxy image](https://hub.docker.com/repository/docker/sigwindowstools/kube-proxy), but doing so requires me to add a secret to the repo for the action to use to access Docker Hub. I could have someone else else do this but it'd be simpler if I can do it myself 😸 .
GitHub action PR is open [here](https://github.com/kubernetes-sigs/sig-windows-tools/pull/45) if you're curious.
@michmike @justaugustus
> Add benmoss to sig-windows-tools-admins

- config/kubernetes/org.yaml
Fixes peribolos failure - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-org-peribolos/1239327869197357056
@nicoaragon is probably now @gnarled-cipher
@gnarled-cipher -- can you confirm that it is indeed you? Once confirmed, we can add you back with the new username. :)
> Remove nicoaragon from kubernetes org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/141, https://github.com/kubernetes/test-infra/pull/16815
I don't have the bandwidth for reviews, etc. for the repo right now.
/cc @xmudrii
> Remove write access to cluster-api-do repo for nikhita

- config/kubernetes/org.yaml
Ref: https://github.com/kubernetes/org/pull/1715
> Add gnarled-cipher to kubernetes org

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/1725
I'm already member of kubernetes org and this PR is to request access to kubernetes-sig I've been working in `cluster-api-provider-digitalocean` project.
/cc @xmudrii @cpanato
> Add prksu to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-api-machinery/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1731
Also adds @mikedanese to @kubernetes-sigs since he is already a member of @kubernetes. 
> Add GitHub teams for clientgofix

- config/kubernetes-sigs/org.yaml
Fixes #1734
I'm already a member of the kubernetes org and this PR is to request access to kubernetes-sig and I've starting working on the cluster-api-provider-digitalocean project.
/cc @xmudrii
> Add MorrisLaw to kubernetes-sigs org.

- config/kubernetes-sigs/org.yaml
I'm a member of `kubernetes` org and am requesting access to `kubernetes-sigs`.
I'm maintaining configs for test passes which live in https://github.com/kubernetes-sigs/windows-testing
/cc @justaugustus
> Adding marosset to kubernetes-sigs org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- config/kubernetes-sigs/sig-multicluster/teams.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-scalability/teams.yaml
Most of these are artifacts of having manually created the team
in the days before we managed them with peribolos
Also removed myself from sig-scalability teams as I haven't
participated there in a while
> Remove myself from teams I don't participate in

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This PR adds new `cluster-api-provider-digitalocean` maintainers to the CAPI-DO-maintainers GitHub team. The new maintainers are already added to the project [OWNERS file](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/master/OWNERS_ALIASES).
/hold
~until https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/146 is not merged~
> Add new cluster-api-provider-digitalocean maintainers

- config/kubernetes/sig-docs/teams.yaml
- Synced Italian teams with k8s/website repo (as soon as https://github.com/kubernetes/website/pull/19790 merges)
- Corrected localization affiliation from Italian -> German (as German approver)
> Update Italian localization teams & corrected language affilation

- config/kubernetes-csi/org.yaml
Justification:
Maintainer/Owner of kubernetes volume plugins:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/OWNERS
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/iscsi/OWNERS
Lead contributor @
https://github.com/kubernetes-incubator/external-storage/graphs/contributors
Contributed CSI features like metrics support:
https://github.com/kubernetes/kubernetes/pull/76188
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
> Add humblec to kubernetes-csi org

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/wg-policy/OWNERS
- config/kubernetes-sigs/wg-policy/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1669
Also adds @ericavonb and @hannibalhuang to k-sigs since they are already members of the @kubernetes org.
> Add GitHub teams for wg-policy-prototypes

- config/kubernetes/sig-docs/teams.yaml
Add @sftim (me) as a website maintainer.
I'm a technical lead for SIG Docs; see [`OWNERS_ALIASES@a4a1d2f`](https://github.com/kubernetes/community/blob/a4a1d2f561eac609403f0db7d31d764daaea3b00/OWNERS_ALIASES#L46) in [k/community](https://github.com/kubernetes/community).
> Add @sftim as website maintainer

- OWNERS_ALIASES
- config/kubernetes/sig-contributor-experience/teams.yaml
Ref: https://github.com/kubernetes/community/pull/4693
/hold
until https://github.com/kubernetes/community/pull/4693 is merged
/assign @mrbobbytables @cblecker @Phillels @castrojo
> sig-contribex: add castrojo to OWNERS_ALIASES and teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-storage/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1800, https://github.com/kubernetes/org/issues/1801 
Also adds @humblec to k-sigs since they are already a member of the @kubernetes org (they are an approver for both repos)
> Add GitHub teams for gluster provisioner repos

- config/kubernetes/sig-architecture/teams.yaml
- Remove obsolete GH teams
- Add '-leads' team
- Add SIG Chairs to all teams
Groups are now structured per the recommendations [here](https://github.com/kubernetes/community/issues/2323#issuecomment-400776769) (h/t @cblecker!):
```
sig-foo
|_ sig-foo-leads
|_ sig-foo-pr-reviews
```
Fixes: https://github.com/kubernetes/org/issues/1798
/assign @johnbelamaric @dims @derekwaynecarr
> sig-arch: Consolidate GitHub teams

- config/kubernetes/org.yaml
Ref: https://github.com/kubernetes/org/issues/1812
The repo is being archived.
/assign @neolit123
> Remove GitHub teams for kubernetes-anywhere repo

- config/kubernetes/sig-docs/teams.yaml
This PR updates SIG Docs team rosters to reflect current team and role membership.
- @kbarnard10 replaced @Bradamant3 as SIG Docs chair. #1629 
- SIG Docs added technical lead roles: 
- @kbhawkey #1683
- @sftim  #1747 
- @onlydole this PR
- It's useful to have a team for reaching chairs and tech leads specifically, especially for netlify-related issues. https://github.com/kubernetes/website/pull/20489/
> Update SIG Docs team membership

- config/kubernetes/org.yaml
- config/kubernetes/sig-release/teams.yaml
https://github.com/organizations/kubernetes/settings/audit-log?q=actor%3Adanielromlein+action%3Aorg.remove_member
Looks like @danielromlein removed themselves from the org on March 16.
cc: @jeefy @floreks @maciaszczykm
> Remove danielromlein from org

- config/kubernetes-incubator/org.yaml
They seem to have renamed their GitHub username - https://github.com/pbx0
Ref: peribolos failure - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-org-peribolos/1253527213274304512
```
{"client":"github","component":"peribolos","file":"external/io_k8s_test_infra/prow/github/client.go:526","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateOrgMembership(kubernetes-incubator, pbx0, false)","time":"2020-04-24T03:36:44Z"}
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership\"}","file":"external/io_k8s_test_infra/prow/cmd/peribolos/main.go:517","func":"main.configureOrgMembers.func1","level":"warning", …
```
> Remove pbx0 from kubernetes-incubator

- config/kubernetes/sig-release/teams.yaml
Add CI Signal shadows for the 1.19 release cycle.
Ref: https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release_team.md#kubernetes-119-release-team
cc @hkamel @RobertKielty @sayanchowdhury @VineethReddy02 
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Add 1.19 release CI Signal team members

- config/kubernetes-sigs/org.yaml
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
I currently am a member of the k8s general org. I'm requesting access to the kubernetes-sigs org so that I can collaborate/review PRs on the service-apis project.
> sigs: add cmluciano to k8s-sigs org

- config/kubernetes/sig-release/teams.yaml
@justaugustus proposed that we add the release manager associates to the milestone-maintainers team, so we can triage stuff.
The list of the release manager associates can be found in the [sig-release repo](https://github.com/kubernetes/sig-release/blob/master/release-managers.md#associates).
/assign @justaugustus 
cc @markyjackson-taulia @sethmccombs @Verolop
> Add Release Manager Associates to milestone-maintainers

- config/kubernetes-csi/org.yaml
Ref: https://github.com/kubernetes/org/issues/1867
Also adds @andyzhangx to the kubernetes-csi org, since they are already a member of the @kubernetes org.
> Add GitHub teams for csi-driver-smb

- config/kubernetes-sigs/sig-scheduling/teams.yaml
Ref https://github.com/kubernetes-sigs/descheduler/issues/273#issuecomment-627096107
I was recently added as an approver to the kubernetes-sigs/descheduler repo, having admin access to the repo will enable me to assist with release branching and general maintenance of the repo going forward
> Add damemi to descheduler admins

- config/kubernetes-sigs/sig-network/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1328
`alexgervais` is now a member of kubernetes-sigs since https://github.com/kubernetes/org/issues/1689
> Add team member for ingress-controller-conformance

- OWNERS_ALIASES
ptone has stepped down as a lead
ref: https://github.com/kubernetes/community/pull/4778
> Update wg-iot-edge leads

- config/kubernetes/org.yaml
The repo is being archived - https://github.com/kubernetes/org/issues/1888
> Remove GitHub teams for kube-deploy

- config/kubernetes/sig-architecture/teams.yaml
This should make it simpler to ping everyone when chatting about enhancements-related items.
Note that `@enhancements` should be used for subproject-related issues, NOT Enhancement tracking issues (it'll be spammy for subproject owners otherwise).
/assign @johnbelamaric @mrbobbytables @jeremyrickard 
cc: @palnabarun @harshanarayana @kikisdeliveryservice @msedzins
> sig-arch: Add enhancements GitHub team for notifications

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-instrumentation/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1907
Also adds @ehashman and @logicalhan to kubernetes-sigs since they are already members of the kubernetes org.
> Add GitHub teams for instrumentation-tools

- config/kubernetes-sigs/org.yaml
(Needed for https://github.com/kubernetes/org/pull/1924)
Adds the following @kubernetes/release-engineering members to k-sigs: @hasheddan, @sethmccombs, @Verolop
> Add Release Manager Associates to kubernetes-sigs

- config/kubernetes-sigs/sig-release/teams.yaml
...so we can tag the team for reviews, etc.
(This may fail the presubmit as some @kubernetes/release-engineering members may not be k-sigs members.)
> sig-release: Add a release-engineering team to kubernetes-sigs

- config/kubernetes/org.yaml
- config/kubernetes/sig-cluster-lifecycle/teams.yaml
first commit:
- Clear inactive maintainers:
chuckha, errordeveloper, jamiehannaford, jbeda, liztio, lukemarsden,
medinatiger, pipejakob, stealthybox
Hope to see you again soon.
- Add rosti.
--------
second commit:
- Move the kubeadm teams to the SIG teams.yaml
> config/kubernetes/org.yaml: update kubeadm-maintainers

- config/kubernetes-sigs/org.yaml
Fixes: https://github.com/kubernetes/org/issues/1939
> Add yodahekinsew to kubernetes-sigs

- config/kubernetes-sigs/sig-release/teams.yaml
Grants Triage role to kubernetes-sigs/k8s-container-image-promoter
I've already granted the triage role on the repo; this adds @listx and @yodahekinsew to the team, so they can triage the https://github.com/kubernetes-sigs/k8s-container-image-promoter/projects/3 project.
/assign @tpepper @saschagrunert @alejandrox1 
ref: https://github.com/kubernetes/org/pull/1938, https://github.com/kubernetes/org/pull/1943, https://github.com/kubernetes/org/issues/1939
> sig-release: Add active image promoter contribs to release-engineering

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-storage/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1942
Also adds @brahmaroutu @copejon and @wlan0 to @kubernetes-sigs since they are already members of the @kubernetes GitHub org.
/assign @idealhack
> Add GitHub teams for COSI repos

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Related to the submission to move cluster-api-provider-packet to
kubernetes-sigs https://github.com/kubernetes/org/issues/1934
> Add cluster-api-provider-packet-admins and maintainers teams

- config/kubernetes-sigs/org.yaml
They are already a member of kubernetes.
This should resolve the issue when repo-infra is brought in as a submodule
ref: kubernetes-sigs/kubefed#1244
ref: https://kubernetes.slack.com/archives/C1TU9EB9S/p1593719089153000
ref: https://github.com/kubernetes/repo-infra/pull/193
/cc @cblecker
> Add clarketm to the kubernetes-sigs org

- config/config_test.go
- config/kubernetes/sig-docs/teams.yaml
Currently, we only check if teams have the `privacy: closed `field during review. Let's automate it :)
/cc @cblecker @mrbobbytables @spiffxp
> Add test to ensure teams have privacy:closed

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1974
Fixes https://github.com/kubernetes/org/issues/1982
Fixes https://github.com/kubernetes/org/issues/1987
Fixes https://github.com/kubernetes/org/issues/1998
> Add members 2020-07-07

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-cluster-lifecycle/teams.yaml
please review one commit at a time.
----
first commit:
Move the teams for the following sub projects:
- etcdadm
- kubespray
- kops
- minikube
Re-order the SIG teams alphabetically.
-----------
second commit:
"pr-reviews" is a redundant list, at this point. We can use
the main team for all the purposes.
Remove jbeda, liztio, karan, krousey, medinatiger, pipejakob, xiangpengzhao, zouyee.
Thank you for the past contributions!
> move SIG Cluster Lifecycle teams to SIG sub-folders and prune the main SIG team

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-docs/OWNERS
- config/kubernetes-sigs/sig-docs/teams.yaml
This PR updates repo admins to the current roster of [SIG Docs chairs](https://github.com/kubernetes/community/tree/master/sig-docs#chairs).
Related: https://github.com/kubernetes-sigs/reference-docs/pull/162/files#r451224287
/cc @jimangel @kbarnard10 
/sig docs
/priority important-soon
> Update reference docs permissions

- OWNERS_ALIASES
- config/kubernetes/sig-release/teams.yaml
To fulfill the role as new technical lead we need to be part of the SIG
release admin role.
Ref: https://github.com/kubernetes/community/pull/4867
/assign @kubernetes/sig-release-admins 
/cc @kubernetes/sig-release
> Add saschagrunert and alejandrox1 as SIG Release admins 

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-node/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1873
@pjbgf is a member of @kubernetes and is implicitly eligible for membership to k-sigs.
/assign @saschagrunert
> Add GitHub teams for seccomp operator

- OWNERS_ALIASES
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/wg-naming/OWNERS
- config/kubernetes-sigs/wg-naming/teams.yaml
- config/kubernetes/wg-naming/OWNERS
- config/kubernetes/wg-naming/teams.yaml
WG Naming, now with GitHub teams for notifications on the `kubernetes` and `kubernetes-sigs` GH orgs!
/assign @cblecker @nikhita 
/cc @celestehorgan @zacharysarah @jdumars 
Formation PR: https://github.com/kubernetes/community/pull/4884
> Add WG Naming teams

- config/kubernetes/sig-testing/teams.yaml
Also adds `repo-infra-admins` team.
Discussed with @fejta earlier today.
k/repo-infra is in the critical path for Release Engineering work, both
as a consumer in k/release, and as owners for the Go update process.
Adding myself as an admin here to help maintain the repo and cut releases.
/assign @fejta @BenTheElder @spiffxp @mikedanese 
cc: @kubernetes/release-engineering 
ref: https://github.com/kubernetes/repo-infra/pull/195
> sig-testing: Add justaugustus to repo-infra teams

- config/kubernetes-sigs/sig-testing/teams.yaml
ref: https://github.com/kubernetes-sigs/secret-sync-rotation/issues/3
> Renaming secret-sync-rotation to k8s-gsm-tools

- config/kubernetes-sigs/sig-service-catalog/teams.yaml
Following up on https://github.com/kubernetes/org/issues/2019, this PR adds f0rmiga (me) from SUSE as a Minibroker admin.
> Add f0rmiga as adminstrator to minibroker repo

- config/kubernetes-client/org.yaml
- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-auth/teams.yaml
- config/kubernetes/sig-node/teams.yaml
- config/kubernetes/sig-openstack/teams.yaml
- config/kubernetes/sig-scheduling/teams.yaml
- config/kubernetes/sig-storage/teams.yaml
ref: https://github.com/kubernetes/org/issues/2013
/assign @cblecker @nikhita 
FYI regarding team removal: Members that were a part of a team should be removed, but if the team is still in the main org.yaml file, it won't have the additional commit msg.
I'll upload the script I used to do it in a separate PR. 
/hold
> Remove inactive members

- config/kubernetes/sig-scalability/teams.yaml
- Drop extraneous teams
- Add '-leads' team
- Update membership to include all scale OWNERS
- Add key SIG Release personnel to main GH team
Discussed in a few SIG Release (RT/RelEng) meetings, that we need tighter interlock with Scale.
Part of https://github.com/kubernetes/community/issues/2323
/assign @mm4tt @shyamjvs @wojtek-t
cc: @kubernetes/sig-release-admins @hasheddan @LappleApple 
/hold for SIG Scalability approval
> sig-scalability: Prune/update teams

- config/kubernetes/sig-release/teams.yaml
unclear which of the other entries should be removed
See: https://github.com/kubernetes/sig-release/issues/1150
> add current actual google build admins to build-admins

- config/kubernetes-sigs/org.yaml
Needed for https://github.com/kubernetes-sigs/contributor-tweets/issues/2#issuecomment-663598159. They are already a member of @kubernetes and are doing amazing work in the contribex marketing team. :) 
/assign @rajula96reddy
> Add rajula96reddy to kubernetes-sigs org

- config/kubernetes/sig-release/teams.yaml
Based on https://github.com/kubernetes/enhancements/pull/1554, as a sig lead for instrumentation I should be able to triage PRs.
cc @brancz @logicalhan
> Add dashpole and logicalhan to milestone maintainers

- config/kubernetes/sig-cluster-lifecycle/teams.yaml
Updating Kops maintainers section to match Kops approvers:
https://github.com/kubernetes/kops/blob/4e3a5d2d36dfd3a23fe3bd4352c83f038fb546b5/OWNERS#L13-L21
/cc @justinsb @rifelpet @johngmyers
> Update Kops maintainers

- config/kubernetes/sig-testing/teams.yaml
chaodaiG just started oncall rotation, add to this group for admin access of test-infra
> Add chaodaiG as test-infra-maintainers

- config/kubernetes/sig-docs/teams.yaml
fixed: #2089
Updated teams.yaml according to OWNER_ALIAS on k/website.
https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L116-L127
> Update sig-docs-ja member

- config/kubernetes-client/OWNERS
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/OWNERS
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/OWNERS
- config/kubernetes-sigs/OWNERS
- config/kubernetes-sigs/org.yaml
- config/kubernetes/OWNERS
ref: https://github.com/kubernetes/community/pull/4995
/hold
until https://github.com/kubernetes/community/pull/4995 merges
Since the whole roster of NMCs is new, this adds the new NMCs as reviewers in OWNERS files. They will be moved to approvers after a month. :+1: 
I haven't added new folks to k-incubator because we intend to shut down the org.
/assign @cblecker @mrbobbytables 
cc @ameukam @palnabarun @savitharaghunathan
> Update New Membership Coordinators in OWNERS files

- config/kubernetes-sigs/org.yaml
II'm already a member of `kubernetes` org and was added in https://github.com/kubernetes/org/issues/1936.
This PR is adding me to the `kubernetes-sigs` org.
Thanks!
> Add chizhg to kubernetes-sigs org

- config/kubernetes/sig-docs/teams.yaml
As per slack discussion https://kubernetes.slack.com/archives/CGB1MCK7X/p1597166062151500, adding @Fale as approver for the IT localization of the website
xref https://github.com/kubernetes/website/pull/23098
/assing @rlenferink 
/cc @Fale
> Add fale to IT approver

- config/kubernetes/org.yaml
My username changed a while ago but noticed that some automation systems are case sensitive.
> config/kubernetes/org.yaml: Change to new github username

- config/kubernetes/sig-contributor-experience/teams.yaml
- config/kubernetes/sig-release/teams.yaml
SIG Release:
- Add `sig-release-leads` team (Chairs, Technical Leads, and Program Managers for SIG Release)
- Add `sig-release-pms` team (Grants access to maintain SIG Release project boards)
SIG ContribEx:
- Add @LappleApple to `project-board-maintainers`
@kubernetes/sig-release-admins @kubernetes/sig-contributor-experience-leads 
/assign @tpepper @mrbobbytables
> Grant Lauri access to manage some project boards

- config/kubernetes-sigs/sig-network/teams.yaml
This adds @hbagdi, @jpeach, and myself as new maintainers for the [Service APIs subproject](https://github.com/kubernetes-sigs/service-apis). 
/cc @bowei
/sig network
> Adding new service-apis maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
https://github.com/ericzhang08 doesn't exist anymore and it broke peribolos.
Ref: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-org-peribolos/1298662606931759104
```
{"client":"github","component":"peribolos","file":"external/io_k8s_test_infra/prow/github/client.go:526","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateOrgMembership(kubernetes, ericzhang08, false)","time":"2020-08-26T17:02:48Z"}
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","file":"external/io_k8s_test_infra/prow/cmd/peribolos/main.go:517","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembe …
```
> Remove ericzhang08 from kubernetes, kubernetes-sigs

- config/kubernetes-sigs/sig-service-catalog/teams.yaml
Add jhvhs as a maintainer on SIG Service Catalog.
/cc @mszostok
> add jhvhs to sig-service-catalog-maintainers

- config/kubernetes/sig-docs/teams.yaml
This PR removes @makoscafee from SIG Docs teams by updating k/org with changes from https://github.com/kubernetes/website/pull/23631.
/assign @jimangel @kbarnard10
> Remove makoscafee from docs teams

- config/kubernetes/sig-release/teams.yaml
This PR does some updates related to 1.20 kicking off: 
* Updated milestone maintainers to remove 1.19 release team folks (thank you for your service!) and add 1.20 incoming leads (thank you for volunteering)
* Updates @mrbobbytables to be labeled as ContribEx instead of 1.19 RT Lead Shadow
* Updates release-team to reflect 1.20 team
* Updates the ci-signal team to remove 1.19 shadows and make @RobertKielty the lead (he can add shadows once selected).
ref: https://github.com/kubernetes/sig-release/issues/1201 https://github.com/kubernetes/sig-release/issues/1185
/hold
/sig release
/area release-eng release-team
cc: @kubernetes/release-engineering @kubernetes/release-team @kubernetes/milestone-maintainers
Signed-off-by: Jeremy Rickard <rickardj@vmware.com>
> 1.20 Release Updates 

- config/kubernetes-sigs/org.yaml
I'm a kubernetes org member and I am working on scheduler-plugins (coscheduling with PodGroup CRD， kubernetes-sigs/scheduler-plugins#42), I would like to be a member to help me send PRs more conveniently.
I have contributed a lot to Kubernetes.
56 merged PRs: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Amerged+author%3Acwdsuzhou
83 reviewed PRs: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+reviewed-by%3Acwdsuzhou
68 issues commented: https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Acwdsuzhou
> Add cwdsuzhou as a member of kubernetes-sigs

- config/kubernetes-sigs/org.yaml
Hi, according to this [guide](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) I open this PR to add myself to kubernetes sigs org to 
- PRs reviewed / authored
- https://github.com/kubernetes-sigs/kustomize/pulls?q=is%3Apr+is%3Aclosed+author%3AShell32-Natsu
- Issues responded to
- https://github.com/kubernetes-sigs/kustomize/issues?q=is%3Aissue+mentions%3A%40me+
- SIG projects I am involved with
- kustomize
> Add Shell32-natsu as a member of kubernetes-sigs

- OWNERS_ALIASES
wg-machine-learning has been retired
ref: https://github.com/kubernetes/community/issues/5034
> Remove wg-machine-learning from OWNERS_ALIASES

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-release/teams.yaml
- Add @Pluies to kubernetes-sigs org
Florent is a maintainer of k-sigs/zeitgeist and requires access to
continue maintaining the repo.
ref: https://github.com/kubernetes/org/issues/2172#issuecomment-688752677
Closes: https://github.com/kubernetes/org/issues/2181
- sig-release: Add @Pluies and @yastij as k-sigs/zeitgeist maintainers
ref: https://github.com/kubernetes/org/issues/2172#issuecomment-688763264
/assign @nikhita @saschagrunert 
cc: @kubernetes/release-engineering
> sig-release: Add Pluies and yastij as k-sigs/zeitgeist maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Part of onboarding issues for @xmudrii, @puerco, @mkorbi, @gianarb, and @onlydole: https://github.com/kubernetes/sig-release/issues/1226, https://github.com/kubernetes/sig-release/issues/1227
/assign @nikhita @mrbobbytables 
/cc  @tpepper @saschagrunert @alejandrox1
cc: @kubernetes/release-engineering
> sig-release: Update Release Manager groups

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
I tend to be the one who admins this repo the most, and right now there is an [open issue](https://github.com/kubernetes-sigs/image-builder/issues/216) to modify the repo's about section to include a doc link. I need admin access to do so.
/assign @timothysc @justinsb 
/cc @detiber
> Add codenrhoden as admin for image-builder repo

- config/kubernetes/sig-docs/teams.yaml
I want to join the sig-docs-zh team: 
I've become reviewer for zh docs.
I have worked for website for a long time.
So far, I have participated in website pr(460+) and issue (15+).
I hope I can have more permissions to make more contributions to the zh localization of the website.
https://github.com/kubernetes/website/pulls?q=is%3Apr+assignee%3Atanjunchen+is%3Aclosed   196 
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Atanjunchen+is%3Aclosed  106
https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3A%40me+    132
https://github.com/kubernetes/website/issues?q=is%3Aopen+is%3Aissue++tanjunchen+  16 
such as https://github.com/kubernetes/website/issues/17649、https://github.com/kubernetes/website/issues/18411
/cc @tengqm
> add tanjunchen to sig-docs-zh team

- config/kubernetes/sig-release/teams.yaml
As part of the onboarding process for the 1.20 release team, adding 1.20 Docs Shadows to release-team 
/sig release
/assign @justaugustus @alejandrox1 @tpepper @saschagrunert 
cc @jeremyrickard @savitharaghunathan @hasheddan @palnabarun @lachie83
> Add 1.20 RT docs shadows to the release team

- config/kubernetes/sig-release/teams.yaml
This adds 1.20 CI Signal Shadows to Release Team
/sig release
/assign @justaugustus @alejandrox1 @tpepper @saschagrunert
cc @jeremyrickard @savitharaghunathan @hasheddan @palnabarun @lachie83
> Add 1.20 CI Signal Shadows to release-team and ci-signal team

- config/kubernetes/sig-docs/teams.yaml
As part of the onboarding process for the 1.20 release team, adding 1.20 Docs Shadows and Lead to website milestone maintainers
/sig docs
cc @reylejano-rxm @SomtochiAma @eagleusb @kcmartin 
/assign @jimangel @sftim @irvifa
> Add 1.20 Release Docs team to website milestone maintainer team

- config/kubernetes-sigs/sig-network/teams.yaml
This is a follow up to https://github.com/kubernetes/org/pull/2118. 
/sig network
/cc @danehans @hbagdi @jpeach
/assign @bowei
> Adding Daneyon as a Service APIs maintainer

- config/kubernetes-sigs/sig-multicluster/teams.yaml
- config/kubernetes-sigs/sig-service-catalog/teams.yaml
This team was added to SIG Service Catalog in error. I think it's supposed to be part of SIG multicluster, but I'm not really sure. I can edit the PR to add it to there if that is in fact where it's supposed to be.
/cc @pmorie 
/cc @JeremyOT
> remove mcs-api-admins team from sig service catalog teams

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-docs/teams.yaml
- config/kubernetes/sig-docs/teams.yaml
ref: https://github.com/kubernetes/website/issues/23797
Don't merge this PR until all conditions are true:
This PR updates repo permissions and contacts for @irvifa becoming a chair and @zacharysarah transitioning to chair emeritus.
/assign @irvifa @jimangel @kbarnard10
> SIG Docs chair transition 2020

- config/kubernetes/sig-architecture/teams.yaml
- Add Lauri Apple as an Enhancements subproject owner
- Update Enhancements teams for 1.20 release cycle
/assign @dims @johnbelamaric @derekwaynecarr 
cc: @kubernetes/enhancements @LappleApple @kikisdeliveryservice 
ref: https://groups.google.com/g/kubernetes-sig-architecture/c/_LcElBQ0uc8, https://kubernetes.slack.com/archives/C5P3FE08M/p1601585313029600, https://github.com/kubernetes/enhancements/pull/2077
> sig-architecture: Update Enhancements teams

- config/kubernetes-sigs/sig-node/teams.yaml
Renaming the operator to it's new proposed name.
Refers to https://github.com/kubernetes/org/issues/2177
> Rename seccomp-operator to security-profiles-operator

- config/kubernetes-sigs/sig-cli/teams.yaml
Chris has been taking on a pretty active role in Krew over the past 6 months. He was the primary driver of implementing decentralized plugin repositories in krew ([meta-issue](https://github.com/kubernetes-sigs/krew/issues/566), [issues & PRs](https://github.com/kubernetes-sigs/krew/issues?q=label%3Aarea%2Fmulti-index+author%3Achriskim06+)).
Since the successful launch of this feature he continued his work on krew through PR reviews and [fixes](https://github.com/kubernetes-sigs/krew/issues?q=author%3Achriskim06+created%3A%3E%3D2020-08-19+).
Chris should therefore have maintainer rights for krew, so that he can continue his work more efficiently.
@chriskim06
@ahmetb
> Add Chris Kim as Krew maintainer

- OWNERS_ALIASES
- config/kubernetes/org.yaml
Update membership with the results of the 2020 SC election.
/committee steering
ref: https://github.com/kubernetes/steering/issues/180
> steering: update OWNERS_ALIASES and teams

- config/kubernetes-sigs/sig-release/teams.yaml
- Remove Caleb, HH
- Add Justin SB, Sascha
Part of CIP repo improvements: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/266
/assign @saschagrunert @tpepper 
cc: @listx @kubernetes/release-engineering
> sig-release: Update container-image-promoter teams

- config/kubernetes-client/OWNERS
- config/kubernetes-csi/OWNERS
- config/kubernetes-sigs/OWNERS
- config/kubernetes/OWNERS
The current New Membership Coordinators have been _amazing_ at working through all the incoming membership requests. They've also been very careful around adding new members and have not been hesitant to ask questions when in doubt.
I think it's time we promote @ameukam @palnabarun and @savitharaghunathan to approvers! :tada: :tada: :tada: 
We also discussed this in the GitHub Management today and there were lots of +1s!
/hold
for ack by other approvers
/cc @kubernetes/owners 
/assign @cblecker @mrbobbytables @spiffxp
> Promote NMCs to approvers for active orgs

- config/kubernetes-sigs/sig-cli/teams.yaml
Opened in consultation with @pwittrock. 
This PR gives me admin rights to the `cli-experimental` repo in order to set up a custom domain for the repo in Netlify.
Permissions are temporary and should be removed no later than 15 November 2020.
/assign @pwittrock
> Temporary admin permissions to set up a site in Netlify

- config/kubernetes/sig-release/teams.yaml
This PR updates the release-team members to reflect the entire 1.20 team (we had missed a few shadows). I also updated some of the comments just for consistency.
/hold until reviewed by sig-release leads and RT sub team leads
/sig release
ref #kubernetes/sig-release#1306
cc: @kubernetes/release-engineering @kubernetes/release-team 
Signed-off-by: Jeremy Rickard <rickardj@vmware.com>
> Update release-team membership to reflect all shadows

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-release/teams.yaml
- Add n3wscott to kubernetes-sigs org (fixes: https://github.com/kubernetes/org/issues/2299)
- sig-release: Add n3wscott to zeitgeist-maintainers
cc: @n3wscott @kubernetes/release-engineering
> sig-release: Add n3wscott to zeitgeist-maintainers

- config/kubernetes-sigs/sig-cli/teams.yaml
With the Netlify site integration added and a [PR opened to add the site](https://github.com/kubernetes/org/pull/2287), I'm removing myself from SIG CLI admins [as specified](https://github.com/kubernetes/org/pull/2286). 
/assign @pwittrock
> Remove myself as a SIG CLI admin

- config/kubernetes/org.yaml
This fixes peribolos: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-org-peribolos/1324535322997952512
The GitHub user https://github.com/skilxn-go renamed their username to @Ye-Tian-Zero. The rename broke peribolos. 
Ref: https://github.com/kubernetes/org/issues/1607 
fyi @Ye-Tian-Zero
> Replace skilxn-go with Ye-Tian-Zero

- config/kubernetes/sig-release/teams.yaml
E_TOOMANY, since @kubernetes/release-engineering uses team mentions a lot.
/assign @BenTheElder @hasheddan
cc: @kubernetes/build-admins 
ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1605031002183800
> sig-release: Unnest build-admins from release-engineering

- config/kubernetes/sig-docs/teams.yaml
Updated teams.yaml according to OWNER_ALIAS on k/website.
https://github.com/kubernetes/website/pull/24922
@kakts is already an org member so there's no issue for this PR.
> Update SIG-docs-ja reviewers

- config/kubernetes/org.yaml
- config/kubernetes/sig-docs/teams.yaml
This will fix the currently broken peribolos - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-org-peribolos/1326241899245211648
https://github.com/mistyhacks does not exist anymore. They probably moved to https://github.com/mdlinville but it looks like they have stepped away from the project - https://github.com/kubernetes/website/pull/16694. 
> Remove mistyhacks to fix peribolos

- config/kubernetes/org.yaml
I was wondering why @derekwaynecarr was able to edit my PR to update a release note and i could not edit other's PR and found this group.
Also, we may need to prune this group at some point (cc @kubernetes/owners)
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
> Add dims as k8s maintainer

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-windows/teams.yaml
Moving windows-testing admins/maintainers groups from config/kuberntees-sigs/org.yaml to config/kubernetes-sigs/sig-windows/teams.yaml to keep things tidy.
> Moving windows-testing admin/maintainer groups under sig-windows/teams.yaml

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/sig-release/teams.yaml
The access portion of: https://github.com/kubernetes/sig-release/pull/1331
- Promote @puerco to full-fledged Release Manager
- Add @ameukam as Release Manager Associate
- Tim, @hoegaarden, and @dougm retire as Release Managers
- @tpepper is now Emeritus Chair
...but remains as subproject owner!
- @hasheddan joins as SIG TL and Senior Release Manager
- @saschagrunert moves from TL to Chair
- Sync SIG Release k-sigs teams from k org config
- Drop inactive maintainers
- OWNERS: Sync aliases from k/community
/assign @cblecker @mrbobbytables 
/cc @saschagrunert @hasheddan 
cc: @kubernetes/sig-release-leads @kubernetes/release-engineering
> Update SIG leadership and Release Managers (promotions, new members, retirement)

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2305
fixes #2327
fixes #2328 
fixes #2329
fixes #2335
fixes #2345
PS: #2235 is partially fixed with #2337. Adding the user to @kubernetes in this PR. Will `/approve` #2337 after this goes in.
/assign @savitharaghunathan @ameukam
> Add members 2020-11-25

- config/kubernetes/org.yaml
- config/kubernetes/sig-docs/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Fixes https://github.com/kubernetes/org/issues/2348
https://github.com/reylejano-rxm does not exist anymore and they have
changed their username to https://github.com/reylejano.
Ref:
- https://github.com/kubernetes/org/issues/1555
- https://github.com/kubernetes/org/issues/2348
This fixes peribolos - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-org-peribolos/1332512581797023744
fyi @reylejano
> Fix reylejano's username

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2350
Adding just the admins team because the list of folks with admin and write access is the same.
> Add GitHub team for kubectl-check-ownerreferences

- cmd/merge/main.go
Refine too many args for fmt string.
Same time I think the String maybe wrong.
Like:
key = b, value = "b.yaml"
key = a, value = ""
It will generate `b=b.yaml,a,a=`.
> Refine too many args for fmt string

- config/kubernetes-csi/org.yaml
Fixes https://github.com/kubernetes/org/issues/2371
> k-csi: remove GitHub teams for fibre-channel and flex repos

- config/kubernetes-sigs/org.yaml
Needed for https://github.com/kubernetes-sigs/contributor-tweets/pull/30  They are already a member of @kubernetes and also part of the contribex marketing sub-project
/assign @Pensu
> Add Pensu to kubernetes-sigs org

- config/kubernetes/sig-docs/teams.yaml
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Remove me from `website-maintainers`
- Remove 1.20 shadows except for Rey (1.21 lead) from `website-milestone-maintainers`
cc @kubernetes/sig-docs-leads @reylejano
> Remove 1.20 shadows from sig docs teams

- config/kubernetes-sigs/org.yaml
coderanger
kubernetes-sigs
@pwittrock 
Kubernetes Org Member, controller-runtime/Kubebuilder helper
> Add coderanger to kubernetes-sigs

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
@floryut has been driving the past couple of releases of Kubespray (see https://github.com/kubernetes-sigs/kubespray/issues/6535) but doesn't have to forge releases & tags. Let's welcome @floruyt to the maintainer's team.
> Add floryut as a Kubespray maintainer

- config/kubernetes-sigs/sig-storage/teams.yaml
This PR adds kmova as admin to the following projects:
- kubernetes-sigs/nfs-subdir-external-provisioner
- kubernetes-sigs/nfs-ganesha-server-and-external-provisioner
Fixes: https://github.com/kubernetes/org/issues/2389
/cc @msau42 @xing-yang @saad-ali @jsafrane 
Signed-off-by: kmova <kiran.mova@mayadata.io>
> add kmova as admin to nfs provisioner projects

- config/kubernetes-csi/org.yaml
This PR adds Jiawei0227 to the livenessprobe and node-driver-registrar repo maintainer.
/cc @msau42
> Add Jiawei0227 to kubernetes-csi maintainer

- config/kubernetes/sig-docs/teams.yaml
Add @yoonian to sig-docs-ko-reviewes. (Reviewer for Korean l10n contents)
This k/org update is based on kubernetes/website#25850
> Add yoonian to sig-docs-ko-reviews

- config/kubernetes/sig-release/teams.yaml
- Add RT Lead, EA, RT Lead shadows and Role Leads to
- `milestone-maintainers`
- `release-team`
- Add RT Lead, EA, RT Lead Shadows to `release-team-leads`
- Add CI Signal Lead to `ci-signal`
ref: https://github.com/kubernetes/sig-release/issues/1404
/assign
/sig release
/area release-team
/assign @justaugustus @saschagrunert @jeremyrickard @hasheddan @alejandrox1
/cc @kikisdeliveryservice @savitharaghunathan @bai
> Update SIG Release teams for 1.21 Release

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
A change to the CAPA maintainers/admins.
For reference, [current CAPA mainatiners](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/OWNERS_ALIASES#L22).
/cc @randomvariable
> chore: update with additional CAPA maintainers

- config/kubernetes/sig-release/teams.yaml
Adds jeremyrickard to the appropriate sig-release github teams as part
of technical lead onboarding.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
xref https://github.com/kubernetes/sig-release/issues/1421
/assign @justaugustus @saschagrunert 
/hold
> teams: Add jeremyrickard as SIG Release Technical Lead

- OWNERS_ALIASES
as per https://github.com/kubernetes/community/pull/5386, i am stepping down from sig-windows chair.
updating with the new chairs and TLs for sig-windows
ref https://github.com/kubernetes/org/pull/2416
Signed-off-by: Michael Michael <michmike@cs.stanford.edu>
> michmike vacating sig-windows chair position

- config/kubernetes/sig-release/teams.yaml
- Adds 1.21 CI Signal shadows to the release-team, ci-signal teams
- Removes 1.20 CI Signal shadows from those teams
Welcome to the team, y'all! 🎉 
/cc @mkorbi @n3wscott @PriyankaH21 @s278gupt
> Update 1.21 CI Signal shadows for release-team, ci-signal

- config/kubernetes/sig-release/teams.yaml
Adding new bug triage team members and cleaning up old team members from
1.20.
Resolves #2423, #2425.
> Update for teams.yaml for Bug Triage 1.21

- config/kubernetes/sig-release/teams.yaml
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
Add 1.21 Enhancements Shadows to `milestone-maintainers` and `release-team` github teams
/hold for feedback on if shadows should be added to the milestone maintainers team. I think they should have the ability to remove/add milestone on enhancement/issues.
/assign @palnabarun @kikisdeliveryservice @savitharaghunathan @bai
> Add 1.21 Enhancements shadows to github teams

- config/kubernetes/sig-architecture/teams.yaml
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Add 1.21 Enhancements team to `sig-architecture` github team `enhancements`
- Remove 1.20 Shadows from the `enhancements` team
/assign @palnabarun @savitharaghunathan @kikisdeliveryservice @bai 
note: This was missed in the previous PR https://github.com/kubernetes/org/pull/2442. I will do a follow-up to add this step to the enhancements role handbook as well.
> Add 1.21 Enhancements team to github enhancements team

- config/kubernetes/sig-docs/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Add 1.21 Docs Shadows to `website-milestone-maintainers` in  sig-docs/teams.yaml and `release-team` in sig-release/teams.yaml GitHub teams
/assign @palnabarun @kikisdeliveryservice @savitharaghunathan @bai
/hold for feedback if shadows should be added to the `website-milestone-maintainers` team. 
I think they should have the ability to add the 1.21 milestone on kubernetes/website PRs.
> Add 1.21 Docs Shadows to GitHub teams

- config/kubernetes-sigs/sig-testing/teams.yaml
As per https://github.com/kubernetes-sigs/kind/issues/2024 and https://github.com/kubernetes-sigs/kind/pull/2025.
Add @amwat and @aojea to the `kind-maintainers` and `kind-admins` teams 🎉 
/cc @BenTheElder
> Add amwat and aojea to kind-{admins,maintainers}

- config/kubernetes-sigs/org.yaml
I am a current Member of Kubernetes, and would like to be added to K-SIGs to start on the path towards becoming a Reviewer.
> Add celanthe to k-sigs org

- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Hey! After a few iterations in sig-release and after a few months helping
as an Associate, I am stepping back.
I recently spoke with a couple of teammates in the sig release and I value
the title I am holding, and I am sure other people from the community
want to contribute as an Associate. Now I have a better idea about how to
contribute and I don't need a title for that.
> Retire from my role as Release Associate

- config/kubernetes/sig-testing/teams.yaml
specifically:
- add sig-testing/sig-testing-leads
- move sig-testing-pr-reviews under sig-testing
---
META: this was mostly a PR to verify what creating a new PR from an old local clone looks like following a rename of this repo's default branch
> Setup SIG Testing subteams

- config/kubernetes-sigs/org.yaml
This should have been originally added as part of #2455, but I forgot to include `kubernetes-sigs` in the request.
> Add shysank to kubernetes-sigs members

- config/kubernetes-sigs/sig-instrumentation/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2182
Only adding the admins GitHub team since the list of folks with admin and write access is the same.
> Add GitHub team for prometheus-adapter

- config/kubernetes-sigs/sig-multicluster/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2468
https://github.com/qiujian16 is not a kubernetes/k-sigs GitHub org member and would need to apply for membership.
> Add GitHub team for work-api repo

- config/kubernetes-sigs/sig-network/teams.yaml
This accompanies https://github.com/kubernetes-sigs/service-apis/pull/541 and related discussion in https://github.com/kubernetes-sigs/service-apis/issues/536. Not quite sure what the correct order of operations here is.
> Renaming Service APIs to Gateway API

- config/kubernetes/sig-instrumentation/teams.yaml
This PR:
- pares down instrumentation to just three GitHub teams: leads, approvers (as defined in k/k/OWNERS_ALIASES), and members
- removes all inactive members
I am defining "inactive" as [<50 contributions on devstats for the past year](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All) **and** does not attend [regular SIG meetings](https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#).
This is part of our SIG review for our annual report. I will be following this up with a PR to add active members who aren't yet on the list.
/cc @logicalhan
> SIG Instrumentation members cleanup

- config/kubernetes/org.yaml
Org counterpart to https://github.com/kubernetes/security/pull/121
/assign @cji
> Offboard Craig

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
As per https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/234#issuecomment-779840516:
* I'm stepping down as a project maintainer
* @timoreimann is promoted to a project maintainer
This PR:
* Removes me from the `cluster-api-provider-digitalocean-admin` and the `cluster-api-provider-digitalocean-maintainers` teams
* Adds @cpanato to the `cluster-api-provider-digitalocean-admin` team
* Adds @timoreimann to the `cluster-api-provider-digitalocean-maintainers` team
/assign @cblecker @dims 
/cc @cpanato @MorrisLaw @prksu @timoreimann
> cluster-api-provider-digitalocean: Update team membership

- config/kubernetes-sigs/org.yaml
For https://github.com/kubernetes-sigs/contributor-playground/pull/586
Divya is already a member of @kubernetes 
/assign @divya-mohan0209 @palnabarun
> Add divya-mohan0209 to kubernetes-sigs

- config/kubernetes/sig-release/teams.yaml
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
`milestone-maintainers` was downgraded to `Triage` role and no longer have `Write` access to the k/enhancements repo. Updating the description to reflect the latest change. 
ref: https://github.com/kubernetes/enhancements/issues/590#issuecomment-760635910
> Edit description for milestone-maintainers to reflect triage access

- config/kubernetes/sig-docs/teams.yaml
Adding Seokho Son as a website milestone maintainer to support the KO localization efforts.
/sig docs
/cc @seokho-son
> updating Korean website milestone maintainers

- config/kubernetes-sigs/sig-instrumentation/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2527
> Remove GitHub teams for mutating-trace-admission-controller

- config/kubernetes-sigs/org.yaml
YuikoTakada is already member of kubernetes org.
To join her to mentors at upstream training in Japan, add her to kubernetes-sigs member.
> Add YuikoTakada to kubernetes-sigs member

- config/kubernetes/sig-instrumentation/teams.yaml
All members on this list have been identified as regular SIG Instrumentation contributors over the past year. We would like to thank and welcome all of you to the GitHub team!
cc @kubernetes/sig-instrumentation-leads
> Welcome new SIG Instrumentation contributors

- config/kubernetes-sigs/org.yaml
gavinfish is already member of kubernetes org.
Need kubernetes-sig org membership to work on descheduler.
> Add gavinfish to kubernetes-sig org

- hack/remove-members.sh
This was originally opened in PR #2048  where it was desired that this script be replaced with a go version. Issue #2052 was created with that purpose, but hasn't been moved on yet. It's probably better that this get merged for now instead of living only on my local system. 😬 
It can be removed once the tool is written.
/cc @nikhita
> Add remove-members helper script

- config/kubernetes/sig-docs/teams.yaml
Sync maintainers with OWNERS_ALIASES(https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES):
- @devlware 
- @jhonmike 
Add new maintainers to Portuguese team:
- @jailton 
- @rikatz 
- @yagonobre 
/cc @femrtnz @jcjesus
> Update maintainers of sig-docs Portuguese team.

- config/kubernetes/sig-docs/teams.yaml
@alexbrand is stepping down from the sig-docs team as owner. This PRs removes him from the owner and maintainer teams, will remain part of the team sig-docs-es reviewer.
@electrocucaracha will be the new owner for the sig-docs-es team.
/cc @alexbrand
> feat: update sig-docs-es member list

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Adding @timoreimann as admin to the cluster-api-provider-digitalocean repo to have a backup maintainer in case I'm not available 
Timo is maintainer of CAPDO and also works for DO
> add timoreimann as admin for cluster-api-provider-digitalocean

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/org.yaml
- config/kubernetes/wg-k8s-infra/OWNERS
- config/kubernetes/wg-k8s-infra/teams.yaml
Prompted by wg-k8s-infra leads rotation: https://github.com/kubernetes/community/pull/5633
But tried to pay down some org debt and refresh members while I was here
See commits for details
> teams: refresh wg-k8s-infra teams

- config/kubernetes-sigs/sig-auth/teams.yaml
Give the two HNC leads (@adrianludwin and @yiqigao217) write access to wg-multitenancy so they can set milestones on issues (note that the milestone bot isn't active on this repo)
Approved by @tashimi
> New wg-multitenancy maintainers

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
I just found out via the issue above that actually none of the maintainers of CAPO 
has admin access to the CAPO repository. It would be nice to get that.
I don't know how the general policy in the ClusterAPI project is regarding this rights.
So feel free to reject the request :)
xref: https://github.com/kubernetes/org/issues/2580
> Add sbueringer to cluster-api-provider-openstack-admins

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
A change to the  cluster-api-provider aws maintainers/admins.
For reference, [current CAPA maintainers.](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/OWNERS_ALIASES#L22)
/cc @randomvariable
/cc @richardcase
> Update cluster-api-provider aws maintainer list

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2410
Also adds @mcluseau to the k-sigs org since they are already a kubernetes org member
> Add GitHub teams for kpng repo

- config/kubernetes-csi/org.yaml
This will make it simpler to release new versions of that component.
> kubernetes-csi: pohly as admin of csi-driver-host-path

- config/kubernetes/sig-docs/teams.yaml
Requesting temporary write access to the website repo for the 1.21 release per the [Release Docs Handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#request-for-temporary-write-access-to-website-repo)
/assign @jimangel @irvifa @kbarnard10
> Request temporary write access to website repo for the 1.21 release

- config/kubernetes/sig-docs/teams.yaml
- Remove me from `website-maintainers`
- Remove 1.21 shadows except for Victor (1.22 release docs lead) from `website-milestone-maintainers`
cc @kubernetes/sig-docs-leads @PI-Victor
> Remove 1.21 shadows from sig docs team

- config/kubernetes-csi/org.yaml
Required for performing releases of the CSI external-provisioner.
@msau42
> kubernetes-csi: Add chrishenzie as maintainer of external-provisioner

- config/kubernetes/sig-storage/teams.yaml
We occassionally need to rerun an image build job for a tagged release
because QEMU sometimes is flaky. Members of this team will be able to
trigger that themselves instead of having to track down someone from
test-infra.
> sig-storage: create team for use in image publishing job config

- .github/ISSUE_TEMPLATE/repo-create.md
Ref: https://github.com/kubernetes/org/issues/2589#issuecomment-809548423
While this link is also mentioned in the "Approvals" section, most
folks don't read it. So this commit explicitly mentions it in a comment
in the issue template.
cc @cblecker @spiffxp
> .github: add link to repo donation rules in issue template

- config/kubernetes/org.yaml
I am already a member of kubernetes-sig (https://github.com/kubernetes/org/issues/2317) and need kubernetes membership for prow and image promotion.
> add tam7t to kubernetes org

- config/kubernetes/sig-release/teams.yaml
- Add RT Lead, EA, RT Lead shadows and Role Leads to
- milestone-maintainers
- release-team
- Add RT Lead, EA, RT Lead Shadows to release-team-leads
- Add CI Signal Lead to ci-signal
ref: https://github.com/kubernetes/sig-release/issues/1522
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @hasheddan
/cc @annajung @divya-mohan0209 @erismaster @kikisdeliveryservice
> Update SIG Release teams for 1.22 Release

- config/kubernetes/sig-docs/teams.yaml
This PR removes @reylejano's temporary write access to the website repo for the 1.21 release
/hold until 1.21 is released, scheduled for 4/8/2021
/assign @jimangel @irvifa @kbarnard10
> Remove temporary write access to website repo for 1.21 for Rey

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-architecture/OWNERS
- config/kubernetes-sigs/sig-architecture/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2636
Also adds @navidshaikh to k-sigs - Navid is already a member of @kubernetes and has implicit membership to k-sigs.
> Add GitHub teams for depstat repo

- config/kubernetes-sigs/sig-storage/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2631
> Add GitHub teams for cosi-driver-minio

- OWNERS_ALIASES
- config/kubernetes-sigs/wg-naming/teams.yaml
- config/kubernetes/sig-docs/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/wg-naming/teams.yaml
This PR removes myself as a lead of WG-Naming and member of SIG Docs teams as part of going emeritus.
Related PRs:
- https://github.com/kubernetes/community/pull/5733
> Going emeritus, removing myself from WGs and SIGs

- config/kubernetes/sig-release/teams.yaml
- Adds 1.22 CI Signal shadows to the release-team, ci-signal teams
- Removes 1.21 CI Signal shadows from those teams
Welcome to the team, y'all! 🎉
> Update 1.22 CI Signal shadows for release-team, ci-signal

- config/kubernetes/sig-docs/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Add users for v1.22 Release team as part of the sig-release team and
website-milestone-maintainers (gives them access to set /milestone
for PRs to k/website as part of their workflow for RT).
Signed-off-by: Victor Palade <victor@cloudflavor.io>
/assign @savitharaghunathan 
~/hold for [@ritpanjw access to the org to be resolved](https://github.com/kubernetes/org/issues/2665#issuecomment-828222961)~
> docs/release team provisioning: Add members for v1.22 Release Docs.

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
I'm maintaining the project for some time, and I need admin access to set up some items in the repo.
/assign @dims @detiber @fabriziopandini
> capg/github-team: add cpanato to the admin group of capg

- config/kubernetes/sig-release/teams.yaml
- Add 1.22 RT shadows to the release team group
- Remove old RT shadows from the release team group
- Add 1.22 Enhancements & bug triage shadows to the milestone maintainers list
- Remove old RT shadows from the milestone maintainers list
ref: kubernetes/sig-release#1522
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @hasheddan
/cc @annajung @divya-mohan0209 @erismaster @kikisdeliveryservice
cc @JamesLaverack @mkorbi @MonzElmasry @PI-Victor @pmmalinov01 @Pensu 
> Updating release team group and milestone maintainers list

- config/kubernetes-sigs/org.yaml
Add managing groups for the gcp-compute-persistent-disk-csi-driver repo.
This repo has been around for a long time, but does not seem to have been managed through this yaml. It is not clear how the owners are set.
/assign @msau42
> Add gcp-compute-persistent-disk-csi-driver groups

- config/kubernetes-csi/org.yaml
This is to help release csi sidecars for sig-storage. 
/cc @msau42
> Add Jiawei0227 to some kubernetes-csi repo maintainer

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2678
Also adds @abhiraut to @kubernetes-sigs, they are already a member of @kubernetes. 
> Add GitHub teams for network-policy-api

- config/kubernetes-sigs/org.yaml
Add kbasv as a member of kubernetes-sigs org as discussed here - https://github.com/kubernetes/org/issues/2656#issuecomment-839863142
> Add kbasv to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
Follow up to #2699 I need to join this org for the ongoing work I am doing in sig-network and so that I can be added as an owner to the new `network-policy-api` repo, See #2678
> Add astoycos to kubernetes-sigs org

- config/kubernetes/sig-release/teams.yaml
This PR adds Joyce and Verónica (@thejoycekung and @Verolop ), Branch Manager shadows for the v1.22 cycle  to the release team group.
/assign @kubernetes/sig-release-leads 
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
> Add thejoycekung and verolop to release-team

- config/kubernetes-sigs/org.yaml
To fix issue with https://github.com/kubernetes-sigs/instrumentation-addons/pull/1
Both are already Kubernetes members.
> Add coffeepac and monotek to k8s-sigs

- config/kubernetes-sigs/sig-testing/teams.yaml
Primarily to be able to change `e2e-framework` repo's main branch name from `master` to main.
> Adding `vladimirvivien` as admin to e2e-framework repo

- config/kubernetes/sig-release/teams.yaml
This PR adds @KnVerey to the milestone members team on behalf of SIG CLI.
Katrina is a maintainer of [Kustomize](https://github.com/kubernetes-sigs/kustomize/) and will be working to clean up [old migrated Kustomize KEPs](https://github.com/kubernetes/enhancements/issues?q=is%3Aopen+is%3Aissue+label%3Asig%2Fcli+kustomize).
> Add KnVerey to milestone members

- config/kubernetes-sigs/sig-network/teams.yaml
The external-dns project needs additonal maintainers with write access
so that GitHub actions for first time contributors can be approved.
time.
ref: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
> Add seanmalloy to external-dns-maintainers

- config/kubernetes-sigs/org.yaml
Add @seanschneeweiss as a member of kubernetes-sigs org as discussed in #2725.
> Add seanschneeweiss to kubernetes-sigs org

- config/kubernetes/sig-architecture/teams.yaml
Was made owner in March via:
https://github.com/kubernetes/enhancements/pull/2550
Also updated teams.yaml for correct 1.22 RT members see:
https://github.com/kubernetes/sig-release/blob/master/releases/release-1.22/release-team.md
> add kikisdeliveryservice as enhancements subproject owner

- config/kubernetes-sigs/sig-instrumentation/teams.yaml
Update to match current repo owners.
Recent update to owners https://github.com/kubernetes-sigs/metrics-server/pull/760
> Update metrics server admins.

- config/kubernetes/wg-k8s-infra/teams.yaml
Motivated by allowing more people to re-run the ci-k8sio-audit job. Then
I realized there are other jobs different groups might want to re-run
Add GitHub teams that correspond to certain kubernetes.io groups:
- k8s-infra-aws-admin
- k8s-infra-gcp-auditors
- k8s-infra-gcp-org-admins
- k8s-infra-group-admins
> wg-k8s-infra: add more sub-teams

- config/kubernetes/org.yaml
peribolos is broken right now - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-org-peribolos/1398588539746127872
```
{"client":"github","component":"peribolos","file":"external/io_k8s_test_infra/prow/github/client.go:526","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateOrgMembership(kubernetes, greenapple10, false)","time":"2021-05-29T10:43:23Z"}
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","file":"external/io_k8s_test_infra/prow/cmd/peribolos/main.go:517","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(kubernetes, greenapple10, false) …
```
> Update username rename: s/GreenApple10/chuntaochen

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- Offboard inactive Release Managers (@tpepper, @idealhack, @feiskyer, @markyjackson-taulia)
- Add @wilsonehusin, @thejoycekung, and @palnabarun as Release Manager Associates (https://github.com/kubernetes/sig-release/issues/1483, https://github.com/kubernetes/sig-release/issues/1567)
- Sync k-sigs @kubernetes/release-engineering team with `kubernetes` org
> releng: Update `release-engineering` team

- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/sig-testing/teams.yaml
Follow-up to https://github.com/kubernetes/org/pull/2743, after noticing a few more teams needed sprucing up.
- Offboarding cleanup for @tpepper and @alejandrox1 
- Transfer k/repo-infra team ownership to SIG Release (ref: https://github.com/kubernetes/community/pull/4985)
- Remove GitHub team for archived licensing subproject (ref: https://github.com/kubernetes/community/pull/5400)
/assign @saschagrunert @hasheddan @jeremyrickard 
cc: @kubernetes/sig-release-leads
> SIG Release: Spring cleaning

- config/kubernetes-sigs/sig-aws/teams.yaml
Similar to https://github.com/kubernetes/org/pull/2482 for ebs 
(main reason I want more permissions is to configure coveralls threshold or maybe disable it altogether because it currently blocks PRs too often e.g. https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/470. I already did it in ebs e.g. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/912#issuecomment-853699031)
> Add self as admin for efs and fsx and remove inactive

- config/kubernetes/org.yaml
This fixes peribolos: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-org-peribolos/1402695359720853504
related - https://github.com/kubernetes/org/issues/925
```
{"client":"github","component":"peribolos","file":"external/io_k8s_test_infra/prow/github/client.go:526","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateOrgMembership(kubernetes, medmedchiheb, false)","time":"2021-06-09T18:37:29Z"}
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","file":"external/io_k8s_test_infra/prow/cmd/peribolos/main.go:517","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership …
```
> Update GitHub username for medmedchiheb

- config/kubernetes/sig-release/teams.yaml
Updating 1.22 comms team to reflect recent changes
/assign @kubernetes/sig-release-leads 
/cc @annajung @divya-mohan0209 @erismaster @kikisdeliveryservice 
/approve cancel in favor of sig-release leadership's approval
> Update 1.22 Comms team

- OWNERS_ALIASES
- config/kubernetes/org.yaml
- config/kubernetes/sig-release/teams.yaml
I'm stepping down from SIG-UI as a chair. I'll still be active as a maintainer, including the metrics-scraper. 
But it makes sense to remove me from certain groups. :)
> jeefy stepping down from sig-ui chair

- OWNERS_ALIASES
- config/kubernetes/sig-release/teams.yaml
As part of the onboard described in this issue: https://github.com/kubernetes/sig-release/issues/1590
> sig-release: add puerco/cpanato to the sig-release teams

- config/kubernetes-sigs/org.yaml
Tyler is an intern at Google and joining the community!
He'll be working under the guidance of Linus Arver (and others) to
improve maintainer and testing experience for artifact promotion tools.
Welcome Tyler!
Closes: https://github.com/kubernetes/org/issues/2783
(This PR also represents my sponsorship for @tylerferrara's org membership.)
cc: @kubernetes/release-engineering @kubernetes/sig-release-leads @listx
> config: Add tylerferrara to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- config/kubernetes/wg-k8s-infra/teams.yaml
Ref: https://github.com/kubernetes/k8s.io/issues/2191
Parf of : https://github.com/kubernetes/k8s.io/issues/1394
> Add k8s-infra-ci-robot as admin of github.com/kubernetes/k8s.io

- config/kubernetes/sig-release/teams.yaml
- Add @kubernetes/sig-release-admins to @kubernetes/repo-infra-admins 
- Add @kubernetes/release-managers to @kubernetes/repo-infra-maintainers
ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1626257726146700?thread_ts=1626164119.119300&cid=CJH2GBF7Y
/assign @saschagrunert @cpanato @puerco 
/area release-eng
> sig-release: Update k/repo-infra teams

- config/kubernetes/sig-docs/teams.yaml
Add chenxuc to  sig-docs-zh-reviews.
related: https://github.com/kubernetes/website/pull/28946
> add chenxuc to zh reviewer

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Removes teams after archival of repo
ref: #2845
/cc @vincepri @neolit123 @timothysc
> Remove cluster-api-bootstrap-provider-kubeadm teams

- config/kubernetes/org.yaml
we are looking into using blockade for PRs that touch `cluster/` in a
similar manner that is used for kubernetes/release - someone will need
to manually remove the blockade label before a PR is allowed to merge
these two cluster/ approvers aren't part of the kubernetes-maintainers
team and so would not have the power to do so
> add cluster/ approvers to kubernetes-maintainers

- config/kubernetes-client/org.yaml
- config/kubernetes/org.yaml
fixes: #2850
Note: original org membership was in kubernetes-sigs.
While policy documentation has not been updated yet, steering has +1'ed making org membership 'universal'. You are joining Kubernetes the project as a whole, and not a specific org.
> Add arahamad to kubernetes, kubernetes-client orgs

- config/kubernetes/sig-release/teams.yaml
- Add RT Lead to sig-release
- Add RT Lead, EA, RT Lead shadows and Role Leads to
- milestone-maintainers
- release-team
- Add RT Lead, EA, RT Lead Shadows to release-team-leads
- Add CI Signal Lead to ci-signal
ref: kubernetes/sig-release#1652
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @cpanato @puerco @hasheddan
/cc @JamesLaverack @jrsapi @mkorbi @MonzElmasry
> Update SIG Release teams for 1.23 Release

- hack/default-branches-report.sh
Related:
- part of: https://github.com/kubernetes/org/issues/2222
outputs a github-flavored markdown checklist of repos per org, with
checkboxes checked if their default branch is named something other than
'master'
run with no args to target the orgs managed by the kubernetes
github-management subproject
> hack: add default-branches-report.sh

- config/kubernetes-csi/org.yaml
So that I can perform releases for these CSI sidecars.
/assign @msau42
> Add chrishenzie as maintainer of kubernetes-csi repos

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-docs/teams.yaml
- config/kubernetes/sig-docs/teams.yaml
Updating SIG Docs chairs.
Ref: https://github.com/kubernetes/website/issues/29354
/cc @parispittman @sftim
> updating SIG Docs co-chairs

- config/kubernetes-csi/org.yaml
I'm helping release the next version of livenessprobe.
/assign @msau42
> Add verult as kubernetes-csi livenessprobe maintainer

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
Related:
- repo creation request: https://github.com/kubernetes/org/issues/2878
I added @adtac as a kubernetes-sigs member as they are already a kubernetes member
@sanposhiho was requested as a team member but they need to go through the usual org membership process first
> Add kubernetes-sigs-scheduler teams / members

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2871 
fixes #2875 
fixes #2892 
fixes #2895
> Add Members 2021-08-18

- config/kubernetes/sig-docs/teams.yaml
i will remain in website-milestone-maintainers a bit longer till the new docs lead is added
Signed-off-by: Victor Palade <victor@cloudflavor.io>
/cc @kubernetes/sig-docs-leads
> remove sig-docs privileges for 1.22 team.

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-node/teams.yaml
- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/sig-scalability/teams.yaml
- config/kubernetes/wg-k8s-infra/teams.yaml
- @hasheddan is now Emeritus (https://github.com/kubernetes/sig-release/issues/1667)
Leaving Dan in as an org member, but he's emeritus from all other
held roles.
- Update references for Chairs/Technical Leads
- Remove previous Release Team members
- Prune inactive subproject maintainers
- https://github.com/kubernetes-sigs/downloadkubernetes:
- @chuckha
- @mauilion
- https://github.com/kubernetes-sigs/k8s-container-image-promoter:
- @justinsb
- https://github.com/kubernetes-sigs/release-notes:
- @jeefy
- https://github.com/kubernetes-sigs/zeitgeist:
- @yastij
- Drop CIP maintainer access for @kubernetes/wg-k8s-infra-leads
WG K8s Infra is transitioning to SIG: https://github.com/kubernetes/community/pull/5928
As part of that, we refine access to this repo to maintainers and …
> SIG Release cleanups

- SECURITY_CONTACTS
- config/kubernetes/org.yaml
This is pull request is part of the process to rename the product
security commitee to the security response commmitee.
Please see [the community
issue](https://github.com/kubernetes/community/pull/5597/files)
Signed-off-by: Luke Hinds <lhinds@redhat.com>
> Product Security Committee rename

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Syncs up with recent changes to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/OWNERS_ALIASES
cc: @alexeldeib
> Add cluster-api-provider-azure maintainer and reviewer

- config/kubernetes/org.yaml
This commit adds fpetkovski as a maintainer to kube-state-metrics.
> Add fpetkovski as a kube-state-metrics maintainer

- config/kubernetes/sig-release/teams.yaml
This PR updates sig-release/teams.yaml for the 1.23 release team:
- add 1.23 RT shadows to the release-team group
- add 1.23 Enhancements and Bug Triage shadows to the milestone-maintainers group
- add 1.23 CI Signal shadows to the ci-signal group
ref: https://github.com/kubernetes/sig-release/issues/1623
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @cpanato @puerco
/cc @JamesLaverack @jrsapi @mkorbi @MonzElmasry @salaxander @cici37 @karenhchu @jlbutler @voigt @encodeflush 
/hold for reviews and for all shadows to be K8s org members
> Release-1.23: update release team, milestone maintainers, ci signal lists for 1.23

- config/kubernetes-csi/org.yaml
I'm helping release the next version of csi-driver-host-path.
/assign @msau42 @mrbobbytables
> Add verult as kubernetes-csi csi-driver-host-path maintainer

- config/kubernetes-sigs/sig-network/teams.yaml
- config/kubernetes-sigs/sig-scheduling/teams.yaml
Hi team. 
This PR
- moves kube-scheduler-simulator-admins and kube-scheduler-simulator-maintainers to sig/scheduling (#2921)
- adds sanposhiho to kube-scheduler-simulator-maintainers (#2919 )
Fixes #2921
Fixes #2919
> Fix: move kube-scheduler-simulator-admins and kube-scheduler-simulator-maintainers to sig/scheduling

- config/kubernetes/sig-docs/teams.yaml
> remove temporary access for pi-victor from website-maintainers

- config/kubernetes/sig-docs/teams.yaml
Add 1.23 RT Docs Shadows to ~`release-team` in sig-release and~ `website-milestone-maintainers` in sig-docs.
Note @mehabhalodiya is away until Sep 2 and I will file a subsequent PR to add her once she's sorted her org membership and CLA signing.
/assign @reylejano @JamesLaverack @jrsapi @mkorbi @MonzElmasry @jeremyrickard
> Add 1.23 RT Docs to sig-docs 'website-milestone-maintainers' team

- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Related:
- Part of: https://github.com/kubernetes/test-infra/issues/23469
- Part of: https://github.com/kubernetes/k8s.io/issues/2191
- Followup to: https://github.com/kubernetes/org/pull/2790
This finishes adding k8s-infra-ci-robot to the rest of the orgs we actively manage
Then adds k8s-infra-cherrypick-robot (used by the `cherrypicker` plugin deployed on prow.k8s.io) to all orgs we actively manage. The intent is to get cherrypicks created by the plugin to automatically have ok-to-test added.
> Add k8s-infra robot accounts to kubernetes orgs

- config/kubernetes/sig-docs/teams.yaml
Signed-off-by: Victor Palade <victor@cloudflavor.io>
cc @kubernetes/sig-docs-leads
> website-milestone-maintainers: remove pi-victor.

- config/kubernetes/sig-security/teams.yaml
ref: #2923
/assign @IanColdwater @tabbysable
> sig-security: Add teams for sig-security repo

- README.md
This reverts commit 79fd5855f986371fc58d173b9dce32c75159ee91.
Test completed, with [EasyCLA being set as an optional context](https://github.com/kubernetes/test-infra/pull/23634) It was non-blocking 👍 
ref: #2977
> Revert "EasyCLA commit test"

- config/kubernetes/sig-testing/teams.yaml
Related:
- Part of: https://github.com/kubernetes/test-infra/issues/21137
- Related to: https://github.com/kubernetes/enhancements/issues/2539
- Followup to: https://github.com/kubernetes/test-infra/pull/23602
We need to give k8s-infra-ci-robot admin access to the kubernetes/test-infra repo to be able to label PRs created via generic-autobumper
Also prune a team member who has since moved on from the project
> sig-testing: update test-infra teams

- config/kubernetes-sigs/org.yaml
I have been mainly involved in release-notes project and be responsible for updating relnotes.k8s.io as 1.23 release team release notes lead.
> Add cici37 to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
I'm requesting to be part of kubernetes-sigs org, I'm the Kubernetes 1.23 release lead and I review release notes and PRs to update relnotes.k8s.io
> Add reylejano to kubernetes-sigs org

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
/assign @vincepri @fabriziopandini 
sync CAPI owners with https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES
> Update SIG cluster lifecycle owners

- config/kubernetes/sig-k8s-infra/teams.yaml
Related:
- Followup to: https://github.com/kubernetes/org/pull/3007
- Followup to: https://github.com/kubernetes/test-infra/pull/23745
This is mostly to exercise jobs to confirm they all still work
> config/kubernetes: sig-k8s-infra team updates

- Makefile
Trying to avoid changing the job config args, which are passed in as `--foo=bar`. This doesn't work with the approach taken in kubernetes/k8s.io to pass flags through to a make target.  So use a different approach.
> make: fix make deploy

- config/kubernetes-sigs/sig-aws/teams.yaml
Added self as maintainer for aws-ebs-csi-driver. Includes membership https://github.com/kubernetes/org/issues/2968
> Added self as maintainer for aws-ebs-csi-driver

- Makefile
Related:
- Followup to: https://github.com/kubernetes/org/pull/3007
Preserve same behavior as bazel, don't force people to run `make clean` each time there are local edits to `config/**/*.yaml`
> make: regen config on edits to config/**/*.yaml
