kubernetes/org

config/kubernetes/sig-docs/teams.yaml
Aligning GitHub Teams with https://github.com/kubernetes/website/pull/28522
=> updating teams

OWNERS_ALIASES, config/kubernetes/org.yaml, config/kubernetes/sig-release/teams.yaml
Contexts:
* https://groups.google.com/g/kubernetes-dev/c/_sGC7W4YiVc/m/QkePzg--AgAJ
* #2781
=> Add shu-mutou to sig-ui leads

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #2788 
fixes: #2789 
fixes: #2794 
fixes: #2796 
fixes: #2798 
fixes: #2799 
/hold
=> Add members 20210622

config/kubernetes/org.yaml
Adding new folks who have been actively contributing and removing folks who are no longer active.
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>
=> Update admins for cloud-provider-vsphere

config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2803
Fixes https://github.com/kubernetes/org/issues/2801
=> Add members 2021-06-25

config/kubernetes-sigs/org.yaml
Signed-off-by: Ke Zhang zhang.ke106@zte.com.cn
Adding myself as member for kubernetes-sigs org
=> Add 249043822 to kubernetes-sigs org

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2808
Fixes https://github.com/kubernetes/org/issues/2809
=> Add members 2021-06-30

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #2813 
fixes #2814
fixes #2815
fixes #2816 
fixes #2817 
fixes #2818 
/cc @nikhita
=> Add members 2021-07-07

config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2823
Fixes https://github.com/kubernetes/org/issues/2821
Fixes https://github.com/kubernetes/org/issues/2820
=> Add members 2021-07-14

config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2826
=> Add tech-geek29 to kubernetes org

config/kubernetes/sig-docs/teams.yaml
Add @jihoon-seo to sig-docs-ko-reviews.
related with https://github.com/kubernetes/website/pull/28948
=> Add jihoon-seo to sig-docs-ko-reviews

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2833
Fixes https://github.com/kubernetes/org/issues/2832
Fixes https://github.com/kubernetes/org/issues/2829
=> Add members 2021-07-16

config/kubernetes-sigs/sig-contributor-experience/teams.yaml
ref: #2589 
/cc @jberkus @coderanger
=> Add lwkd teams to kubernetes-sigs

config/kubernetes/sig-docs/teams.yaml
I want to join the sig-docs-zh-reviews team.
I have met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):
- Member of Kubernetes for 3+ months
- 20+ PRs merged:  https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Amengjiao-liu
- 5+ PRs reviewed:  https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3Amengjiao-liu
Thanks!
/cc @tengqm
=> Add mengjiao-liu to sig-docs-zh-reviews

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
=> Remove bootkube teams

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #2841 
fixes: #2840 
fixes: #2837
fixes: #2836 
fixes: #2835
=> Add members 20210729

config/kubernetes-sigs/sig-network/teams.yaml
This mirrors https://github.com/kubernetes-sigs/gateway-api/pull/734
=> Adding Nick as a Gateway API maintainer

config/kubernetes-sigs/sig-aws/teams.yaml
Add self as aws-efs-csi-driver admin & maintainer
=> Add self as aws-efs-csi-driver admin & maintainer

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 20210730

config/kubernetes/sig-docs/teams.yaml
Temporary adding myself to the `website-maintainers` team for write access to k/website repo for the release preparation/release day.
/assign @jimangel @irvifa @kbarnard10
=> Request temporary access for pi-victor for the 1.22 release process.

config/kubernetes-client/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #2863
fixes: #2862 
fixes: #2861 
fixes: #2859 
fixes: #2855 
=> Add members 20210804

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2879
Fixes https://github.com/kubernetes/org/issues/2877
=> Add members 2021-08-09

config/kubernetes-client/org.yaml, config/kubernetes/org.yaml
Replaces #2884 
(Original author cannot sign EasyCLA yet)
=> Add ambiknai to kubernetes, kubernetes-client orgs

OWNERS_ALIASES
=> Update OWNERS_ALIASES from k8s.io/community

config/kubernetes-sigs/sig-auth/teams.yaml
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
/cc @ritazh
/cc @tam7t
=> add tam7t to secrets-store-csi-driver-maintainers

config/kubernetes/org.yaml
ref: https://github.com/kubernetes/community/issues/5596
/assign @nikhita @spiffxp
=> github/team: rename product-security-committee team to product-security-response

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #2896 
Fixes #2900 
Fixes #2901 
Fixes #2903 
Fixes #2904 
Fixes #2905 
Fixes #2907 
Fixes #2908 
Fixes #2909 
/cc @ameukam @palnabarun
=> Add Members 08-20-2021

config/kubernetes/org.yaml, config/kubernetes/sig-instrumentation/teams.yaml
Add myself to kube-state-metrics-admins team as discussed with @lilic
=> Add mrueg to kube-state-metrics-admins

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #2910
Fixes #2918
Fixes #2924
Fixes #2928
Fixes #2932
Fixes #2933
Fixes #2944
=> Add Members 09-02-2021

config/kubernetes-sigs/sig-api-machinery/teams.yaml
/assign @vincepri 
See https://github.com/kubernetes-sigs/controller-runtime/blob/master/OWNERS_ALIASES#L14
=> Add joelanford to controller-runtime-maintainers and controller-tools-maintainers

config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2953
Fixes https://github.com/kubernetes/org/issues/2952
Fixes https://github.com/kubernetes/org/issues/2950
Fixes https://github.com/kubernetes/org/issues/2949
Fixes https://github.com/kubernetes/org/issues/2934
Fixes https://github.com/kubernetes/org/issues/2941
Fixes https://github.com/kubernetes/org/issues/2936
Fixes https://github.com/kubernetes/org/issues/2931
=> Add members 09-07-2021

config/kubernetes-sigs/provider-ibmcloud/teams.yaml
=> Include mkumatag to provider-ibmcloud team for capi repo

config/kubernetes/sig-docs/teams.yaml
Add @jmyung to sig-docs-ko-reviews.
please refer to https://github.com/kubernetes/website/pull/29249
=> Add jmyung to sig-docs-ko-reviews

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #2937 
fixes: #2939
fixes: #2940
fixes: #2942
fixes: #2947
fixes: #2951
fixes: #2954
fixes: #2959 
=> Add members 2021-09-09

config/kubernetes/sig-docs/teams.yaml
Owners and Reviewers for Hindi localization team.
cc: 
@sftim 
@divya-mohan0209 
@mittalyashu
=> Update sig-docs-hi members

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #2958 
Fixes #2961 
Fixes #2963 
Fixes #2965 
Fixes #2968 
=> Add Members 09-14-2021

README.md
mrbobbytables test account
- Old CLA signed
- EasyCLA not signed
/hold
=> EasyCLA commit test

OWNERS_ALIASES, config/kubernetes/wg-k8s-infra/OWNERS
Related:
- Part of: https://github.com/kubernetes/community/issues/6036
Team renames and label updates will come later
=> OWNERS: mv wg-k8s-infra sig-k8s-infra

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #2975
fixes: #2976
fixes: #2983 
fixes: #2986
fixes: #2993 
fixes: #2994
fixes: #2995
fixes: #3000
=> Add members 20210924

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
=> Remove capi-docker teams

config/kubernetes/org.yaml
ref: https://github.com/kubernetes/org/issues/2847
=> Remove frakti teams

OWNERS_ALIASES, config/kubernetes-sigs/sig-windows/teams.yaml, config/kubernetes/sig-release/teams.yaml, config/kubernetes/sig-windows/teams.yaml
Signed-off-by: Mark Rossetti <marosset@microsoft.com>
Part of https://github.com/kubernetes/community/issues/6045
=> Swap Deep Debroy with Claudiu Belu as Windows TL

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
=> Add capi-kubevirt teams

config/kubernetes/wg-structured-logging/teams.yaml
Requesting to add myself as a member and a reviewer of wg-structured-logging working group
/wg structured-logging
/sig instrumentation
=> Request to add shivanshu1333 to wg-structured-logging

config/kubernetes/sig-docs/teams.yaml
Adding @verma-kunal as reviewer for `hi` localization.
cc: 
@verma-kunal 
@sftim 
@divya-mohan0209 
@mittalyashu
=> Update sig-docs-hi reviewers

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/3020
Fixes https://github.com/kubernetes/org/issues/3019
Fixes https://github.com/kubernetes/org/issues/3017
Fixes https://github.com/kubernetes/org/issues/3014
Fixes https://github.com/kubernetes/org/issues/3006
Fixes https://github.com/kubernetes/org/issues/3002
Fixes https://github.com/kubernetes/org/issues/2999
Fixes https://github.com/kubernetes/org/issues/2985
Fixes https://github.com/kubernetes/org/issues/3023
=> Add members 2021-10-04

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3048 
fixes #3058 
fixes #3063 
fixes #3065 
fixes #3072 
fixes #3074
=> Add Members 2021-11-02

config/kubernetes-csi/org.yaml
I'm helping release the next version of csi-driver-host-path.
/assign @msau42 @spiffxp
=> Add verult as kubernetes-csi node-driver-registrar maintainer

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3073 
fixes #3078 
fixes #3081
=> Add Members 2021-11-05

config/kubernetes/sig-instrumentation/teams.yaml
/cc @kubernetes/kube-state-metrics-maintainers
=> Add dgrisonnet as kube-state-metrics maintainer

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
cc @vincepri @CecileRobertMichon @fabriziopandini
=> Add enxebre to capi maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3082 
fixes #3088 
fixes #3091
=> Add Members 2021-11-12

config/kubernetes-sigs/org.yaml
I already is k8s member and want to apply for sig member.
=> add jonyhy96 as k8s-sig member

OWNERS_ALIASES, config/kubernetes-sigs/sig-service-catalog/teams.yaml, config/kubernetes/sig-release/teams.yaml, config/kubernetes/sig-service-catalog/teams.yaml
Hello,
I'm stepping down as chair of SIG Service Catalog, so I'm removing myself from this list of leads.
See PR in kubernetes/community: https://github.com/kubernetes/community/pull/6215
=> remove jberkhahn from sig-service-catalog-leads

config/kubernetes-sigs/sig-release/teams.yaml
ref: #3106
/assign @justaugustus @saschagrunert @puerco @cpanato  @jeremyrickard
=> Add teams for bom subproject

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3033 
fixes: #3085 
fixes: #3096 
fixes: #3099 
fixes: #3100 
fixes: #3104 
fixes: #3105 
fixes: #3107 
=> Add members 2021-11-21

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3111
fixes #3113
fixes #3115
fixes #3116
fixes #3120
=> Add members 2021-12-02

config/kubernetes-sigs/sig-cli/teams.yaml
=> Add teams for krm-functions-registry

config/kubernetes/sig-docs/teams.yaml
Adding myself to Docs `website-maintainers` temporarily to work on the 1.23 release.
/assign @jimangel @divya-mohan0209
=> add jlbutler to docs website-maintainers for 1.23 release

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3124 
fixes #3128 
fixes #3130 
fixes #3132 
fixes #3133 
fixes #3134 
fixes #3135 
fixes #3137 
fixes #3141  
fixes #3142  
fixes #3144 
/cc @ameukam @nikhita @savitharaghunathan
=> Add members 2021-12-14

config/kubernetes-sigs/sig-k8s-infra/OWNERS, config/kubernetes-sigs/sig-k8s-infra/teams.yaml
Related:
- https://github.com/kubernetes/org/issues/3143
=> sig-k8s-infra: Add teams for oci-proxy

config/kubernetes/sig-docs/teams.yaml
- Add newest chair @divya-mohan0209
- Add newest reviewer (for English) @shannonxtreme
/cc @kubernetes/sig-docs-en-owners
=> Update reviewers & owners (en) for SIG Docs

config/kubernetes-csi/org.yaml
/cc @msau42 
/assign @palnabarun @mrbobbytables
=> Add mauriciopoppe as maintainer of node-driver-registrar and livenessprobe

config/kubernetes-csi/org.yaml
trying to make an alpha release first.
=> add andyzhangx to csi-driver-iscsi admin

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3145
fixes #3151 
fixes #3152
fixes #3154 
fixes #3156 
fixes #3157 
fixes #3159 
fixes #3160
fixes #3162
/cc @nikhita
=> Add Members 2021-01-07

config/kubernetes-sigs/provider-azure/teams.yaml
@nilo19 Could you please review this request? Thank you very much!
=> Add MartinForReal to cloud-provider-azure-admins

config/kubernetes-csi/org.yaml
Maintaining above repositories and requesting these permissions
to faciilitate releases on the same.
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
=> kubernetes-csi: humblec as admin of csi-driver-iscsi and csi-lib-iscsi

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3168
fixes #3170
fixes #3173
fixes #3175
fixes #3176
fixes #3178
fixes #3179
fixes #3180
fixes #3181
fixes #3183
fixes #3184
fixes #3185
fixes #3186
fixes #3187
fixes #3188
fixes #3192
fixes #3193
fixes #3195
fixes #3197
fixes #3198
- add csantanapr to kubernetes, kubernetes-sigs
- add valaparthvi to kubernetes
- add Lp-Francois to kubernetes
- add shuheiktgw to kubernetes
- add Nivedita-coder to kubernetes
- add ptux to kubernetes
- add zvonkok to kubernetes
- add s04 to kubernetes, kubernetes-sigs
- add qabpea to kubernetes-sigs
- add necatican to kubernetes-sigs
- add doshyt to kubernetes, kubernetes-sigs
- add rtsp to kubernetes-sigs
- add rhockenbury to kubernetes
- add DiptoChakrabarty to kubernetes
- add chriskim06 to kubernetes
- add didicodes to kubernetes
- add …
=> Add Members 2022-01-21

config/kubernetes/sig-release/teams.yaml
Follow-up to https://github.com/kubernetes/org/pull/3182
=> Uncomment new members

config/kubernetes/org.yaml
Quick update to reflect my username change!
=> Updating GitHub Username s/ellenkorbes/vkorbes

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3166
fixes: #3202 
fixes: #3203 
fixes: #3206
fixes: #3207 
fixes: #3209 
fixes: #3210 
fixes: #3215 
fixes: #3216 
fixes: #3217
=> Add members 2022-01-31

config/kubernetes/org.yaml
Follow up to kubernetes/committee-security-response#141
/assign @cjcullen @enj @swamymsft
=> Onboard/Offboard Mo/Swamy from SRC

config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-testing/teams.yaml
Ref: https://github.com/kubernetes/org/issues/3228
=> Add GitHub teams for the prow repo

config/kubernetes-sigs/org.yaml
I'm already a part of k8s org https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L622
Creating the PR based on the recommendation https://github.com/kubernetes/org/issues/3249#issuecomment-1038679567
=> add jyotimahapatra to kubernetes-sig

config/kubernetes/org.yaml
I'm already a member of @kubernetes-sigs.
close #3256
=> add MartinForReal to kubernetes org

config/kubernetes-sigs/sig-scheduling/teams.yaml
Ref: https://github.com/kubernetes/org/issues/3263
=> Add GitHub teams for kueue repo

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
add lzhecheng to kubernetes org and kubernetes-sigs org
close: #3242
=> Add lzhecheng to kubernetes org and kubernetes-sigs org

config/kubernetes-sigs/org.yaml
As suggested in https://github.com/kubernetes/org/pull/3271#issuecomment-1042061604 ^^
=> Adding michelle192837 as a k8s-sig member.

config/kubernetes-sigs/provider-azure/teams.yaml
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>
=> Add lzhecheng to cloud-provider-azure-admins

config/kubernetes/provider-azure/teams.yaml
Add @lzhecheng @MartinForReal @nilo19 to admin team of  provider azure
=> Add new admin members to provider azure

config/kubernetes-sigs/org.yaml
As suggested in https://github.com/kubernetes/org/pull/3271#issuecomment-1042061604
=> Add mpherman2 as k8s-sig member

config/kubernetes-sigs/sig-cli/teams.yaml
/cc @KnVerey 
/cc @jeremyrickard 
/cc @mengqiy
=> add natasha41575 to be a krm-functions-registry maintainer

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3255 
fixes #3265 
fixes #3275 
fixes #3278 
fixes #3280
=> Add members 2020-02-25

config/kubernetes-sigs/sig-release/teams.yaml
Ref: https://github.com/kubernetes/org/issues/3259
/assign @leonardpahlke
=> Add GitHub teams for release-team-shadow-stats

config/kubernetes-sigs/sig-contributor-experience/teams.yaml
Ref: https://github.com/kubernetes/org/issues/3208
=> Add GitHub teams for maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3287
fixes #3289 
fixes #3290 
fixes #3291 
fixes #3293 
fixes #3294 
fixes #3301 
fixes #3303 
fixes #3304 
fixes #3306 
fixes #3307  
fixes #3308 
fixes #3309 
fixes #3310
=> Add Members 2022-03-11

config/kubernetes-sigs/sig-k8s-infra/teams.yaml
/cc @ameukam @thockin 
Intend to use to tag releases etc.
=> add myself to oci-proxy admins / maintainers

config/kubernetes-sigs/org.yaml
=> Add mauriciopoppe as maintainer and admin of local-static-provisioner

Makefile, OWNERS, SECURITY_CONTACTS, admin/update.sh, config/kubernetes-client/OWNERS, config/kubernetes-client/org.yaml, config/kubernetes-csi/OWNERS, config/kubernetes-csi/org.yaml, config/kubernetes-incubator/OWNERS, config/kubernetes-incubator/org.yaml, config/kubernetes-nightly/OWNERS, config/kubernetes-nightly/org.yaml, config/kubernetes-nightly/sig-release/teams.yaml, config/kubernetes-retired/OWNERS, config/kubernetes-retired/org.yaml, config/kubernetes-sigs/OWNERS, config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-contributor-experience/teams.yaml, config/kubernetes-sigs/sig-k8s-infra/teams.yaml, config/kubernetes-sigs/sig-release/teams.yaml, config/kubernetes-sigs/sig-testing/teams.yaml, config/kubernetes/OWNERS, config/kubernetes/org.yaml, config/kubernetes/sig-contributor-experience/teams.yaml, config/kubernetes/sig-k8s-infra/teams.yaml, config/kubernetes/sig-release/teams.yaml, config/kubernetes/sig-testing/teams.yaml
Implements https://github.com/kubernetes/community/pull/6596
/cc @cblecker @mrbobbytables @palnabarun @ameukam 
/hold
=> Rotate fejta,spiffxp for ameukam,palnabarun in GitHub Admin Team

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3364 
fixes: #3363 
fixes: #3361 
fixes: #3360 
fixes: #3355
fixes: #3353 
fixes: #3352 
fixes: #3351
fixes: #3346 
fixes: #3345 
fixes: #3344 
fixes: #3343 
fixes: #3335
fixes: #3332
fixes: #3331 
fixes: #3328
fixes: #3321
/hold 
for an ack from another github admin / new member coordinator
=> Add members 2022-04-10

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- Update repo permissions for kubernetes-sigs/cluster-api-provider-packet to reflect current status of the project
=> Update admins/maintainers for k8s-sigs/cluster-api-provider-packet

config/kubernetes-sigs/sig-scheduling/teams.yaml
Related:
- https://github.com/kubernetes/org/issues/3262
=> Retire poseidon teams

config/kubernetes/org.yaml
Member has not accepted or turned down invite.
Missed in the batch removal yesterday (#3367)
=> Remove inactive members

config/kubernetes-sigs/sig-release/teams.yaml
Related:
- https://github.com/kubernetes/org/issues/3218
=> Add teams for testgrid-json-exporter

config/kubernetes-sigs/org.yaml
=> add andyzhangx as maintainer & admin of local-static-provisioner

config/kubernetes-sigs/org.yaml
https://github.com/kubernetes/org/issues/2459
https://github.com/kubernetes/org/blob/4aa38600a6816e60bd6dd350d8f2343b72dfb33b/config/kubernetes/org.yaml#L1299
=> Add wzshiming to kubernetes-sigs org

config/kubernetes-sigs/org.yaml
Signed-off-by: kerthcet <kerthcet@gmail.com>
=> add kerthcet to kubernetes-sig org

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3252
fixes #3365
fixes #3372
fixes #3374
fixes #3376
fixes #3377
fixes #3381
fixes #3383
fixes #3384
fixes #3385
fixes #3386
fixes #3389
fixes #3392
fixes #3393
fixes #3399
fixes #3403
=> Add Members 2022-05-05

config/kubernetes-sigs/provider-azure/teams.yaml
=> Add teams for the azurelustre-csi-driver repo

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Stepping down as maintainer of CAPO due to job changes.
=> cluster-api-provider-openstack: remove chrischdi

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
=> Add cluster-api-cloudstack teams

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3373 
fixes: #3397 
fixes: #3398 
fixes: #3410 
fixes: #3413 
fixes: #3414 
fixes: #3417 
fixes: #3418 
fixes: #3422 
fixes: #3423 
fixes: #3424 
fixes: #3427 
fixes: #3428 
fixes: #3434 
fixes: #3439
fixes: #3440
fixes: #3442
fixes: #3444
fixes: #3448
=> Add members 2022-05-30

config/kubernetes/sig-docs/teams.yaml
ref: https://github.com/kubernetes/website/pull/31858
=> add howieyuen to sig-doc-zh-owners

config/kubernetes-csi/org.yaml
I'll help doing the upcoming releases.
/cc @xing-yang
=> csi-lib-utils, external-provisioner: add pohly as admin

config/kubernetes-sigs/sig-api-machinery/teams.yaml
**Description**
Remove @gabbifish as maintainer.
=> remove gabbifish as maintainer

config/kubernetes-sigs/org.yaml
=> Add carlisia to kubernetes-sigs org

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3447 
fixes: #3470 
fixes: #3472 
fixes: #3477 
fixes: #3478 
fixes: #3483 
fixes: #3484 
fixes: #3486
fixes: #3490 
fixes: #3491 
fixes: #3492 
fixes: #3493 
=> Add members 2022-06-11

config/kubernetes-sigs/sig-instrumentation/teams.yaml
=> Add teams for logtools repo

config/kubernetes-sigs/sig-auth/teams.yaml
=> Add teams for pspmigrator repo

config/kubernetes/sig-release/teams.yaml
onboarding the rest of 1.25 release team
=> onboarding the rest of 1.25 release team

config/kubernetes/sig-docs/teams.yaml
Add 1.25 Docs team to milestone maintainers
=> Add 1.25 Docs Team to GitHub teams

config/kubernetes/org.yaml
Fixes #3504 
Relevant slack thread: https://kubernetes.slack.com/archives/C1TU9EB9S/p1655159318960029
=> Add aladewberry to kubernetes

config/kubernetes-sigs/org.yaml
Alexis and Leiyi are team members on GKE and will be managing releases of these drivers.
=> Add Alexis and Leiyi to pd csi (and filestore csi too for Leiyi)

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> add upodroid to kubernetes, kubernetes-sigs

config/kubernetes-sigs/sig-testing/teams.yaml
Related:
- https://github.com/kubernetes/org/issues/3432
=> Remove k8s-gsm-tools teams

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3431 
fixes: #3502 
fixes: #3508 
fixes: #3509 
fixes: #3510 
fixes: #3511 
fixes: #3513 
=> Add members 2022 06 20

config/kubernetes/sig-docs/teams.yaml
I want to join the **sig-docs-zh-reviews team**.
I've met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):
- Member of Kubernetes for 3+ months.
- 20+ PRs merged: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3AydFu
- 5+ PRs reviewed: https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3AydFu
Thanks you!
/cc @tengqm
Signed-off-by: ydFu <ader.ydfu@gmail.com>
=> Add ydFu to sig-docs-zh-reviews

config/kubernetes/org.yaml
James is doing a bunch of work and maintenance to me, so I'm proposing to add him as a proper admin of ingress-nginx project
=> Add strongjz as ingress-nginx admin

config/kubernetes-sigs/sig-api-machinery/teams.yaml
Already approver there, this is needed to be able to cut releases.
/assign @joelanford @vincepri
=> Add alvaroaleman to controller-tools maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3340
fixes: #3499 
fixes: #3517 
fixes: #3519 
fixes: #3521 
fixes: #3522 
fixes: #3524 
fixes: #3530 
fixes: #3538 
fixes: #3539
fixes: #3529
fixes: #3536
=> Add members 2022-07-04

config/kubernetes-sigs/org.yaml
=> add m-Bilal to kubernetes-sigs

config/kubernetes/org.yaml
/cc @cici37 @cheftako 
Ask for maintainers access to version the repo (via tagging/branching).
=> Add jprzychodzen to cloud-provider-gcp-maintainers

config/kubernetes/org.yaml
fixes: https://github.com/kubernetes/org/issues/3550
=> Add carolinar7 to kubernetes.

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3541
fixes: #3548 
fixes: #3549
fixes: #3554 
fixes: #3557
=> Add members 2022-07-16

config/kubernetes-sigs/sig-network/teams.yaml
This mirrors https://github.com/kubernetes-sigs/gateway-api/pull/1262.
/cc @bowei @hbagdi @shaneutt @youngnick 
/assign @caseydavenport @dcbw @thockin
=> Adding Gateway API Mesh Leads

config/kubernetes-sigs/sig-scheduling/teams.yaml
Ref: https://github.com/kubernetes/org/issues/3479
=> Add GitHub teams for kwok repo

config/kubernetes-client/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> add zqzten to kubernetes, kubernetes-sigs, kubernetes-client

config/kubernetes-csi/org.yaml
For the releases of csi-driver-host-path
=> kubernetes-csi: jingxu97 as admin of csi-driver-host-path

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
- add iXinqi to kubernetes
- add sarazqy to kubernetes, kubernetes-sigs
- add yankay to kubernetes, kubernetes-sigs
- add donghui12 to kubernetes
- add kavyashree-r to kubernetes-sigs
- add Skarlso to kubernetes-sigs
fixes #3566
fixes #3567 
fixes #3569 
fixes #3570 
fixes #3571 
fixes #3575
=> Add Members 2022-07-28

config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-windows/teams.yaml
Ref: https://github.com/kubernetes/org/issues/3585
=> Add GitHub teams for windows-operational-readiness

config/kubernetes/sig-docs/teams.yaml
Add @yoonian to sig-docs-ko-owners
ref: kubernetes/website#35635
=> Add yoonian to sig-docs-ko-owners

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3583
fixes #3586
fixes #3588
fixes #3594
fixes #3597
fixes #3598
fixes #3600
fixes #3602
fixes #3604
=> Add Members 2022-08-11

config/kubernetes-sigs/org.yaml
Based on membership in kubernetes as I'm going to work on the kueue sub-project.
=> Add mimowo to kubernetes-sigs

config/kubernetes/sig-release/teams.yaml
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
=> Add ritazh to milestone-maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3595
fixes #3599 
fixes #3609 
fixes #3610 
fixes #3615 
fixes #3616 
fixes #3617
fixes #3619
/hold for a few more requests
=> Add Members 2022-08-18

OWNERS_ALIASES, config/kubernetes/org.yaml
ref: https://github.com/kubernetes/community/pull/6807
=> Update code-of-conduct-committee group membership

config/kubernetes/org.yaml
Signed-off-by: Ashutosh Kumar <sonasingh46@gmail.com>
=> add sonasingh46 to kubernetes org

config/kubernetes/org.yaml
Follow-up PR to https://github.com/kubernetes/org/issues/3624.
=> Add qbarrand to the kubernetes org

config/kubernetes/sig-docs/teams.yaml
Temporarily adding myself to the website-maintainers team for write access to k/website repo for the release preparation/release day.
/assign @jimangel @reylejano @natalisucks @divya-mohan0209
=> Add kcmartin to website-maintainers team for 1.25 release

config/kubernetes-sigs/sig-instrumentation/teams.yaml
/cc @s-urbaniak 
/assign @logicalhan
=> Update prometheus-adapter teams

config/kubernetes-sigs/sig-instrumentation/teams.yaml
/cc @s-urbaniak 
/assign @logicalhan
=> Update custom-metrics-apiserver teams

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #3390 
Fixes #3608 
Fixes #3614 
Fixes #3623 
Fixes #3627
cc @palnabarun @ameukam 
/hold for review
=> Add members 2022-08-22

config/kubernetes/org.yaml
=> add wespanther to kubernetes

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> add yevgeny-shnaidman to kubernetes, kubernetes-sigs

config/kubernetes-sigs/sig-testing/teams.yaml
bring into parity with current https://sigs.k8s.io/kubetest2/OWNERS
=> config: update kubetest2 teams

config/kubernetes-sigs/sig-node/teams.yaml
Will follow up to rename teams. This is a follow on to #3626
=> Move qbarrand to correct team

config/kubernetes-sigs/sig-node/teams.yaml
Renames the kernel-module-management teams to their correct name.
=> Rename kernel-module-management teams

config/kubernetes-csi/org.yaml
=> Add mauriciopoppe as admin/maintainer of CSI Proxy

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3647
fixes #3648
fixes #3652
fixes #3655
fixes #3658
fixes #3659
fixes #3661
fixes #3663
fixes #3664
fixes #3666
fixes #3667
fixes #3668
fixes #3669
fixes #3670
fixes #3671
fixes #3672
fixes #3674
fixes #3676
=> Add Members 2022-09-12

config/kubernetes-sigs/org.yaml
=> Add harshanarayana to kubernetes-sigs

config/kubernetes/sig-architecture/teams.yaml
Removing old RT Enhancements members and add 1.26 rt enhancements lead.
=> update sig-arch enhancements members

config/kubernetes/sig-api-machinery/teams.yaml, config/kubernetes/sig-apps/teams.yaml, config/kubernetes/sig-auth/teams.yaml, config/kubernetes/sig-autoscaling/teams.yaml, config/kubernetes/sig-cloud-provider/teams.yaml, config/kubernetes/sig-cluster-lifecycle/teams.yaml, config/kubernetes/sig-multicluster/teams.yaml, config/kubernetes/sig-network/teams.yaml, config/kubernetes/sig-scheduling/teams.yaml, config/kubernetes/sig-storage/teams.yaml
Signed-off-by: Mark Rossetti <marosset@microsoft.com>
=> Adding missing sig-*-leads GH groups so sigs can apply lead-opted-in label for enhancements

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3675
fixes #3678
fixes #3679
fixes #3680
fixes #3681
fixes #3682
fixes #3685
fixes #3689
=> Add Members 2022-09-14

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3611
fixes #3691
fixes #3694
fixes #3696 
fixes #3697 
fixes #3698 
fixes #3701 
fixes #3702 
fixes #3703 
=> Add Members 2022-09-21

config/kubernetes/sig-architecture/teams.yaml
A number of folks have volunteered to shadow for PRR this cycle. Adding them here so they can access the project board.
=> Add PRR shadows

config/kubernetes/sig-release/teams.yaml
Add 1.26 RT Shadows
cc @kubernetes/release-team-leads @palnabarun
=> Add 1.26 RT Shadows

config/kubernetes-sigs/org.yaml
Signed-off-by: Kevin Klues <kklues@nvidia.com>
=> Add klueska to kubernetes-sigs org

config/kubernetes-sigs/org.yaml
add @tuxtof to kubernetes-sigs
fixes #3713
=> add tuxtof to kubernetes-sigs

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3700 
fixes: #3709 
fixes: #3712 
fixes: #3716 
fixes: #3717 
=> Add members 2022-09-23

config/kubernetes-sigs/sig-aws/teams.yaml
Add self to efs-csi-driver maintainer
https://github.com/kubernetes/org/issues/3431
=> Add self to efs-csi-driver maintainer - Ashley-wenyizha

OWNERS_ALIASES, config/kubernetes/sig-contributor-experience/teams.yaml
ref: https://github.com/kubernetes/community/pull/6897
=> update contribex leads alias & team

README.md
Update the README with a section which describes how to add yourself to the Kubernetes GitHub organizations.
ref origin PR that mentions the idea to document this: https://github.com/kubernetes/org/pull/3692 
/cc @mrbobbytables @palnabarun
=> Update README, mention adding yourself to k/orgs

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #3719
Fixes #3722
Fixes #3723
Fixes #3727
Fixes #3728
Fixes #3736
Fixes #3742
Fixes #3743
/hold
=> Add Members 2022-10-03

config/kubernetes-sigs/org.yaml
Currently a member of the kubernetes org
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>
=> Add haircommander to kubernetes-sigs

config/kubernetes-sigs/org.yaml
Currently a member of the kubernetes org
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> Add fromanirh to kubernetes-sigs

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Adding self, @CecileRobertMichon & @jsturtevant to the image-builder maintainers list
CC: @codenrhoden @CecileRobertMichon @jsturtevant
=> Add new maintainers to image-builder project

config/kubernetes-sigs/sig-network/teams.yaml
=> sig-network: Add ingress2gateway teams

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3740
fixes: #3741 
fixes: #3749
fixes: #3753 
fixes: #3754 
fixes: #3755 
fixes: #3756
fixes: #3759
=> Add members 2022-10-12

config/kubernetes-sigs/org.yaml
Opened this PR to add me to the kubernetes-sigs org since I am already a part of the kubernetes org https://github.com/kubernetes/org/issues/2820.
I need to join the kubernetes-sigs org inorder to be a reviewer/approver of the kpng subproject https://github.com/kubernetes-sigs/kpng/pull/368
=> Add rajaskakodkar to kubernetes-sigs org

config/kubernetes-sigs/sig-release/teams.yaml
Ref:
- https://github.com/kubernetes/org/issues/3656
=> Add teams for tejolote repo

config/kubernetes-sigs/org.yaml
Closes https://github.com/kubernetes/org/issues/3803
=> Add wondywang to kubernetes-sigs

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/provider-ibmcloud/teams.yaml, config/kubernetes/org.yaml
https://github.com/kubernetes/org/search?q=arahamad-zz
=> rename org member: arahamad-zz to arahamad

config/kubernetes/org.yaml
👋  This PR is to add myself as a member of the kubernetes org. I am already a member of the kubernetes-sigs org.
=> add dthorsen to kubernetes

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3773 
fixes #3775 
fixes #3792 
fixes #3793 
fixes #3795 
fixes #3801 
fixes #3805 
fixes #3806
fixes #3810 
=> Add members 2022 11 03

config/kubernetes/sig-testing/teams.yaml
ref: https://github.com/kubernetes/community/issues/6913
=> update sig testing leads team

config/kubernetes-sigs/sig-k8s-infra/OWNERS, config/kubernetes-sigs/sig-k8s-infra/teams.yaml
Related:
- https://github.com/kubernetes/org/issues/3809
=> k8s-infra: Add teams for porche

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This PR adds a new member to the cluster-api-release-team.
cc @fabriziopandini @sbueringer
=> add joekr to cluster-api-release-team

config/kubernetes-sigs/sig-instrumentation/teams.yaml
ref: https://github.com/kubernetes/org/issues/3769
=> Add usage-metrics-collector teams

config/kubernetes-sigs/sig-instrumentation/teams.yaml
Add myself to the metrics-server team and remove s-urbaniak for inactivity.
=> Update metrics-server team

config/kubernetes-sigs/org.yaml
Add myself as the admin of the node-feature-discovery project.
Fixes #3824
=> Add marquiz to node-feature-discovery-admins

config/kubernetes-sigs/sig-api-machinery/teams.yaml
Signed-off-by: jesus m. rodriguez <jesusr@redhat.com>
=> Adding jmrodri and varshaprasad96 to KB admins

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes #3789
fixes #3794 
fixes #3807 
fixes #3817 
fixes #3822 
fixes #3826 
fixes #3828
fixes #3830 
fixes #3831 
fixes #3832 
fixes #3840 
fixes #3843 
fixes #3844
=> Add Members 20221122

OWNERS_ALIASES, config/kubernetes/sig-release/teams.yaml
Part of https://github.com/kubernetes/sig-release/issues/2099.
/assign @saschagrunert @cpanato @puerco
cc: @kubernetes/sig-release-leads @jeremyrickard @Verolop
=> sig-release: Promote Verónica (Tech Lead) and Jeremy (Chair)

config/kubernetes/sig-api-machinery/teams.yaml
Include a new section for members and add logicalhan to misc and pr-reviews groups.
=> Update sig-api-machinery teams.yaml

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3834 
fixes: #3846 
fixes: #3848 
fixes: #3852 
fixes: #3853 
fixes: #3858 
fixes: #3861 
=> Add members 20221129

config/kubernetes-csi/org.yaml, config/kubernetes/org.yaml
ref https://github.com/kubernetes/org/issues/3378
=> Remove teams for retired repos

config/kubernetes-client/org.yaml, config/kubernetes/org.yaml
I am updating my GitHub handle, need to reflect the new one.
Thanks!
=> update github handle of MoShitrit to moshevayner

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Remove members from org

config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Updated the admin access for SIG Cloud Provider.
Updated the write access for current maintainers.
=> Updated write/admin access to ANP.

config/kubernetes-sigs/org.yaml
I'm a kubernetes member, applying to join kubernetes-sigs today.
https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L1457
=> add wlp1153468871 to kubernetes-sigs

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3871 
fixes: #3882 
fixes: #3883 
fixes: #3889 
fixes: #3891 
fixes: #3894 
fixes: #3901 
fixes: #3906
=> Add members 20221222

config/kubernetes-sigs/sig-windows/teams.yaml
Ref: https://github.com/kubernetes/org/issues/3888
=> Add GitHub teams for windows-service-proxy repo

config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/3910
=> Add songxiao-wang87 to kubernetes org

config/kubernetes-sigs/sig-auth/teams.yaml
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
/assign @tam7t @ritazh 
/cc @nilekhc @salaxander
=> add nilekhc and salaxander to secrets-store-csi-driver maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/3915
Fixes https://github.com/kubernetes/org/issues/3917
Fixes https://github.com/kubernetes/org/issues/3921
Fixes https://github.com/kubernetes/org/issues/3924
Fixes https://github.com/kubernetes/org/issues/3925
Fixes https://github.com/kubernetes/org/issues/3929
Fixes https://github.com/kubernetes/org/issues/3930
Fixes https://github.com/kubernetes/org/issues/3872
/hold
=> Add members 2023-01-12

config/kubernetes-sigs/sig-aws/teams.yaml
See https://github.com/kubernetes-sigs/aws-encryption-provider/pull/90
=> Update AWS enc provider admins and maintainers

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
=> Add cap-addon-provider-helm-teams

config/kubernetes-sigs/sig-multicluster/teams.yaml
ref: https://github.com/kubernetes/org/issues/3841
=> Add teams for sig-multicluster-site repo

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Closes https://github.com/kubernetes/org/issues/3940
Closes https://github.com/kubernetes/org/issues/3941
/assign @salaxander @mrbobbytables
=> Add Kubernetes 1.27 Enhancements Team members to the GitHub organizations

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
FIxes #3938 
Fixes #3935 
Fixes #3907 
Fixes #3952 
Fixes #3939 
Fixes #3961 
Fixes #3956 
Fixes #3964 
Fixes #3957 
Fixes #3960 
FIxes #3950 
/hold
=> Add members 2023-01-18

config/kubernetes/org.yaml
Signed-off-by: torredil <torredil@amazon.com>
=> Add torredil to kubernetes org

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml
Fixes https://github.com/kubernetes/org/issues/3946
=> add fengshunli to kubernetes-csi, kubernetes-client

config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/3959
Fixes https://github.com/kubernetes/org/issues/3962
=> Add members 2023-01-19

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #3977 
Fixes #3973 
Fixes #3970 
Fixes #3983 
Fixes #3985 
Fixes #3974 
/hold
=> Add members 2023-01-26

config/kubernetes/org.yaml
Already a member of kubernetes-sigs - https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/org.yaml#L786.
=> Add saurav-agarwalla to kubernetes

config/kubernetes/sig-release/teams.yaml
Catching up after #3997
/sig node
=> changes to SIG Node leadership for milestones

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
=> Add GitHub teams for logical-cluster repo

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #3996
Fixes #3982 
Fixes #3981 
Fixes #3788 
Fixes #4000 
Fixes #3993 
=> Add members 2023-02-03

config/kubernetes/sig-release/teams.yaml
Add 1.27 CI Signal shadows, for CI Signal board access
=> Add 1.27 CI Signal shadows

config/kubernetes/sig-docs/teams.yaml
Update list of reviewers for the Spanish translation team
\cc @raelga
=> Update sig-docs-es members

config/kubernetes/sig-cluster-lifecycle/teams.yaml
the minikube admin and maintainers lists been very outdated and not updated this in 6 years !
=> updating minikube admins and maintainers

config/kubernetes/sig-docs/teams.yaml
Add mengjiao-liu to sig-docs-en-reviews
Ref: https://github.com/kubernetes/website/pull/39348
/cc @tengqm  @natalisucks
=> Add mengjiao-liu to sig-docs-en-reviews

config/kubernetes-csi/org.yaml
Contributing to CSI sidecar release process. Add sunnylovestiramisu so that can create release tags etc.
=> Add sunnylovestiramisu as csi sidecar maintainer

config/kubernetes-sigs/org.yaml
Contributing to csi driver release process. Add sunnylovestiramisu so that can create release tags etc.
=> Add sunnylovestiramisu as maintainer for pd-csi and filestore drivers

config/kubernetes-sigs/org.yaml
Ref: https://github.com/kubernetes/org/issues/4013
=> Add mengjiao-liu to kubernetes-sigs

config/kubernetes/sig-docs/teams.yaml
I want to join the sig-docs-zh-reviews team.
I have met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):
- Member of Kubernetes for 3+ months
- 170+ PRs merged: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Akinzhi
- 10+ PRs reviewed:https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3Akinzhi
Thanks
=> Add kinzhi to sig-docs-zh-reviews

config/kubernetes-sigs/org.yaml
I recently updated my GitHub username from `Ethyling` to `jjacobelli`
=> Update GitHub username Ethyling => jjacobelli

config/kubernetes-sigs/org.yaml
As requested by @ehashman in https://github.com/kubernetes-sigs/usage-metrics-collector/pull/25#issuecomment-1405394309
=> kubernetes-sigs: Add mrueg as member

config/kubernetes-sigs/org.yaml
Ref https://github.com/kubernetes/org/issues/3930
=> Add Zhuzhenghao to kubernetes-sigs

config/kubernetes/org.yaml
Fixes #4016
Welcome aboard, @tzneal!
=> add tzneal to kubernetes

config/kubernetes/sig-cluster-lifecycle/teams.yaml
=> Add CecileRobertMichon as SIG Cluster Lifecycle Lead

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #3984 
fixes: #4003 
fixes: #4004
fixes: #4008 
fixes: #4011 
fixes: #4012 
fixes: #4015 
fixes: #4022 
fixes: #4026 
fixes: #4029 
fixes: #4030 
=> Add members 21-02-2023

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-nightly/org.yaml
There's a few stale invites, so this removes them.
=> Removing stale invites

config/kubernetes/sig-instrumentation/teams.yaml
Add `rexagod` to SIG Instrumentation team(s).
/cc @mrueg @dgrisonnet
=> Add `rexagod`

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #4039 
Fixes #4034 
FIxes #4031 
=> Add members 2023-02-24

config/kubernetes/org.yaml
Update security-response-committee group membership to match https://github.com/kubernetes/committee-security-response/pull/173
/committee security-response
/assign @ritazh @SaranBalaji90
=> SRC membership updates

config/kubernetes/sig-cloud-provider/teams.yaml
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/18eeadea47fed534aa0d3037e8a5cec24da1e8ab
=> Remove xlgao-zju

config/kubernetes-sigs/org.yaml
Contributing to pd and filestore csi driver release process. Add tyuchn so that can create release tags etc.
=> Add tyuchn as maintainer for pd and filestore drivers

OWNERS_ALIASES, config/kubernetes/sig-release/teams.yaml, config/kubernetes/sig-windows/teams.yaml
Part of https://github.com/kubernetes/community/issues/7158
/hold until 2/28
/sig windows
/assign @jsturtevant @jayunit100 @claudiubelu
=> aravindhp sig-windows lead updates

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/4040
Fixes https://github.com/kubernetes/org/issues/4043
FIxes https://github.com/kubernetes/org/issues/4053
=> Add members 2023-03-02

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/4056
Fixes https://github.com/kubernetes/org/issues/4061
Fixes https://github.com/kubernetes/org/issues/4060
=> Add members 2023-03-03

config/kubernetes/org.yaml
Add myself `AhmedGrati` to `kompose-admin` and `kompose-maintainers`.
=> Add self to kompose-admins, kompose-maintainers

config/kubernetes-sigs/sig-testing/teams.yaml
Ref:
- https://github.com/kubernetes/org/issues/4052
=> Add GitHub teams for cloud-provider-kind repo

config/kubernetes-sigs/sig-k8s-infra/teams.yaml
Ref:
- https://github.com/kubernetes/org/issues/4054
=> Add community-images teams

config/kubernetes-sigs/org.yaml
/fix https://github.com/kubernetes/org/issues/4062
=> Add shyamjvs to kubernetes-sigs org

config/kubernetes-sigs/sig-node/teams.yaml
Remove zvonkok and adrianchiris who contributed to SRO but not to KMM.
Set qbarrand and yevgeny-shnaidman who are the main KMM contributors.
=> Update admins and maintainers of KMM

config/kubernetes/org.yaml
Add myself to kubernetes
Already a kubernetes-sigs member and am owner/admin/significant contributor to:
https://github.com/kubernetes-sigs/aws-file-cache-csi-driver
https://github.com/kubernetes-sigs/aws-fsx-csi-driver
=> add jacobwolfaws to kubernetes

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes https://github.com/kubernetes/org/issues/4085
fixes https://github.com/kubernetes/org/issues/4089
fixes https://github.com/kubernetes/org/issues/4090
fixes https://github.com/kubernetes/org/issues/4097
=> Add members 2023-03-17

config/kubernetes/org.yaml
fixes https://github.com/kubernetes/org/issues/4082
=> add members 2023-03-17 (part 2)

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml
Hey, I am already a member of https://github.com/kubernetes-sigs and https://github.com/kubernetes
Looking forward to contributing and reviewing PR on Go client and csi-driver-nfs. 
Thank you.
=> Add Pradumnasaraf to kubernetes-client, kubernetes-csi org

config/kubernetes-sigs/org.yaml
main org [member](https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L41-L47)
/fixes #4035
=> add afirth to kubernetes-sigs org

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4094
fixes https://github.com/kubernetes/org/issues/4101
fixes https://github.com/kubernetes/org/issues/4107
fixes https://github.com/kubernetes/org/issues/4108
fixes https://github.com/kubernetes/org/issues/4111
fixes https://github.com/kubernetes/org/issues/4112
=> Add members 2023-03-24

OWNERS_ALIASES
Following https://github.com/kubernetes/org/pull/4025, adding myself to OWNERS_ALIASES
/assign @fabriziopandini @justinsb @neolit123
=> Add CecileRobertMichon to sig-cluster-lifecycle-leads

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Updates PMs who should have access to be current as of today
=> add remove cluster-api-provider-azure-pms

config/kubernetes/org.yaml
Requesting membership to the kubernetes org as an existing member of kubernetes-sigs: https://github.com/kubernetes/org/issues/3771
fyi @CecileRobertMichon
=> Add nojnhuh to kubernetes org

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #4126 
/assign mrbobbytables
=> add pkprzekwas to kubernetes-sigs, kubernetes

config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-apps/teams.yaml
=> Add GitHub teams for jobset repo

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #4127
Fixes #4102 
Fixes #4132
=> Add ialidzhikov to kubernetes; add SD-13 and abhay-krishna to kubernetes-sigs

config/kubernetes/sig-docs/teams.yaml
I want to join the sig-docs-zh-reviews team.
I have met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):
Member of Kubernetes for 3+ months
120+ PRs merged: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3AZhuzhenghao
20+ PRs reviewed: https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3AZhuzhenghao
Thanks
/cc @tengqm
=> Add Zhuzhenghao to sig-docs-zh-reviews

OWNERS_ALIASES
=> Update OWNERS_ALIASES to match k/community

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
fixes https://github.com/kubernetes/org/issues/4136
fixes https://github.com/kubernetes/org/issues/4142
fixes https://github.com/kubernetes/org/issues/4141
fixes https://github.com/kubernetes/org/issues/4050
=> Add members 2023-04-07

OWNERS_ALIASES, config/kubernetes/sig-contributor-experience/teams.yaml
Ref: https://github.com/kubernetes/community/issues/7246
=> Add new leads to sig-contribex teams

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4091
fixes https://github.com/kubernetes/org/issues/4156
fixes https://github.com/kubernetes/org/issues/4154
fixes https://github.com/kubernetes/org/issues/4151
fixes https://github.com/kubernetes/org/issues/4158
fixes https://github.com/kubernetes/org/issues/4157
/hold
=> Add members 2023-04-14

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
As discussed with @justinsb and @stealthybox I am stepping down from my duties at Cluster Addons. I haven't found a lot of time lately.
=> cluster-addons: dholbach steps down

config/kubernetes/sig-api-machinery/teams.yaml
ref: https://github.com/kubernetes/org/issues/4146
=> Add teams for cel-admission-webhook repo

config/kubernetes-sigs/sig-multicluster/teams.yaml
ref: https://github.com/kubernetes/org/issues/4122
/area github-management
=> Remove kubefed teams

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4180
fixes https://github.com/kubernetes/org/issues/4173
fixes https://github.com/kubernetes/org/issues/4168
fixes https://github.com/kubernetes/org/issues/4163
fixes https://github.com/kubernetes/org/issues/4095
=> Add members 2023-04-28

config/kubernetes/org.yaml
Requesting membership to the kubernetes org as an existing member of kubernetes-sigs: 
https://github.com/kubernetes/org/issues/3985
https://github.com/kubernetes/org/pull/3986
=> Add g-gaston to kubernetes org

config/kubernetes/org.yaml
Add new admins and maintainers to the cloud-provider-gcp repo and remove the inactive members
=> Cloud provider gcp: new admins and maintainers

OWNERS_ALIASES, config/kubernetes/org.yaml
Craig Ingram (@cji) is joining the Security Response Committee
=> Onboard new SRC member Craig Ingram

config/kubernetes-sigs/sig-aws/teams.yaml
ref: #4173 
ref: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1587
=> Add self to aws-ebs-csi-driver maintainers/admins list

config/kubernetes-sigs/sig-scheduling/teams.yaml
Ref: https://github.com/kubernetes/org/issues/4174
=> Add GitHub team for kube-scheduler-wasm-extension

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4166
fixes https://github.com/kubernetes/org/issues/4196
fixes https://github.com/kubernetes/org/issues/4199
fixes https://github.com/kubernetes/org/issues/4203
fixes https://github.com/kubernetes/org/issues/4205
fixes https://github.com/kubernetes/org/issues/4209
fixes https://github.com/kubernetes/org/issues/4216
(1.28 Release Team Shadows)
fixes https://github.com/kubernetes/org/issues/4212
fixes https://github.com/kubernetes/org/issues/4213
fixes https://github.com/kubernetes/org/issues/4214
fixes https://github.com/kubernetes/org/issues/4215
fixes https://github.com/kubernetes/org/issues/4221
fixes https://github.com/kubernetes/org/issues/4223
fixes https://github.com/kubernetes/org/issues/4225
fixes …
=> Add members 2023-05-17 (including 1.28 Release Team shadows)

config/kubernetes/sig-cluster-lifecycle/teams.yaml
=> Remove emeritus_approvers from kops-maintainers

config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4226
fixes https://github.com/kubernetes/org/issues/4229
fixes https://github.com/kubernetes/org/issues/4228
=> Add members 2023-05-19 (1.28 Release Team Shadows)

config/kubernetes-sigs/sig-aws/teams.yaml
I'm a kubernetes-sigs member and am an owner of the repo. Looking to add myself as an admin and maintainer as well
=> Add self to aws-fsx-csi-driver maintainers/admins list

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Add myself to kubespray-maintainers
I'm driving the releases of Kubespray (see https://github.com/kubernetes-sigs/kubespray/issues/10075 but doesn't have to forge releases & tags.
=> Add yankay to kubespray-maintainers team 

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4241
fixes https://github.com/kubernetes/org/issues/4238
fixes https://github.com/kubernetes/org/issues/4240
(1.28 Release Shadows)
fixes https://github.com/kubernetes/org/issues/4243
fixes https://github.com/kubernetes/org/issues/4235
fixes https://github.com/kubernetes/org/issues/4234
fixes https://github.com/kubernetes/org/issues/4233
=> Add members 2023-05-24 (include 1.28 Release Shadows)

config/kubernetes/org.yaml
Sync with api-approvers from https://github.com/kubernetes/kubernetes/blob/e1ad9bee5bba8fbe85a6bf6201379ce8b1a611b1/OWNERS_ALIASES#L318-L324
=> Add msau42/deads2k to api-approvers/api-reviewers lists

config/kubernetes-sigs/sig-scheduling/teams.yaml
Project is archived - ref #4200 
=> Remove kube-batch teams

config/kubernetes/org.yaml
Member of kubernetes-sigs already. 
Raising this PR so I can become an OWNER in the test-infra for the CAPC project (https://github.com/kubernetes/test-infra/pull/29597)
=> Add chrisdoherty4 to kubernetes org

config/kubernetes/sig-cluster-lifecycle/teams.yaml
ref to https://github.com/kubernetes/kubernetes/pull/118341
=> add pacoxu to kubeadm maintainer

config/kubernetes/org.yaml
Adding myself to the kubernetes org since I'm a maintainer of kubernetes-sigs/image-builder group.
=> add kkeshavamurthy to kubernetes

config/kubernetes-csi/org.yaml
I'm a member of kubernetes and kubernetes-sigs.
- https://github.com/kubernetes/org/issues/3854
- https://github.com/kubernetes/org/issues/2402
=> add carlory to  kubernetes-csi

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
fixes https://github.com/kubernetes/org/issues/3561
fixes https://github.com/kubernetes/org/issues/4206
fixes https://github.com/kubernetes/org/issues/4250
fixes https://github.com/kubernetes/org/issues/4257
=> Add members 2023-06-07

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
=> Add teams for cluster-api-ipam-provider-in-cluster

config/kubernetes/org.yaml
ref: https://kubernetes.slack.com/archives/C03KT3SUJ20/p1686115372343689
original org membership request: https://github.com/kubernetes/org/issues/3557
=> Rename NitishKumar06 to nitishfy

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4269
fixes https://github.com/kubernetes/org/issues/4270
fixes https://github.com/kubernetes/org/issues/4272
=> Add members 2023-06-09

config/kubernetes-sigs/sig-contributor-experience/teams.yaml
Ref: https://github.com/kubernetes/org/issues/4218
=> contribex: Add teams for sigs-github-actions repo

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
fixes https://github.com/kubernetes/org/issues/4280
fixes https://github.com/kubernetes/org/issues/4281
fixes https://github.com/kubernetes/org/issues/4282
fixes https://github.com/kubernetes/org/issues/4283
fixes https://github.com/kubernetes/org/issues/4284
fixes https://github.com/kubernetes/org/issues/4288
fixes https://github.com/kubernetes/org/issues/4294
=> Add members 2023-06-16

config/kubernetes-sigs/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4300
=> add hangscer8 to kubernetes-sigs (2023-06-23)

config/kubernetes-sigs/sig-auth/teams.yaml
ref: https://github.com/kubernetes/org/issues/4297
=> remove multi-tenancy teams

config/kubernetes-sigs/sig-aws/teams.yaml, config/kubernetes-sigs/sig-cloud-provider/teams.yaml, config/kubernetes/sig-cloud-provider/teams.yaml
Volunteering to help with admin duties as some folks are heading (or already) on vacation. Some folks have moved on as well, but will leave cleanup for later.
=> Add dims as admin to aws-* related repos

config/kubernetes-sigs/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4308
=> add joe-atzinger to kubernetes-sigs (2023-06-30)

config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/4319
=> update czybjtu to nayihz

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4312
fixes https://github.com/kubernetes/org/issues/4316
=> Add members 2023-07-07

config/kubernetes-sigs/sig-node/teams.yaml
ref: https://github.com/kubernetes/org/issues/4224
=> Add noderesourcetopology-api teams

config/kubernetes-sigs/sig-network/teams.yaml
Fixes https://github.com/kubernetes-sigs/network-policy-api/issues/118
=> add Dan Winship as an admin

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4324
fixes https://github.com/kubernetes/org/issues/4325
fixes https://github.com/kubernetes/org/issues/4326
fixes https://github.com/kubernetes/org/issues/4327
fixes https://github.com/kubernetes/org/issues/4328
=> Add members 2023-07-14

config/kubernetes/org.yaml
cc @apelisse 
For access to run Github Actions for new contributors, ref: https://github.com/kubernetes/kube-openapi/pull/408#issuecomment-1591649454
=> Add jefftree to kube-openapi maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #4301 
fixes: #4329
fixes: #4330 
fixes: #4333 
fixes: #4338 
fixes: #4339 
=> Add members 2023 07 19

config/kubernetes-sigs/org.yaml
fixes: #4337 
Missed adding yesterday
=> add zhanggbj to kubernetes-sigs

config/kubernetes/org.yaml
Joining Kubernetes org as I am already part of kubernetes-sigs
=> Add willie-yao to kubernetes

config/kubernetes/sig-docs/teams.yaml
I am honored to hear that you were willing to recommend me .Thank you(@windsonsea) for the invitation to join `sig-docs-zh-owners`. I consider it an honor to have the opportunity to contribute further.
I have met the [requirements for approver](https://github.com/kubernetes/community/blob/master/community-membership.md#approver):
- Reviewed over 400 PRs:
https://github.com/kubernetes/website/pulls?q=is%3Apr+commenter%3Aydfu+-author%3Aydfu
- Merged over 100 PRs:
https://github.com/kubernetes/website/pulls?q=is%3Amerged+is%3Apr+author%3AydFu
- Been a member of Kubernetes for more than 30 months.
- Acted as a reviewer for Kubernetes/website Chinese documents for over 14 months.
I am committed to contributing to the community and believe that taking on the role of an approver will allow me to …
=> Add ydFu to sig-docs-zh-owners

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4290
fixes https://github.com/kubernetes/org/issues/4302
fixes https://github.com/kubernetes/org/issues/4336
fixes https://github.com/kubernetes/org/issues/4342
fixes https://github.com/kubernetes/org/issues/4348 
fixes https://github.com/kubernetes/org/issues/4349
=> Add members 2023-07-28

config/kubernetes-sigs/sig-cloud-provider/teams.yaml, config/restrictions.yaml
=> Add cloud-provider-equinix-metal teams

Makefile
/sig contributor-experience
/assign @Priyankasaggu11929
=> fix script path for deploy target

config/kubernetes/sig-docs/teams.yaml
Add dipesh-rawat to sig-docs-en-reviews
Ref: https://github.com/kubernetes/website/pull/41627
/cc @sftim @reylejano @natalisucks @tengqm
=> Add dipesh-rawat to sig-docs-en-reviews

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 20230803

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Uncommenting myself as I wasn't a member at the time of #4353 but now am through #4361
=> Add mjlshen to capi release team after membership was obtained

config/kubernetes-sigs/org.yaml
I am an active member of `kubernetes org` and would like to apply to join the `kubernetes-sigs org`,
and look forward to contributing more.
- Meet the conditions for [community membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem)
- https://github.com/kubernetes/org/issues/2475
=> Add ydFu to kubernetes-sigs org

config/kubernetes-sigs/sig-network/teams.yaml
As discussed offline, I need this to set up releases and being able to edit issues/projects etc
/cc @robscott
=> add LiorLieberman to ingress2gateway admin

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4350
fixes https://github.com/kubernetes/org/issues/4351
fixes https://github.com/kubernetes/org/issues/4368
fixes https://github.com/kubernetes/org/issues/4369
fixes https://github.com/kubernetes/org/issues/4372
fixes https://github.com/kubernetes/org/issues/4373
=> Add members 2023-08-11

config/kubernetes-client/org.yaml
I am an active member of `kubernetes org` and would like to apply to join the `kubernetes-client org`,
and look forward to contributing more.
- Meet the conditions for [community membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem)
- https://github.com/kubernetes/org/issues/2475
=> Add ydFu to kubernetes-client org

config/kubernetes/sig-docs/teams.yaml
Remove me from `website-maintainers`
=> Remove 1.28 lead from sig docs team

config/kubernetes/sig-release/teams.yaml
xref https://github.com/kubernetes/org/pull/4255
=> add pacoxu to milestone maintainer for kubeadm

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4382
fixes https://github.com/kubernetes/org/issues/4383
fixes https://github.com/kubernetes/org/issues/4386
fixes https://github.com/kubernetes/org/issues/4389
fixes https://github.com/kubernetes/org/issues/4393
fixes https://github.com/kubernetes/org/issues/4394
It also include a few very minor cleanups.
=> Add members 2023-08-18

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #4406 
fixes: #4405 
fixes: #4399 
fixes: #4397
=> Add members 20230824

config/kubernetes/provider-openstack/teams.yaml
this PR updates the current maintainers for cloudprovider openstack https://github.com/kubernetes/cloud-provider-openstack
=> update openstack teams

config/kubernetes-sigs/org.yaml
I am a currently active member of the Kubernetes org and need org access to the Kubernetes SIGs org, as I am contributing to Kustomize.
=> Add stormqueen1990 to kubernetes-sigs org

config/kubernetes/sig-testing/teams.yaml
active folks from: https://github.com/kubernetes/test-infra/blob/master/OWNERS_ALIASES#L125-L133
=> Update test-infra repo admins and maintainers

config/kubernetes/sig-testing/teams.yaml
Follow up from https://github.com/kubernetes/org/pull/4404
=> Add folks who are on-call for test-infra

config/kubernetes/sig-contributor-experience/teams.yaml
=> Update contributor comms team

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4413
fixes https://github.com/kubernetes/org/issues/4416
fixes https://github.com/kubernetes/org/issues/4426
fixes https://github.com/kubernetes/org/issues/4428
fixes https://github.com/kubernetes/org/issues/4437
fixes https://github.com/kubernetes/org/issues/4442
=> Add members 2023-09-08

config/kubernetes-sigs/org.yaml
=> Add members 20230911

config/kubernetes/sig-api-machinery/teams.yaml
=> Replace lavalamp with jpbetz for SIG apimachinery teams aliases

config/kubernetes-sigs/org.yaml
=> Add member: bells17

config/kubernetes-sigs/sig-aws/teams.yaml
Admin / maintainer of AWS CSI drivers, updating permissions.
=> Add torredil to CSI drivers maintainers/admins list

config/kubernetes/org.yaml
fixes: https://github.com/kubernetes/org/issues/4457
fixes: https://github.com/kubernetes/org/issues/4460
=> Add member 20230918

config/kubernetes/sig-docs/teams.yaml, config/kubernetes/sig-release/teams.yaml
Hey y'all,
Adding myself to sig-docs-en-owners for the v1.29 release. Also adding the v1.29 shadows and myself to website-milestone-maintainers and release team, as well as removing v1.27 shadows. 
cc: @Priyankasaggu11929 @reylejano
=> Kat for 1.29

config/kubernetes-sigs/sig-cli/teams.yaml
=> add koba1t to kustomize maintainers

config/kubernetes-sigs/sig-aws/teams.yaml
See aws-ebs-csi-driver Owners List: [Update OWNERS](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1737)
Closes #4479 
CC: @ConnorJC3 @torredil
=> Update aws-ebs-csi-driver admin and maintainer lists.

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Add myself to kubespray-maintainers
I'm contributing already to the releases of Kubespray see below:  but doesn't have to forge releases & tags.
* https://github.com/kubernetes-sigs/kubespray/issues/10389
* https://github.com/kubernetes-sigs/kubespray/issues/9638
* https://github.com/kubernetes-sigs/kubespray/issues/10075
* https://github.com/kubernetes-sigs/kubespray/issues/10179
but doesn't have to forge releases & tags.
=> Add mzaian to kubespray-maintainers team

config/kubernetes/sig-docs/teams.yaml
Hi, I have been a part of sig-docs for approximately 2 years, and I want to sincerely express my deep appreciation for the invaluable knowledge I have gained through the review comments provided by maintainers and the collaborative review process I have been involved in. It is truly an honor for me to be a member of such a talented team and have the opportunity to work with you.
Here is my efforts and growth journey in years:
- English PRs I opened: [100+](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Awindsonsea+label%3Alanguage%2Fen+is%3Aclosed)
- English PRs I reviewed: [80+](https://github.com/kubernetes/website/pulls?q=is%3Apr++reviewed-by%3Awindsonsea+label%3Alanguage%2Fen+)
cc @sftim @tengqm @dipesh-rawat @mengjiao-liu
=> Add windsonsea to sig-docs-en-reviews

config/kubernetes-sigs/sig-contributor-experience/teams.yaml
=> Remove contributor-tweets teams

config/kubernetes/org.yaml
I have been a member of kubernetes-sig org and would like to apply to join the kubernetes org, and look forward to contributing more.
- https://github.com/kubernetes/org/issues/4154
related works:
- https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aclosed+author%3Anayihz
=> add nayihz to kubernetes org

config/kubernetes-csi/org.yaml
=> Add martinforreal to kubernetes-csi org

config/kubernetes-client/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
fixes https://github.com/kubernetes/org/issues/4462
fixes https://github.com/kubernetes/org/issues/4466
fixes https://github.com/kubernetes/org/issues/4470
fixes https://github.com/kubernetes/org/issues/4472
fixes https://github.com/kubernetes/org/issues/4473
fixes https://github.com/kubernetes/org/issues/4474
fixes https://github.com/kubernetes/org/issues/4476
fixes https://github.com/kubernetes/org/issues/4477
fixes https://github.com/kubernetes/org/issues/4483
fixes https://github.com/kubernetes/org/issues/4485
fixes https://github.com/kubernetes/org/issues/4488
fixes https://github.com/kubernetes/org/issues/4489
fixes https://github.com/kubernetes/org/issues/4492
=> Add members 2023-09-30

OWNERS_ALIASES, config/kubernetes/provider-openstack/teams.yaml
Update to reflect changes in https://github.com/kubernetes/cloud-provider-openstack/pull/2318
=> Update cloud-provider-openstack maintainers

config/kubernetes-sigs/org.yaml
- Reference: https://github.com/kubernetes/org/issues/4494#issuecomment-1742147606
=> Add nitishfy to kubernetes-sigs org

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
fixes #4475
fixes #4491 
fixes #4496 
fixes #4500
=> Add members 2023-10-05

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
fixes: #4464 
fixes: #4484
=> Add members 2023-10-06

config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-multicluster/teams.yaml, config/restrictions.yaml
=> Add teams for cluster-inventory-api

OWNERS_ALIASES, config/kubernetes/sig-release/teams.yaml
Part of resolving https://github.com/kubernetes/community/issues/7572.
Also adds @MikeZappa87 and myself to milestone maintainers, as we forgot to do that earlier this year.
=> Add Dan Winship as SIG Network Technical Lead

config/kubernetes-sigs/sig-network/teams.yaml, config/restrictions.yaml
=> Add teams for blixt repo

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes
#4505 
#4510 
#4513 
#4515 
#4517
#4518
=> Add members 2023 oct 14

config/kubernetes/org.yaml
=> Add a7i to kubernetes org

config/kubernetes/org.yaml
I am one of the primary contributors to that repo
=> Add sdmodi as maintainers of cloud-provider-gcp repo

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml
I'm a member of kubernetes and kubernetes-sigs already, this PR adds me to the rest of the organizations.
=> Add dulek to kubernetes-csi and kubernetes-client

config/kubernetes-sigs/org.yaml
Add timwangmusic to k8s/sigs members list
=> Add timwangmusic to k8s/sigs members list

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #4507
Fixes #4508
Fixes #4509
Fixes #4511 
Fixes #4527 
Fixes #4528 
Fixes #4530 
Fixes #4532
Fixes #4533
Fixes #4539
=> Add Members 2023-10-25

config/kubernetes-sigs/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4520
=> Add members 2023-10-26-0900

config/kubernetes-sigs/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4541
fixes https://github.com/kubernetes/org/issues/4543
=> Add members 2023-10-26

config/kubernetes-csi/org.yaml
=> Add cvvz to kubernetes-csi org

config/kubernetes-sigs/org.yaml
The PR:
fixes https://github.com/kubernetes/org/issues/4547
=> Add members 2023-10-28

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
fixes https://github.com/kubernetes/org/issues/4554
=> Add members 2023-10-28-1500

config/kubernetes-client/org.yaml
This PR:
fixes https://github.com/kubernetes/org/issues/4552
=> add mstruebing to kubernetes-client

config/kubernetes-client/org.yaml
Add me as an admin for the javascript client so I can help maintain the repository by merging PRs and creating releases
=> add mstruebing as javascript client admin

config/kubernetes-sigs/org.yaml
This PR:
fixes: https://github.com/kubernetes/org/issues/4553
=> add matrus2 to kubernetes-sigs

config/kubernetes-sigs/sig-scheduling/teams.yaml
=> Add tenzen-y to kueue repo admins

config/kubernetes/org.yaml
... based on membership of kubernetes-sigs
=> Add skitt to kubernetes

OWNERS_ALIASES, config/kubernetes-sigs/sig-k8s-infra/teams.yaml, config/kubernetes/sig-k8s-infra/teams.yaml, config/kubernetes/sig-release/teams.yaml, config/kubernetes/sig-testing/teams.yaml
xref: https://github.com/kubernetes/community/pull/7584
=> Rotate sig k8s leadership

config/kubernetes-sigs/org.yaml
Adding org ownership for kubernetes-sigs.
=> Add cartermckinnon to kubernetes-sigs

config/kubernetes-client/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/4521
Fixes https://github.com/kubernetes/org/issues/4561
Fixes https://github.com/kubernetes/org/issues/4563
=> Add member 20231102

config/kubernetes-client/org.yaml
add davidgamero to javascript-admins teams
=> add davidgamero to javascript-admins teams

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes/org.yaml
I'm a member of kubernetes-sigs already, this PR adds me
to kubernetes-client and kubernetes-csi.
=> Add EmilienM to kubernetes, kubernetes-csi and kubernetes-client

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes #4572
Fixes #4573
Fixes #4568
=> Add member 20231103

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #4571 
fixes: #4574 
fixes: #4576 
fixes: #4578 
fixes: #4579 
fixes: #4582 
fixes: #4583 
=> Add members 20231113

config/kubernetes/sig-docs/teams.yaml
Add @jongwooo to sig-docs-ko-reviewes. (Reviewer for Korean l10n contents)
=> Add jongwooo to sig-docs-ko-reviews

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/4592
Fixes https://github.com/kubernetes/org/issues/4593
Fixes https://github.com/kubernetes/org/issues/4595
Fixes https://github.com/kubernetes/org/issues/4601
=> Add member 20231124

config/kubernetes/org.yaml
based on membership of kubernetes-sigs
=> Add musaprg to kubernetes

config/kubernetes-sigs/sig-aws/teams.yaml
add mskanth972 as owner to aws-efs-csi-driver
=> add mskanth972 as owner to aws-efs-csi-driver

config/kubernetes/org.yaml
currently a member of kubernetes-sigs, adding myself to kubernetes following these instructions: https://github.com/kubernetes/org/blob/main/README.md#kubernetes-github-organization
=> add cahillsf to kubernetes

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Closes https://github.com/kubernetes/org/issues/4607
=> add VannTen to kubernetes/kubernetes-sigs ORG 

config/kubernetes/sig-docs/teams.yaml
Adding myself to the website-maintainers role for the upcoming v1.29 release day.
/assign @natalisucks @reylejano
=> Adds katcosgrove to website maintainers for 1.29 release day

config/kubernetes/org.yaml
Based on membership of `kubernetes-sigs org`, I would like to add myself as a member of the `kubernetes org`.
ref: https://github.com/kubernetes/org/issues/4604
=> Add mochizuki875 to kubernetes org

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2023-12-11

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add wg-policy members

config/kubernetes-sigs/org.yaml
=> Add members 2023-12-14

OWNERS_ALIASES
Ref https://github.com/kubernetes/community/issues/7618
/assign @mwielgus @swatisehgal
=> WG-Batch leads update

config/kubernetes/org.yaml
=> Add members 2023-12-22

config/kubernetes/org.yaml
=> Add members 2023-12-18

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2023-12-20

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
fixes #4637 
fixes #4638
=> Add members 2023-12-27

config/kubernetes/org.yaml
I am already a [member of kubernetes-sigs](https://github.com/kubernetes/org/issues/4500), and would like to add myself to the kubernetes org.
=> Add nrb to kubernetes org

config/kubernetes-sigs/sig-windows/teams.yaml
Also removing dougland 
/sig windows
/assign @aravindhp @jsturtevant @knabben
=> Adding AravindhP as maintainter to sig-windows-tool repo

config/kubernetes-sigs/sig-windows/teams.yaml
/sig windows
/assign @knabben @jsturtevant @aravindhp @claudiubelu
=> Updating sig-windows github groups

config/kubernetes/org.yaml
This PR:
- fixes #4648 
- fixes #4653
=> Add members 2024-01-04-eve

config/kubernetes-sigs/org.yaml
=> Add Members 2024-01-06

config/kubernetes/org.yaml
=> Add members 2024-01-08

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4636 
- fixes #4641 
- fixes #4649 
- fixes #4652
=> Add members 2024-01-04

config/kubernetes-sigs/org.yaml
=> Add Members 2024-01-08-noon

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add Members 2024-01-08-eve

config/kubernetes-sigs/sig-testing/teams.yaml, config/restrictions.yaml
Ref https://github.com/kubernetes/org/issues/4654
/assign @kubernetes/owners
=> config: add teams for hydrophone under k-sigs/sig-testing

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4666 
- fixes #4669
=> Add members 2024-01-11

config/kubernetes/org.yaml
This PR:
- fixes #4674 
- fixes #4675 
- fixes #4678
=> Add members 2024-01-15

config/kubernetes-sigs/org.yaml
=> Add members 2024-01-12

config/kubernetes/org.yaml
=> Add members 2024-01-16

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4681 
- fixes #4685 
- fixes #4687 
- fixes #4688 
- fixes #4691
=> Add members 2024-01-18

config/kubernetes/org.yaml
This PR:
- fixes #4689 
- fixes #4694
=> Add members 2024-01-19

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-01-21

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4696 
- fixes #4697 
- fixes #4699
=> Add members 2024-01-20

config/kubernetes-sigs/sig-network/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/4673
=> Add teams for knftables repo

config/kubernetes/sig-release/teams.yaml
Need this as TL of API Machinery to opt-in SIG API Machinery KEPs to the current release.
=> Add jpbetz to milestone maintainer team

Makefile
PR fixes a typo in my Github handle (@Priyankasaggu11929) in the Makefile
=> Minor: fix typo in GitHub Handle (Priyankasaggu11929) 

config/kubernetes/sig-apps/teams.yaml
Removing myself from sig-apps teams as I am no longer actively working there.
=> Remove tnozicka from sig-apps teams

config/kubernetes/org.yaml
=> Add members 2024-01-23

config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml
=> Add jasonbraganza to kubernetes-client, kubernetes-csi

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4714 
- fixes #4715
=> Add members 2024-01-24

config/kubernetes/org.yaml
=> Add members 2024-01-25

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Just noticed that I forgot to add me in this groups
cc @sbueringer @chrigl
=> Add fabriziopandini to CAPV GitHub admins and maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes https://github.com/kubernetes/org/issues/4724
=> add adityabhatia to kubernetes-sigs, kubernetes

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Adding myself to the approvers for cluster-api relevant staging images.
xref:
https://github.com/kubernetes-sigs/cluster-api/pull/9997
/assign sbueringer
=> sig-cluster-lifecycle/cluster-api: add chrischdi to maintainers

config/kubernetes/sig-release/teams.yaml
Need this as lead of SIG Autoscaling to opt-in KEP to current release cycle.
=> Add gjtempleton to Milestone Maintainer team

config/kubernetes-sigs/org.yaml
This PR:
- fixes #4731 
- fixes #4732
=> Add members 2024-02-07

config/kubernetes/org.yaml
=> Add members 2024-02-07-eve

config/kubernetes/sig-docs/teams.yaml, config/kubernetes/sig-release/teams.yaml
I just remembered - we choose to comment him out to get the other shadows set up. 
cc @chanieljdan
=> commenting in daniel chan now that his org request is approved.

config/kubernetes/org.yaml
=> Add members 2024-02-08

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4741 
- fixes #4744
=> Add members 2024-02-09

config/kubernetes/sig-release/teams.yaml
As TL for SIG Scheduling https://github.com/kubernetes/community/tree/master/sig-scheduling
=> Add alculquicondor to milestone-maintainers

config/kubernetes/org.yaml, config/restrictions.yaml
This repo was archived, so removing it from the config
=> Remove funding repo

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-02-13

config/etcd-io/org.yaml, config/restrictions.yaml
Fixes https://github.com/kubernetes/org/issues/4754
/hold
Hold pending repo migration.
=> Added team for etcd-io/auger

config/kubernetes/sig-release/teams.yaml
Missed this earlier! Just adds RT lead shadows to the correct groups.
=> Add RT lead shadows to teams

config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/4770
Fixes https://github.com/kubernetes/org/issues/4745
=> Add members 19 feb 2024

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: https://github.com/kubernetes/org/issues/4762
fixes: https://github.com/kubernetes/org/issues/4756
fixes: https://github.com/kubernetes/org/issues/4757
=> Add members 2024-02-19

config/kubernetes-sigs/org.yaml
I am already a member of kubernetes, add myself to kubernetes-sigs to facilitate my contributions to projects under it.
=> add tnqn to kubernetes-sigs

config/kubernetes-client/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-02-25

config/kubernetes-sigs/sig-testing/teams.yaml, config/restrictions.yaml
=> Add new teams for kubernetes-sigs/testgrid

config/kubernetes-sigs/sig-auth/teams.yaml, config/restrictions.yaml
fixes https://github.com/kubernetes/org/issues/4779
=> Add new teams for kubernetes-sigs/referencegrant-poc

config/kubernetes/org.yaml
=> Add members 2024-02-27

config/kubernetes/org.yaml
=> Add members 2024-02-28

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml, config/kubernetes/sig-apps/teams.yaml
fixes: #4794
I have verified that it is indeed them.
=> Rename AhmedGrati -> TessaIO

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4791 
- fixes #4795
=> Add members 2024-02-29

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
/assign @mboersma @jsturtevant @kkeshavamurthy
=> Promote drew-viles to maintainer of image-builder

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4800 
- fixes #4801
=> Add members 2024-03-05

config/kubernetes/sig-release/teams.yaml
/cc @Vyom-Yadav
So Vyom can access the ci signal and bug triage boards.
=> Add Vyom as co lead of release signal team

config/etcd-io/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4804 
- fixes #4809
=> Add members 2024-03-09

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-03-12

config/kubernetes-sigs/org.yaml
=> Add members 2024-03-12-morn

OWNERS_ALIASES, config/kubernetes-sigs/sig-instrumentation/teams.yaml, config/kubernetes/sig-instrumentation/teams.yaml
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>
=> sig-instrumentation: add `rexagod`

config/kubernetes/sig-release/teams.yaml
Add @neoaggelos and @sanchita-07 to the @kubernetes/release-team-release-signal team
cc @Vyom-Yadav @pacoxu
=> sig-release: add neoaggelos and sanchita-07 to release-team-release-signal

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-03-13

OWNERS_ALIASES, config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml, config/kubernetes/sig-cluster-lifecycle/teams.yaml
Follow up from https://github.com/kubernetes/community/pull/7754
/assign @fabriziopandini @neolit123 @vincepri @justinsb
=> Remove myself from SIG Cluster Lifecycle owners

config/kubernetes/org.yaml
Previously a member of kubernetes-sigs
=> Add sunjayBhatia to kubernetes org

OWNERS_ALIASES, config/kubernetes/sig-release/teams.yaml
Adding as part of https://github.com/kubernetes/community/issues/7759
=> add stefan as apimachinery lead

config/etcd-io/org.yaml
=> Add James to etcd maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4823 
- fixes #4825 
- fixes #4826 
- fixes #4829
=> Add members 2024-03-16

config/etcd-io/org.yaml
Fixes https://github.com/kubernetes/org/issues/4844.
cc @ahrtr, @jmhbnz
=> Add elbehery to etcd-io members.

config/kubernetes-sigs/sig-network/teams.yaml
As discussed offline, we are adding Mattia as ingress2gateway maintainer
/cc @shaneutt @robscott @youngnick @mlavacca
=> add mlavacca as ingress2gateway maintainer

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-04-15-noon

config/kubernetes/sig-docs/teams.yaml
Adding myself to the website-maintainers role for the upcoming v1.30 release day.
/assign @natalisucks @reylejano
=> Add drewhagen to website-maintainers team for 1.30 release

config/kubernetes/org.yaml
=> Add members 2024-04-22

OWNERS_ALIASES, config/kubernetes-sigs/sig-cli/teams.yaml, config/kubernetes/org.yaml, config/kubernetes/sig-cli/teams.yaml, config/kubernetes/sig-release/teams.yaml
Ref https://github.com/kubernetes/community/issues/7803
/assign @mpuckett159 @eddiezane
=> Update sig-cli leads

config/kubernetes-sigs/org.yaml
Add admin and write access for @dannawang221 to [gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) and [gcp-filestore-csi-driver](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver)
=> Add dannawang0221 to pdcsi and filestore csi repo

config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Prep to archive repo.
ref: https://github.com/kubernetes/org/issues/4774
=> Remove cloud-provider-baiducloud teams

config/kubernetes/org.yaml
=> Add members 2024-04-25

config/kubernetes-sigs/sig-apps/teams.yaml
This is needed since I need to push new branch to remote for releasing
=> Add liurupeng as lws admin

config/kubernetes-sigs/org.yaml
=> Add members 2024-04-26

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4909 
- fixes #4911 
- fixes #4915 
- fixes #4916
=> Add members 2024-04-27

config/kubernetes-sigs/sig-auth/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/4902
=> sig-auth: Add teams for secrets-store-sync-controller

config/kubernetes/org.yaml, config/restrictions.yaml
Per: https://github.com/kubernetes/org/issues/4805
cc @kubernetes/sig-node-leads
=> Add `cri-client` staging repository

OWNERS_ALIASES
As per https://github.com/kubernetes/community/issues/7850
=> added wg serving

config/kubernetes/org.yaml
This PR:
- fixes https://github.com/kubernetes/org/issues/4923
=> add levi106 to kubernetes

config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-architecture/teams.yaml, config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4886
/assign @kubernetes/sig-architecture-leads
=> sig-architecture: add wg-device-management gh teams

config/etcd-io/org.yaml, config/kubernetes-client/org.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4878
- fixes #4913
- fixes #4921
=> Add members 2024-05-01

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> add tico88612 to kubernetes-sigs, kubernetes

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml, config/kubernetes/sig-k8s-infra/teams.yaml
Please help me get my GH handle updated. Thanks!
=> Update Riaankl Github handle to riaankleinhans after a name change on my profile

OWNERS_ALIASES
Adding salaxander as a SIG docs tech lead
CC @natalisucks @divya-mohan0209 @reylejano
=> docs: add salaxander as SIG docs tech lead

OWNERS_ALIASES
Adding myself as SIG Docs tech lead!
=> Add Kat Cosgrove as SIG Docs tech lead

config/kubernetes/sig-architecture/teams.yaml
Update prod-readiness team based on https://github.com/kubernetes/enhancements/pull/4566 
=> Add soltysh to prod-readiness approvers

config/kubernetes/sig-release/teams.yaml
Ref: https://github.com/kubernetes/community/issues/7834
=> SIG Autoscaling - Milestone Maintainers Update

OWNERS_ALIASES
As per https://github.com/kubernetes/community/issues/7876
=> added Jeffwan as a wg serving chair

config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-etcd/OWNERS, config/kubernetes-sigs/sig-etcd/teams.yaml, config/restrictions.yaml
Also added ahrtr and wenjiaswe to k-sigs org as a prereq 👍 
ref: https://github.com/kubernetes/org/issues/4908
=> Add teams for etcd-manager repo

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixed #4940
- Fixed #4943
- Fixed #4946
=> Add members 2024-05-14

config/kubernetes/org.yaml
This PR:
- Fixed https://github.com/kubernetes/org/issues/4953
=> Add members 2024-05-17

config/etcd-io/sig-etcd/teams.yaml
Add me to the the sig-etcd/etcd-reviewers team.
Part of etcd-io/etcd#18020.
=> Add ivanvc as sig-etcd/etcd reviewer

config/etcd-io/sig-etcd/teams.yaml
Part of https://github.com/etcd-io/etcd/issues/18020.
=> Add siyuanfoundation as sig-etcd/etcd reviewer

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-05-21

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4965 
- fixes #4968
=> Add members 2024-05-23

config/kubernetes-sigs/org.yaml
=> Add members 2024-05-24

config/kubernetes-sigs/org.yaml
[Enable automated testing on the `gateway-api` project.](https://github.com/kubernetes-sigs/gateway-api/pull/3107#issuecomment-2123754462).
I am [a member of the Kubernetes org](https://github.com/kubernetes/org/blob/ee39e69521c17f8417a9c0b640fb184839183bfc/config/kubernetes/org.yaml#L231) and [I read that this qualifies me](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem).
=> Join kubernetes-sigs org

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4967
- fixes #4973
- fixes #4976
- fixes #4979
=> Add members 2024-05-25

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixed https://github.com/kubernetes/org/issues/4966
- Fixed https://github.com/kubernetes/org/issues/4969
=> Add members 2024-05-26

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #4975 
- fixes #4986 
- fixes #4987
=> Add members 2024-05-29

config/kubernetes/sig-release/teams.yaml
References https://github.com/kubernetes/sig-release/issues/2493
cc @katcosgrove @gracenng @Priyankasaggu11929
=> Add 1.31 release team permissions

config/kubernetes/org.yaml
/assign @bowei @thockin @wojtek-t
=> update cloud-provider-gcp admins and remove inactive members

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-06-07

config/kubernetes/sig-docs/teams.yaml
Update sig-docs-ja-owners member 
ref: https://github.com/kubernetes/website/pull/46724
=> Add bells17 to sig-docs-ja-owners team

config/kubernetes/org.yaml
This PR:
- fixes #5009 
- fixes #5011
=> Add members 2024-06-11

config/kubernetes-sigs/sig-architecture/teams.yaml, config/restrictions.yaml
=> sig-arch: Add verify-conformance teams

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-06-12

config/kubernetes-sigs/sig-node/teams.yaml
Adding @ybettan to the admin teams as he is taking over the leadership for the project
=> Add ybettan to KMM admin teams

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5016 
- fixes #5017
=> Add members 2024-06-14

config/etcd-io/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5020  
- fixes #5022
=> Add members 2024-06-15

config/kubernetes/org.yaml
This PR:
- Fixed https://github.com/kubernetes/org/issues/5023
=> Add members 2024-06-17

config/kubernetes-sigs/org.yaml
Towards https://github.com/kubernetes/org/issues/4873#issuecomment-2172345942 
/assign @jasonbraganza @Priyankasaggu11929
=> add ericsmalling to kubernetes-sigs

config/kubernetes-csi/org.yaml
=> Add members 2024-06-19

config/kubernetes-sigs/org.yaml
This PR:
- fixes #5031 
- fixes #5032
=> Add members 2024-06-21

config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/5034
/assign @Priyankasaggu11929 @nikhita
=> add mszadkow to kubernetes-sigs

config/etcd-io/org.yaml
This PR:
- Fixed https://github.com/kubernetes/org/issues/5046
=> Add members 2024-07-05 

config/kubernetes-sigs/sig-security/teams.yaml
Ref https://github.com/kubernetes/org/issues/4873
/assign @Priyankasaggu11929 @palnabarun @nikhita
=> k-sigs/sig-security: add in teams for cve-feed-osv

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5051 (original ref: #5005)
=> Rename members 2024-07-08

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-07-11

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes https://github.com/kubernetes/org/issues/5060
=> Add members 2024-07-15

config/kubernetes-sigs/sig-network/teams.yaml, config/restrictions.yaml
ref https://github.com/kubernetes/org/issues/5054
=> Archive kubernetes-sigs/kpng

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixed https://github.com/kubernetes/org/issues/5066
=> Add members 2024-07-17

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5059 
- fixes #5065
=> Add members 2024-07-18

config/kubernetes-csi/org.yaml, config/kubernetes/org.yaml
Fixes #4111 
I'm already in kubernetes-sigs, but need to join kubernetes and kubernetes-csi. Was made aware that I should make PR for joining other orgs myself due to [this comment](https://github.com/kubernetes/org/issues/3722#issuecomment-1265273330). Was told I should not raise a new issue. Let me know if this is not the case or previous comment is out of date.
Thank you so much!!!
=> Add AndrewSirenko to kubernetes and kubernetes-csi

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-07-24

config/kubernetes-sigs/sig-architecture/teams.yaml, config/kubernetes-sigs/sig-network/teams.yaml, config/restrictions.yaml
ref: #5072 
ref: #4997 
ref: #4996 
=> Add repos for wg-serving, networking

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5075
- fixes #5081
=> Add members 2024-07-31

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Syncs admin list with https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/OWNERS_ALIASES#L16-L21
=> Add furkatgofurov7 to CAPI Operator admins list

config/kubernetes-sigs/org.yaml
Already part of K8s org - https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L409
=> Adding to k8s sigs

config/kubernetes/org.yaml
=> Add members 2024-08-05

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-08-03

config/etcd-io/sig-etcd/teams.yaml
https://github.com/etcd-io/etcd/issues/18370
=> Add thedtripp as sig-etcd/etcd member

config/kubernetes/sig-node/teams.yaml
cc @sohankunkerkar  @kubernetes/sig-node-cri-o-test-maintainers
=> Add sohankunkerkar to `sig-node-cri-o-test-maintainers`

config/etcd-io/org.yaml, config/etcd-io/sig-etcd/teams.yaml, config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/5093
cc: SIG Etcd leads (@ahrtr @jmhbnz @serathius @wenjiaswe)
=> sig-etcd: add gh teams for etcd-operator

config/kubernetes/sig-docs/teams.yaml
[website issue #47454](https://github.com/kubernetes/website/issues/47454)
Oops, I forgot to add myself under this list last week. Required to freeze the website ahead of release day tomorrow
@natalisucks @reylejano @katcosgrove @salaxander
=> adding Drew to milestone maintainers in order to freeze the website

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-08-13

OWNERS_ALIASES, config/kubernetes/sig-node/teams.yaml, config/kubernetes/sig-release/teams.yaml
/sig node
/assign @haircommander
Related to: https://github.com/kubernetes/community/issues/8011
=> added Peter Hunt as a sig node chair

config/kubernetes/sig-cloud-provider/teams.yaml
Adding myself as a maintainer to cloud provider aws repo to create releases and branches for new versions.
=> Add kmala to sig-cloud-provider-aws maintainers

config/kubernetes/sig-docs/teams.yaml
adding salaxander as sig docs tech lead
=> docs: adding salaxander as sig docs tech lead

config/etcd-io/org.yaml
=> Add members 2024-08-23

config/kubernetes/sig-cluster-lifecycle/teams.yaml
Update the admins of the kOps repo
=> Update kOps maintainers

config/kubernetes-sigs/org.yaml
=> Add members 2024-08-27

config/etcd-io/org.yaml, config/etcd-io/sig-etcd/teams.yaml
Ref: https://github.com/kubernetes/org/pull/5115#discussion_r1733653669
=> Add hakman and justinsb to etcd.io

config/kubernetes-sigs/sig-apps/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5106
=> sig-apps: add teams for llm-instance-gateway

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5118
- fixes #5120
=> Add members 2024-08-29

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixed https://github.com/kubernetes/org/issues/5117
=> Add members 2024-08-30

config/kubernetes/sig-release/teams.yaml
xref: https://github.com/kubernetes/sig-release/issues/2603
cc @katcosgrove @gracenng
=> Add 1.32 release team permissions

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/5129
Fixes https://github.com/kubernetes/org/issues/5127
=> Add org members – Sept 5, 2024

config/kubernetes/org.yaml
=> Add members 2024-09-07

config/kubernetes/sig-node/teams.yaml
I am already a reviewer for sig-node. Adding myself to a few places to catch any other places I missed.
=> Add kannon92 to some sig-node orgs

config/kubernetes/org.yaml
=> Add members 2024-09-12

config/kubernetes/org.yaml
=> add kfswain to Kubernetes

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5143 
- fixes #5148 
- fixes #5152
=> Add members 2024-09-14

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5155 
- fixes #5157 
- fixes #5162
=> Add members 2024-09-17

config/kubernetes/org.yaml
=> Add members 2024-09-18

config/kubernetes/sig-release/teams.yaml
Update teams.yaml - Added comms shadows for the 1.32 cycle
=> Added Comms shadows for 1.32

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5165
- fixes #5166
=> Add members 2024-09-19

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5154
- fixes #5169
=> Add members 2024-09-20

config/kubernetes/sig-release/teams.yaml
Update Release Docs team in teams.yaml
cc @katcosgrove @gracenng
=> Add 1.32 release docs subteam permissions

config/kubernetes/sig-apps/teams.yaml
Following up on https://github.com/kubernetes/kubernetes/pull/127468
=> Add mimowo to the sig-apps team

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5097
/assign @kubernetes/sig-cluster-lifecycle-leads
=> sig-cluster-lifecycle: add karpenter-provider-cluster-api github teams

config/kubernetes/org.yaml
This PR:
- fixes #5179 
- fixes #5180
=> Add members 2024-09-26

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5168 
- Fixes #5186
=> Add members 2024-09-28

config/kubernetes/sig-release/teams.yaml
cc @fsmunoz @katcosgrove @gracenng
=> Update teams.yaml with release notes shadows 1.32

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5172 
- Fixes #5177 
- Fixes #5187
=> Add members 2024-10-02

config/kubernetes-sigs/sig-aws/teams.yaml
xref: https://github.com/kubernetes/org/issues/5177
xref: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2164
/cc @torredil @ConnorJC3 @AndrewSirenko
=> Update teams.yaml to add ElijahQuinones

config/kubernetes-csi/org.yaml, config/kubernetes/org.yaml
Hello, 
I'm already in kubernetes-sigs, but need to join kubernetes and kubernetes-csi. Please let me know if you need anything else added to this PR.
Thank you in advanced !!!
=> Add ElijahQuinones to kubernetes and kubernetes-csi

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5192 
- Fixes #5203 
- Fixes #5205
=> Add members 2024-10-04

config/kubernetes-csi/org.yaml
=> Add members 2024-10-08

config/etcd-io/sig-etcd/teams.yaml
As a team member of the etcd org, I would like to gain triage access to perform my work for the community.
=> Add henrybear327 to etcd team member

OWNERS_ALIASES, config/kubernetes/org.yaml
cc: @kubernetes/steering-committee 
ref: https://github.com/kubernetes/steering/issues/286
=> Update Steering members following 2024 election cycle

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixed https://github.com/kubernetes/org/issues/5208
- Fixed https://github.com/kubernetes/org/issues/5210
=> Add members 2024-10-09

config/kubernetes-sigs/org.yaml
=> Add members 2024-10-15

config/kubernetes/org.yaml
This PR:
- Fixed https://github.com/kubernetes/org/issues/5213
/assign
=> Add members 2024-10-16

config/kubernetes-sigs/org.yaml
=> Add members 2024-10-17

config/kubernetes/sig-release/teams.yaml
A release team shadow has elected to step back for the cycle for personal reasons. We thank you for your hard work, and hope to see you in a future release!
cc: @gracenng @fsmunoz
=> Release Team Update

config/kubernetes-sigs/org.yaml
=> Add members 2024-10-23

config/kubernetes-sigs/sig-scheduling/teams.yaml
And scheduler-simulator
Ref https://github.com/kubernetes-sigs/kueue/pull/3296
=> Remove alculquicondor from Kueue github admin

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-10-24

OWNERS_ALIASES
Partially address https://github.com/kubernetes/community/issues/8103
=> Kevin stepping in for Aldo for wg-batch leads

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml, config/restrictions.yaml
xref
- https://github.com/kubernetes/community/pull/8093
- https://github.com/kubernetes/org/issues/5194
=> sig-cl: remove CAPI nested provider teams

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes: https://github.com/kubernetes/org/issues/5237
Fixes: https://github.com/kubernetes/org/issues/5239
---
GitHub Username Change –
Fixes: https://github.com/kubernetes/org/issues/5240
=> Add members nov-4-2024

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/5242
=> Add members Nov-5-2024

config/kubernetes/org.yaml, config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/5224
/assign @deads2k @enj @liggitt @mikedanese @ritazh
cc @kubernetes/owners
=> sig-auth: add  staging repository

config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/5243
=> Add members Nov-07-2024

config/etcd-io/sig-etcd/teams.yaml
As a team member of the etcd org, I would like to gain triage access to perform my work for the community.
=> Add ArkaSaha30 to etcd team member

config/kubernetes/org.yaml
=> Add members 2024-11-15

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2024-11-18

config/etcd-io/sig-etcd/teams.yaml
As stated by @ivanvc in https://github.com/kubernetes/org/issues/5261#issuecomment-2486625368
=> add ghouscht to etcd triage group

config/kubernetes-sigs/org.yaml
=> Rename "tu1h" to "0ekk"

config/kubernetes-sigs/org.yaml
Addresses https://github.com/kubernetes/org/issues/5270
=> Add inductor in kubernetes-sigs

config/kubernetes-sigs/org.yaml
=> Add members 2024-11-22

config/kubernetes-sigs/sig-storage/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5238
/assign @kubernetes/sig-storage-leads
=> sig-storage: add container-object-storage-interface gh teams

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fix https://github.com/kubernetes/org/issues/5265
=> Add members – Nov 26, 2024

config/kubernetes/sig-docs/teams.yaml
@divya-mohan0209  @dipesh-rawat 
The PR www.github.com/kubernetes/website/pull/47782 is merged and raising this for seeking the approval of yours to add my username to the file under hindi reviewer role. 
/assign @divya-mohan0209  @dipesh-rawat
=> Update teams.yaml for adding niranjandarshann

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fix https://github.com/kubernetes/org/issues/5274
=> Add members Dec-03-2024

config/kubernetes-sigs/sig-apps/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5279
/assign @kubernetes/sig-apps-leads 
=> sig-apps: add github teams for kjob repo

config/etcd-io/sig-etcd/teams.yaml
=> Add new team for maintaining etcdlabs repository

config/etcd-io/org.yaml, config/kubernetes-sigs/org.yaml
This PR:
- fixes #5285 
- fixes #5290
=> Add members 2024-12-06

config/kubernetes-sigs/org.yaml
=> Add members 2024-12-07

config/kubernetes-client/org.yaml
=> Add members 2024-12-08

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- fixes #5298 
- fixes #5306 
- fixes #5310
=> Add members 2024-12-19

config/kubernetes/sig-cluster-lifecycle/teams.yaml
ref to https://github.com/kubernetes/kubernetes/pull/129250
=> add carlory to kubeadm maintainer

config/kubernetes-sigs/sig-network/teams.yaml, config/kubernetes/org.yaml
As I have announced on May, I am stepping down from ingress-nginx project (for now). I need some time for myself, and I am not really being able to take care of the project and my personal life together :)
=> rikatz is stepping down from ingress-nginx

config/kubernetes-csi/org.yaml
=> Add members 2024-12-22-eve

config/kubernetes/org.yaml
Remove inactive reviewers.
/cc @strongjz @tao12345666333 @cpanato
=> Ingress NGINX: Update owners.

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR
- Fixes #5314 
- Fixes #5317
=> Add members 2024-12-22

config/kubernetes/org.yaml
As a member of `kubernetes-sigs` I'm adding myself to the `kubernetes` org.
This is the original issue where I requested `kubernetes-sigs` membership https://github.com/kubernetes/org/issues/4877.
=> Add salasberryfin to kubernetes

config/kubernetes/sig-release/teams.yaml
Ref: https://github.com/kubernetes/sig-release/issues/2705
cc @katcosgrove @gracenng @neoaggelos
=> Add 1.33 release team permissions

config/kubernetes/org.yaml
=> Add members 2025-01-09-noon

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5323 
- Fixes #5332 
- Fikes #5333
=> Add members 2025-01-10

config/kubernetes-sigs/sig-scalability/OWNERS, config/kubernetes-sigs/sig-scalability/teams.yaml, config/restrictions.yaml
ref https://github.com/kubernetes/org/issues/5334 
/assign @kubernetes/owners
=> sig-scalability: add inference-perf teams

config/kubernetes-sigs/org.yaml
=> Add members 2025-01-18

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5340 
- Fixes #5347 
- Fixes #5348 
- Fixes #5351 
- Fixes #5353 
- Fixes #5355
=> Add members 2025-01-20

config/kubernetes/org.yaml
This PR:
- Fixes #5353
(xref: Missed adding them in #5356)
=> Add members 2025-01-21

config/kubernetes/sig-release/teams.yaml
This PR is created to add v1.33 Release Signal Shadow to the team.
One shadow needs to get approval for the membership: https://github.com/kubernetes/org/issues/5347 before this PR can be merged. 
cc @jasonbraganza @Priyankasaggu11929 to help approve the membership,
Thanks for your help, I really appreciate it!
cc: @npolshakova @gracenng @katcosgrove for review.
=> Update v1.33 Release Signal Shadows

config/kubernetes-sigs/org.yaml
=> Add members 2025-01-23

config/kubernetes-sigs/org.yaml
=> Add members 2025-01-24

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2025-01-25

config/etcd-io/sig-etcd/teams.yaml
This reverts commit 57ecb8a1cc24877a4bbcd611f3b8daa72bb90915.
All release activities have been completed successfully 🎉 
cc @ivanvc
=> Revert "Elevate etcd team permissions for release window."

config/kubernetes/sig-architecture/teams.yaml
As discussed with @johnbelamaric & @soltysh, adding myself as a production readiness review shadow - thanks!
=> Adding bridgetkromhout as PRR shadow

config/kubernetes/org.yaml
=> Update approvers and reviewers dropping inactive members and adding shadows

config/etcd-io/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5377 
- Fixes #5378 
- Fixes #5384 
- Fixes #5385
=> Add members 2025-01-30

config/kubernetes/sig-release/teams.yaml
Update Release Docs team in teams.yaml
@katcosgrove @gracenng
=> Add docs shadows for 1.33

config/kubernetes/sig-release/teams.yaml
We will need to manage the enhancement board for the 1.33 release communication space.
=> Add Comms shadows

config/kubernetes-sigs/sig-storage/teams.yaml
Add admin permissions to @hime to [gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) admin.
=> Add hime as admin to gcp-compute-persistent-disk-csi-driver

config/kubernetes-sigs/org.yaml
=> Add members 2025-02-11

config/etcd-io/sig-etcd/teams.yaml
Required for release v3.6.0-rc.0.
/cc @ahrtr
=> Elevate etcd team permissions for release window.

config/kubernetes-sigs/org.yaml
=> Add members 2025-02-13

config/kubernetes-sigs/org.yaml
This PR:
- Fixes #5372 
- Fixes #5400
=> Add members 2025-02-14

config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/5417
=> Add members 21-02-2025

config/kubernetes-sigs/sig-cloud-provider/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5404
=> Add teams for provider-ibmcloud-test-infra repo

config/kubernetes/org.yaml
=> Add members 2025-02-27

config/kubernetes/org.yaml
=> Add mainred to kubernetes org

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5429 
- Fixes #5430
=> Add members 2025-03-01

config/kubernetes-sigs/org.yaml
This PR:
- Fixes #5431
- Fixes #5432
=> Add members 2025-03-04

config/etcd-io/sig-etcd/teams.yaml
Add myself to the release team in preparation for today's releases.
/cc @jmhbnz @ahrtr
=> etcd: Update release-etcd team for release window

OWNERS_ALIASES, config/kubernetes/org.yaml
Welcome @divya-mohan0209 and @stmcginnis.
Thank you for your amazing work @hlipsig and @salaxander 💜.
/hold
=> cocc: update for 2025 election

config/kubernetes/org.yaml
=> Add members 2025-03-07

config/kubernetes/sig-docs/teams.yaml
Add @jongwooo to sig-docs-ko-owners
ref: https://github.com/kubernetes/website/pull/49425
=> Add jongwooo to sig-docs-ko-owners

config/kubernetes-sigs/sig-cloud-provider/teams.yaml
My team in EKS is responsible for maintaining the repo. We need write access to push a tag to cut a new release
=> Adding yue9944882 to aws iam authn

config/kubernetes-sigs/sig-windows/teams.yaml
=> Add zylxjtu to gmsa admin/maintainer

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Fix https://github.com/kubernetes/org/issues/5462
Fix https://github.com/kubernetes/org/issues/5456
Fix https://github.com/kubernetes/org/issues/5460
=> Add members march 13 2025

config/etcd-io/sig-etcd/teams.yaml
ref: https://github.com/etcd-io/etcd/pull/19572
cc @ahrtr @jmhbnz @serathius @spzala @wenjiaswe
=> config/etcd-io/sig-etcd: add fuweid as maintainer

config/kubernetes-csi/org.yaml, config/restrictions.yaml
Part of https://github.com/kubernetes/org/issues/5450
- **Archive kubernetes-csi/cluster-driver-registrar**
- **Archive kubernetes-csi/driver-registrar**
=> Archive repo cluster-driver-registrar and driver-registrar

config/etcd-io/org.yaml, config/kubernetes/org.yaml
=> Add members 2025-03-10

config/kubernetes/org.yaml
=> Add members 2025-03-17

config/kubernetes-sigs/sig-multicluster/teams.yaml, config/restrictions.yaml
=> sig-multicluster: add teams for kubernetes-sigs/multicluster-runtime

config/kubernetes/org.yaml
=> Add members 2025-03-20

config/etcd-io/sig-etcd/teams.yaml
Need write permissions to do release v0.1.0.
/cc @ahrtr
=> etcd: add ivanvc to etcd-operator maintainers

config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-ui/OWNERS, config/kubernetes-sigs/sig-ui/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5468
fixes: https://github.com/kubernetes/org/issues/5504
=> Add headlamp teams

OWNERS_ALIASES, config/kubernetes-sigs/sig-auth/teams.yaml, config/kubernetes/sig-auth/teams.yaml, config/kubernetes/sig-release/teams.yaml
https://github.com/kubernetes/community/issues/8390
=> SIG Auth: Leadership Change

config/kubernetes-sigs/sig-architecture/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5498
=> Add team for maintainer-tools repo

config/kubernetes/sig-instrumentation/teams.yaml
follow-up to https://github.com/kubernetes/kube-state-metrics/pull/2650
=> sig-instrumentation: update ksm teams

config/kubernetes/org.yaml
Per https://github.com/kubernetes/community/pull/8343 and https://github.com/kubernetes/community/issues/8370
=> Add mengqiy to perf-tests maintainers

config/kubernetes/sig-scheduling/teams.yaml
=> add macsko and dom4ha to the approver team

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #5511 
fixes: #5516
fixes: #5521
fixes: #5532
fixes: #5534 
=> Add members 2025-04-14

config/kubernetes-sigs/sig-api-machinery/teams.yaml, config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5519
=> Add teams for kube-api-linter repo

config/kubernetes-sigs/sig-aws/teams.yaml
PRs for this repo
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1585
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1569
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1520
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1507
=> Add dankova22 to owner for aws-efs-csi-driver

config/kubernetes/sig-docs/teams.yaml
Replacing previous GitHub username, @sftim.
Follow up to #5499
=> Add LMKTFY to SIG Docs

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This adds 2 new maintainers to the team for CAPG.
//cc @cpanato
=> chore: add new CAPG maintainers

config/kubernetes/sig-docs/teams.yaml
https://github.com/kubernetes/org/issues/5488
=> id: added za as approvers and reviewers for id content

config/kubernetes-sigs/org.yaml
=> Add members 2025-04-21

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Changed my github username from jacobwolfaws -> kuba-wolf. Updating kubernetes and kubernetes-sigs to reflect this change.
=> Change jacobwolfaws to kuba-wolf

config/kubernetes-sigs/sig-testing/teams.yaml
=> Add stmcginnis to sig-testing kind groups

config/etcd-io/org.yaml, config/kubernetes-sigs/org.yaml
This PR:
- Fixes #5558  
- Fixes #5564
=> Add members 2025-04-29

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #4843 
- Fixes #5559
- Fixes #5562
=> Add members 2025-04-30

OWNERS_ALIASES, config/kubernetes/sig-release/teams.yaml, config/kubernetes/sig-scheduling/teams.yaml
=> SIG Scheduling: Leadership Change

config/kubernetes-sigs/org.yaml
Already a member of Kubernetes, see:
1. https://github.com/kubernetes/org/blob/1d5167df96affdd83e41c307f1f395d33c29fda7/config/kubernetes/org.yaml#L45
2. https://github.com/kubernetes/org/issues/5133
cc @aojea
=> add adrianmoisey to kubernetes-sigs

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2025-05-03

config/kubernetes-csi/org.yaml
Need permission to create release/tags
/assign @xing-yang
=> Add sunnylovestiramisu as admin for volume populators

config/etcd-io/sig-etcd/teams.yaml
ref: https://github.com/kubernetes/org/pull/5567
/cc @ivanvc
=> Add joshjms to etcd member

config/kubernetes/org.yaml
ref: https://github.com/kubernetes/org/pull/5567
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Ajoshjms
/cc @ivanvc
=> Add joshjms to kubernetes org

config/kubernetes/sig-cluster-lifecycle/teams.yaml
Follow: https://github.com/kubernetes/kubernetes/pull/131674, add HirazawaUi as maintainers/admins for kubeadm.
=> add HirazawaUi to kubeadm maintainers/admins

config/etcd-io/sig-etcd/teams.yaml
This reverts commit 01b273d6b7f0cf8ab274bafa89926f4071a9d2ff.
=> Revert "etcd: Update release-etcd team for release window"

config/kubernetes-sigs/org.yaml
=> Add members 2025-05-09

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5586
- Fixes #5593
=> Add members 2025-05-13

config/kubernetes-sigs/sig-network/teams.yaml
@astoycos has been out of the picture for a while and @tssurya and @npinaeva have been running the WG, so add them to the admin group so they can do releases and such. (Also add @aojea since he's an approver there.)
=> Update network-policy-api admins

config/etcd-io/org.yaml
=> Add members 2025-05-15

config/kubernetes-sigs/org.yaml
=> Add members 2025-05-16

config/kubernetes-sigs/org.yaml
Note: I am already a Kubernetes org member
fyi @aramase @enj @stlaz
=> Add benjaminapetersen to kubernetes-sigs org

OWNERS_ALIASES, config/kubernetes-sigs/sig-windows/teams.yaml, config/kubernetes/sig-release/teams.yaml, config/kubernetes/sig-windows/teams.yaml
Related to https://github.com/kubernetes/community/pull/8470
/sig windows 
/assign @marosset @claudiubelu @aravindhp @zylxjtu @knabben
=> Update sig-windows teams

config/kubernetes-sigs/sig-node/teams.yaml, config/kubernetes/org.yaml, config/restrictions.yaml
Give wangzhen127 admin access and hakman write access
=> Update node-problem-detector member access

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
Removing inactive user from Kubernetes orgs
=> Remove khareyash05 from kubernetes orgs

config/kubernetes/sig-release/teams.yaml
Ref: https://github.com/kubernetes/sig-release/blob/master/releases/release-1.34/release-team.md
=> Add v1.34 branch management team to milestone-maintainers

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5624 
- Fixes #5630 
- Fixes #5637 
- Fixes #5643
- Fixes #5653
- Fixes #5659, #5666
- Fixes #5661
- Fixes #5664
=> Add members 2025-06-21

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2025-06-23

config/kubernetes-sigs/org.yaml
I am already part of Kubernetes org, adding as member to kubernetes-sigs org.
cc @mimowo @tenzen-y
=> add alaypatel07 to kubernetes-sigs

config/kubernetes/sig-docs/teams.yaml
RE https://github.com/kubernetes/website/pull/51182#issuecomment-2973679677
=> Adding Andygol as reviewer/approver for Ukrainian content

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2025-07-11

config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-cloud-provider/teams.yaml, config/kubernetes/org.yaml
This PR:
- Executes username change requested in [#5665](https://github.com/kubernetes/org/issues/5665#issuecomment-3047832761)
(orignal membership request: #121)
=> Rename members 2025-07-11 (m00nf1sh -> M00nF1sh)

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fixes: #5699
fixes: #5700 
fixes: #5703 
fixes: #5705
=> Add members 2025 07 18

config/etcd-io/org.yaml, config/etcd-io/sig-etcd/teams.yaml
I am already a Kubernetes member. Please add me to etcd-io.
/cc @ivanvc @siyuanfoundation 
Thanks!
=> add hwdef to etcd-io

config/etcd-io/org.yaml, config/etcd-io/sig-etcd/teams.yaml, config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml, config/kubernetes-sigs/sig-storage/teams.yaml, config/kubernetes-sigs/sig-testing/teams.yaml, config/kubernetes/org.yaml, config/kubernetes/sig-cluster-lifecycle/teams.yaml, config/kubernetes/sig-contributor-experience/teams.yaml, config/kubernetes/sig-docs/teams.yaml, config/kubernetes/sig-release/teams.yaml, config/kubernetes/sig-testing/teams.yaml
=> Clean up inactive members - June 2025

config/kubernetes/org.yaml
Add maintainers for ingress-gce @mmamczur , @TortillaZHawaii
=> Update maintainer list for ingress-gce

config/kubernetes-sigs/org.yaml
I'm already part of the kubernetes org. Adding `rushmash91` to sigs.
=> add rushmash91 to kubernetes-sigs

config/kubernetes-csi/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5726 
- Fixes #5734 
- Fixes #5743 
- Fixes #5745 
- Fixes #5747 
- Fixes #5748
=> Add members 2025-08-02

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
=> Add members 2025-08-02 Eve

config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
more information here:
- https://github.com/kubernetes/org/issues/5756
/cc @fabriziopandini
cc @vielmetti
=> sig-cl: remove capi provider packet teams

config/kubernetes-client/org.yaml, config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5771
- Fixes #5778 
- Fixes #5781
=> Add members 2025-08-19

config/kubernetes/sig-docs/teams.yaml
Raising this PR to request approver access to https://github.com/kubernetes/website.
cc @divya-mohan0209 @natalisucks @reylejano
=> Add SayakMukhopadhyay as approver to sig-docs

config/kubernetes/sig-docs/teams.yaml
Syncing the teams.yaml for SIG Docs per the OWNERS file under k/website
=> Update the teams.yaml for sig docs

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5780 
- Fixes #5785
=> Add members 2025-08-22

config/etcd-io/org.yaml, config/etcd-io/sig-etcd/teams.yaml
As suggested [here](https://github.com/etcd-io/etcd/pull/20490#issuecomment-3215933586) adding myself to etcd members.
=> add logicalhan to etcd members

config/kubernetes/org.yaml
=> Add members 2025-08-29 eve

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5805
- Fixes #5814
=> Add members 2025-09-05

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
This PR:
- Fixes #5841
- Fixes #5844
- Fixes #5858
- Fixes #5861
- Fixes #5862
- Fixes #5864
=> Add members 2025-09-26

OWNERS_ALIASES
syncing - https://github.com/kubernetes/community/blob/d71ff1332c77beebcdbeaa2b7004453a2a136d1f/wg-ai-gateway/README.md?plain=1#L24-L31
=> add ai gateway wg leads

config/kubernetes/sig-architecture/teams.yaml, config/kubernetes/sig-release/teams.yaml
Added to:
* `enhancements`
* `milestone-maintainers`
* `release-team`
* `release-team-enhancements`
cc: @drewhagen @katcosgrove
=> Add 1.35 enhancements shadows to appropriate groups

config/kubernetes/sig-release/teams.yaml
=> Update the Release Signal 1.35 members

config/kubernetes-sigs/org.yaml, config/kubernetes/org.yaml
fix https://github.com/kubernetes/org/issues/5893
fix https://github.com/kubernetes/org/issues/5896
=> Add members oct-3-2025

OWNERS_ALIASES, config/kubernetes-sigs/sig-k8s-infra/teams.yaml, config/kubernetes/sig-k8s-infra/teams.yaml, config/kubernetes/sig-release/teams.yaml
Related to:
- https://github.com/kubernetes/community/issues/8633
- https://github.com/kubernetes/community/issues/8634
=> k8s-infra: Rotate leads
