- OWNERS_ALIASES
- config/kubernetes-sigs/sig-cli/teams.yaml
- config/kubernetes/sig-cli/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Part of kubernetes/community#6102
I'm not sure about some of the changes in this one. I added myself to all the SIG-related Github teams, on the assumption those are for getting pinged on relevant issues. But for subproject teams, I only added myself to cli-experimental admins (because that should probably come with Kustomize admin--our docs are there). Should I be on any other subproject team? @pwittrock do you want to be removed from any of these places?
/cc @eddiezane @pwittrock @soltysh @seans3
> SIG-CLI: KnVerey to lead, pwittrock to emeritus

- config/kubernetes-sigs/sig-cli/teams.yaml
* Updates the `cli-utils-admins` to include the full set of new SIG CLI leadership
* Updates the `cli-utils-maintainers` to include active members `karlkfi` and `mortent`, while removing legacy maintainers.
> Updates SIG CLI cli-utils repository admins and maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cli/teams.yaml
I am already a member of the kubernetes org since 2019: https://github.com/kubernetes/org/issues/751
I'd like to join the kubernetes-sigs organization and continue my contribution to sig-cli and kustomize. 
Some recent PR I contributed to kustomize https://github.com/kubernetes-sigs/kustomize/pull/4180
@KnVerey @monopole @seans3
> Add yuwenma@ to the kubernetes-sigs org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Hey folks,
goal of this PR is to cleanup the CAPO admin and maintainer groups. 
According to a short Slack discussion (https://kubernetes.slack.com/archives/C8TSNPY4T/p1635322637149000) it should be fine to only include folks who are currently active maintainers of CAPO.
@chaosaffe @dims @luxas @roberthbailey @timothysc @chrigl Please let me know, in case it's not okay to remove you from those groups.
> Cleanup cluster-api-provider-openstack groups, promote jichenjc to admin

- OWNERS_ALIASES
- config/kubernetes/org.yaml
Part of https://github.com/kubernetes/steering/issues/219.
Emeritus:
- @nikhita 
- @derekwaynecarr 
Returning:
- @parispittman 
- @cblecker 
New:
- @justaugustus 
- @tpepper 
Includes a sync of the OWNERS_ALIASES with k/community, which brings in the new Steering members (as well as additional governance group updates).
/assign @cblecker @mrbobbytables 
cc: @kubernetes/steering-committee
> steering: Update membership following 2021 election

- config/kubernetes/org.yaml
Emeritus:
- @AevaOnline 
- @tashimi 
New:
- @palnabarun 
- @vllry 
cc: @kubernetes/code-of-conduct-committee 
ref: https://groups.google.com/g/kubernetes-dev/c/psxNavBV4i0, https://github.com/kubernetes/community/pull/5967
/assign @mrbobbytables @cblecker
> Update CoCC GitHub team to represent current membership

- config/kubernetes-csi/org.yaml
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
I'm already part of `kubernetes` and `kubernetes-sigs` org. I'm one of the maintainers for the [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) `sig-auth` subproject and have lately been working on some changes in the csi related components in `kubernetes-csi` org.
Issues:
- https://github.com/kubernetes-csi/node-driver-registrar/issues/created_by/aramase
- https://github.com/kubernetes-csi/livenessprobe/issues/created_by/aramase
PRs:
- https://github.com/kubernetes-csi/node-driver-registrar/pulls/aramase
- https://github.com/kubernetes-csi/livenessprobe/pulls/aramase
- https://github.com/kubernetes-csi/external-provisioner/pulls/aramase
> add aramase to kubernetes-csi org

- config/kubernetes-sigs/org.yaml
I'd like to join the kubernetes-sigs organization to review kubernetes-sigs/contributor-playground for upstream-training in Japan.
I am already a member of the kubernetes org: #2803
> Add s-kawamura-w664 to the kubernetes-sigs org

- config/kubernetes/sig-docs/teams.yaml
I invited @mehabhalodiya to become a reviewer for the upstream (English) localization for [k/website](https://github.com/kubernetes/website).
This PR will add Meha as a reviewer for English.
> Add mehabhalodiya as (en) reviewer for SIG Docs

- config/kubernetes/sig-release/teams.yaml
Part of https://github.com/kubernetes/sig-release/issues/1772.
- sig-release: Rename pub-bot team to publishing-bot-admins
- publishing-bot-admins: Prune inactive members
- publishing-bot-admins: Add sig-release-admins
- publishing-bot-maintainers: Create team 
/assign @puerco @cpanato @nikhita @dims 
/cc @kubernetes/publishing-bot-reviewers 
cc: @kubernetes/release-engineering 
/hold for reviews from pub-bot maintainers
> releng: Update publishing-bot teams to include Release Managers

- config/kubernetes-nightly/OWNERS
- config/kubernetes-nightly/org.yaml
- config/kubernetes-nightly/sig-release/OWNERS
- config/kubernetes-nightly/sig-release/teams.yaml
Part of https://github.com/kubernetes/sig-release/issues/1772.
- config: Init kubernetes-nightly org
- k-nightly: Add NMCs as members
- k-nightly: Add SIG Release teams
- k-nightly: Add Release Engineering as org members
- k-nightly: Promote publishing-bot-admins to org admins
- k-nightly: Update config to reflect existing org membership
- Add @k8s-publishing-bot (member)
Slack convo: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1638832884428700
> config: Init kubernetes-nightly org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
The [approval](https://github.com/kubernetes/org/issues/3116) for this member was granted given his contributions to the website translation which means @kubernetes org. This change fixes the permissions to the user.
> Fix anyulled member to the right org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This patch adds `srm09` to the CAPV admins and maintainers list. Also, removing community members who are not involved with this project directly anymore.
> Adds srm09 to capv admins and maintainers list

- config/kubernetes/sig-docs/teams.yaml
This PR cleans up the config for 1.23 release docs team.
* removes the 1.23 release docs lead and shadows from sig-docs milestone maintainers (save 1.24 lead)
* migrates lead comment to the 1.24 release docs lead
* removes temp maintainer privs for 1.23 release docs lead
cc @kubernetes/sig-docs-leads @nate-double-u
> Cleanup 1.23 release docs team in sig-docs team

- config/kubernetes/sig-docs/teams.yaml
- Add @jihoon-seo to sig-docs-ko-owners.
- related with kubernetes/website#31206
> Add jihoon-seo to sig-docs-ko-owners

- config/kubernetes-sigs/org.yaml
GitHub-Issue: https://github.com/kubernetes/org/issues/3171
Signed-off-by: Douglas Schilling Landgraf <dlandgra@redhat.com>
> org: Add dougsland to kubernetes sig org

- config/kubernetes/sig-release/teams.yaml
- Add RT Lead to sig-release
- Update sig-release/release-team with RT Lead, EA, RT Lead shadows, Role Leads, Role Shadows and subproject owners
- Add RT Lead, EA, RT Lead shadows, Role Leads, Enhancements shadows, and Bug Triage shadows to milestone-mantainers
- Replace current sig-release/release-team/release-team-leads members with RT Lead, EA, RT Lead Shadows
- Replace sig-release/release-team/ci-signal with CI Signal Lead and CI Signal Shadows
xref https://github.com/kubernetes/sig-release/issues/1791
> 1.24 Release Team Onboarding

- config/kubernetes-sigs/org.yaml
I'm already a member of `kubernetes` org: https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L371
> Add Fedosin to kubernetes-sigs organization

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-api-machinery/teams.yaml
- membership of kubernetes-sigs, implicitly granted due to existing membership of kubernetes 
- grant write access for k/structured-merge-diff to jiahuif, endorsed by @apelisse
> grant write access for k/structured-merge-diff to jiahuif

- config/kubernetes-sigs/org.yaml
- config/kubernetes/sig-docs/teams.yaml
- Jim Angel steps down as chair
- Natali Vlatko is incoming chair
- Rey Lejano is also incoming chair
- Qiming Teng is incoming technical lead
per https://groups.google.com/g/kubernetes-sig-docs/c/cgrAyDLxydk
/sig docs
> Update SIG Docs leadership

- config/kubernetes/sig-release/teams.yaml
context: amwat has moved on to an offer at another employer and juan is helping staff our oncall #3193 
cc @juanfescobar @justaugustus
> add juanfescobar to build-admins, remove amwat

- config/kubernetes-sigs/sig-cli/teams.yaml
Second part of updates/cleanup in https://github.com/kubernetes-sigs/kustomize/pull/4426. Per [Kustomize's contributor ladder](https://github.com/kubernetes-sigs/kustomize/blob/master/CONTRIBUTING.md#contributor-ladder), owners should be on the "admins" list here and approvers should be on "maintainers". Since the former has more permissions than the latter, it is not necessary to add owners to both. The (unfortunate) reality is that we don't have any approvers besides our owners at this point, hence the second list now being empty. Emeritus status is reflected in Kustomize's internal owners file rather than being duplicated here.
/cc @natasha41575
> Update Kustomize teams

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Add `cluster-api-operator-admins` team to sig-cluster-lifecycle.
> Add CAPI operator team

- .github/ISSUE_TEMPLATE/membership.yml
Adds questions to verify sponsors are listed in an owners file and are from separate member companies.
> Update org membership request template

- config/kubernetes-sigs/org.yaml
I am already a member of `kubernetes` org: https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L65
> Add amacaskill to the kubernetes-sigs org

- .github/ISSUE_TEMPLATE/membership.yml
The current group is being sunset in favor of the new group. This changes the link to point directly to it.
> Use new dev email in membership request

- config/kubernetes/sig-docs/teams.yaml
Jim Angel is a SIG Docs co-chair until the end of the first quarter, March 31, 2022 per [email to dev@](https://groups.google.com/a/kubernetes.io/g/dev/c/SP6weMvx3wg/m/l8LAL-OFCQAJ)
/cc @jimangel
> Re-add Jim Angel for SIG Docs

- config/kubernetes-sigs/org.yaml
Adding myself as a member to kubernetes-sigs to simplify contributions to image-builder and other projects (as per https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem for existing k8s org members)
> kubernetes-sigs: add endocrimes as member

- config/kubernetes-sigs/org.yaml
fixes: https://github.com/kubernetes/org/issues/3270
chaodaiG is already a member of kubernetes
> Add chaodaiG as k8s-sig member

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Signed-off-by: Stefan Büringer buringerst@vmware.com
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/6109
/assign @fabriziopandini
> cluster-api: add sbueringer to cluster-api-maintainers

- config/kubernetes-sigs/org.yaml
@chases2  is already a member of kubernetes
Needed to maintain boskos as oncall member
xref to https://github.com/kubernetes/org/pull/3271
> Add chases2 to kubernetes-sigs/org as member

- config/kubernetes-sigs/org.yaml
I'm [already a member of the kubernetes org](https://github.com/kubernetes/org/issues/1253) and need to join kubernetes-sigs now. Thanks!
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>
> Add bridgetkromhout to the kubernetes-sigs org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Add myself to `kubespray-admins` 
I'm one of the maintainers and would like to extend my access to kubespray repo.
https://github.com/kubernetes-sigs/kubespray/releases
https://github.com/kubernetes-sigs/kubespray/graphs/contributors
Already seen with @ant31 and @mattymo
> Add floryut to  kubespray-admins team

- config/kubernetes/sig-docs/teams.yaml
Add 1.24 Docs Shadows to `website-milestone-maintainers` in sig-docs/teams.yaml and `release-team` in `sig-release/teams.yaml` GitHub teams
/assign @palnabarun @kikisdeliveryservice @savitharaghunathan @bai
/cc @JamesLaverack
> Add 1.24 Docs Shadows to GitHub teams

- OWNERS_ALIASES
Added new SIG Docs co-chairs and tech lead to sig-docs-leads
See https://github.com/kubernetes/community/blob/master/sig-docs/README.md
cc: @natalisucks @tengqm 
/assign @jimangel @divya-mohan0209
> Add new SIG Docs co chairs and tech lead to owners aliases

- config/kubernetes/org.yaml
- config/kubernetes/sig-cli/teams.yaml
This PR replaces unused sig-cli teams with updated and simplified ones.
> Update sig-cli GitHub teams

- config/kubernetes/org.yaml
Add killianmuldoon, currently a member of kubernetes-sigs, to the kubernetes org.
> Add killianmuldoon to Kubernetes org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
@oomichi and @cristicalin are both valuable members, who are now full time approvers/maintainers of kubespray.
Hats down for you guys.
> Add oomichi/cristicalin to kubespray-maintainers team

- config/kubernetes/org.yaml
Add Ankitasw, currently a member of kubernetes-sigs, to the kubernetes org.
> Add Ankitasw to kubernetes org

- config/kubernetes/org.yaml
Add josh-ferrell, currently a member of kubernetes-sigs, to the kubernetes org.
> Add josh-ferrell to Kubernetes org

- config/kubernetes/org.yaml
Add shivi28, currently a member of kubernetes-sigs, to the kubernetes org.
> Add shivi28 to Kubernetes org

- config/kubernetes/sig-instrumentation/teams.yaml
See our 2020 cleanup in https://github.com/kubernetes/org/pull/2497 and https://github.com/kubernetes/org/pull/2541.
The first commit removes inactive contributors. I am defining "inactive" as ([<50 contributions on devstats for the past year](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All) **and** does not attend [regular SIG meetings](https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#)) **or** requested emeritus status from the project.
The second commit adds two new SIG members, @CatherineF-dev and @pohly. Congratulations and welcome!
/cc @kubernetes/sig-instrumentation-leads
> SIG Instrumentation team updates for 2021

- config/kubernetes-sigs/org.yaml
Adds @rohityadavcloud and @davidjumani to kubernetes-sig org as members.
This inline with a discussion on https://github.com/kubernetes/org/issues/3279 to have the two become org members to facilitate the migration of cloudstack CAPI provider (https://github.com/aws/cluster-api-provider-cloudstack) repo to k8s-sigs.
Fixes https://github.com/kubernetes/org/issues/3312
Fixes https://github.com/kubernetes/org/issues/3319
> Add rohityadavcloud and davidjumani to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
According to the community documentation, a member in a Kubernetes related Github organizations are implicitly eligible for membership in related organizations. See: https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem
everpeace is eligible to be a member of kubernetes-sigs organization because he is a member of kubernetes organization (https://github.com/kubernetes/org/issues/1173).
> Add everpeace to kubernetes-sigs organization

- config/kubernetes/org.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
The username does not exist anymore and peribolos is [failing](https://testgrid.k8s.io/sig-contribex-org#ci-peribolos):
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-org-peribolos/1516492932016771072
```
{"component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:1293","func":"main.configureTeamMembers.func1","level":"warning","msg":"UpdateTeamMembership(kubernetes-maintainers(kubernetes-maintainers), kashomon, false) failed: status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-membership-for-a-user\"}","severity":"warning","time":"2022-04-19T19:11:09Z"}
{"component":"unset","file":"/home/prow/go/src/github.com/kuberne …
```
> Remove Kashomon from github orgs

- config/kubernetes/sig-docs/teams.yaml
Add ptux to sig-docs-ja-reviews
related with https://github.com/kubernetes/website/pull/32734
> Add ptux to sig-docs-ja-reviews

- config/kubernetes/org.yaml
I am already a member of `kubernetes-sigs`: https://github.com/kubernetes/org/blob/28d11c73076b3596a537a0b82192492e3e00d25a/config/kubernetes-sigs/org.yaml#L68
> Add apricote to kubernetes org

- config/kubernetes/sig-docs/teams.yaml
Temporarily adding @nate-double-u, @pi-victor, and @jlbutler to the `website-maintainers` team for write access to k/website repo for the release preparation/release day. Adding @PI-Victor and @jlbutler as a contingency as I will be travelling on release day. Both Jesse and Victor have been docs leads previously (and are currently participating in v1.24).
/assign @divya-mohan0209 @jimangel @natalisucks @reylejano
> add nate-double-u, pi-victor, jlbutler to website-maintainers team for 1.24 release

- config/kubernetes-sigs/org.yaml
Fixes an error where Github alias was wrong. 
Original issue here: https://github.com/kubernetes/org/issues/3372
Signed-off-by: Rishabh Singhvi <rdpsin@amazon.com>
> Fix alias for new member rdpsin

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Syncs up with recent changes to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/OWNERS_ALIASES
cc: @cpanato @Jont828
> Sync CAPZ owners with Azure provider project

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
I'm spending more time in https://github.com/kubernetes-sigs/aws-iam-authenticator and I'm already in [OWNERS](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/OWNERS#L14) file. 
I'd like to create tags and releases for aws-iam-authenticator and based on https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization looks like i need to have write permission to be able to create tags and releases.
> Providing jyotimahapatra write access on aws-iam-authenticator

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
I missed the `provider` part of the team names when I created #3454 , updating to match standard convention.
ref: #3279
ref: #3454
> Rename cluster-api-cloudstack -> cluster-api-provider-cloudstack teams

- config/kubernetes/sig-release/teams.yaml
This PR is to grand access to CI Signal lead to start working on 1.25 release. I will open a follow up PR to update all 1.25 release team members once they all become Kubernetes org members.
cc @RinkiyaKeDad
> Onboard 1.25 RT Leads and CI Signal Lead

- config/kubernetes/sig-release/teams.yaml
- Add RT Lead to sig-release
- Update sig-release/release-team with RT Lead, EA, RT Lead shadows, Role Leads, Role Shadows and subproject owners
- Add RT Lead, EA, RT Lead shadows, Role Leads, Enhancements shadows, and Bug Triage shadows to milestone-mantainers
- Replace current sig-release/release-team/release-team-leads members with RT Lead, EA, RT Lead Shadows
- Replace sig-release/release-team/ci-signal with CI Signal Lead and CI Signal Shadows
xref https://github.com/kubernetes/sig-release/issues/1902
> 1.25 release team on-boarding

- config/kubernetes-sigs/sig-aws/teams.yaml
Signed-off-by: Eddie Torres <torredil@amazon.com>
Remove users who are no longer active contributors to `aws-ebs-csi-driver`.
> Cleanup aws-ebs-csi-driver maintainers

- config/kubernetes-sigs/sig-scheduling/teams.yaml
There is currently only one active maintainer with write access to the
descheduler repo. Adding a second maintainer with write access allows
multiple people to help with create git tags and branches for releases.
> Add seanmalloy and ingvagabund to descheduler repo with write access

- config/kubernetes/org.yaml
Adds @davidjumani and @rohityadavcloud as a member of the kubernetes org
- Required for https://github.com/kubernetes/k8s.io/pull/3792#issuecomment-1143127185
- Fixes https://github.com/kubernetes/org/issues/3488
> Add davidjumani and rohityadavcloud to kubernetes org

- config/kubernetes/org.yaml
A typo made in this [PR](https://github.com/kubernetes/org/issues/3478) added @krol and not @krol3
ref: https://github.com/kubernetes/org/pull/3500
/cc @cici37 @reylejano @kcmartin
> Fix typo, rm krol and add krol3

- config/kubernetes-sigs/org.yaml
Hi, I'm a member of the [kubernetes org](https://github.com/kubernetes/org/blob/c0adbc758d3f0354f260cf06ec78875e6870ece6/config/kubernetes/org.yaml#L894) and would like to get added to the kubernetes-sigs org. I referred [this membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) guide, which says:
> "If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly "
So I'm opening this PR, let me know if I need to open an issue instead. Thanks!
> Add mrajashree as member in kubernetes-sigs org

- config/kubernetes-csi/org.yaml
Hi, I'm a member of the [kubernetes org](https://github.com/kubernetes/org/blob/c0adbc758d3f0354f260cf06ec78875e6870ece6/config/kubernetes/org.yaml#L105) and would like to get added to the  kubernetes-csi. I referred [this membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) guide, which says:
> "If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly"
resolve https://github.com/kubernetes/org/issues/3525
> Add arhell as member in kubernetes-csi

- config/kubernetes-client/org.yaml
Hi, I'm a member of the [kubernetes org](https://github.com/kubernetes/org/blob/c0adbc758d3f0354f260cf06ec78875e6870ece6/config/kubernetes/org.yaml#L105) and would like to get added to the  kubernetes-client. I referred [this membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) guide, which says:
> "If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly"
resolve https://github.com/kubernetes/org/issues/3525
> Add arhell as member in kubernetes-client

- config/kubernetes-sigs/sig-network/teams.yaml
This mirrors https://github.com/kubernetes-sigs/gateway-api/pull/1231 and adds @shaneutt as a Gateway API maintainer.
> Adding Shane Utt as Gateway API Maintainer

- config/kubernetes/sig-release/teams.yaml
This PR is part of RMA onboarding for  @jrsapi and myself.
* Adds @jrsapi  to @kubernetes/release-engineering  and milestone-maintainers
* Adds @jeremyrickard  to `release-engineering` (I was already in MM for my other SIG Release hat)
Ref: https://github.com/kubernetes/sig-release/issues/1965 
/assign @Verolop  @saschagrunert @justaugustus 
Signed-off-by: Jeremy Rickard <jrickard@microsoft.com>
> releng: RMA Onboarding for Jeremy and Joseph

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
I'm one of the primary contributors to the cluster-api-provider-kubevirt project. We'd like to spread the ownership of the repo out a little bit further and I've volunteered to help there. I'll need the ability to create tags/releases as well as manage secrets for CI.
> Add David Vossel as cluster-api-provider-kubevirt admin/maintainer

- config/kubernetes/org.yaml
Signed-off-by: Shane Utt <shaneutt@linux.com>
Note: I am already a member of kubernetes-sigs, and a maintainer of Gateway API.
> add shaneutt to kubernetes org

- config/kubernetes/sig-node/teams.yaml
Adding myself to the `sig-node-pr-reviews` team to opt in to pings on repos where we're not in `OWNERS` files but node technical review is required (e.g kubernetes/website for docs), as they've been struggling to reach anyone in the sig without slack.
Also adding myself to the test-failures group although it isn't often used as a catch for when it is (for when folks don't ping me/sergey/slack directly).
> sig-node: add endocrimes to teams

- config/kubernetes/org.yaml
Hi, I'm a member of the [kubernetes-sigs org](https://github.com/kubernetes/org/blob/2d1ce973592fe7d5bbb51275bc48bd92ea7781b5/config/kubernetes-sigs/org.yaml#L605) and would like to get added to the kubernetes. I referred [membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) guide, which says:
> "If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly"
Fixes: #3544
> Add Prajyot-Parab to kubernetes

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
In order to help unblock development and release of the CAPC repository, we would like to add a few more maintainers to the CAPC repo to have the ability to create branches and tags. These individuals are already listed in the OWNERS file in CAPC: https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/main/OWNERS
> Adding new maintainers to CAPC repo

- config/kubernetes/sig-docs/teams.yaml
This PR adds a `sig-docs-blog-owners` team under SIG Docs teams
This GH team will be used to administrate the [SIG Docs blog project board](https://github.com/kubernetes/website/projects/11)
Members are members of the `sig-docs-blog-owners`  OWNES_ALIASES https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES#L2
> Add sig-docs-blog-owners to SIG Docs teams

- config/kubernetes/sig-docs/teams.yaml
Sync with [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES) in k/website.
The modification can be found in this two PR.
- kubernetes/website#35563 
- kubernetes/website#11391
CC zh team lead @tengqm
> Sync sig-docs zh team members

- config/kubernetes/sig-release/teams.yaml
I'd like to be added to the milestone maintainer group, as a person that is working in EU timezone I think that this will improve the round trip and spread the load
/assign @BenTheElder @thockin 
assign to Tim and Ben as respective Sig network and testing leads
> add aojea to the milestone maintainer group

- config/kubernetes/sig-docs/teams.yaml
Adds [Garima Negi](https://github.com/Garima-Negi) as a reviewer for Hindi l10n as discussed on [Slack](https://kubernetes.slack.com/archives/CJ14B9BDJ/p1655230491320389)
ref: https://github.com/kubernetes/website/pull/35052
> Add Garima Negi as reviewer for Hindi l10n

- config/kubernetes/sig-docs/teams.yaml
Add t-inu to sig-docs-ja-reviews.
ref: https://github.com/kubernetes/website/pull/35970
> Add t-inu to sig-docs-ja-reviews

- config/kubernetes/org.yaml
- Revert "add wangchen615 to kubernetes"
- add Rishit-dagli to kubernetes
- add hlipsig to kubernetes
https://github.com/kubernetes/org/pull/3620 merged before the force-push could propagate to the branch. Raising this PR to correct the wrong additions and add the pending members.
/assign @savitharaghunathan
> fix remaining org memberships

- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/provider-ibmcloud/teams.yaml
- config/kubernetes/org.yaml
The account has been renamed to arahamad-zz as can be found by
checking if a user repository redirects. In this case, redirect
has been checked by accessing the repository:
https://github.com/arahamad/ibmcloud-storage-volume-lib
This problem was noticed because of a failing run of the peribolos
postsubmit job. Failing run link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-org-peribolos/1560538034468818944
> fix username for arahamad

- config/kubernetes/org.yaml
Hossein changed the username from encodeflush to @hosseinsalahi 
ref: https://github.com/kubernetes/sig-release/pull/2003#event-7274104377
cc @palnabarun
> Update username encodeflush to hosseinsalahi

- config/kubernetes-sigs/sig-node/teams.yaml
Add @qbarrand as a maintainer for [Kernel Module Management](https://github.com/kubernetes-sigs/kernel-module-management) that we are transitioning from https://github.com/qbarrand/oot-operator.
> Add qbarrand as KMM admin

- config/kubernetes/sig-release/teams.yaml
Remove 1.25 release team and add 1.26 release team leads and team leads. Shadows will be confirmed after 9/12
/priority important-soon
/cc @palnabarun @saschagrunert
> add tenative 1.26 release team without team shadows

- config/kubernetes-sigs/sig-node/teams.yaml
Follow up on mistake I made in #3650
Caught by CI: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-org-peribolos/1565015810299138048
> Fix bad previous name in kmm teams

- config/kubernetes-sigs/sig-network/teams.yaml
astoycos is an owner in the
adminNetworkPolicy API repo
and should be added here as
well.
Related to https://github.com/kubernetes/org/issues/3643
> Add astoycos to NPAPI admins

- config/kubernetes-sigs/org.yaml
James Strong is a member of the kubernetes org:
https://github.com/kubernetes/org/blob/93aa088144549e3d8a434cecc5d3b7459ef783f6/config/kubernetes/org.yaml#L1268
This should grant him access to k-sigs too. This PR adds him to the `kubernetes-sigs` org to enable him to lgtm on reviews on our projects there.
/cc @strongjz 
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
> Update James Strong's k-sigs membership

- config/kubernetes/sig-docs/teams.yaml
With the 1.25 release cycle complete, this PR does the following:
- add comment to krol3 to identify krol3 as the 1.26 release team docs lead in `website-milestone-maintainers`
- remove the 1.25 release team docs team from `website-milestone-maintainers`:
- didicodes
- cathchu
- sethmccombs
- kcmartin
- source: https://github.com/kubernetes/sig-release/blob/master/releases/release-1.25/release-team.md and PR author was the Emeritus Adviser on the 1.25 release team
- remove kcmartin as the 1.25 rt docs lead from `website-maintainers`
- add reylejano to `website-maintainers` as a [SIG Docs co-chair ](https://github.com/kubernetes/community/tree/master/sig-docs#chairs) and as a [`sig-docs-en-owner`](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES#L20)
> Cleanup after 1.25 cycle and add reylejano to SIG Docs website-maintainer

- config/kubernetes/sig-scheduling/teams.yaml
Per https://github.com/kubernetes/kubernetes/issues/111392#issuecomment-1194116115, update the outdated teams.yaml in sig-scheduling.
> update sig-scheduler teams.yaml

- config/kubernetes/sig-release/teams.yaml
Creating Github teams for the enhancements and docs teams with selected shadows so we can leverage these teams for permissions to the Github project board for tracking enhancements. 
See https://kubernetes.slack.com/archives/C02BY55KV7E/p1662554313333169
cc - @gracenng @palnabarun @leonardpahlke @krol3
> Create teams for release enhancements and docs

- config/kubernetes/sig-release/teams.yaml
For purposes of using the GitHub project board that Enhancements has set up for the current release cycle, and as discussed in in[ #release-comms](https://kubernetes.slack.com/archives/CNT9Y603D/p1663175150499059?thread_ts=1662994419.135199&cid=CNT9Y603D)
> Create team for Communications

- .github/ISSUE_TEMPLATE/membership.yml
Creating a membership request is sometimes done by members who are already part of the Kubernetes community. The note added to the issue template should prevent this, as it is not necessary to ask for sponsorship if you are already part of one of the K8 organizations.
/cc @palnabarun @mrbobbytables
> Add note to membership issue template; no need to request membership if you are already part of a K8s org 

- config/kubernetes/sig-release/teams.yaml
This PR is part of RMA onboarding for @salaxander  and myself.
Adds @cici37 and @salaxander  to https://github.com/orgs/kubernetes/teams/release-engineering and milestone-maintainers
Ref: https://github.com/kubernetes/sig-release/issues/2034
/assign @jeremyrickard
> releng: RMA onboarding for cici37 and salaxander

- config/kubernetes/sig-release/teams.yaml
For purposes of using the GitHub project board the bug-triage needs to create a GH team for the 1.26 release cycle.
@leonardpahlke @palnabarun
> Create team for Bug-Triage

- config/kubernetes/sig-docs/teams.yaml
This PR adds atoato88 as sig-docs-ja-reviews.
ref: https://github.com/kubernetes/website/pull/37072
> Add atoato88 as sig-docs-ja-reviews

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Renaming @kris-nova to @krisnova.
fixes following error:
```
{"component":"unset","error":"status code 422 not one of [200], body: {\"message\":\"Members must be users, not organizations.\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:476","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(kubernetes-sigs, kris-nova, false) failed","severity":"warning","time":"2022-10-02T20:08:24Z"}
```
> Rename kris-nova to krisnova

- config/kubernetes/sig-release/teams.yaml
This PR adds `release-team-release-notes` for having contact with the Release Notes Team at GitHub
> Create team for Release Notes

- OWNERS_ALIASES
- config/kubernetes/org.yaml
Part of https://github.com/kubernetes/steering/issues/256
Onboard:
- BenTheElder
- palnabarun
Offboard:
- dims
- liggitt
cc: @kubernetes/steering-committee 
/assign @mrbobbytables @cblecker
> Onboard/Offboard Steering Committee members as per 2023 elections

- config/kubernetes/sig-release/teams.yaml
xref: https://github.com/kubernetes/website/pull/37169, https://github.com/kubernetes/release/pull/2697
> drop googlers that no longer have deb/rpm access from build-admins

- OWNERS_ALIASES
- config/kubernetes/org.yaml
Update the COCC membership to reflect new committee
Part of https://github.com/kubernetes/community/issues/6916
Signed-off-by: Jeremy Rickard <jrickard@microsoft.com>
> Update CoCC membership for new members

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-auth/teams.yaml
Adds @enj to k-sigs as well.
ref: #3688
> Add sig auth tools teams

- config/kubernetes/org.yaml
Part of https://github.com/kubernetes/community/issues/6916
> drop palnabarun from code-of-conduct-committee team

- config/kubernetes/org.yaml
Ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-org-peribolos/1582464514404651008
```
{"component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:1280","func":"main.configureTeamMembers.func1","level":"warning","msg":"UpdateTeamMembership(goog-gke(goog-gke), ihmccreery, false) failed: status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-membership-for-a-user\"}","severity":"warning","time":"2022-10-18T20:19:26Z"}
{"component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:192","func":"main.main","level":"fatal","msg":"Configuration failed: failed to …
```
> Remove ihmccreery, username does not exist anymore

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- config/kubernetes/org.yaml
Ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-org-peribolos/1583552054008221696
```
{"client":"github","component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/github/client.go:917","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateTeamMembershipBySlug(kubernetes-sigs, cluster-api-operator-admins, alexander-demichev, false)","severity":"info","time":"2022-10-21T20:15:29Z"}
{"component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:1280","func":"main.configureTeamMembers.func1","level":"warning","msg":"UpdateTeamMembership(cluster-api-operator-admins(cluster-api-operator-admins), alexander-demichev, false) failed: status code 404 not one of …
```
> Update username for alexander-demichev

- config/kubernetes/sig-docs/teams.yaml
This PR updates the website-maintainers group and website-milestone-maintainers groups with:
- @natalisucks (SIG Docs co-chair)
- @divya-mohan0209 (SIG Docs co-chair)
- @a-mccarthy (SIG Docs localization subproject owner)
- @nate-double-u (SIG Docs en and blog approver)
> Update sig docs website-maintainers and website-milestone-maintainers

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Josh has left the organization and is no longer working on or maintaining the CAPC repo. https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/184/files
> Remove Josh since his departure from the maintaining org

- config/kubernetes/sig-docs/teams.yaml
Following obtaining a Kubernetes organization membership (#3749), I'd like to join the Russian localization team — it is crucial to carry on all related works since all current sig-docs-ru members don't seem to be active anymore (I've tried to reach all of them with no luck), thus all new PRs for this language are stuck.
> Add shurup as a sig-docs-ru member

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This PR adds a new github team called the `cluster-api-release-team`.
> add cluster-api-release-team github team

- config/kubernetes/org.yaml
User no longer exists. This PR fixes peribolos.
Ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-org-peribolos/1591888797027536896
```
{"component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:1289","func":"main.configureTeamMembers.func1","level":"warning","msg":"UpdateTeamMembership(kubernetes-maintainers(kubernetes-maintainers), kargakis, false) failed: status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-membership-for-a-user\"}","severity":"warning","time":"2022-11-13T20:27:44Z"}
{"component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:194","fun …
```
> Remove kargakis from kubernetes org

- config/kubernetes-sigs/sig-aws/teams.yaml
I am a kubernetes-sigs member and an owner for the aws-fsx-csi-driver - I'd like to add myself here as well.
- Sigs member: https://github.com/kubernetes/org/pull/3720
- Owners: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/256
> Add self to aws-fsx-csi-driver maintainers/admins list

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
ref: https://github.com/kubernetes/org/issues/3836
Adds @medyagh and @spowelljr to k-sigs in addition to the teams
> Add teams for minikube gui repo

- config/kubernetes-sigs/sig-instrumentation/teams.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-instrumentation/teams.yaml
/cc @logicalhan @ehashman @dashpole
> Cleanup sig-instrumentation teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-node/teams.yaml
ref: https://github.com/kubernetes/org/issues/3837
Note: this PR also adds @bart0sh to the kubernetes-sigs org, they are already a member of kubernetes.
> Add dra-example-driver repo teams

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Adding myself and Fabrizio to Cluster API admins.
The idea is that through the admin access to the repo we will also get access to Netlify.
Adding Fabrizio as well so he can also help out with Netlify duties.
xref: https://kubernetes.slack.com/archives/C1TU9EB9S/p1669656532332839?thread_ts=1669638214.266839&cid=C1TU9EB9S
> Add sbueringer & fabriziopandini to cluster-api-admins

- config/kubernetes-sigs/sig-network/teams.yaml
This mirrors https://github.com/kubernetes-sigs/gateway-api/pull/1528. I'd assumed it's best to keep the groups separate but equal here to match other config, but let me know if I should just merge this into a single group here as well.
> Updating Gateway API Admins to match Gateway API Maintainers

- config/kubernetes/sig-docs/teams.yaml
This PR replaces 'zhangxiaoyu-zidif' by 'tengqm' as one of the website maintainers, because the former reviewer has not been active for two years.
> Replace website maintainers

- config/kubernetes/sig-cloud-provider/teams.yaml
Ole has been creating tags for releases for the cloud-provider-aws repository, but does not currently have permissions to create the release itself.
> Add Ole Markus With to cloud-provider-aws maintainers

- config/kubernetes-sigs/sig-release/teams.yaml
Follow-up on https://github.com/kubernetes-sigs/promo-tools/issues/694#issuecomment-1350499791
This PR adds @palnabarun, @Verolop, and me (Release Managers) to the promo-tools-maintainers team. Also, @Verolop is added to the promo-tools-admins team (part of https://github.com/kubernetes/sig-release/issues/2099).
/assign @saschagrunert @puerco @jeremyrickard @Verolop
> Add Release Managers as maintainers for promo-tools

- config/kubernetes-sigs/org.yaml
The user changed its name so we have to update it in k-sigs as well.
Follow-up of https://github.com/kubernetes/org/pull/3641
Refers to https://github.com/kubernetes-sigs/testgrid-json-exporter/pull/10
> Update `encodeflush` to `hosseinsalahi`

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Changes to the aliases for the 2 Cluster API provider AWS teams to match the owners_aliases for maintainers/admins as of 2022-10-19.
Until the https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3775 merges on 19th October:
/hold
Fixes: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3621
Signed-off-by: Richard Case <richard.case@outlook.com>
> feat: Cluster API Provider AWS Team Changes

- config/kubernetes-sigs/sig-windows/teams.yaml
I have been helping and maintaing the project. With admin access I can continue my efforts in the CI/CD for testing different CNIs with sig-windows-dev-tools.
Signed-off-by: Douglas Schilling Landgraf <dlandgra@redhat.com>
> teams: add dougsland to sig-windows-dev-tools admin

- config/kubernetes/sig-docs/teams.yaml
We at SIG-Docs Hindi localization would like to add @Babapool and @bishal7679 as an official reviewer for Hindi as discussed [here](https://kubernetes.slack.com/archives/CJ14B9BDJ/p1670247355517609) and [here](https://kubernetes.slack.com/archives/CJ14B9BDJ/p1670313142357499) on Slack.
Vitthal has been contributing to Hindi l10n for some time now and helped us localizing more docs and review PRs.
see https://github.com/kubernetes/website/pull/38479
see https://github.com/kubernetes/website/pull/38598
cc @Babapool @bishal7679 @divya-mohan0209
> Add Vitthal Sai Kaul and Bishal Das as SIG-Docs Hindi l10n Reviewers

- config/kubernetes/sig-docs/teams.yaml
I want to join the sig-docs-zh-reviews team.
I have met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):
- Member of Kubernetes for 3+ months
- 280+ PRs merged: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Amy-git9
- 30+ PRs reviewed:https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3Amy-git9
Thanks
> Add my-git9 to sig-docs-zh-reviews

- config/kubernetes/org.yaml
As per the [community membership doc](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) I can simply open a PR to add myself to kubernetes when I'm already in kubernetes-sigs. I'm contributing to CAPO under kubernetes-sigs, and as part of that I have also needed to work with test-infra, which is why I want this.
> Add myself to kubernetes (already in kubernetes-sigs)

- config/kubernetes/sig-release/teams.yaml
Initial update for the 1.27 release and cleanup from 1.26. Additional updates will be needed once all shadows have been selected.
> update sig-release teams for 1.27 release

- config/kubernetes/org.yaml
Following the below directive mentioned while adding myself to the kubernetes org via git issue;
> if you are already part of any Kubernetes GitHub organization like kubernetes-sigs and you are filing this request to be added to kubernetes, you do not need to open this request and can add yourself directly! The org memberships are now equivalent and sponsorship is not needed to join additional Kubernetes GitHub orgs.
raising this PR to add myself to the kubernetes org.
Groups I am part of
- Kubernetes-sigs
- Cluster-api-release-team
> add nawazkh to kubernetes org

- config/kubernetes-sigs/org.yaml
- @jrsapi is already a member of Kubernetes and now, as a release manager associate he needs to be part of the k-sigs as well because we have projects for sig-release there
see https://github.com/kubernetes-sigs/tejolote/pull/23 as reference
> adding `jrsapi` to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
On January 9, 2023 the user "fromanirh" renamed their github handle to "ffromani".
Signed-off-by: Francesco Romani <fromani@redhat.com>
> update github handle fromanirh -> ffromani

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This change updates the GitHub groups for CAPG with the current maintainers (see [OWNERS](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/OWNERS_ALIASES))
Signed-off-by: Richard Case <richard.case@suse.com>
/cc @cpanato @dims
> Updated CAPG groups with current maintainers

- Makefile
- README.md
- hack/add-members.sh
Members can now be added using:
`make add-members WHO=username1,username2 REPOS=kubernetes-sigs,kubernetes`
> Add make target to add org members

- config/kubernetes-sigs/org.yaml
This reverts commit 5a94ef39b7808fe74fd1eb126b7c152f1a657221.
They have rotated all their credentials and can be restored.
fixes: #3890
> Revert "Remove qiujian16 from kubernetes-sigs org"

- config/kubernetes-sigs/org.yaml
Hi - I'm already a member of the `kubernetes` org. I'm just adding myself to `kubernetes-sigs`
https://github.com/kubernetes/org/blob/31d4d663487a39566cba745bfc65edc65fbcb2d2/config/kubernetes/org.yaml#L371
> add dprotaso to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
We should add Peter to the `cri-tools-maintainers` handle after the merge of: https://github.com/kubernetes-sigs/cri-tools/pull/1044
cc @feiskyer @haircommander @mrunalp @Random-Liu @yujuhong
> Add `haircommander` to `cri-tools-maintainers`

- config/kubernetes-sigs/org.yaml
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
I'm a kubernetes member, applying to join kubernetes-sigs today.
https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L451
> Add Fish-pro to kubernetes-sigs

- config/kubernetes/sig-architecture/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Signed-off-by: Mark Rossetti <marosset@microsoft.com>
Adding 1.27 enhancements shadows to appropriate groups
/assign @salaxander @JamesLaverack
> Adding 1.27 enhancements team to appropriate groups

- config/kubernetes/sig-instrumentation/teams.yaml
I'd like to join sig-instrumentation as I'm already maintaining a subproject (kube-state-metrics).
@dgrisonnet
> sig-instrumentation: Add mrueg

- config/kubernetes-nightly/org.yaml
Promote cici37 to kubernetes nightly org member for publishing-bot related work.
Related to https://github.com/kubernetes/org/pull/3978, https://github.com/kubernetes/sig-release/issues/2152
/cc @jeremyrickard
> Promote cici37 to kubernetes nightly org member

- config/kubernetes/sig-instrumentation/teams.yaml
Hello, I'd like to be added to the aforementioned SIG as I'm already a reviewer in [k/KSM](https://github.com/kubernetes/kube-state-metrics).
Thanks.
> Add `rexagod` to sig-instrumentation

- config/kubernetes/sig-release/teams.yaml
Add @gracenng  and me to appropriate groups for being Release Manager Associates.
Related to https://github.com/kubernetes/sig-release/issues/2163
> Add members to appropriate groups for being Release Manager Associates

- config/kubernetes/sig-node/teams.yaml
I'd like to support SIG node with bug triage, features as well as PR reviews. Therefore I propose to get add myself to the teams to be able to receive the GitHub notifications.
cc @kubernetes/sig-node-bugs, @kubernetes/sig-node-feature-requests, @kubernetes/sig-node-pr-reviews, @kubernetes/sig-node-proposals, @kubernetes/sig-node-test-failures
Signed-off-by: Harshal Patil <harpatil@redhat.com>
> Add `harche` to SIG Node teams

- config/kubernetes/sig-node/teams.yaml
I'd like to support SIG node with bug triage, features as well as PR reviews. Therefore I propose to get add myself to the teams to be able to receive the GitHub notifications.
> Add `saschagrunert` to SIG Node teams

- OWNERS_ALIASES
- config/kubernetes/sig-node/teams.yaml
In response to https://github.com/kubernetes/enhancements/issues/24#issuecomment-1410951614
It looks like the team is missing.
> added sig-node-leads

- config/kubernetes/sig-release/teams.yaml
Add bug triage shadows for 1.27 to the respective teams, as required for access to the GitHub project board.
Following https://github.com/kubernetes/org/pull/3706
cc @salaxander @JamesLaverack
> add bug triage team for 1.27

- config/kubernetes/sig-release/teams.yaml
Added Comms shadows for 1.27 to the respective team in order to get access to the GitHub project board.
cc @JamesLaverack @salaxander
> Add comms team for 1.27

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- Removing `joao-luna-98` as the user now 404s
- Removing `BinacsLee` as this user has been converted into an organization
> Remove users from configuration to fix peribolos

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
I have been a member of the kubernetes organization since April 27, 2021. (PR: https://github.com/kubernetes/org/pull/2664   Issue: https://github.com/kubernetes/org/issues/2658)
Yesterday I changed my username (from `BinacsLee` to `binacs`) and caused me to be removed from the organization. (PR: https://github.com/kubernetes/org/pull/4019)
I am now requesting to rejoin the organization with a new username `binacs`.
cc @ameukam @nikhita Thanks a lot!
> add back binacs(BinacsLee)

- config/kubernetes/sig-docs/teams.yaml
Sync `sig-docs-xx-owners` and `sig-docs-xx-reviews` member with [k/website OWNERS_ALIASES](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES).
Also cleanup `website-maintainers` and `website-milestone-maintainers`, removed who have no any `owners` or `reviews` role.
Please let me know if any change should be revert.
Hold this PR until 2023-02-05 as it involved 40 contributors.
/hold
/cc @kubernetes/sig-docs-leads
---
Removed A:
- @aisonaku as `ru-owners`, `website-maintainers`, `website-milestone-maintainers`
- @claudiajkang as `ko-owners`, `website-maintainers`, `website-milestone-maintainers`
- @dianaabv as `ru-owners`, `website-maintainers`, `website-milestone-maintainers`
- @msheldyakov as `ru-owners`, `website-maintainers`, `website-milestone-maintainers`
- @ngtuna as …
> Cleanup sig-docs teams

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Add killianmuldoon to the CAPI maintainer team.
PR making changes on the CAPI OWNER_ALIASES is at https://github.com/kubernetes-sigs/cluster-api/pull/7996
> Add killianmuldoon as CAPI maintainer

- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
Don't know if they've renamed or just removed their account, but https://github.com/nzoueidi is 404'ing.
> Remove nzoueidi

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Adding members to aws-file-cache-csi-driver team
accidentally closed previous pr: https://github.com/kubernetes/org/pull/4051
> Add members to aws-file-cache-csi-driver team

- config/kubernetes-sigs/org.yaml
By following the system advice, I opened this PR to add me to the kubernetes-sigs as a [member](https://github.com/kubernetes/org/issues/3423).
```
since you are already a member of https://github.com/kubernetes, feel free to open a PR directly to add yourself to k-sigs. 😄
Otherwise, we can get this in when we go through the next set of membership requests. 👍
```
- PRs authored
[600+ to k8s website](https://github.com/kubernetes/website/pulls/windsonsea)
- PRs reviewed
[60+ to k8s website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Awindsonsea+reviewed-by%3A%40me+is%3Aclosed)
- Issues responded to
[16 to k8s website](https://github.com/kubernetes/website/issues/created_by/windsonsea)
- SIG projects I am involved with
- kubernetes/website
- kubernetes/community
- …
> Add windsonsea to kubernetes-sigs as a member

- config/kubernetes/org.yaml
- config/kubernetes/sig-apps/teams.yaml
Move declaration of kompose GitHub teams to simplify approval.
> sig-apps: relocate kompose teams

- config/kubernetes-sigs/sig-k8s-infra/teams.yaml
We've been using `-maintainers` NOT `-writers`:
https://cs.k8s.io/?q=-maintainers%3A&i=nope&files=&excludeFiles=&repos=kubernetes/org
EDIT: Adding a new group `-maintainers` in addition to `-writers` per guidance from @mrbobbytables
> writers should be maintainers (community-images and porche)

- config/kubernetes-sigs/sig-node/teams.yaml
This reflects the desired repo OWNERS state.
PTAL @pjbgf @jhrozek @JAORMX 
cc @ccojocar 
Refers to https://github.com/kubernetes-sigs/security-profiles-operator/pull/1524, https://github.com/kubernetes/test-infra/pull/28912, https://github.com/kubernetes/k8s.io/pull/4866
> Update Security Profiles Operator owners

- config/kubernetes/org.yaml
Hi, I'm already a member of the [kubernetes-sigs](https://github.com/kubernetes/org/issues/2173) and [kubevirt](https://github.com/kubevirt/project-infra/pull/2113) organizations, my contributions are listed there.
Now I need a kubernetes org membership to set up an staging repository for nfs-server-provsioner project:
- https://github.com/kubernetes/k8s.io/pull/4881#issuecomment-1458106742
- https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/122#issuecomment-1458134244
/cc @msau42 @sftim @wongma7 @jsafrane could you sponsor this request, please?
Thank you
> add kvaps to kubernetes org

- config/kubernetes/sig-release/teams.yaml
Needed for access to the docs tracking GitHub project board
> add 1.27 docs shadows to group

- config/kubernetes/sig-docs/teams.yaml
Add myself to the `sig-docs-zh-reviews` after [website PR #39964](https://github.com/kubernetes/website/pull/39964), to get the permission, thanks.
> Add windsonsea to sig-docs-zh-owners

- config/kubernetes-nightly/sig-release/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Accompanying GitHub team membership changes to https://github.com/kubernetes/sig-release/issues/2152, https://github.com/kubernetes/sig-release/pull/2156
* Promote cici37 to Branch Manager
/hold until [Branch Managers](https://github.com/kubernetes/sig-release/pull/2156) merges.
/assign @jeremyrickard
/cc https://github.com/orgs/kubernetes/teams/release-managers
/milestone v1.27
/priority important-soon
> releng: Promote Cici Huang to Release Manager

- OWNERS_ALIASES
- config/kubernetes/sig-network/teams.yaml
Per chair transition procedure, there were no objections to Mike being proposed as dcbw's replacement, thus Mike is now a chair.
https://groups.google.com/g/kubernetes-sig-network/c/sZF25bnqZ-8
@MikeZappa87 @thockin @shaneutt
> sig-net: transfer co-chair from dcbw to MikeZappa87

- config/kubernetes-sigs/sig-network/teams.yaml
This PR updates `config/kubernetes-sigs/sig-network/teams.yaml` to add a new admin and maintainer and remove an inactive one. 
/cc @szuecs
> Update external-dns admins and maintainers

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
related - https://github.com/kubernetes-sigs/provider-aws-test-infra/pull/1
Also see this repo where we have a test-e2e-node that works with AWS
- https://github.com/dims/remote-aws-runner 
and possibly some stuff from:
- https://github.com/aws/aws-k8s-tester
> Add dims as admin for provider-aws-test-infra repo

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This PR updates the team called the cluster-api-release-team.
> Update cluster-api-release-team github team

- config/kubernetes-sigs/sig-instrumentation/teams.yaml
Adding @campoy and @ndipebot to usage-metrics-collector-admins and usage-metrics-collector-maintainers.
> Add campoy and ndipebot to usage-metrics-collector orgs

- config/kubernetes-sigs/org.yaml
Add ArangoGutierrez into the admin and maintainers group of the kubernetes-sigs node-feature-discovery project. He was recently added as a project approver in kubernetes-sigs/node-feature-discovery#1180.
> kubernetes-sigs: add ArangoGutierrez as nfd admin and maintainer

- config/kubernetes/org.yaml
After speaking with @sbueringer  https://github.com/kubernetes/k8s.io/pull/5077#issuecomment-1502805630 I wanted to add myself to the kubernetes org.
From https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem
> If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly or [opening an issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) against the kubernetes/org repo, as above.
> Add new member to kubernetes org

- config/kubernetes-sigs/org.yaml
I have a membership for kubernetes org. I contributed to kubelet and scheduler with touching/writing 4 KEPs.
Now I'm going to contribute [kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api).
[The document](https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#issue-and-pull-request-management) says I'm also eligible for membership of kubernetes-sigs org. 
> If you are a Kubernetes GitHub organization member, you are eligible for membership in the Kubernetes SIGs GitHub organization and can request membership by [opening an issue](https://github.com/kubernetes/org/issues/new?template=membership.md&title=REQUEST%3A%20New%20membership%20for%20%3Cyour-GH-handle%3E) against the kubernetes/org repo.
> add bg-chun to kubernetes-sigs

- config/kubernetes-sigs/sig-scheduling/teams.yaml
- remove @adtac 
- move @sanposhiho to the admin
- no one in maintainers then, so remove it.
ref: https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/297
> remove adtac and add sanposhiho to the simulator admin

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
add mowangdk to  alibaba-cloud-csi-driver admin
> add mowangdk to  alibaba-cloud-csi-driver admin and remove fredkan from alibaba-cloud-csi-driver

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Also remove hidekazuna, who stepped down a while ago.
/hold pending merge of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1537
> Add lentzi90 to cluster-api-provider-openstack-admins

- config/kubernetes-sigs/org.yaml
@eddycharly is already in kubernetes, but not in kubernetes-sigs. Adding his handle here.
> Add eddycharly to kubernetes-sigs members

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-testing/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/sig-testing/teams.yaml
getting the sig lists up-to-date with chair rotation per kubernetes/community#7239
> removed spiffxp and added xmcqueen per nomination sig-testing chair

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Syncs up the GH ownership with image-builder's [`OWNERS_ALIASES`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/OWNERS_ALIASES#L18)
> Add mboersma to image-builder-admins

- config/kubernetes-sigs/sig-network/teams.yaml
Make sure the k8s org team members for the network-policy-api admins are up to date with the [repo's owners file](https://github.com/kubernetes-sigs/network-policy-api/blob/master/OWNERS).
Follow up to https://github.com/kubernetes-sigs/network-policy-api/pull/97
> sync NPAPI owners to org team members

- config/kubernetes/sig-release/teams.yaml
As part of 1.28 release cycle commencing. Find 1.28 release team members [here](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.28/release-team.md)
As discussed with @furkatgofurov7, we will not add bug triage shadows to `milestone-maintainers` until we find out where they'll need it.
cc @kubernetes/sig-release-leads @leonardpahlke
> Add 1.28 team member to sig-release YAML

- OWNERS_ALIASES
- config/kubernetes/sig-cli/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Per the announcement https://groups.google.com/g/kubernetes-sig-cli/c/J_WelkrSwBM/m/brDiEhVRAgAJ this updates the leads in SIG-CLI
> Update SIG-CLI chairs and TL

- OWNERS_ALIASES
This PR updates this owners file to match https://github.com/kubernetes/community/blob/master/sig-cloud-provider/README.md#leadership (which was updated in April in https://github.com/kubernetes/community/pull/7251).
> Updating SIG Cloud Provider leads

- config/kubernetes/sig-release/teams.yaml
This PR updates this sig-release team file to match https://github.com/kubernetes/community/blob/master/sig-cloud-provider/README.md#leadership (which was updated in April in https://github.com/kubernetes/community/pull/7251).
> Adding new SIG Cloud Provider leads

- config/kubernetes-sigs/org.yaml
chendave is already a member of kubernetes org, and is a reviewer of kubadm and scheduler.
Need to kubernetes-sig member to work with other sig projects (kubetest2, test-infra etc.)
> Add chendave to kubernetes-sigs org

- Makefile
- OWNERS
- SECURITY_CONTACTS
- admin/update.sh
- config/kubernetes-client/OWNERS
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/OWNERS
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/OWNERS
- config/kubernetes-incubator/org.yaml
- config/kubernetes-nightly/OWNERS
- config/kubernetes-nightly/org.yaml
- config/kubernetes-retired/OWNERS
- config/kubernetes-retired/org.yaml
- config/kubernetes-sigs/OWNERS
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
- config/kubernetes-sigs/sig-k8s-infra/teams.yaml
- config/kubernetes-sigs/sig-release/teams.yaml
- config/kubernetes/OWNERS
- config/kubernetes/org.yaml
- config/kubernetes/sig-api-machinery/teams.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
- config/kubernetes/sig-k8s-infra/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/wg-structured-logging/teams.yaml
Ref https://github.com/kubernetes/community/pull/7327
Change root OWNERS and ADMIN variables in scripts
Remove self from wg-structured-logging-members, no longer active, didn't want to elevate to `maintainer` role in the teams here.
config: GH admin rotation - update team configs
Move ameukam to members wherever applicable.
Add MadhavJivrajani as maintainer anew or move
from member to maintainer wherever necessary.
config: GH Admin rotation - update org OWNERS and configs
Add MadhavJivrajani as admin in all orgs and move ameukam
to member wherever applicable.
Add MadhavJivrajani as reviewer and approver in OWNERS of
all orgs and move ameukam to emeritus.
/cc @kubernetes/owners 
> Rotate ameukam and add MadhavJivrajani as GitHub Admin

- config/kubernetes/sig-docs/teams.yaml
I started contributing to the k8s-website more than 1 years ago, and k8s-website is my inspiration for contributing to the open source community, I've learned a lot from the contributors here.
I would like to apply to join the sig-docs-zh-reviews team and contribute even more in the future and help guide new contributors.
I have met the [requirements for approver](https://github.com/kubernetes/community/blob/master/community-membership.md#approver):
- Member of Kubernetes for 14+ months
- Reviewer of kubernetes/website Chinese documents for 6+ months
- 380+ PRs merged: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Amy-git9
- 100+ PRs reviewed:https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3Amy-git9
My commits ranked 6rd among all …
> Add my-git9 to sig-docs-zh-owners

- config/kubernetes/org.yaml
Adds myself to the kubernetes org so I can have ownership in k/k8s.io (https://github.com/kubernetes/k8s.io/pull/5477).
Direct PR since I'm already a member of kubernetes-sigs (#3160).
> add schrej to kubernetes org

- config/kubernetes-sigs/sig-scheduling/teams.yaml
Now, @codefromthecrypt has got the membership. They are the most active contributor in the repo and no reason we don't get them in the admin for smooth development.
/cc @kerthcet
> Add codefromthecrypt to the kube-scheduler-wasm-extension team

- OWNERS_ALIASES
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/sig-testing/teams.yaml
Ref https://github.com/kubernetes/community/issues/7346
Also updated membership a bit more, since some lists look inconsistent. (Some folks who are no longer involved in SIG Testing should probably also be removed but I want to leave that for later.)
> Rotate SIG Testing chairs

- OWNERS_ALIASES
- config/kubernetes/sig-docs/teams.yaml
Multiple reviewers & approvers housekept per below PRs/issues:
@jimangel moved to emeritus per [this PR](https://github.com/kubernetes/website/pull/38864). 
=> Removed from OWNERS_Aliases
=> Per confirmation from Jim, we have also untagged him as an approver/reviewer for English content.
@rikatz stepped down from pt-approvers/reviewers per [this PR](https://github.com/kubernetes/website/pull/40814)
=> Removed from sig-docs-pt-owners & sig-docs-pt-reviews
@Garima-Negi & @verma-kunal being housekept from sig-docs-hi-reviews per [this issue](https://github.com/kubernetes/website/issues/41598)
@mittalyashu being housekept from website-maintainers, since he is no longer a Hindi Localization maintainer
@savitharaghunathan being housekept from website-milestone-maintainers since she is no longer …
> Housekeeping SIG Docs OWNERS_Aliases and teams.yaml

- OWNERS_ALIASES
- config/kubernetes/org.yaml
Luke has stepped down from the SRC (https://github.com/kubernetes/committee-security-response/issues/182) and this PR is part of our offboarding process.
> Offboard Luke Hinds from SRC

- config/kubernetes/sig-architecture/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Changed teams.yaml to add new shadows and remove-update enhancements group of previous cycle
> Update teams.yaml to address remaining changes for the v1.28 release cycle

- config/kubernetes-csi/org.yaml
Adds myself to the kubernetes-csi org, as there is a project being used for SIG Storage work that is restricted to org members.
I am already a member of the kubernetes and kubernetes-sigs GitHub orgs.
> Add self to kubernetes-csi org

- config/kubernetes-csi/org.yaml
Adds wackxu to the kubernetes-csi org, as there is a project being used for SIG Storage work that is restricted to org members.
https://github.com/orgs/kubernetes-csi/projects/72/views/1
I am already a member of the kubernetes GitHub orgs.
And I am the emeritus approvers of https://github.com/kubernetes-csi/external-snapshotter
> REQUEST: New kubernetes-csi membership for wackxu

- config/kubernetes/org.yaml
- config/kubernetes/sig-autoscaling/teams.yaml
- config/restrictions.yaml
- Removing a number of inactive members ( @aleksandra-malinowska, @bskiba, @davidopp, @DirectXMan12, @losipiuk, and @piosz) from SIG Autoscaling related GH groups
- Adding in new members - myself to all SIG related groups for now, @towca, @BigDarkClown, and @x13n to SIG Autoscaling sub-project release related groups
- Moved autoscaling-* related groups and restrictions from the root org.yaml into SIG owned org.yaml
> SIG Autoscaling Github Groups Cleanup

- Makefile
The PR updates `peribolos` target in the Makefile, to add a `clean` step before building the binary to ensure a fresh output directory at the beginning.
> update peribolos make target to begin with a fresh output dir

- Makefile
The PR:
- reverts the prior changes from https://github.com/kubernetes/org/pull/4356
-  updates the `$(MERGED_CONFIG)` target in the Makefile to include a `clean` step
This ensures the [post-org-peribolos](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-org-peribolos/1686252591400357888) postsubmit job starts with a fresh output directory, avoiding any stale repo clones (for ex - of `k/test-infra`) with outdated data.
> update "$(MERGED_CONFIG)" target to begin with a clean output dir

- admin/update.sh
We now have the ability to manage team repo permissions with a restrictions model using peribolos as part of https://github.com/kubernetes/org/pull/2614
But from the logs of the latest peribolos run:
```
{"component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:850","func":"main.configureOrg","level":"info","msg":"Skipping team repo permissions configuration","severity":"info","time":"2023-08-01T09:44:21Z"}
```
This is because the flag that actually tells peribolos to reconcile team repo permissions ([`--fix-team-repos`](https://github.com/kubernetes/test-infra/blob/955da602bebe2ee209e80e9d38b2fb89192a42c0/prow/cmd/peribolos/main.go#L93)) was not set.
This commit rectifies that.
/assign @nikhita @Priyankasaggu11929 
/hold …
> admin: tell peribolos to reconcile team repo permissions

- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
- config/restrictions.yaml
The PR fixes the typo in the repo name (`lkwd` -> `lwkd`).
Also a fix for the following error in the failing `post-org-peribolos` job: 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-org-peribolos/1686345196503044096 
```
{"component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:194","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure kubernetes-sigs team lwkd-admins repos: failed to update team 4981835(lwkd-admins) permissions on repo lkwd to admin: status code 404 not one of [204], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/teams/teams#add-or-update-team-repository-permissions\"}","severity":"fatal","time":"2023-08-01T12:19:04Z"}
```
> fix repo name - s/lkwd/lwkd/g

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Update of CAPV team members as was discussed in 2023/06/22 meeting.
Related to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2082/files
> Refresh of Cluster API Provider vSphere team members

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
New CAPI v1.6 RT members announced here: https://kubernetes.slack.com/archives/C8TSNPY4T/p1690324526230509
This PR:
- removes old and adds new v1.6 RT members from/to the list in alphabetical order
> CAPI: Update list with v1.6 CAPI Release Team Members GitHub handles

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Syncing with recent changes made to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/OWNERS_ALIASES
cc: @sonasingh46
> sync CAPZ maintainer team members with OWNERS

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Reverts `sig-cluster-lifecycle` team changes from the commit - https://github.com/kubernetes/org/commit/eda81258d445e6d8d3968623970a96dcafe52079
Part of https://github.com/kubernetes/org/pull/4363
/sig contributor-experience
> revert sig-cluster-lifecycle team changes from commit eda8125

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-api-machinery/teams.yaml
Summary:
While GitHub is not case-sensitive, the [Elekto tool used for CNCF elections currently does need username case to match GitHub-official reality](https://github.com/kubernetes/community/blame/master/elections/steering/documentation/README.md#L226). This means that we should be consistent in how we store GitHub usernames, matching the official capitalization, so as to be able to correctly generate voter lists from devstats data.
What is currently wrong:
In the course of preparing for this year's steering election, I learned from the esteemed @mrbobbytables and subsequently [documented that election eligibility pulls from several files](https://github.com/kubernetes/community/pull/7443/files). When generating the eligible voters list using those files as input, I noticed that my …
> Correcting case for GitHub usernames

- config/kubernetes-csi/org.yaml
I am an active member of `kubernetes org` and would like to apply to join the `kubernetes-csi org`,
and look forward to contributing more.
- Meet the conditions for [community membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem)
- https://github.com/kubernetes/org/issues/2475
> Add ydFu to kubernetes-csi org

- config/kubernetes/sig-docs/teams.yaml
Temporarily adding myself to the website-maintainers team for write access to the k/website repo for the release preparation/release day.
/assign @divya-mohan0209 @natalisucks @reylejano
(SIG Docs Chairs)
> Add Rishit-dagli to website-maintainers team for 1.28 release

- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
- config/kubernetes-sigs/sig-scheduling/teams.yaml
- config/kubernetes-sigs/sig-windows/teams.yaml
- config/kubernetes/sig-api-machinery/teams.yaml
- config/kubernetes/sig-architecture/teams.yaml
- config/kubernetes/sig-k8s-infra/teams.yaml
- config/kubernetes/sig-security/teams.yaml
- config/restrictions.yaml
The PR: 
- update `repos:` permissions for the following GitHub teams under kubernetes and kubernetes-sigs orgs:
- `cel-admission-webhook-admins`
- `cel-admission-webhook-maintainers`
- ` maintainers-maintainers`ask
- `sigs-github-actions-admins`
- `sigs-github-actions-maintainers`
- `kube-scheduler-wasm-extension-admins`
- `cel-admission-webhook-admins`
- `cel-admission-webhook-maintainers`
- `sig-security-admins`
- `sig-security-maintainers`
- update `restrictions.yaml` to whitelist new repo permissions added as part of ^
- add `aroradaman` to `sig-windows-dev-tools-admins` GH team
(as per the ask in [4370#issuecomment-1671371021](https://github.com/kubernetes/org/pull/4370#issuecomment-1671371021))
> Peribolos: update repo permissions for GH teams

- Makefile
- OWNERS
- SECURITY_CONTACTS
- admin/update.sh
- config/kubernetes-client/OWNERS
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/OWNERS
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/OWNERS
- config/kubernetes-incubator/org.yaml
- config/kubernetes-nightly/OWNERS
- config/kubernetes-nightly/org.yaml
- config/kubernetes-retired/OWNERS
- config/kubernetes-retired/org.yaml
- config/kubernetes-sigs/OWNERS
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
- config/kubernetes/OWNERS
- config/kubernetes/org.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
- config/kubernetes/sig-docs/teams.yaml
- config/kubernetes/sig-k8s-infra/teams.yaml
- config/kubernetes/wg-structured-logging/teams.yaml
Ref https://github.com/kubernetes/community/pull/7464
**Commit 1**
`.*: add Priyankasaggu11929 and rotate out idvoretskyi as admin`
Change root OWNERS and ADMIN variables in scripts.
**Commit 2**
`remove Priyankasaggu11929 from wg-structured-logging teams.yaml`
**Commit 3**
`config: GH admin rotation - update team configs`
Move idvoretskyi to members wherever applicable.
Add Priyankasaggu11929 as maintainer anew or move from member to maintainer wherever necessary.
**Commit 4**
`config: GH Admin rotation - upgrade org OWNERS and configs`
Add Priyankasaggu11929 as admin in all orgs and move idvoretskyi to member wherever applicable.
Add Priyankasaggu11929 as reviewer and approver in OWNERS of all orgs and move idvoretskyi to emiratus.
/cc https://github.com/orgs/kubernetes/teams/owners …
> Add priyankasaggu11929 as GitHub Admin

- admin/update.sh
Now that peribolos is back on its feet, we don't need the skip-removals flag.
Ref https://github.com/kubernetes/org/issues/4365
/assign @Priyankasaggu11929 
/area github/management
/sig contributor-experience
> Revert "update admin/update.sh to include --skip-removals flag"

- config/kubernetes-csi/org.yaml
Fixes the typo `s/repo/repos/g` in csi-proxy-maintainers and csi-proxy-admins github team configs.
ref:  https://kubernetes.slack.com/archives/C01672LSZL0/p1692808314288179
> peribolos: fix typo s/repo/repos/g in csi-proxy-maintainers/admins team

- config/kubernetes-sigs/org.yaml
I need the authorization for contributing to kustomize.
> Add bugoverdose to kubernetes-sigs

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Adding hughdanliu and gomesjason, the primary maintainers of the repo, as admins/maintainers to the AWS FSx for OpenZFS CSI driver: https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver
> Add hughdanliu and gomesjason as admins for aws-fsx-openzfs-csi-driver

- config/kubernetes-sigs/org.yaml
I am an active member of kubernetes org and would like to apply to join the kubernetes-sigs org, and look forward to contributing more.
Meet the conditions for [community membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem)
SIG projects I am involved with:
https://github.com/kubernetes-sigs/controller-runtime
> Request: Add troy0820 to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
I am an active member of `kubernetes org` and would like to apply to join the `kubernetes-sigs org`, and look forward to contributing more.
* Meet the conditions for [community membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem)
* [REQUEST: New membership for @pegasas  #4405](https://github.com/kubernetes/org/issues/4405)
SIG projects I am involved with:
* https://github.com/kubernetes-sigs/gateway-api
* https://github.com/kubernetes-sigs/kueue
> Add pegasas to kubernetes-sigs org

- Makefile
- cmd/merge/main.go
- cmd/merge/main_test.go
- config/config_test.go
Strict unmarshalling allows us to fail when we see an unrecognised
key. This helps prevent subtle issues like `repo` being written instead
of `repos`. Previously, the unmarshalling would have ignored this. This
is quite serious because now this means that the desired state of a team
is that there is no repo under it when there clearly is a repo mentioned.
Hence, peribolos would remove this repo.
Strict unmarshalling prevents us from doing that.
Plus, this uses the yaml packages maintained by the Kubernetes community,
and this is also used in test-infra.
There are now more than 1 test files in the repo, using
`./...` with a flag will not suffice if that flag is not
defined in those test files.
---
One such issue that could've been prevented by strict unmarshalling: …
> cmd/merge: use strict unmarshalling for merging configs

- cmd/helpers/helper.go
- cmd/merge/main.go
- cmd/restrictions/main.go
- config/config_test.go
This PR removes the use of ioutil package as it has been deprecated since Go 1.16
> Migrating away from deprecated ioutil

- config/kubernetes/org.yaml
I am currently an active member of the Kubernetes-SIGs org and need org access to the Kubernetes org.
related works:
- https://github.com/kubernetes/k8s.io/pull/5798
- https://github.com/kubernetes/k8s.io/pull/5775
- https://github.com/kubernetes/org/issues/4387
- https://github.com/kubernetes/k8s.io/issues/5774
> Add zwpaper to kubernetes org

- config/kubernetes/sig-release/teams.yaml
Part of https://github.com/kubernetes/sig-release/issues/2313
PR updates the `milestone-maintainers`, `release-team`, `release-team-leads`,  `sig-release` github teams for  1.29 Release Team members.
cc: https://github.com/orgs/kubernetes/teams/release-team-leads, @salaxander
> [1.29] update milestone-maintainers, release-team, release-team-leads,  sig-release github teams

- config/kubernetes/sig-cloud-provider/teams.yaml
Ref: https://github.com/kubernetes/org/issues/4438
> sig-cloud-provider: add teams for cloud-pv-admission-labeler repo

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
- config/kubernetes/sig-cloud-provider/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4438
The PR does following in order to fix the failing `post-org-peribolos` CI Job - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-org-peribolos/1701202482555785216
- correctly add the GitHub teams and the respective repo perms for new [cloud-pv-admission-labeler](https://github.com/kubernetes-sigs/cloud-pv-admission-labeler) repo under path - `config/kubernetes-sigs/sig-cloud-provider`.
- revert the changes from PR - https://github.com/kubernetes/org/pull/4445 (53950cf3)
- update `config/restrictions.yaml` to whitelist the new repo.
> sig-cloud-provider: add teams for k-sigs/cloud-pv-admission-labeler repo

- config/kubernetes/sig-scheduling/teams.yaml
Ref: https://github.com/kubernetes/kubernetes/pull/119396#issuecomment-1717022820
---
Sometimes, we want to ping approvers only especially when we want to ask for `/approve`.
I always do that with @ kubernetes/sig-scheduling-leads + @ kerthcet ([example](https://github.com/kubernetes/kubernetes/pull/119396#pullrequestreview-1623468480)), it's easier to have a group for approvers for such cases.
---
Also, we have several teams with the same members. This PR also removes them, and only keeps sig-scheduling-leads, sig-scheduling-approvers and sig-scheduling-misc.
> Add sig-scheduling-approvers and cleanup teams

- config/kubernetes/sig-release/teams.yaml
This PR adds the 1.29 Release sub-teams role shadows to the `release-team-*` github teams (child of parent team - `release-team`)
cc: @kubernetes/sig-release-leads, @kubernetes/release-team, @salaxander
> [1.29] add release sub-teams role shadow to release-team-* gh team

- config/kubernetes-sigs/org.yaml
I'm working on OSS CVE automation for pdcsi and filestorecsi, admin permission is required for me (tyuchn@) to set up depandabot, github action, etc.
> Grant tyuchn@ admin access to pdcsi and filestorecsi repo

- OWNERS_ALIASES
- config/kubernetes/org.yaml
(Part of https://github.com/kubernetes/steering/issues/273.)
Add:
- Maciej Szulik - @soltysh
- Paco Xu 徐俊杰 - @pacoxu
- Patrick Ohly - @pohly
Now Emeritus:
- Carlos Tadeu Panato Jr. - @cpanato
- Christoph Blecker - @cblecker
- Tim Pepper - @tpepper
Thanks to all of the Emeritus members for your service and welcome to the new Steering Committee members!
/assign @mrbobbytables @BenTheElder @palnabarun 
/cc @kubernetes/steering-committee 
/hold
> Update Steering members following 2023 election cycle

- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
Since we do branch-based development of each week's edition, they need to be admins in order to create new editions. 
/sig contributor-experience
> Add Sreeram and Fyka to LWKD admins

- config/kubernetes/sig-node/teams.yaml
A group dedicated for maintaining all tests on https://testgrid.k8s.io/sig-node-cri-o.
/cc @haircommander @harche @rphillips @sairameshv @kannon92 @kwilczynski
Anyone else I forgot to add to the group?
> Add `sig-node-cri-o-test-maintainers` group

- config/kubernetes-sigs/org.yaml
We are adding Prow source owners as members of the @kubernetes-sigs org. This would resolve [issue #68](https://github.com/kubernetes-sigs/prow/issues/68)
> Add prow owners as members

- config/kubernetes-sigs/org.yaml
@ellistarn is an existing member of `kubernetes` org. 
This PR is to extend their membership to `kubernetes-sigs` org as well.
> add ellistarn to kubernetes-sigs

- config/kubernetes/sig-contributor-experience/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Ref: https://github.com/kubernetes/community/issues/7623
/assign @kubernetes/sig-contributor-experience-leads
> config: phase out contribex leads

- config/kubernetes-sigs/org.yaml
@tallaxes is an existing member of `kubernetes` org. 
This PR is to extend their membership to `kubernetes-sigs` org as well.
> add tallaxes to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-autoscaling/OWNERS
- config/kubernetes-sigs/sig-autoscaling/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4562
/assign @kubernetes/owners
> sig-autoscaling: add teams for karpenter repo

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-windows/teams.yaml
Changing OWNER_ALIAS and SIG-Windows team permissions
Relates to https://github.com/kubernetes/community/issues/7614
> Changing Jay Vyas to Amim Knabben for SIG-Windows repo access

- config/kubernetes-sigs/sig-release/teams.yaml
- config/restrictions.yaml
Part of https://github.com/kubernetes/org/issues/4170
/assign @kubernetes/sig-release-leads 
> sig-release: add github teams for release-actions repo

- config/kubernetes-sigs/org.yaml
I'm working on OSS CVE automation for pdcsi and filestorecsi, admin permission is required for me (songjiaxun@) to set up depandabot, github action, etc.
> Grant songjiaxun@ admin access to pdcsi and filestorecsi repo

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This PR updates the release team users  for the new Cluster API release v1.7 team.
> Update capi v1.7 release team members

- config/kubernetes/sig-docs/teams.yaml
Remove v1.29 Docs shadows from website-milestone-maintainers, aside from @drewhagen (v1.30 Docs Lead)
cc: @kubernetes/sig-docs-leads
> Remove 1.29 docs shadows from SIG Docs team

- config/kubernetes/sig-release/teams.yaml
Initial PR to add RT Lead and Subteam Leads for v1.30.
> Add 1.30 Release Team Permissions

- config/kubernetes-sigs/sig-release/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4550
/assign @kubernetes/sig-release-leads
> sig-release: add team repo permissions for obscli

- config/kubernetes-sigs/org.yaml
Already Part of [Kubernetes Org](https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L1013)
Working on multiple parts of [sig-kubernetes/lwkd](https://github.com/kubernetes-sigs/lwkd) being part of the Org would help to ease the work.
> Add mfahlandt to kubernetes-sigs org

- config/kubernetes/sig-architecture/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Adds RT lead shadows and subteam leads to milestone maintainers, and enhancements lead to the SIG Arch team.
Removes members from previous cycles.
> [1.30] Add Leads to Milestone Maintainers 

- config/kubernetes-sigs/sig-network/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4640
**Note:** [@mikezappa87](https://github.com/mikezappa87) is not a member of kuberntes-sigs org at the moment, so the tool doesn't allow to add them as member in the GH teams.
> sig network: add teams for node-ipam-controller repo

- config/kubernetes/sig-release/teams.yaml
As the 1.30 Enhancements Team is now formed, this PR adds them to  `release-team` and `release-team-enhancements`.
> add 1.30 Enhancements Team

- config/kubernetes/sig-docs/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Add 1.30 Docs Shadows to sig-docs and sig-release teams
/assign @katcosgrove @gracenng @neoaggelos @ramrodo @sanchita-07 @fsmunoz
> Add 1.30 Docs Shadows to GitHub teams

- config/kubernetes/sig-release/teams.yaml
What type of PR is this:
What this PR does / why we need it:
Add 1.30 Comms Shadows to sig-release team
/assign @katcosgrove @gracenng @neoaggelos @ramrodo @sanchita-07 @fsmunoz
> Add 1.30 Comms shadows to github teams

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-docs/teams.yaml
Remove `kbhawkey` from sig-docs-leads and reference-docs-maintainers.
> remove kbhawkey from sig docs leads

- config/kubernetes-sigs/sig-network/teams.yaml
Updates the admin members for [Blixt](https://github.com/kubernetes-sigs/blixt) to adjust for recent changes in [maintainers](https://github.com/kubernetes-sigs/blixt/commit/07e7e8c9383dac0647d91b5e0d1f53aa94a1d0a7).
> chore: update sig-network team.yaml for blixt project admins

- config/kubernetes-client/OWNERS
- config/kubernetes-csi/OWNERS
- config/kubernetes-sigs/OWNERS
- config/kubernetes/OWNERS
This PR promotes @jasonbraganza to approver for all active Kubernetes orgs! 🎉
@jasonbraganza has been consistently managing the influx of new org membership requests with thorough reviews over the past several months.
The decision was discussed in the GitHub Admin group, with many +1 votes.
Additionally, the PR rotates the previous cohort of NMC, adding them as emeritus.
Thank you @savitharaghunathan, for all your work in the NMC role :pray: 
/hold
for ack by other approvers
/cc @kubernetes/owners
/assign  @cblecker @MadhavJivrajani @mrbobbytables @nikhita @palnabarun
_PS: while onboarding @jasonbraganza as NMC earlier, the step to add them as reviewer was missed. PR address that change as well._
> NMC: promote jasonbraganza as approver for active orgs

- config/etcd-io/OWNERS
- config/etcd-io/org.yaml
- config/restrictions.yaml
This adds the etcd-io org under administration
> Add etcd-io org

- config/kubernetes-sigs/org.yaml
Already Part of [Kubernetes Org](https://github.com/kubernetes/org/blob/ee69123fa1b1fd6a670ae4d63ac62bde9a919e39/config/kubernetes/org.yaml#L1621)
For work with knftables, kind, and others...?
> Add uablrek to kubernetes-sigs org

- config/kubernetes/sig-network/teams.yaml
Antonio and I were added to the `sig-network-leads` _group_ but not the `sig-network-leads` _team_ I guess? Which apparently means we can't set `lead-opted-in` on KEPs? (https://github.com/kubernetes/enhancements/issues/784#issuecomment-1924751192)
/assign @thockin 
cc @shaneutt @MikeZappa87 @aojea
> update sig-network-leads team

- config/kubernetes/org.yaml
Add mneverov as org member of kubernetes. Required to define him as owner of the prowjobs in https://github.com/kubernetes/test-infra
> add mneverov to kubernetes org

- .github/ISSUE_TEMPLATE/membership.yml
- .github/ISSUE_TEMPLATE/repo-create.yml
In https://github.com/kubernetes/org/pull/4498 we added the `etcd-io` org following the creation of [sig-etcd](https://kubernetes.io/blog/2023/11/07/introducing-sig-etcd/).
This is a quick follow-up to ensure the repo templates work for managing the etcd-io org.
> Add etcd-io org to repo templates

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Syncs up the team members for `cluster-api-addon-provider-helm` with current reality in [cluster-api-addon-provider-helm](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/main/OWNERS_ALIASES).
/cc @jackfrancis @Jont828
> Update team members for CAAPH

- config/kubernetes-sigs/org.yaml
I'm already a member of [kubernetes org](https://github.com/orgs/kubernetes/people?query=jongwooo). Ref:
https://github.com/kubernetes/org/blob/65a1623176b091db0561973de7430cefdcea170a/config/kubernetes/org.yaml#L780
I'm starting to contribute to kubernetes-sigs org(image-builder, gateway-api, etc..). This PR is to extend my membership to kubernetes-sigs org as well.
> Add jongwooo to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
I'm already a member of kubernetes org and I'm starting to contribute to Kubernetes upstream contributing training event which uses https://github.com/kubernetes-sigs/contributor-playground repository
> add nasa9084 to kubernetes-sigs

- cmd/korg/korg.go
- hack/default-branches-report.sh
This PR:
- updates the `korg` tool to add etcd-io as a valid org
> Update korg tool to recognise etcd-io org

- config/etcd-io/org.yaml
Fixes https://github.com/kubernetes/org/issues/4763.
/hold
Hold pending https://github.com/kubernetes/org/pull/4765.
This pr will be the first test of using k/org automation to add new etcd-io org members.
cc @ahrtr, @serathius, @wenjiaswe
> Add erikgrinaker to etcd-io members

- config/kubernetes-sigs/sig-testing/teams.yaml
e2e-framework Owners : https://github.com/kubernetes-sigs/e2e-framework/blob/main/OWNERS
/assign @aojea @BenTheElder @vladimirvivien
> update e2e-framework github team to reflect the actual members

- config/kubernetes-sigs/org.yaml
This add write permissions for @pwschuurman to [gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) and [gcp-filestore-csi-driver](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver) repositories.
> Add pwschuurman as maintainer to pdcsi and filestorecsi github repos

- config/etcd-io/org.yaml
We (etcd auger maintainers) are having issues figuring out why github actions workflows are not running on the `etcd-io/auger` repository so need to temporarily increase the permissions the `maintainers-auger` team has until we can get to the bottom of it.
Relates to: https://github.com/etcd-io/auger/pull/12 
cc @wenjiaswe, @siyuanfoundation
> Grant admin permisssion for auger to maintainers-auger team

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-architecture/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4705
This PR also adds in members who are listed as admins/maintainers in the above issue to the kubernetes-sigs org since they are already part of one of the other Kubernetes orgs.
/assign @Priyankasaggu11929
> config: setup apisnoop repo

- config/kubernetes-csi/org.yaml
Adds self to the kubernetes-csi org.
I am already a member of the kubernetes and kubernetes-sigs GitHub orgs.
> Add torredil to kubernetes-csi org

- config/kubernetes-sigs/sig-apps/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4737
/assign @kubernetes/sig-apps-leads 
> sig apps: add team repo permissions for lws repo

- config/kubernetes-sigs/org.yaml
Add write permissions for @amacaskill to  [gcp-filestore-csi-driver](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver) repository.
> Add amacaskill as maintainer to filestorecsi github repos

- config/kubernetes/sig-docs/teams.yaml
This pull request adds myself as an approver (`sig-docs-en-owners`) for the English language. I have already been included in the [OWNERS file (here)](https://github.com/kubernetes/website/blob/865021d2879dcec49cd3df64c9a384cbda6933f5/OWNERS_ALIASES#L27) under [k/website](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES) and have been actively participating in PR approvals as usual. Adding myself here to ensure consistency across the board.
> Add dipesh-rawat to sig-docs-en-owners

- .github/ISSUE_TEMPLATE/membership.yml
Adds 2 items to suggest that users ensure their affiliation is up to date. It is not required, but preferred.
/hold
> Add suggested affiliation check to membership template

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-instrumentation/teams.yaml
- config/kubernetes/sig-instrumentation/teams.yaml
I've removed myself from the alias/team for Instrumentation leads as well as repos I am not active in. POLA, etc.
/cc @kubernetes/sig-instrumentation-leads
> Remove ehashman as SIG Instrumentation lead

- config/etcd-io/org.yaml
Following https://github.com/etcd-io/website/pull/816 and https://github.com/kubernetes/org/pull/4838 this pull request adds me to the etcd website maintainers team.
Also added a second commit to tidy up some permissions to reflect emeritus maintainers that are no longer active or listed in `OWNERS` files as approvers.
> Update etcd website maintainers

- hack/add-members.sh
`go run` now works very well and avoids the path dependency.
> chore: do not require gobin to be in path

- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
Per approval, here: https://github.com/kubernetes-sigs/lwkd/pull/326
Mario needs to be an admin, because that's the only way for folks to add feature branches.
> Add Mario Fahland to LWKD owners.

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Syncs up maintainers with the [OWNERS_ALIASES](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/main/OWNERS_ALIASES) in CAAPH. Specifically, @mboersma moves to maintainer from reviewer.
/assign @Jont828
> Sync CAAPH maintainers

- config/kubernetes-sigs/sig-aws/teams.yaml
Add seanzatzdev-amazon as an admin/maintainer of the AWS EFS CSI Driver
See AWS EFS CSI Driver OWNERS File here:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/OWNERS
> Add seanzatzdev-amazon as member/efs-csi admin/maintainer

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes: #4827 
fixes: #4831
fixes: #4834
fixes: #4835
fixes: #4836
fixes: #4841
fixes: #4845
fixes: #4847 
fixes: #4848 
fixes: #4855 
fixes: #4857 
fixes: #4859 
fixes: #4860 
fixes: #4864
fixes: #4865
fixes: #4866
fixes: #4877
fixes: #4867
> Add members 20240403

- Makefile
- admin/update.sh
This PR updates two things:
- Updates the prow source code location to the new repo
- Sets a variable to configure the number of hourly tokens we consume for peribolos. This should drastically speed up execution.
> Update prow location and rate limit

- config/kubernetes/sig-release/teams.yaml
I'd like to use the /milestone command to organize issues and PRs, in particular for the DRA work.
https://github.com/orgs/kubernetes/projects/95 would benefit from having proper milestones on the items listed there.
> milestone-maintainers: add pohly

- Makefile
As @BenTheElder pointed out https://github.com/kubernetes/org/pull/4887#discussion_r1569209311, it's better for us to use the pseudo version for the main branch, as opposed to the "latest" tag, in the case that the prow repo starts using versioned tags in the future.
> Use main branch instead of latest

- config/kubernetes-sigs/org.yaml
Recently I have been contributing to https://github.com/kubernetes-sigs/prow, but am not a member of kubernetes-sigs org yet, which makes other kubernetes-sigs members comment `/ok-to-test` every time to trigger the CI tests of my PRs.
Hence I want to be a member of kubernetes-sigs org by opening this PR.
(I am already a member of kubernetes org.)
PTAL!
> Add jihoon-seo to kubernetes-sigs org

- config/kubernetes-sigs/sig-network/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4856
> sig-network: add team repo permissions for kube-network-policies repo

- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
PR adds the  `sig-contributor-experience` GH team & sub-teams to kubernetes-sigs org.
Derived from: https://github.com/kubernetes/org/blob/747db2142f493cdaf7cfa52535dc1cab0d0bc853/config/kubernetes/sig-contributor-experience/teams.yaml#L102-L155
> add sig-contributor-experience GH team & sub-teams to k-sigs org

- config/kubernetes/sig-docs/teams.yaml
- Remove me from website-maintainers
- Remove 1.30 shadows except for @Princesso (1.31 release docs lead) from website-milestone-maintainers
/cc @kubernetes/sig-docs-leads
> Remove 1.30 shadows from sig docs team

- config/kubernetes/org.yaml
Adding #4904 
Fixes #4904
Following example from https://github.com/kubernetes/org/pull/4905
Just to expedite the merge of WG Serving charter.
> added terrytangyuan as an org member

- config/kubernetes-sigs/sig-storage/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4875
/assign @kubernetes/sig-storage-leads 
> sig-storage: remove container-object-storage-interface-csi-adapter teams for repo archival

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/4904. This was missed in https://github.com/kubernetes/org/pull/4917.
/cc @SergeyKanzhelev @mrbobbytables
> Add terrytangyuan as an kubernetes-sigs org member

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This PR updates the release team users for the new Cluster API release v1.8 team.
> Update capi v1.8 release team members

- config/kubernetes/sig-docs/teams.yaml
ref. https://github.com/kubernetes/website/pull/46053
- Add @Okabe-Junya to `sig-docs-ja-reviewer`
FYI:
- merged PRs (k/website): https://github.com/pulls?q=is%3Amerged+is%3Apr+author%3AOkabe-Junya+archived%3Afalse+repo%3Akubernetes%2Fwebsite (20+)
- reviewed PRs (k/website): https://github.com/pulls?q=is%3Apr+reviewed-by%3AOkabe-Junya+repo%3Akubernetes%2Fwebsite+ (35+)
This pr is sponsored by @nasa9084 @bells17
> Add Okabe-Junya to `sig-docs-ja-reviewer`

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-autoscaling/teams.yaml
- config/kubernetes/sig-autoscaling/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Relates to https://github.com/kubernetes/community/issues/7834
Also standardised casing on @MaciekPytel's handle.
Have currently left @mwielgus as a member `sig-autoscaling-api-reviews` as the current lone approver for the core HPA API code.
> SIG Autoscaling - Leads Update

- config/kubernetes-csi/org.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/4874
/assign @kubernetes/sig-storage-leads 
> sig-storage: add team repo permissions for external-snapshot-metadata repo

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> add raywainman to kubernetes-sigs, kubernetes

- config/kubernetes-sigs/sig-testing/teams.yaml
to reflect: https://github.com/kubernetes-sigs/e2e-framework/blob/main/OWNERS
/assign @vladimirvivien
> update e2e-framework team

- config/kubernetes-sigs/org.yaml
This add write permissions for @Sneha-at  to [gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) and [gcp-filestore-csi-driver](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver) repositories.
> Add to maintainers list for pdcsi and filestorecsi repos

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Syncs up with recent changes to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/OWNERS_ALIASES
Specifically, adds @Jont828 and @willie-yao to admins/maintainers.
/cc @jackfrancis @Jont828 @nojnhuh
> Sync CAPZ admins with Azure provider project

- README.md
- config/etcd-io/org.yaml
The PR corrects a typo in the "GitHub" company name.
Additionally, repo's description should be fixed:
> Fix typo in the GitHub word

- config/kubernetes-sigs/org.yaml
- Add @Okabe-Junya to kubernetes-sigs
I am already part of the Kubernetes org, so I add myself directly
> However, if you are already part of the Kubernetes organization, you do not need to do this and can add yourself directly to the appropriate files.
> Add Okabe-Junya to kubernetes-sigs

- config/etcd-io/org.yaml
`thelinuxfoundation` is the LF's bot account which has ownership of all CNCF projects. 
In particular, it's needed at this point in order to add etcd to LFX Insights via a GitHub app. 
This is a follow up to a discussion with @mrbobbytables @palnabarun @Priyankasaggu11929 and @MadhavJivrajani on Monday May 20.
> Add thelinuxfoundation to etcd org

- config/kubernetes/org.yaml
We haven't done feature branches in quite a while. lavalamp@ has stepped down from several roles as well (thanks!)
let's cleanup this group as it has admin rights to k/k repository
> drop kubernetes-feature-branch-admins group with admin rights to k/k

- config/kubernetes-sigs/org.yaml
Adding myself to the kubernetes-sigs org for my role as a SIG Docs tech lead
> Add katcosgrove to kubernetes-sigs org

- config/kubernetes/org.yaml
Hello :wave:,
I am planning to contribute to some kubernetes KEP very soon and as I am already a kubernetes-sigs member and that the org membership is equivalent I figured it could be nice to be added to the kubernetes org beforehand! Let me know if that's ok :pray:!
> Add MrFreezeex to kubernetes org members

- config/kubernetes/sig-release/teams.yaml
Follow up on #4936, add release branch manager to `release-team`, `release-team-leads`, `milestone-maintainers`
Ref https://github.com/kubernetes/sig-release/issues/2517#issuecomment-2145887205
cc @katcosgrove @gracenng @Priyankasaggu11929
> Add 1.31 release branch manager permissions

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Hi all, 
@VannTen has been a core maintainer of [kubernetes-sigs/kubespray ](https://github.com/kubernetes-sigs/kubespray)some time now, and he made significant contribution🥳.
It will help us manging the repo/issues to add him to our github team !  
Best,
Antoine
> Kubespray/maintainers: add VannTeen

- config/kubernetes-sigs/org.yaml
Hi, I'm an active member of the kubernetes org: 
https://github.com/kubernetes/org/blob/08250771502b06ca101e6f188ebbcbb8e54681b9/config/kubernetes/org.yaml#L132
and I am requesting membership in kubernetes-sigs based on the instructions in https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem:
> If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly or [opening an issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) against the kubernetes/org repo, as above.
> Add benluddy to kubernetes-sigs

- config/kubernetes/sig-docs/teams.yaml
@kirkonru has formally joined the organisation (#4757), and we want to have him in sig-docs-ru, so he will be able to review the Russian-related PRs for the website.
> Add kirkonru to sig-docs-ru

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This was proposed and approved here:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2115/
> Add EmilienM to CAPO admins

- config/kubernetes/org.yaml
Also add @puerco to maintainers as configured in the project's code owners and remove @aledbf  and @bowei as they stepped back from their role some time ago. See https://github.com/kubernetes/ingress-nginx/blob/main/OWNERS.
> Ingress NGINX: Promote Gacko to admin.

- OWNERS_ALIASES
- config/kubernetes-nightly/sig-release/OWNERS
- config/kubernetes-sigs/sig-release/OWNERS
- config/kubernetes/sig-release/OWNERS
Part of https://github.com/kubernetes/sig-release/issues/2516.
Context: There are some existing PRs e.g., https://github.com/kubernetes/org/pull/4797, https://github.com/kubernetes/org/pull/4964 that could be reviewed/approved by subproject leads, now that the role exists.
cc: @kubernetes/sig-release-leads @gracenng @katcosgrove @xmudrii
> sig-release: Add subproject leads as reviewers/approvers

- config/kubernetes/sig-docs/teams.yaml
This pull request adds myself as part of  `sig-docs-hi-owners` and `sig-docs-hi-reviews` for the Hindi language. These changes already been included in the [OWNERS file (here)](https://github.com/kubernetes/website/blob/6efe7f32137ccc08ff0f33ccc7d484fa7af9d13f/OWNERS_ALIASES#L100-L107) under [k/website](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES) as part of PR [kubernetes/website#46573](https://github.com/kubernetes/website/pull/46573/files) and I have been actively participating in PR reviews and approvals as usual. Adding myself here to ensure consistency across the board.
> Add dipesh-rawat to sig-docs-hi-owners and sig-docs-hi-reviews

- go.mod
- specify go patch version to clarify forwards compatibility
[Go 1.21 Release Notes](https://tip.golang.org/doc/go1.21)
> To improve forwards compatibility, Go 1.21 now reads the go line in a go.work or go.mod file as a strict minimum requirement: go 1.21.0 means that the workspace or module cannot be used with Go 1.20 or with Go 1.21rc1. This allows projects that depend on fixes made in later versions of Go to ensure that they are not used with earlier versions. It also gives better error reporting for projects that make use of new Go features: when the problem is that a newer Go version is needed, that problem is reported clearly, instead of attempting to build the code and printing errors about unresolved imports or syntax errors.
> chore: specify go patch version

- config/etcd-io/sig-etcd/teams.yaml
To edit an incorrect security advisory repo admin permission is required. Refer:
- https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/editing-a-repository-security-advisory
- https://docs.google.com/document/d/1Pl2e8YTtgt3pYeIZSXJIn4gknp6tTW14htMat1JaM4k
- https://github.com/etcd-io/etcd/security/advisories/GHSA-5x4g-q5rc-36jp
This commit will be reverted once the remedial work is done.
> Grant maintainers-etcd admin permission on etcd-io/etcd

- config/etcd-io/sig-etcd/teams.yaml
This reverts commit efc4526d26f10962c6f31aa83fbc858393b5a105.
The remedial repo admin work has now been completed so we can return to least required day to day privilege of `maintain`.
> Revert "Grant maintainers-etcd admin permission on etcd-io/etcd"

- config/kubernetes-sigs/sig-security/teams.yaml
lol
follow up from https://github.com/kubernetes/org/pull/5049
Ref https://github.com/kubernetes/org/issues/4873
/assign @Priyankasaggu11929
> fix repo name for cve-feed-osv repo

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- config/restrictions.yaml
https://sigs.k8s.io/etcdadm is being archived
- https://github.com/kubernetes/org/issues/5013
> config: cleanup etcdadm teams

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-multicluster/teams.yaml
- config/kubernetes/sig-multicluster/teams.yaml
pmorie moving to emeritus, skitt becoming co-chair, jeremyot unchanged; see
https://groups.google.com/g/kubernetes-sig-multicluster/c/xhj2OnFO-8M for the discussion and lazy consensus (deadline July 1, 2024).
> SIG-MC leadership change: pmorie emeritus, skitt co-chair

- config/kubernetes/sig-release/teams.yaml
@drewhagen and @sanchita-07 have joined the release signal team as shadows stepped down.
> Add drewhagen and sanchita-07 to release-team-release-signal

- config/kubernetes/sig-docs/teams.yaml
I inadvertently omitted adding myself to the website-maintainers team.
- https://github.com/kubernetes/org/pull/5006
/cc @inductor 
Could you please comment with a `:+1:` message?
https://kubernetes.slack.com/archives/CAG2M83S8/p1719848352505059?thread_ts=1719817449.041639&cid=CAG2M83S8
> Add bells17 to website-maintainers team

- config/kubernetes-sigs/sig-network/teams.yaml
As per the [mailing list discussion](https://groups.google.com/g/kubernetes-sig-network/c/nFN64I33zUo), this adds @mlavacca as a Gateway API maintainer.
The project-specific PR for this update is https://github.com/kubernetes-sigs/gateway-api/pull/3231
This also removes bowei while we're in here, who was a historical maintainer but no longer an active one.
> docs: add Mattia Lavacca as a Gateway API maintainer

- config/etcd-io/sig-etcd/teams.yaml
So that we can fix the branch protection settings for `etcd-io/etcd` as discussed in maintainer slack.
Permissions to be reverted to `maintain` via subsequent pr after updates made.
cc @serathius, @ahrtr, @wenjiaswe
> Temporarily elevate `maintainers-etcd` team permissions

- config/etcd-io/sig-etcd/teams.yaml
This reverts commit 2c459d858f267575d2a0473fbcdcef82dbb9e7b0 as the needed GitHub settings tweaks have been applied so we can revert to least privilege permissions.
cc @wenjiaswe, @ahrtr, @serathius
> Revert "Temporarily elevate etcd maintainer permissions."

- config/kubernetes/sig-docs/teams.yaml
xref https://github.com/kubernetes/website/pull/47301
- Add @Okabe-Junya (myself) to `sig-docs-ja-owners`
- merged PR (labeled `language/ja`): [35+](https://github.com/pulls?q=is%3Amerged+is%3Apr+author%3AOkabe-Junya+archived%3Afalse+repo%3Akubernetes%2Fwebsite+label%3Alanguage%2Fja+)
- reviewed PR (labeled `language/ja`): [85+](https://github.com/pulls?q=is%3Apr+reviewed-by%3AOkabe-Junya+archived%3Afalse+repo%3Akubernetes%2Fwebsite+label%3A%22language%2Fja%22)
- exactly three months since I became a reviewer: https://github.com/kubernetes/org/pull/4922
> Add Okabe-Junya to sig-docs-ja-owners

- config/etcd-io/sig-etcd/teams.yaml
We (sig-etcd leads) are creating a new GitHub team within our etcd-io org for the release team. 
The members of this team will act as leads or advisors for upcoming etcd releases, on an agreed rotation and have repository write permissions to carry out `etcd-io/etcd` releases.
Historically etcd releases have only been carried out by maintainers which is challenging due to our currently small number of project maintainers. We've been gradually making improvements over time to address this, through improving our release processes, introducing release shadow roles and rotating the release manager for each release.
We now think the time is right to extend the release team beyond maintainers, to also include reviewers, as reviewers are all future maintainers for etcd that we have a lot of …
> Add etcd release team

- config/kubernetes/sig-node/teams.yaml
Adding to the following groups:
- `sig-node-bugs`
- `sig-node-cri-o-test-maintainers`
- `sig-node-feature-requests`
- `sig-node-pr-reviews`
- `sig-node-proposals`
PTAL @kwilczynski 
/assign @mrunalp
> Add kwilczynski to SIG Node groups

- config/kubernetes/sig-docs/teams.yaml
Temporary adding myself to the website-maintainers team for write access to k/website repo for the release preparation tasks. (Note that the 1.31 docs lead is out sick, so I'll be standing in to help with some tasks leading up to the release)
@katcosgrove will help with sync tasks during Release Day itself, but I'll be around to prepare the day before and pick up any async stuff.
Thanks!
/assign @reylejano @natalisucks @salaxander
> Add drewhagen to website-maintainers team for 1.31 release

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
New CAPI v1.9 RT members announced here: https://kubernetes.slack.com/archives/C8TSNPY4T/p1723216277709389
This PR removes old and adds new v1.9 RT members from/to the list in alphabetical order
> Update capi v1.9 release team members

- config/kubernetes-sigs/org.yaml
Adding myself _(`dipesh-rawat`)_ to the kubernetes-sigs org.
I’m already a member of the Kubernetes organization.
https://github.com/kubernetes/org/blob/4dcd914f4c1b622d2c29e9123a7488ba205839a6/config/kubernetes/org.yaml#L286
> Add dipesh-rawat to kubernetes-sigs

- config/kubernetes-sigs/sig-scheduling/teams.yaml
@mimowo has been an approver for the project since June (https://github.com/kubernetes-sigs/kueue/pull/2351) and I think he's ready to take more responsibilities
/assign @tenzen-y
> Add mimowo and remove ahg-g from Kueue admins

- config/etcd-io/sig-etcd/teams.yaml
Tomorrow we are releasing etcd v3.5.16.
Part of: https://github.com/etcd-io/etcd/issues/18485
Elevated permissions required as per https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/release.md#release-steps
Permissions will be returned to normal after release completed by a subsequent pr.
cc @serathius, @ahrtr, @ivanvc
> Elevate etcd team permissions for release window

- config/kubernetes/sig-release/teams.yaml
👋 Hello, I'd like to be able to use [certain commands](https://github.com/kubernetes/enhancements/issues/2305#issuecomment-1902271611), as well as edit descriptions for outstanding issues (that come under the SIG) in `k/enhancements` which have inactive author(s) who've left.
I believe adding myself to the `milestone-maintainers` list should address this.
> Add `rexagod` to `milestone-maintainers`

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Adds a new maintainer group for the  k-sigs/cluster-api-ipam-provider-in-cluster repo to give write access to @mcbenjemaa.
> Add mcbenjemaa as cluster-api-ipam-provider-in-cluster maintainer

- config/etcd-io/sig-etcd/teams.yaml
Reverts permissions now that the release of etcd `v3.5.16` and `v3.4.34` has been completed to return to bau least privilege settings.
cc @ahrtr, @ivanvc
> Revert "Elevate etcd team permissions for release window"

- config/kubernetes/sig-architecture/teams.yaml
- config/kubernetes/sig-release/teams.yaml
This PR adds the members of the enhancements team to the appropriate groups for their role. 
cc @fsmunoz @katcosgrove @gracenng
> Add enhancements team for 1.32 to appropriate groups

- config/kubernetes/sig-release/teams.yaml
per release signal handbook, adding experienced shadows to milestone maintainers; also adding rest of the team to release-signal team
cc:
@fsmunoz
@katcosgrove
@gracenng 
/hold in case we want to merge all updates to teams.yaml in one PR - this commit contains the changes we need for Release Signal specifically.
> Adding Release Signal Shadows

- config/kubernetes-sigs/sig-network/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/5121
> sig-network: add gh teams for gwctl repo

- config/kubernetes/sig-docs/teams.yaml
Add 1.32 Docs Shadows to `website-milestone-maintainers` in sig-docs/teams.yaml
> Add 1.32 RT Docs team to website milestone maintainers

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
This updates the CAPA maintainers group with recent changes.
Relates: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5119
Relates: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5082
Relates: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5081
> chore: update capa group

- config/kubernetes/sig-instrumentation/teams.yaml
@fpetkovski became an emeritus maintainer a [while ago](https://github.com/kubernetes/kube-state-metrics/commit/dc679e1b3afc94005f1a99ec33cfdffec5ff13da), removing access to the repo here. 
CC: @rexagod @dgrisonnet @logicalhan @dashpole
> Remove fpetkovski from kube-state-metrics groups

- config/kubernetes-sigs/org.yaml
I was already added to kubernetes org https://github.com/kubernetes/org/pull/5012 and want to join the kubernetes-sig
> Add kmala to kubernetes-sigs

- config/kubernetes/sig-release/teams.yaml
Partially address https://github.com/kubernetes/community/issues/8103.
Adding Kevin to milestone maintainer as part of his wg-batch role.
> Update teams.yaml for wg-batch organizer change

- config/kubernetes-sigs/sig-network/teams.yaml
- config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5228
> sig-network: add gh teams for cni-dra-driver repo

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
ref: https://github.com/kubernetes/org/issues/5228
PR also adds @MikeZappa87 to the `kubernetes-sigs` ([existing member of kubernetes org](https://github.com/kubernetes/org/blob/576889959d93738483ec72371f378eb15f6adb34/config/kubernetes/org.yaml#L731))
/assign @kubernetes/sig-network-leads
> sig-network: add MikeZappa87 to cni-dra-driver gh teams

- config/kubernetes/org.yaml
- config/kubernetes/sig-architecture/teams.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
Addressing failing peribolos CI jobs – https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-org-peribolos/1854208102841192448
Refer below slack thread, providing context and confirmation for org membership removal – https://kubernetes.slack.com/archives/C01672LSZL0/p1730967827429449?thread_ts=1730734412.432269&cid=C01672LSZL0
> Update org membership – LappleApple

- config/etcd-io/sig-etcd/teams.yaml
We released today etcd v3.5.17 and v3.4.35. So we can remove the elevated permissions.
Part of:
* etcd-io/etcd#18845
* etcd-io/etcd#18846
Elevated permissions required as per https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/release.md#release-steps
This reverts commit b80bfcfcf6b7410909cf719a6e95ba37b08db56a.
/cc @serathius, @ahrtr, @jmhbnz 
/hold (@jmhbnz, please ensure branch protection is enabled again)
> Revert "Elevate etcd team permissions for release window."

- config/kubernetes-sigs/sig-cli/teams.yaml
The existing maintainers for repo kubectl-validate have all switched jobs and add maintainer to maintain the repo and cut release for existing customers.
> Add maintainer into kubectl-validate repo

- .github/ISSUE_TEMPLATE/repo-create.yml
Clarifies that a repo needs to be owned by a single SIG, and that WGs cannot own repos.
> Add additional note to repo creation template

- config/kubernetes/sig-release/teams.yaml
A release signal shadow has become completely inactive. I have worked with EAs/subproject leads @gracenng @katcosgrove to select a shadow who is eager to support us for the rest of the cycle.
This will help us continue load balancing our sub-team. Thanks for your help, we appreciate it!
cc: @fsmunoz
> updating Release Signal shadows

- config/kubernetes/sig-docs/teams.yaml
ref. https://github.com/kubernetes/website/pull/48864
Feature Description
Add @b1gb4by  to sig-docs-ja-reviewer
FYI:
merged PRs (k/website): 
https://github.com/pulls?q=is%3Amerged+is%3Apr+author%3Ab1gb4by+archived%3Afalse+repo%3Akubernetes%2Fwebsite+ (11+)
reviewed PRs (k/website): 
https://github.com/pulls?q=is%3Apr+reviewed-by%3Ab1gb4by+repo%3Akubernetes%2Fwebsite+ (14+)
This pr is sponsored by @inductor @Okabe-Junya @nasa9084
> Add: Add b1gb4by

- OWNERS_ALIASES
- config/kubernetes/sig-cloud-provider/teams.yaml
- config/kubernetes/sig-release/teams.yaml
this change brings the sig cloud-provider leads information up to date. Andrew Sy Kim and Nick Turner have become emeritus leads, and as such we are removing them from the day-to-day duties related to the leads positions. similarly we are also putting Bridget Kromhout, Walter Fender, and Michael McCune as the current contacts.
this is in support of https://github.com/kubernetes/community/issues/7865
this is a continuation of #4964 
/sig cloud-provider
cc @bridgetkromhout @cheftako @nckturner @andrewsykim
> update sig-cloud-provider owners and leads

- config/kubernetes-sigs/sig-storage/teams.yaml
- config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5238
/assign @kubernetes/sig-storage-leads
> sig-storage: remove container-object-storage-interface-api gh teams

- config/kubernetes-sigs/sig-architecture/teams.yaml
Admin access is needed to maintain Kubernetes conformance on these 2 repos:
- apisnoop
- verify-conformace
Fyi: @mfahlandt @xmudrii @jeefy 
/cc @BobyMCbobs
> Add Kubermatic to apisnoop and verify-conformance repos

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-k8s-infra/teams.yaml
- config/kubernetes/sig-k8s-infra/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/sig-testing/teams.yaml
Add myself (@xmudrii) as a SIG K8s Infra Tech Lead.
**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/community/issues/8204
/assign @BenTheElder @dims @ameukam @upodroid
> Add xmudrii as K8s Infra Tech Lead

- OWNERS_ALIASES
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-instrumentation/teams.yaml
- config/kubernetes/sig-instrumentation/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Issue: https://github.com/kubernetes/community/issues/8149
> Add richabanker to sig-instrumentation-leads

- config/kubernetes-sigs/sig-apps/teams.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
Ref https://github.com/kubernetes/org/issues/5302 and https://github.com/kubernetes/community/pull/8211
> k-sigs: rename and move inference project from sig-apps to sig-net

- config/kubernetes/sig-autoscaling/teams.yaml
The VPA project would like to start using milestones to track PRs and issues for review. In order to do so we need access to manage milestones.
cc'ing @gjtempleton, who is the chair of sig-autoscaling
Note: I'm unsure if this is the correct process, please point me in the right direction if it is not
> Add sig-autoscaling-milestone-maintainers

- config/kubernetes/sig-docs/teams.yaml
This is a cleanup PR for the SIG Docs' teams.yaml after the 1.32 release:
- remove 1.32 release team docs lead from website maintainers
- remove prior release team members from website milestone maintainers
- add the 1.33 release team docs lead as a website milestone maintainer
See https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#clean-up-access for cleanup tasks
cc @chendave @rayandas
> Cleanup SIG Docs teams.yaml after 1.32 release and prepare for 1.33 release

- config/kubernetes-client/org.yaml
This commit adds myself to the javascript-admin team and removes davidgamero as requested.
cc: @brendandburns @davidgamero
> add cjihrig to javascript-admins

- config/etcd-io/sig-etcd/teams.yaml
Follow-on from https://github.com/etcd-io/website/pull/938 to ensure new approver @ivanvc will have the appropriate permissions in our `etcd-io/website` repository.
cc @ivanvc, @serathius, @ahrtr
> Add ivanvc to etcd website maintainers team

- config/kubernetes/sig-autoscaling/teams.yaml
I am owner of several sub-projects in the autoscaler repo. Having this access will allow me to cut releases without having to bug other folks.
> Add raywainman as maintainer/review of autoscaling repo

- config/etcd-io/sig-etcd/teams.yaml
As spotted on https://github.com/etcd-io/etcd-operator/issues/43, the etcd members don't have triage permissions on the etcd-operator repository.
Would this be okay? Or do we want to keep the etcd-operator repository with more independence, and add a new team that has triage permissions?
> etcd: allow etcd-operator triage permission for etcd members

- config/kubernetes/sig-scheduling/teams.yaml
This PR updates sig-scheduling-misc team members based on the current reviewers/approvers:
https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES
I added @dom4ha as well since I think will join the list soon ;)
> fix: update sig-scheduling-misc team

- config/kubernetes-sigs/sig-network/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/5299
cc: @kubernetes/owners 
/assign @kubernetes/sig-network-leads
> sig-network: add github teams for nat64 repo

- config/kubernetes-sigs/sig-network/teams.yaml
Updating github admins to match the list of maintainers created here: https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/203
> Update gw-inference-extension admins to match maintainers

- OWNERS_ALIASES
- config/kubernetes/org.yaml
- config/kubernetes/provider-gcp/OWNERS
- config/kubernetes/provider-gcp/teams.yaml
- config/restrictions.yaml
Create team directory for provider-gcp and move cloud-provider-gcp-* groups there.
Also:
- remove @sdmodi who left the GKE team.
- add @mmamczur, member of the team that owns service controller part of cloupd-provider-gcp
- update OWNER_ALIASES, add a few people as OWNERS, remove @abgworrall since he is no longer at Google
> Create team directory for provider-gcp and update group members

- config/etcd-io/org.yaml
Is kubernetes/kubernetes-sigs github org membership enough to be added here in etcd-io github org? if so, please add me as well. 
thanks!
> add dims to etcd-io

- config/kubernetes/sig-architecture/teams.yaml
- config/kubernetes/sig-release/teams.yaml
This PR adds the members of the 1.33 Enhancements team to the appropriate groups for their role.
cc @npolshakova @neoaggelos @katcosgrove @gracenng
> Add Enhancements team for 1.33 to appropriate groups

- config/kubernetes-sigs/org.yaml
Adding myself to k8s-sigs as a contributor for [kubernetes-sigs/ibm-powervs-block-csi-driver](https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/)
Thanks! 
Ref for k8s org-membership: https://github.com/kubernetes/org/issues/5348
> Add kishen-v to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
We want kick off project and list work items in github and track our progress for Multi-Network project.
PR also adds @mskrocki to the kubernetes-sigs ([existing member of kubernetes org](https://github.com/kubernetes/org/blob/a7941617380cf05064fdfaf4d73420d3c061902e/config/kubernetes/org.yaml#L779))
> Add mskrocki and LionelJouin as admins for multi-network repos.

- config/kubernetes-sigs/org.yaml
I'm a member of kubernetes organization https://github.com/kubernetes/org/blob/b7c61135cc604e6f4f3c4ed643e6975351ea64dd/config/kubernetes/org.yaml#L106.
Since I started actively working on github.com/kubernetes-sigs/lws and github.com/kubernetes-sigs/jobset repositories, this PR adds me into the kubernetes-sigs organization.
> Add ardaguclu to kubernetes-sigs org

- OWNERS_ALIASES
- config/kubernetes/sig-contributor-experience/teams.yaml
Based on the issue [#8304 ](https://github.com/kubernetes/community/issues/8304) add mfahlandt as ne Co Chair for Contributor Experience
> Add mfahlandt as Co Chair for Contributor Experience - update comms

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-storage/teams.yaml
This add write permissions for @tonyzhc to [gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver).
> Add tonyzhc to kubernetes-sigs/sig-storage/gcp-compute-persistent-disk-csi-driver org

- config/etcd-io/sig-etcd/teams.yaml
* De-elevate permissions, as we pushed the v3.4.36 release one week.
* Update the release-etcd team to align with the change in the release process (https://github.com/etcd-io/etcd/pull/19450).
> etcd: Update release-etcd team

- config/etcd-io/sig-etcd/teams.yaml
In preparation for v3.4.36 and v3.6.0-rc.1 releases. Setting the group with me as the only team member to test the new workflow.
/cc @jmhbnz
> etcd: Update release-etcd team for release window

- config/etcd-io/sig-etcd/teams.yaml
Returning the `release-etcd` team members to its empty state after releasing v3.4.36 and v3.6.0-rc.1.
/cc @jmhbnz 
This reverts commit dc557c3c244f2bd278fe026f50877dbab5717bfe.
> Revert "etcd: Update release-etcd team for release window"

- config/kubernetes-sigs/sig-network/teams.yaml
- config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5433
> sig-network: add github teams for network-policy-finalizer repo

- config/etcd-io/sig-etcd/teams.yaml
So that we can maintain the proto docs that get generated and hosted on https://etcd.io
cc @ahrtr, @serathius, @ivanvc
> Give maintainers-website permissions for etcd-io/protodoc

- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
- config/restrictions.yaml
Ref: https://github.com/kubernetes/org/issues/5397
/assign @kubernetes/sig-contributor-experience-leads 
> sig-contribex: remove sigs-github-actions teams for repo archival

- config/etcd-io/org.yaml
/cc @ivanvc @ahrtr 
Ref PR: https://github.com/etcd-io/etcd-operator/pull/96
Also joined the `wg-etcd-operator` group and looking to become a regular contributor, so being an org member would make it easier for me to speed things up.
Thanks!
> add moshevayner to etcd-io

- config/kubernetes/sig-api-machinery/teams.yaml
I noticed the discrepancy when going to ping on https://github.com/kubernetes/test-infra/pull/34210
cc @sttts @kubernetes/sig-api-machinery-leads
> add sttts to sig-api-machinery-leads

- config/kubernetes-sigs/org.yaml
per https://github.com/kubernetes/org/blob/16ac965bebae325e775476a1c80aed414584da8b/config/kubernetes/org.yaml#L126
needed for the descheduler project: https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+reviewed-by%3Aatiratree+is%3Aclosed
> add atiratree to kubernetes-sigs

- config/kubernetes-csi/org.yaml
This commit syncs external-snapshot-metadata repo OWNERS with the corresponding external-snapshot-metadata-maintainers and external-snapshot-metadata-admins teams.
This is required in order for the missing members to be able to create release branches and tag releases.
refer:
- https://github.com/kubernetes-csi/external-snapshot-metadata/blob/main/OWNERS
- https://github.com/orgs/kubernetes-csi/teams/external-snapshot-metadata-maintainers
- https://github.com/orgs/kubernetes-csi/teams/external-snapshot-metadata-admins
- https://github.com/kubernetes/org/issues/4874
> sig-storage: sync team members & OWNERS of external-snapshot-metadata

- cmd/helpers/helper.go
- cmd/restrictions/main.go
- config/config_test.go
- go.mod
- go.sum
Move to standard usage of `sigs.k8s.io/yaml`
> fix: move to sigs.k8s.io/yaml

- config/etcd-io/sig-etcd/teams.yaml
With v3.6.0-rc.3 and v3.5.21 out, we can revert the previous commit and set back the original state of the team members.
/cc @jmhbnz @ahrtr 
This reverts commit 7b957583280150baa9d4851cdbc8394fb532b303.
> etcd: Revert "Update release-etcd team for release window"

- OWNERS_ALIASES
This pull request adds @ivanvc to `sig-etcd-leads` to reflect their new role as co-chair for sig-etcd.
Ivan has been a longstanding trusted sig-etcd community member who was today promoted to co-chair with unanimous support from the current sig-etcd leads. Ivan's promotion will ensure we can support the growth of our sig and continue developing leadership talent within the sig.
cc @wenjiaswe, @serathius, @ahrtr
> Add ivanvc to sig-etcd-leads

- config/etcd-io/sig-etcd/teams.yaml
I'm working on Antithesis integration as proposed in https://github.com/etcd-io/etcd/issues/19299.
We would like to setup a github workflow that calls a third party service with credentials. This should be doable by setting up a secret in github actions as described in https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions. At the moment no etcd maintainer has permissions to do that. 
I get permission I copied the the etcd-operator-admins group and I would like to give `admin` access to SIG etcd leads. 
Can be temporary just for the secret setup.
/cc @ahrtr @jmhbnz @ivanvc @wenjiaswe
> Create a separate group with etcd admin access

- config/kubernetes/org.yaml
Thank you all for operating kubernetes ecosystem!
This PR simply adds myself into `kubernetes` org.
[I am already in the `kubernetes-sigs` org.](https://github.com/orgs/kubernetes-sigs/people?query=HoKim98)
https://github.com/kubernetes/org/blob/dd390f598dc2b2068b87a12e2058446aa6dbb25f/config/kubernetes-sigs/org.yaml#L373
At first, I had no intention of participating in this organization separately, but I ended up participating belatedly to smoothly resolve several existing issues related to the `PodLevelResources` feature gate.
> Add HoKim98 to kubernetes member

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fix https://github.com/kubernetes/org/issues/5535
Fix https://github.com/kubernetes/org/issues/5497 (updating existing org membership - @sftim to @lmktfy)
> Add org members — April 16, 2025

- OWNERS_ALIASES
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-docs/teams.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-docs/teams.yaml
Replacement GitHub username will be: @lmktfy. Previous GitHub user @sftim is superseded.
For corroboration that I'm the same Tim, see https://kubernetes.slack.com/archives/C05PWRWPZSQ/p1743165608442659 (message on Kubernetes Slack) or https://github.com/sftim
I will send in follow-up PRs to add lmktfy (depends on issue https://github.com/kubernetes/org/issues/5497) and to update other related repos in light of this change.
> Drop sftim as org member

- config/kubernetes-sigs/sig-network/teams.yaml
This PR removes emeritus approvers and add current approvers to the github teams.
> sig-network: update external-dns team

- config/kubernetes/sig-docs/teams.yaml
Temporary adding myself to the `website-maintainers` team for write access to `k/website` repo for the release preparation/release day.
/assign @reylejano 
cc: @katcosgrove @npolshakova
> Add rayandas to website-maintainers team for 1.33 release

- config/kubernetes-sigs/sig-aws/teams.yaml
- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Removing jacobwolfaws from admin/write permissions to the 3 aws repos I have access to.
Also removing non-admins/maintainers for the aws-fsx-csi-driver + adding @dims to write permissions for the aws-fsx-csi-driver. This just cleans things up
> Remove jacobwolfaws + others permissions for aws repos

- config/kubernetes-sigs/sig-storage/teams.yaml
Adding myself and @BlaineEXE to [kubernetes-sigs/cosi-driver-sample](https://github.com/kubernetes-sigs/cosi-driver-sample).
> chore: add shanduur and BlaineEXE to cosi-driver-sample

- config/kubernetes/sig-docs/teams.yaml
This PR removed myself from website maintainers and milestone maintainers which I had added for 1.33 release. 
cc: @kubernetes/sig-docs-leads
> Remove temporary accesses

- config/kubernetes/sig-docs/teams.yaml
I'd like to re-apply for sig-docs-ko-owners & sig-docs-ko-reviews role.
I had sig-docs-ko-owners & sig-docs-ko-reviews roles by 2023.
After stabilizing some personal status through 2025(moving job position), I would like to re-apply for the roles to facilitate Korean L10n progress.
Thank you for the discussion @seokho-son , and appreciate so much in advance if you are supportive on this PR.
Note that this PR aligns with https://github.com/kubernetes/website/pull/49551
> Add ianychoi to sig-docs-ko-*

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Removing admin/maintainers who have been quiet for an extended period. 
Adding the current SIG Cloud Provider leads to the list. 
Adding Imran Pochi as one of the more engaged contributors to the maintainers.
> Updating ANP admin/maintainers list.

- config/kubernetes-sigs/sig-ui/teams.yaml
I know normally reviewers do not have write permissions in the repo, but in this case the headlamp core team is used to push branches directly, so it's more convenient than having forks outside.
> Add missing maintainers + headlamp-reviewers team to the sig-ui teams

- config/kubernetes-sigs/provider-ibmcloud/teams.yaml
@Prajyot-Parab is one of the active member and approver for the project, hence adding him as an admin to the repository for an additional maintenance required for the project.
> Include Prajyot-Parab as an admin for cluster-api-provider-ibmcloud

- config/kubernetes-sigs/sig-storage/teams.yaml
This adds write permissions for @juliankatz to [gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver).
> Add juliankatz as pcdsi driver maintainer and admin

- config/kubernetes/org.yaml
already part of kubernetes-sigs org
For adding to instrumentation team https://github.com/kubernetes/org/pull/5583
> Add slashpai to kubernetes org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Add myself to kubespray-maintainers team.
I'm driving the releases of Kubespray (see https://github.com/kubernetes-sigs/kubespray/issues/12175), discussed with @yankay and joined the kubespray-maintainer team.
I'll be able to help manage milestones for each release.
> Add tico88612 to kubespray-maintainers team

- config/kubernetes-sigs/sig-node/teams.yaml
Reflects my transition into Emeritus status as per https://github.com/kubernetes-sigs/security-profiles-operator/pull/2852.
cc: @saschagrunert @ccojocar @JAORMX @jhrozek PTAL
> Update SPO groups

- config/kubernetes-sigs/sig-scalability/teams.yaml
This change updates inference-perf admins to active maintainers at https://github.com/kubernetes-sigs/inference-perf/blob/main/OWNERS_ALIASES
> Update inference-perf admins to active maintainers

- config/kubernetes/sig-release/teams.yaml
- Add v1.34 Release Team Lead, Lead Shadows and Subteam leads to various teams.
- Cleanup members from previous releases.
Ref: https://github.com/kubernetes/sig-release/issues/2779
/cc @katcosgrove @fsmunoz
> Add v1.34 release team permissions and cleanup older releases

- config/kubernetes/org.yaml
This PR adds `alimaazamat` to the kubernetes org.
She is already a member of the kubernetes-sigs org:
- https://github.com/kubernetes/org/commit/42f0a644c1641dc999cc58c77cf372c237f7366f
In order more force multiply her value across the Kubernetes community, let's add her to kubernetes as well.
> add alimaazamat to kubernetes org

- config/kubernetes/sig-docs/teams.yaml
Add t-inu to the website-maintainers team.
Because I had missed adding it in the following PR.
- https://github.com/kubernetes/org/pull/5470
/assign @natalisucks
cc @Okabe-Junya
> Add t-inu to website-maintainers team

- config/kubernetes/sig-release/teams.yaml
- Added 1.34 Release Signal shadows to Release signal Team
- Added experienced shadow @tico88612 as one of milestone maintainer.
> Add 1.34 release signal team permissions

- config/kubernetes-sigs/sig-node/teams.yaml
- config/kubernetes/sig-node/teams.yaml
- config/restrictions.yaml
#5640 put these teams in kubernetes-sigs, not kubernetes where the actual repo is. This PR fixes this issue.
> Fix node-problem-detector repo teams

- config/kubernetes/sig-docs/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Update Release Docs team in release-team-docs in sig-release/teams.yaml and website-milestone-maintainers
cc @katcosgrove @Vyom-Yadav
> Add 1.34 Docs shadows to release-team-docs and website milestone maintainers

- config/kubernetes/org.yaml
I'm already a member of the kubernetes-sigs organization (see: https://github.com/kubernetes/org/issues/4915), and I’d like to request to be added as a member of the kubernetes org.
https://github.com/kubernetes/org/blob/f568618f6fe15022f7fe7d8bbb7594ae37dd5f3d/config/kubernetes-sigs/org.yaml#L610
> Add mbobrovskyi to kubernetes

- config/kubernetes/org.yaml
I'm already a member of `kubernetes-sigs` org: https://github.com/kubernetes/org/issues/4795 and I'd like to nominate myself for a membership in the `kubernetes` org
> Add PBundyra to k8s org

- config/kubernetes/org.yaml
Adding mdzraf to kubernetes org as I am already part of kubernetes-sigs and kubernetes-csi.
> Add mdzraf to kubernetes org

- config/kubernetes/org.yaml
This is a membership join request.
I’m a member of k8s-sigs https://github.com/kubernetes/org/blob/c62a004e356f77d8d4f19eb1010fcf99edb86171/config/kubernetes-sigs/org.yaml#L411
I’m requesting to join also to Kubernetes org.
my contributions can be seen in 
- https://github.com/kubernetes-sigs/external-dns/pulls?q=is%3Apr+is%3Aclosed+author%3Aivankatliarchuk
- https://github.com/kubernetes-sigs/external-dns/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Aivankatliarchuk+
Sponsor 1
@szuecs 
and 
Sponsor 2
@aojea
> add ivankatliarchuk to kubernetes org

- config/etcd-io/org.yaml
- config/kubernetes-sigs/org.yaml
This PR:
- Adds @ronaldngounou and @wendy-ha18 to the etcd-io org (xref: #[5677](https://github.com/kubernetes/org/pull/5677#issuecomment-3007281182))
- Fixes #5678
> Add members 2025-06-26

- config/kubernetes/org.yaml
Adding Taylor to the kubernetes org so that she may be added as a billing manager in the kubernetes enterprise account.
/hold
> add taylorwaggoner to kubernetes

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
Signed-off-by: Stefan Büringer buringerst@vmware.com
This PR adds Alvaro & myself to CR & CT admins.
Also removes fillzpp from controller-runtime-maintainers as he is approver not maintainer in https://github.com/kubernetes-sigs/controller-runtime/blob/main/OWNERS_ALIASES#L19
(I"ll update the admin / maintainer lists in CR & CT once this PR is merged)
> Update admin / maintainer groups for controller-runtime & controller-tools

- config/kubernetes/org.yaml
ryanzhang-oss is already in the Kubernetes-sig org
> Add ryanzhang-oss to kubernetes

- hack/remove-members.sh
Fixes the documentation around the default `DRYRUN` value
> Fix documentation in hack/remove-members.sh

- config/kubernetes-sigs/org.yaml
I am already a member of the kubernetes org, I need basic privileges to be able to help with https://github.com/kubernetes-sigs/secrets-store-csi-driver releases.
/cc aramase enj
> Add stlaz to kubernetes-sigs org

- config/etcd-io/sig-etcd/teams.yaml
v3.6.4 was released last Friday. Return the release-etcd team members to BAU.
/cc @ahrtr @jmhbnz 
This reverts commit f5117b4252f3cf2b4ea83495ae4fdc9675b0aff9.
> etcd: Restore release-etcd team members

- config/kubernetes/sig-docs/teams.yaml
Here is the English translation:
Hi, following up on PR https://github.com/kubernetes/website/pull/51410, I would like to be added to the blog owners' group here as well.
I would also need edit access to the https://github.com/orgs/kubernetes/projects/93 board. Is joining the blog owners' group sufficient, or is another permission required? If so, could you please let me know how to gain access?
Thanks a lot;
Graziano
> Add graz-dev as blog owner

- config/kubernetes-csi/org.yaml
- config/kubernetes/org.yaml
Already in kubernetes-sig.
Request membership for both kubernetes and kubernetes-csi.
> Add laozc to both kubernetes and kubernetes-csi org

- config/kubernetes/sig-cluster-lifecycle/teams.yaml
sync with the k/kubeadm OWNERS file, so that anyone can cut system-validators releases.
also remove Fabrizio from k/kubeadm admins, but can be re-added if he wishes.
/cc @pacoxu @SataQiu
> sig-cl: sync system-validators admins/maintainers

- config/kubernetes-sigs/sig-instrumentation/teams.yaml
- config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5740
/assign @kubernetes/sig-instrumentation-leads 
> sig-instrumentation: add gh teams for resource-state-metrics repo

- go.mod
- go.sum
SSIA
Follow the latest release 
- https://github.com/kubernetes-sigs/yaml/pull/133
> Bump sigs.k8s.io/yaml to v1.5.0

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-architecture/teams.yaml
- config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5408
/assign @kubernetes/sig-architecture-leads 
cc: @kubernetes/owners 
---
Note: This PR also adds `vinayakankugoyal` to `kubernetes-sigs` org,  to satisy org membership requirements for creating gh teams.
> sig-arch: add gh teams for admission-policies repo

- config/kubernetes/sig-docs/teams.yaml
1.34 was released yesterday, this PR removes the 1.34 release docs lead, michellengnx, from website-maintainers as part of the post release tasks
This is a follow-up PR to https://github.com/kubernetes/org/pull/5794
> Remove michellengnx from website-maintainers after 1.34 release

- config/kubernetes/sig-release/teams.yaml
Per https://github.com/kubernetes/community/pull/8343 and https://github.com/kubernetes/community/issues/8370
> Add mengqiy to milestone maintainer

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- config/restrictions.yaml
ref: github.com/kubernetes/org/issues/5772, https://github.com/kubernetes/org/issues/5762
/assign @kubernetes/sig-cluster-lifecycle-leads 
> sig-cluster-lifecycle: add gh teams for minikube-os/preloads repos

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
In https://github.com/kubernetes/org/issues/5789#issuecomment-3286751958 @mrbobbytables noted that he added the people he could add at the time he created the team. "team has been created with members that are currently members of k-sigs: https://github.com/kubernetes/org/pull/5837" 
Now that @Priyankasaggu11929 updated the members in https://github.com/kubernetes/org/pull/5839, it's possible to add two more of the kro admins who couldn't be added initially until their membership in k-sigs was processed. (A third one should be coming next week; I'll add that after https://github.com/kubernetes/org/issues/5842 is complete.)
> Adding kro maintainers

- config/kubernetes/sig-docs/teams.yaml
Adding khanhtc1202 & ntheanh201 as sig-docs-vi-owners/reviewers
Ref: https://github.com/kubernetes/website/pull/52424#issuecomment-3314397607
> adding khanhtc1202 & ntheanh201 as sig-docs-vi-owners/reviewers

- config/kubernetes-sigs/sig-storage/teams.yaml
Contributing to Filestore CSI driver release process. Add `riteshghorse` so that I can create release tags etc.
> Add riteshghorse as maintainer for gcp-filestore-csi-driver

- Makefile
- OWNERS
- SECURITY_CONTACTS
- admin/update.sh
- config/etcd-io/org.yaml
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/OWNERS
- config/kubernetes-incubator/org.yaml
- config/kubernetes-nightly/OWNERS
- config/kubernetes-nightly/org.yaml
- config/kubernetes-retired/OWNERS
- config/kubernetes-retired/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Ref: [Issue: #8622, sig-contribex announcement for nomination ](https://github.com/kubernetes/community/pull/8622)
**Commit 1**
`add jasonbraganza as admin (scripts and security)`
Change root OWNERS and ADMIN variables in scripts.
**Commit 2**
`add or promote jasonbraganza as admin (OWNERS and org.yaml files)`
Add jasonbraganza as admin in all orgs.
Add jasonbraganza as reviewer and approver in OWNERS of all orgs.
/cc @kubernetes/owners 
/assign @Priyankasaggu11929
> Add jasonbraganza as GitHub admin

- config/kubernetes-sigs/sig-network/teams.yaml
- config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5848
> sig-network: add gh teams for wg-ai-gateway repo

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
As an existing member of the etcd-io org, I'm adding myself to the kubernetes-sigs org per
kubernetes/org [application template](https://github.com/kubernetes/org/blob/main/.github/ISSUE_TEMPLATE/membership.yml) (org memberships are equivalent; PR-based self-add).
> add ballista01 to kubernetes-sigs, kubernetes

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-autoscaling/teams.yaml
- config/restrictions.yaml
ref: https://github.com/kubernetes/org/issues/5836
Fix https://github.com/kubernetes/org/issues/5898
commit 1: b989bca26d96e1c93658f6023de23cdbab82a317, add github teams for karpenter-provider-ibm-cloud repo
commit 2: b133b868eab3af16edc2f3b58c8b3ceb7ade5ec2, add @pfeifferj to Kubernetes-sigs org
---
@pfeifferj - please note, I am unable to add `jirn073-76`, `viktoryatheone` to the GH teams atm because it requires Kubernetes-sigs org membership. Please feel free to open a PR to add them to the required GH teams after their org membership is in place as well.
/assign @kubernetes/sig-autoscaling-leads 
> sig-autoscaling: add gh teams for karpenter-provider-ibm-cloud repo
