kubernetes/org

- config/kubernetes/org.yaml
> Update membership - Sept 3

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
I manually invited all of these people, and updated the configs accordingly.
Fixes #50
Fixes #57
Fixes #59
Fixes #61 
Fixes #63
> Update org membership - sep 4

- admin/README.md
- admin/update.sh
/assign @spiffxp @calebamiles @cblecker
> Fix README.md and update.sh script

- config/kubernetes-sigs/org.yaml
> Add proposed cri-tools admins to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
> Add yujuhong to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
> Add runcom to kubernetes-sigs org

- config/kubernetes/org.yaml
> Add brahmaroutu to kubernetes org

- config/kubernetes-sigs/org.yaml
> Add caesarxuchao to kubernetes-sigs org

- config/kubernetes/org.yaml
> Add pigletfly to kubernetes org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Took another dump.
Looks like (at)theairkit deleted their account.
@amwat, @BenTheElder, @munnerz, @krzyzacy added in #86 
@jennybuckley added in #70 
/assign @spiffxp @fejta
> Update org configs - Sept 12

- config/kubernetes-sigs/org.yaml
ref: https://github.com/kubernetes/org/issues/88
> Add owners for kubernetes-sigs/sig-storage-lib-external-provisioner

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members

- admin/BUILD.bazel
> Fix syntax on required-admins

- Gopkg.lock
- vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
- vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
- vendor/k8s.io/test-infra/prow/clonerefs/options.go
- vendor/k8s.io/test-infra/prow/clonerefs/run.go
- vendor/k8s.io/test-infra/prow/cmd/peribolos/main.go
- vendor/k8s.io/test-infra/prow/cmd/tide/pr-authors.md
- vendor/k8s.io/test-infra/prow/config/BUILD.bazel
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/config/jobs.go
- vendor/k8s.io/test-infra/prow/config/secrets_agent.go
- vendor/k8s.io/test-infra/prow/config/tide.go
- vendor/k8s.io/test-infra/prow/entrypoint/run.go
- vendor/k8s.io/test-infra/prow/gcsupload/run.go
- vendor/k8s.io/test-infra/prow/github/client.go
- vendor/k8s.io/test-infra/prow/github/types.go
- vendor/k8s.io/test-infra/prow/pod-utils/clone/clone.go
- vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
- vendor/k8s.io/test-infra/prow/pod-utils/gcs/target.go
- vendor/k8s.io/test-infra/prow/tide/README.md
pulls in https://github.com/kubernetes/test-infra/pull/9476
/assign @fejta
> Update k8s.io/test-infra to 36f61e5

- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/org.yaml
- config/kubernetes-retired/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Will revert when I confirm that everything works :)
> Add my sockpuppet to all orgs .. for science!

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #102, fixes #103, fixes #104, fixes #105
> Add new memberships for September 21

- config/kubernetes-sigs/org.yaml
> Add nikhita to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> New membership for ameukam

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add dougm and nikopen

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #120.
fixes #126.
fixes #127.
> Add new memberships - October 2

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add bertinatto to kubernetes, kubernetes-sigs

- OWNERS_ALIASES
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
ref: #112 (in lieu of #132)
Fixes #134
> Add members - October 2

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add some members

- config/kubernetes-client/OWNERS
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/OWNERS
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/OWNERS
- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/OWNERS
- config/kubernetes-sigs/org.yaml
- config/kubernetes/OWNERS
/cc @justaugustus @mrbobbytables
> Add justaugustus and mrbobbytables as front line membership reviewers

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add chaosaffe to k, k-sigs orgs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes: #121 
/assign @cblecker 
> Add m00nf1sh to k, k-sigs orgs

- config/kubernetes/org.yaml
> Add liyinan926 to Kubernetes Org

- config/kubernetes-sigs/org.yaml
GitHub Username
@Lion-Wei 
Organization you are requesting membership in
@kubernetes-sigs
Requirements
I am already a member of @kubernetes.
> Add Lion-Wei and m1093782566 to kubernetes-sigs

- config/kubernetes/org.yaml
> Add chrisohaver to Kubernetes Org

- .github/ISSUE_TEMPLATE/integrations.md
- .github/ISSUE_TEMPLATE/membership.md
- .github/ISSUE_TEMPLATE/repo-archive.md
- .github/ISSUE_TEMPLATE/repo-create.md
Depends on https://github.com/kubernetes/test-infra/pull/9738
ref: https://github.com/kubernetes/org/issues/149
/cc @fejta @cblecker
> Use area/github-* labels in issue templates

- config/kubernetes-incubator/org.yaml
- config/kubernetes/org.yaml
> Add warmchang to kubernetes and kubernetes-incubator orgs

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add dstrebel + pohly

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add alvaroaleman to k, k-sigs orgs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes: https://github.com/kubernetes/org/issues/163
Fixes: https://github.com/kubernetes/org/issues/157
> Add gyuho + tizhou86

- config/kubernetes/org.yaml
> Add chentao1596 to Kubernetes Org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add jinzhejz and mcrute to Kubernetes and Kubernetes-sigs Orgs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #170
fixes #173
fixes #175
> Add new memberships - October 18th

- config/kubernetes-sigs/org.yaml
> Add marquiz to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
> Add jingxu97 to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
> Add new members (181023)

- config/kubernetes-sigs/org.yaml
> Add more kube-batch contributors to k-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #186 
fixes #189 
fixes #190
> Add members to kubernetes / kubernetes-sigs orgs

- config/kubernetes-sigs/org.yaml
> Add liggitt to k-sigs

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
> Add new org members - Oct 26

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members to kubernetes and kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes: #202 
Fixes: #203 
Fixes: #204 
Fixes: #205 
Fixes: #206 
Fixes: #209 
Fixes: #210 
Fixes: #211 
> Add new members (181030)

- config/kubernetes-incubator/org.yaml
> Add yue9944882 to kubernetes-incubator org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> New memberships - Nov 3

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add immutableT and idealhack to orgs.

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add animeshsingh and jbartosik to orgs

- config/kubernetes/org.yaml
> Add wenjiaswe to kubernetes org

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #229
fixes #230 
fixes #231 
fixes #232 
fixes #233 
fixes #235 
> Add members 09-11-2018

- config/kubernetes/org.yaml
> Add aoxn and zhangqx2010 to kubernetes org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add fleeto and cofyc to orgs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add danielqsj to kubernetes, kubernetes-sigs orgs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #237 
fixes #240 
fixes #251 
> Add members 19112018

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #250
also ref #248 to add sig-dogs folks to k-sigs
> Add new members for Nov 20

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add yastij  and jonpusifer to orgs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> New Members (181122)

- config/kubernetes-sigs/org.yaml
ref https://github.com/kubernetes/org/issues/172
> Add balajismaniam to kubernetes-sigs

- config/kubernetes/org.yaml
> Add hhoover to kubernetes org

- config/kubernetes/org.yaml
> Add soggiest to kubernetes org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #274
fixes #276 
fixes #277 
> Add users 2018-11-29

- config/kubernetes-client/org.yaml
- config/kubernetes/org.yaml
> Add members 2018-11-30

- config/kubernetes/org.yaml
fixes #266 
fixes #283 
fixes #288 
fixes #289 
fixes #290 
fixes #291 
fixes #292 
fixes #295 
> Add members 2018-12-10

- config/kubernetes-sigs/org.yaml
as required to fully implement https://github.com/kubernetes/org/issues/285
> Add piosz, brancz, dashpole to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
- per [287][]
[287]: https://github.com/kubernetes/org/issues/287
> Add Monkeyanator to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2018-12-19

- README.md
Peribolos is no longer WIP. \o/
/assign @fejta @cblecker
> Remove WIP note in README

- config/kubernetes-sigs/org.yaml
> Add members 2018-12-24

- config/kubernetes-sigs/org.yaml
> Add members 2018-12-26

- config/kubernetes/org.yaml
> Add members 2019-01-03

- config/kubernetes/org.yaml
> Add members 2019-01-07

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-01-08

- config/kubernetes-sigs/org.yaml
> Add members 2019-01-09

- OWNERS_ALIASES
- config/kubernetes/sig-contributor-experience/teams.yaml
I'd like to help/participate in reviews and discussions related to sig contributor-experience. :)
/cc @cblecker @parispittman @Phillels 
> Add nikhita to sig contributor-experience teams

- config/BUILD.bazel
- config/config_test.go
Found that the org tests were running against the single configuration, not the fully merged team configuration.
/assign @fejta 
/cc @nikhita
> Run org tests against merged configuration

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- kubernetes (claurence, ibrasho, nwoods3)
- kubernetes-sigs (interma)
Fixes: #301 
Fixes: #352 
Fixes: #354 
Fixes: #355 
> Add new members (190114)

- config/kubernetes/org.yaml
I'd like to help/participate in reviews and discussions related to sig instrumentation.
/cc @brancz @piosz @fabxc
> Add danielqsj as a member to sig instrumentation teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #294 
fixes #362 
fixes #360 
fixes #364 
> Add members 2019-01-15

- config/kubernetes/org.yaml
> Add eduartua to kubernetes org.

- config/kubernetes/sig-contributor-experience/teams.yaml
I'd like to help/participate in issues and PRs related to sig-contribex. :)
Hum... this yaml is not alphabetized, how do we do that?
/cc @parispittman @cblecker @nikhita
> Add idealhack as a member to sig-contribex teams

- config/kubernetes/sig-release/teams.yaml
I'd like to help/participate in issues and PRs related to sig-release. :)
/cc @justaugustus @tpepper @calebamiles
> Add idealhack as a member to sig-release team

- admin/BUILD.bazel
> Re-enable Peribolos Team Sync

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-01-17

- config/kubernetes/sig-release/teams.yaml
original request was here, pre-prune:
https://github.com/orgs/kubernetes/teams/kubernetes-milestone-maintainers/discussions/5
/assign @tpepper @fabriziopandini 
cc @timothysc @luxas
> re-add fabriziopandini to milestone maintainers

- config/kubernetes-csi/org.yaml
This is in service of #342 but I cleaned up team descriptions while I was here
> Update kubernetes-csi teams for csi-release-tools

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-01-18

- config/kubernetes/org.yaml
- config/kubernetes/sig-pm/OWNERS
- config/kubernetes/sig-pm/teams.yaml
/assign @calebamiles @idvoretskyi @jdumars @cblecker
> Add SIG PM teams

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #389 
fixes #392 
fixes #393 
fixes #396 
fixes #398
> Add members 2019-01-22

- OWNERS_ALIASES
- config/kubernetes/wg-component-standard/OWNERS
- config/kubernetes/wg-component-standard/teams.yaml
fixes #363
/assign @luxas 
Let me know if that looks good to you.
> Create new wg-component-standard team

- config/kubernetes/org.yaml
Change-Id: Ib1c453e2889fa9afe16f0afdb16d81be343922b8
> Add dims to k8s.io/utils

- config/kubernetes/org.yaml
:bash_fire:
@kubernetes/sig-testing anyone else want in on this?
cc: @fejta @BenTheElder @cjwagner @ixdy @stevekuznetsov
> Add bash-firefighters team

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #395
fixes #399 
fixes #408 
fixes #411 
fixex #412 
fixes #415 
> Add members 2019-01-24

- config/kubernetes/org.yaml
minikube-admins: +balopat,+tstromberg,-pwittrock
minikube-maintainers: +afbjorklund
Context: https://github.com/kubernetes/minikube/issues/3345
> Update minikube-admins & minikube-maintainers

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
@rlenferink 
@kubernetes-sigs
@kubernetes-client
I'm a member of @kubernetes already
----------
/cc @mrbobbytables 
> Add rlenferink to kubernetes-sigs, kubernetes-client orgs.

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-01-25

- config/kubernetes/org.yaml
> Add members 2019-01-27

- config/kubernetes-sigs/org.yaml
ref: https://github.com/kubernetes/org/issues/308
> Add teams for etcdadm repo

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-01-28

- OWNERS
> Fixed broken link to OWNERS docs in OWNERS file

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #430 
fixes #432 
fixes #433 
/cc @mrbobbytables
> Add members 2019-01-30

- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/org.yaml
@rlenferink 
@kubernetes-csi
@kubernetes-incubator
I'm a member of @kubernetes already
----------
/cc @mrbobbytables 
> Add rlenferink to kubernetes-csi, kubernetes-incubator orgs.

- config/kubernetes/org.yaml
> Update kubectl groups per current SIG leadership

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-02-04

- config/kubernetes/org.yaml
> Update group membership for roberthbailey.

- config/kubernetes/org.yaml
> Add members 2019-02-06

- config/kubernetes-sigs/org.yaml
/assign @timothysc @roberthbailey
> Add vincepri to cluster-api-maintainers

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
fixes #456 
fixes #461 
fixes #462 
> Add members 2019-02-08

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #455
fixes #457 
fixes #464 
fixes #465
> Add members 2019-02-11

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-windows/OWNERS
- config/kubernetes-sigs/sig-windows/teams.yaml
ref: https://github.com/kubernetes/org/issues/451
> Add teams for kubernetes-sigs/windows-gmsa access

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-02-12

- config/kubernetes/org.yaml
Adding myself to kops to help Justin with some overrides, given aws e2e issues and issue triage.
cc @justinsb
> Add myself to k8s.io/kops

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #472 
fixes #475 
fixes #476 
fixes #477 
fixes #478 
fixes #480 
> Add members 2019-02-13

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-azure/teams.yaml
> Update Azure teams + add ritazh to k,k-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #482 
fixes #483 
fixes #484 
fixes #485 
> Add members 2019-02-14

- config/kubernetes/org.yaml
cc @lavalamp @rmmh @thockin @ixdy
> Add dims as maintainer for k/k8s.io repo

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #487 
fixes #492 
fixes #494 
fixes #495 
> Add members 2019-02-16

- config/kubernetes/org.yaml
fixes #499 
fixes #500
fixes #501 
> Add members 2019-02-18

- config/kubernetes/sig-pm/teams.yaml
/assign @calebamiles @idvoretskyi @jdumars
> sig-pm: Add project-board-maintainers team

- config/kubernetes/org.yaml
> Add members 2019-02-19

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #508 
fixes #509 
fixes #511 
fixes #513 
> Add members 2019-02-20

- config/kubernetes/org.yaml
> Add members 2019-02-23

- .github/ISSUE_TEMPLATE/general-support.md
> One-character typo fix

- config/kubernetes/sig-docs/teams.yaml
Fixes https://github.com/kubernetes/org/issues/532
> Add teams for French localization

- config/kubernetes-incubator/org.yaml
/assign @pwittrock 
Syncing up team members since we renamed repo as we decided on slack discussion
> Sync up team members for apiserver-builder-alpha

- config/kubernetes-incubator/org.yaml
- config/kubernetes/org.yaml
fixes #527 
fixes #529 
fixes #530 
fixes #531 
fixes #535 
fixes #537 
> Add members 2019-02-27

- config/kubernetes-incubator/org.yaml
I'd like to help in reviews and fix work related to apiserver-builder.
/cc @nikhita
> add adohe to kubernetes-incubator

- config/kubernetes-csi/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-02-28

- config/kubernetes/org.yaml
> Add rjbez17 to kubernetes org.

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
> Add members 2019-03-01

- config/kubernetes/org.yaml
> Add members 2019-03-03

- config/kubernetes/org.yaml
/assign @cblecker @fejta 
Ref: https://github.com/kubernetes/steering/issues/89
> Rename PST team to PSC

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/559
/cc @sboeuf @mrunalp @rhatdan 
/hold 
for lgtm by @mrunalp
> Add sboeuf and rhatdan to cri-o-maintainers team

- config/kubernetes/org.yaml
> Add members 2019-03-04

- config/kubernetes-sigs/org.yaml
ref https://github.com/kubernetes/org/issues/308#issuecomment-458360650
> Add dlipovetsky to etcdadm teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-03-06

- config/kubernetes/sig-release/teams.yaml
This PR adds @xmudrii to kubernetes-milestone-maintainers as per #574 
Fixes #574
/cc @nikhita
> Add xmudrii to kubernetes-milestone-maintainers

- config/kubernetes/org.yaml
> Add members 2019-03-07

- OWNERS_ALIASES
- SECURITY_CONTACTS
See https://github.com/kubernetes/security/issues/8 for more information
> Update embargo doc link in SECURITY_CONTACTS and change PST to PSC

- config/kubernetes-sigs/org.yaml
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
@mrunalp PTAL
> Add umohnani8 to cri-o maintainers team

- config/kubernetes-client/org.yaml
- config/kubernetes/org.yaml
fixes #479 
fixes #587
fixes #589
fixes #590
> Add members 2019-03-11

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-cluster-lifecycle/teams.yaml
- config/kubernetes/sig-release/teams.yaml
This is primarily to reduce email load. 
/assign @spiffxp
> Clean up group membership for roberthbailey

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #594 
fixes #595 
fixes #596 
> Add members 2019-03-13

- config/kubernetes-sigs/sig-azure/teams.yaml
- config/kubernetes/sig-azure/teams.yaml
* Add missing teams for cloud-provider-azure repo
* Update members for csi repos
/assign @justaugustus @cblecker
> Update teams for sig-azure

- config/kubernetes-sigs/org.yaml
fixes #470 
fixes #603
/pony pie
it's π day :P
> Add members 2019-03-14

- config/kubernetes-sigs/sig-auth/teams.yaml
srampal (Sanjeev Rampal) is one of the key contributors driving the multi-tenancy proposal in wg-multitenancy.
> Add srampal to multi-tenancy teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes: #614, fixes: #612, fixes: #609, fixes: #608
> Add new members (3/16/19)

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #611 
fixes #613 
fixes #619 
> Add members 2019-03-17

- config/kubernetes/org.yaml
> Add members 2019-03-18

- config/kubernetes-client/org.yaml
Ref: https://github.com/kubernetes/org/issues/626
/cc @yue9944882 @mbohlool 
/assign @yue9944882
> Add teams for kubernetes-client/perl

- config/kubernetes-sigs/org.yaml
Fix https://github.com/kubernetes/org/issues/632
> Add hex108 to kubernetes-sigs members

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Ref: https://github.com/kubernetes/org/issues/630#issuecomment-474871018
@luxas was not a member of k-sigs so I've added him to the org here.
/assign @timothysc
> Grant SCL leads admin access to all SCL subproject repos

- config/kubernetes/org.yaml
> Add members 2019-03-20

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #623 
fixes #640 
fixes #641 
> Add members 2019-03-22

- config/kubernetes/org.yaml
> Add members 2019-03-25

- config/kubernetes/sig-docs/teams.yaml
Add German speaking team members for documentation
> Add German language team members

- .github/ISSUE_TEMPLATE/repo-create.md
All files are automatically populated from the staging directory in k/k.
Example - https://github.com/kubernetes/org/issues/642
/cc @spiffxp @mrbobbytables @justaugustus @rlenferink
> Don't ask approvers and security contacts for staging repos

- config/kubernetes-incubator/org.yaml
ref: https://github.com/kubernetes/org/pull/649
/cc @nikhita @steveperry-53
> adding jimangel to kubernetes-incubator

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #655 
fixes #658
fixes #660
> Add members 2019-03-27

- config/kubernetes-sigs/org.yaml
This is a long overdue PR to add relevant folks to the cluster-api-vsphere repo under kubernetes-sigs
/cc @sflxn @sidharthsurana @figo
> Add folks to cluster-api-vsphere

- config/kubernetes/org.yaml
> Add members 2019-04-01

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-aws/OWNERS
- config/kubernetes-sigs/sig-aws/teams.yaml
Ref: https://github.com/kubernetes/org/issues/467 and https://github.com/kubernetes/org/issues/468
/assign @d-nishi @leakingtapan
> Add teams for aws-*-csi-driver repos

- config/kubernetes/org.yaml
> Add members 2019-04-02

- config/kubernetes/org.yaml
> Add members 2019-04-04

- config/kubernetes/org.yaml
fixes #687 
fixes #688 
fixes #689 
fixes #690 
> Add members 2019-04-05

- OWNERS_ALIASES
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-multicluster/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/sig-scheduling/teams.yaml
- config/kubernetes/wg-lts/teams.yaml
https://github.com/quinton-hoole-2 no longer exists, @quinton-hoole is the real one now :)
This should make peribolos green.
> Remove quinton-hoole-2, keep quinton-hoole

- BUILD.bazel
- WORKSPACE
Updated bazel workspace settings to match those of k/k
/assign @fejta
> Update bazel workspace for k8s.io/org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #696, fixes #697
/assign @nikhita @cblecker
> New members (4/8/19)

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-04-10

- config/kubernetes-sigs/org.yaml
> Add Miouge1 as a Kubespray maintainer

- config/kubernetes/org.yaml
> Remove jlowdermilk as the user no longer exists

- config/kubernetes-sigs/org.yaml
> Add hzxuzhonghu to kubernetes-sigs

- config/kubernetes-incubator/org.yaml
Signed-off-by: Doug Davis <dug@us.ibm.com>
/cc @jberkhahn @jboyd01
> Clean-up svc-cat stuff - just 2 owners/maintainers now

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #709 
fixes #710 
/area github-management
> Add members 2019-04-13

- config/kubernetes/org.yaml
> Add members 2019-04-15

- config/kubernetes/org.yaml
> Add femrtnz to kubernetes org

- config/kubernetes/sig-architecture/teams.yaml
> Add code-organization-project-admins team

- config/kubernetes/org.yaml
fixes #735 
One off to unblock #729 
> Add jcjesus to kubernetes org.

- config/kubernetes-sigs/sig-vmware/OWNERS
- config/kubernetes-sigs/sig-vmware/teams.yaml
Ref: https://github.com/kubernetes/org/issues/730
/assign @frapposelli @codenrhoden
> Add teams for vsphere-csi-driver

- config/kubernetes/sig-instrumentation/teams.yaml
> add hankang to sig-instrumentation teams.yaml

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
Opened at the request of @nikhita
Issue: https://github.com/kubernetes/org/issues/743
> Add @dvonthenen to k8s-sigs and k8s-csi

- config/kubernetes-csi/org.yaml
Ref: https://github.com/kubernetes/org/issues/718
/cc @mrbobbytables @justaugustus
> Remove teams for archived repos in kubernetes-csi

- config/kubernetes/org.yaml
> Add members 2019-04-19

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-04-21

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
These align with changes to the OWNERS_ALIASES for cluster-api
> Update groups for cluster-api and cluster-api-provider-aws

- config/kubernetes-sigs/org.yaml
Ref: https://github.com/kubernetes/org/issues/753
> Remove teams for website-metadata

- config/kubernetes/org.yaml
Fixes: #750, fixes: #751, fixes: #759, fixes: #760 
/assign @nikhita @cblecker
> New members (4/23/19)

- config/kubernetes/org.yaml
> New members (4/24/19)

- config/kubernetes/org.yaml
@sharifelgamal has been helping with minikube maintenance tasks, and recently joined the Kubernetes org
Thanks!
> Add sharifelgamal to minikube-maintainers

- config/kubernetes-sigs/org.yaml
> Add myself as admin to kubernetes-sigs/sig-storage-local-static-provisioner

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #764 
fixes #765 
fixes #768 
fixes #769 
> Add members 2019-04-25

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-04-26

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-04-29

- config/kubernetes-incubator/org.yaml
Fixes https://github.com/kubernetes/org/issues/779
/assign @MrHohn
> Add admins-cluster-proportional-vertical-autoscaler team

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-05-01

- config/kubernetes-sigs/sig-ibmcloud/OWNERS
- config/kubernetes-sigs/sig-ibmcloud/teams.yaml
ref: https://github.com/kubernetes/org/issues/782
> Add teams for cluster-api-provider-ibmcloud

- config/kubernetes-sigs/sig-ibmcloud/teams.yaml
/cc @cblecker
FYI @xunpan @jichenjc
> Added more maintainers for cluster api ibm cloud

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-05-03

- config/kubernetes/sig-docs/teams.yaml
Ref: https://github.com/kubernetes/org/pull/748#issuecomment-486870227
> sig-docs: fix description for admin teams

- config/kubernetes/org.yaml
> Add alenkacz to kubernetes org

- config/kubernetes-sigs/org.yaml
> Add members 2019-05-06

- config/kubernetes/sig-docs/teams.yaml
@mkorbi volunteered to be part of the German translation team. The following PR will add him to the OWNERS file: https://github.com/kubernetes/website/pull/14134. Lets get him added to the GitHub team as well :)
/cc @mkorbi 
/assign @zacharysarah 
/sig docs
> Added mkorbi to German translation team

- config/kubernetes-sigs/sig-cli/teams.yaml
Ref: https://github.com/kubernetes/org/issues/798
cc @Liujingfang1
> Add teams for cli-utils

- config/kubernetes/org.yaml
> add members 2019-05-08

- config/kubernetes/org.yaml
Workaround until we can better figure out permissions for feature branch maintenance.
> Add kubernetes-feature-branch-admins group

- config/kubernetes/org.yaml
> Add members 2019-05-10

- .github/ISSUE_TEMPLATE/site-create.md
ref: https://git.k8s.io/community/github-management/subproject-site-requests.md#requesting-a-netlify-site
ref: https://github.com/kubernetes/community/issues/3454#issuecomment-491934519
/cc @cblecker
> Add netlify site request issue template.

- config/kubernetes/sig-docs/teams.yaml
> Fix up docs groups

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-multicluster/OWNERS
- config/kubernetes-sigs/sig-multicluster/teams.yaml
> Rename federation-v2 to kubefed

- config/kubernetes/org.yaml
> Add members 2019-05-14

- config/kubernetes/sig-release/teams.yaml
> added 1.15 branch managers to k-release-managers

- config/kubernetes/org.yaml
> Add members 2019-05-16

- config/kubernetes/sig-pm/teams.yaml
ref https://github.com/kubernetes/test-infra/issues/12594 (@vllry):
> CC @justaugustus (on behalf of SIG-PM, which I can't find a handle for)
/assign @calebamiles @idvoretskyi @jdumars
> Update SIG PM teams

- config/kubernetes/sig-docs/teams.yaml
> Add juandiegopalomino to website-milestone-maintainers

- config/kubernetes/org.yaml
> Add members 2019-05-20

- config/kubernetes/org.yaml
fixes #832 
fixes #836 
fixes #837 
> Add members 2019-05-23

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #835 
fixes #841 
fixes #842 
> Add members 2019-05-26

- config/kubernetes-client/org.yaml
Related to https://github.com/kubernetes/org/issues/846
> Add membership to irvifa in kubernetes-client.

- config/kubernetes-csi/org.yaml
> Add myself to @kubernetes-csi

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/848
Fixes https://github.com/kubernetes/org/issues/854
/assign @cblecker @nikhita
> Add new members (5/30/19)

- config/kubernetes/sig-contributor-experience/teams.yaml
ref: https://github.com/kubernetes/community/issues/3727#issuecomment-497220572
> Add team for youtube-admins

- config/kubernetes-sigs/org.yaml
I'm already a member of @kubernetes
> add jberkhahn to kubernetes-sigs

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #830
fixes #860 
fixes #861 
fixes #862 
> Add members 2019-05-30

- config/kubernetes-sigs/org.yaml
I still hang around to help out with sig-service-catalog, which is moving to this org soon.
/cc @jberkhahn
> add MHBauer

- config/kubernetes/org.yaml
> Add members 2019-06-01

- config/kubernetes-sigs/sig-windows/teams.yaml
Ref: https://github.com/kubernetes/org/issues/863
/assign @michmike
> Add teams for sig-windows-tools

- config/kubernetes-sigs/org.yaml
Add screeley44 to kubernetes-sigs org.yaml
> Add Scott Creeley (screeley44) to kubernetes-sigs org.yaml

- config/kubernetes-csi/org.yaml
> Add members 2019-06-03

- config/kubernetes-sigs/org.yaml
> Add SataQiu to @kubernetes-sigs

- config/kubernetes-sigs/org.yaml
Adding @akutz as maintainer and admin for cluster-api-provider-vsphere
> Add @akutz to cluster-api-provider-vsphere

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #877 
fixes #885 
fixes #886 
fixes #887 
> Add members 2019-06-05

- config/kubernetes/org.yaml
fixes #888 
fixes #890 
fixes #895
> Add new members for June 6, 2019

- config/kubernetes/org.yaml
> add andrewsykim as admin/maintainer for cloud-provider-vsphere

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #891
fixes #892
fixes #898
fixes #902
> Add members 2019-06-11

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-06-13

- config/kubernetes/org.yaml
fixes #907 
fixes #910 
fixes #912 
> Add members 2019-06-14

- config/kubernetes-sigs/sig-azure/teams.yaml
I am not a part of the Azure org anymore.
> Remove tariq1890 from sig-azure/cluster-api-azure

- config/kubernetes/sig-azure/teams.yaml
I am not a part of the Azure org anymore.
> Remove tariq1890 from sig-azure

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes: #914, fixes: #919, fixes: #921
> Add new members (6/17/19)

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-auth/teams.yaml
Adding myself to maintainers as requested by @tashimi.
> Add ryan to multitenancy wg maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-06-19

- config/kubernetes-client/OWNERS
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/OWNERS
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/OWNERS
- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/OWNERS
- config/kubernetes-sigs/org.yaml
- config/kubernetes/OWNERS
/cc @nzoueidi 
Holding for final ack and sync with updating community repo (PR forthcoming).
/hold
> Add nzoueidi as a New Membership Coordinator

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Ref https://github.com/kubernetes/org/issues/938
/assign @chuckha @timothysc
> Add teams for cluster-api-provider-docker

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #936 
Fixes #935
Fixes #934
Fixes #933
Fixes #932
> Add members 2019-06-20

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-apps/OWNERS
- config/kubernetes-sigs/sig-apps/teams.yaml
Ref: https://github.com/kubernetes/org/issues/880
/assign @xing-yang @liyinan926 @janetkuo
> Add teams for execution-hook

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes: #892, fixes: #940, fixes: #941, fixes: #943
> Add new members (6/22/19)

- config/kubernetes-sigs/org.yaml
> Add members 2019-06-24

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
ref #937 
/assign @chuckha @timothysc
> Add teams for cluster-api-bootstrap-provider-kubeadm.

- config/kubernetes/org.yaml
Ref: https://github.com/kubernetes/org/pull/954#issuecomment-505595781
cc @yoojinl
> Add yoojinl to Kubernetes GitHub org

- config/kubernetes-sigs/sig-node/OWNERS
- config/kubernetes-sigs/sig-node/teams.yaml
Ref: https://github.com/kubernetes/org/issues/957
/assign @marquiz
> Add teams for node-feature-discovery-operator

- config/kubernetes/org.yaml
> Add new members (6/26/19)

- config/kubernetes/org.yaml
Fixes: #958, fixes: #962, fixes: #964
> Add new members (6/26/19) - le deuxieme PR

- config/kubernetes-sigs/org.yaml
> Add members 2019-06-27

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/953
Fixes https://github.com/kubernetes/org/issues/961
Fixes https://github.com/kubernetes/org/issues/968
> Add members 2019-06-28

- config/kubernetes/org.yaml
> Add members 2019-07-01

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes: #975, fixes: #976, fixes: #979, fixes: #981, fixes: #984 
/assign @nikhita @cblecker
> Add new members (7/3/19)

- config/kubernetes/org.yaml
> Add members 2019-07-07

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Ref: https://github.com/kubernetes/org/issues/988
/assign @timothysc
> Add teams for image-builder

- config/kubernetes/org.yaml
> Add members 2019-07-08

- config/kubernetes/org.yaml
> Add ehashman to kubernetes

- config/kubernetes/sig-instrumentation/teams.yaml
Follow-up to #993/#994.
/cc @brancz @piosz
> Add ehashman to sig-instrumentation

- config/kubernetes/sig-docs/teams.yaml
> Add nasa9084 to sig-docs-l10n-admins

- config/kubernetes/sig-release/teams.yaml
follow up of https://github.com/kubernetes/org/pull/974#issuecomment-507361053
> added more Release Manager Associates to release-engineering team

- config/kubernetes/org.yaml
> Add members 2019-07-09

- config/kubernetes/org.yaml
> Add members 2019-07-10

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-07-12

- config/kubernetes-incubator/org.yaml
Add myself as a member of kubernetes-incubator.
> Add member for kubernetes-incubator.

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-07-16

- config/kubernetes/org.yaml
> Add members 2019-07-20

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes: #1029, fixes: #1028, fixes: #1027, fixes: #1026, fixes: #1023, fixes: #1030
> Add new members (7/22/19)

- config/kubernetes-sigs/org.yaml
> Add members 2019-07-17

- config/kubernetes/org.yaml
Fixes #1032
Fixes #1033
Fixes #1034
Fixes #1035
Fixes #1036
Fixes #1037
> Add members 2019-07-24

- config/kubernetes/org.yaml
Fixes #1039
Fixes #1040
Fixes #1042
> Add members 2019-07-25

- config/kubernetes-sigs/org.yaml
---
name: Organization Membership Request
about: Request membership in a Kubernetes Org
title: 'REQUEST: New membership for kfox1111'
labels: area/github-membership
assignees: ''"
---
kfox1111
kubernetes-sigs/sig-auth
- @rjbez17
- @dims 
* Helped with the ephemeral csi storage spec / implementation
* Implemented the initial ephemeral implementation in csi-driver-host-path
* Implemented the csi-driver-image-populator driver
> Add kfox1111 to wg-multitenancy

- config/kubernetes/sig-testing/teams.yaml
Specifically:
- chases2, clarketm joined recently
- michelle192837 occasionally goes oncall for prow.k8s.io
> Update sig-testing teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1048 
Fixes #1054 
Fixes #1053 
Fixes #1056 
/area gitbub-membership
> Add members 2019-07-31

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- cluster-api-provider-docker
- cluster-api-bootstrap-provider-kubeadm
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
> Grant myself maintainer to 2 more Cluster API repos

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1043 
Fixes #1066 
Fixes #1062
> Add members 2019-08-03

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1065
Fixes https://github.com/kubernetes/org/issues/1070
> Add members 2019-08-06

- config/kubernetes/org.yaml
cc @nikhita @brancz @andyxning @tariq1890
>  config/kubernetes/org.yaml: Sync with kube-state-metrics OWNERS file

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/1069
> Add Fei-Guo to kubernetes-sigs org

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Request to add chrigl and jichenjc into cluster-api-openstack maintainer
as we need create branch and other admin privileges..
> Add chrigl and jichenjc into cluster-api-openstack maintainer

- config/kubernetes/org.yaml
> Add members 2019-08-07

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1077
Fixes https://github.com/kubernetes/org/issues/1079
Fixes https://github.com/kubernetes/org/issues/1080
> Add members 2019-08-08

- config/kubernetes/sig-release/teams.yaml
Ref: https://github.com/kubernetes/website/pull/15750#issuecomment-519978706
> adding 1.16 docs lead to milestone maintainers

- config/kubernetes-sigs/org.yaml
/cc @nikhita 
/meow
Fixes: #1093
> Add yue to kubernetes-sigs

- config/kubernetes/org.yaml
fixes #1064 
fixes #1082 
fixes #1083 
fixes #1084 
fixes #1087 
fixes #1089 
> Add members 2019-08-11

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1088
Fixes https://github.com/kubernetes/org/issues/1096
> Add members 2019-08-13

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1024
fixes #1091
fixes #1098
fixes #1103 
> Add members 2019-08-14

- config/kubernetes-incubator/org.yaml
It shouldn't be present if it's empty
> Drop empty maintainers field

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Signed-off-by: Chuck Ha <chuckh@vmware.com>
Adds @detiber to the CABPK maintainers list to give him access to the /milestone command.
> Adds detiber as cabpk maintainer

- config/kubernetes-sigs/org.yaml
> add xichengliudui to kubernetes-sigs

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
prep for migration from kubernetes-incubator https://github.com/kubernetes/org/issues/1094
> Setup teams for kubernetes-sigs/apiserver-builder-alpha

- config/kubernetes-csi/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1100
Fixes https://github.com/kubernetes/org/issues/1104
> Add members 2019-08-18

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1115
Fixes https://github.com/kubernetes/org/issues/1116
Fixes https://github.com/kubernetes/org/issues/1117
Fixes https://github.com/kubernetes/org/issues/1118
Fixes https://github.com/kubernetes/org/issues/1119
/assign @cblecker @justaugustus
> Add members 2019-08-20

- config/kubernetes/sig-cluster-lifecycle/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1110
/cc @yastij @timothysc @neolit123
> Add teams for system-validators repo

- config/kubernetes-sigs/org.yaml
> Add odinuge to kubernetes-sigs

- config/kubernetes/org.yaml
> Add members 2019-08-22

- config/kubernetes/org.yaml
Fixes #1111
Fixes #1138 
Fixes #1141
Fixes #1147 
> Add members 2019-08-29

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/1151, https://github.com/kubernetes/org/issues/1150, https://github.com/kubernetes/org/issues/1149
> Add members 2019-09-03

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1146
/assign @fredkan @xianlubird
> Add teams for alibaba-cloud-csi-driver

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1157
Fixes https://github.com/kubernetes/org/issues/1160
Fixes https://github.com/kubernetes/org/issues/1162
> Add members 2019-09-06

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1164
fixes #1166
fixes #1167 
fixes #1170
fixes #1171
> Add members 2019-09-09

- config/kubernetes-csi/org.yaml
- config/kubernetes/org.yaml
fixes #1165
fixes #1169
fixes #1173
fixes #1175
fixes #1177
> Add members 2019-09-11

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1178
Fixes https://github.com/kubernetes/org/issues/1183
Fixes https://github.com/kubernetes/org/issues/1186
Fixes https://github.com/kubernetes/org/issues/1187
> Add members 2019-09-13

- config/kubernetes/org.yaml
fixes #1184
fixes #1190
fixes #1192
> Add members 2019-09-17

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1194
fixes #1195
fixes #1196
fixes #1199 
> Add members 2019-09-19

- config/kubernetes/sig-release/teams.yaml
Doug MacEachern and Yang Li are joining the patch release team.
Signed-off-by: Tim Pepper <tpepper@vmware.com>
> patch-release-team: Add dougm and idealhack

- config/kubernetes/sig-testing/teams.yaml
> Add chases2 to test-infra oncall

- config/kubernetes/sig-cluster-lifecycle/teams.yaml
/cc @kubernetes/sig-cluster-lifecycle
> Add ereslibre to sig-cluster-lifecycle{-pr-reviews}

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1201
Fixes https://github.com/kubernetes/org/issues/1202
Fixes https://github.com/kubernetes/org/issues/1204
> Add members 2019-09-23

- config/kubernetes/org.yaml
- config/kubernetes/sig-testing/teams.yaml
Also move this under sig-testing's folder.
/assign @cblecker @nikhita
/cc @BenTheElder @clarketm
> Update repo-infra-maintainers members

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1214
Fixes https://github.com/kubernetes/org/issues/1215
Fixes https://github.com/kubernetes/org/issues/1216
> Add members 2019-09-25

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Signed-off-by: Vince Prignano <vincepri@vmware.com>
> Add myself to CAPI kubeadm provider admin

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1219
Fixes https://github.com/kubernetes/org/issues/1220
Fixes https://github.com/kubernetes/org/issues/1222
Fixes https://github.com/kubernetes/org/issues/1223
Fixes https://github.com/kubernetes/org/issues/1224
Fixes https://github.com/kubernetes/org/issues/1225
> Add members 2019-09-27

- config/kubernetes-sigs/sig-aws/OWNERS
- config/kubernetes-sigs/sig-azure/OWNERS
- config/kubernetes-sigs/sig-ibmcloud/OWNERS
- config/kubernetes-sigs/sig-vmware/OWNERS
- config/kubernetes/sig-aws/OWNERS
- config/kubernetes/sig-azure/OWNERS
- config/kubernetes/sig-gcp/OWNERS
- config/kubernetes/sig-ibmcloud/OWNERS
- config/kubernetes/sig-openstack/OWNERS
/shrug
/cc @andrewsykim @justaugustus @mrbobbytables
> Fix labels for cloud provider in OWNERS files

- config/kubernetes/org.yaml
fixes #1207 
fixes #1209
fixes #1229 
fixes #1235 
> Add members 2019-09-30

- config/kubernetes/org.yaml
fixes #1230
fixes #1234 
fixes #1238 
> Add members 2019-10-01

- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
ref: https://github.com/kubernetes/org/issues/1233
> Add teams for the discuss-theme repo.

- config/kubernetes-sigs/org.yaml
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>
/assign @akutz
> add myself as an admin to sigs.k8s.io/cluster-api-provider-vsphere

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1244  
fixes #1249 
fixes #1251 
fixes #1252 
fixes #1253 
> Add members 2019-10-02

- config/kubernetes/sig-release/teams.yaml
As Release Lead, I'll need to update the milestones on issues, PRs, and enhancements where appropriate.
/assign @tpepper
/sig release
> Add guineveresaenger to milestone maintainers

- config/kubernetes/org.yaml
> Add members 2019-10-03

- config/kubernetes/org.yaml
/cc @nikhita @parispittman @dims @spiffxp @derekwaynecarr @timothysc
> Update steering committee GitHub team

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1239 
Fixes #1260 
Fixes #1261 
> Add members 2019-10-04

- config/kubernetes/org.yaml
> Add members 2019-10-05

- config/kubernetes/org.yaml
> Add members 2019-10-06

- config/kubernetes/sig-release/teams.yaml
Request to be added as milestone maintainer for 1.17 release.
/cc @alenkacz
> Add hasheddan as a milestone maintainer for 1.17

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1269 
Fixes #1270 
Fixes #1273
Fixes #1274
Fixes #1276
Fixes #1277
> Add members 2019-10-08

- config/kubernetes/sig-release/teams.yaml
Added to be able to do tasks required of Release Notes team
> Added evillgenius75 to milestone maintainers

- .bazelrc
> Use --config=remote in ci

- config/kubernetes/org.yaml
Added this as per conversation on https://github.com/kubernetes/org/issues/1283
> Adding myself to maintainers of k/dns repo

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1291
Fixes #1289
Fixes #1287
Fixes #1285
> Add members 2019-10-11

- config/kubernetes/org.yaml
> Add members 2019-10-12

- config/kubernetes-sigs/org.yaml
> Add ksubrmnn to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1297 
Fixes #1300 
Fixes #1301
Fixes #1309 
> Add members 2019-10-15

- config/kubernetes-sigs/org.yaml
> add hwdef to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1320 
Fixes #1315 
Fixes #1240 
> Add members 2019-10-17

- config/kubernetes/sig-release/teams.yaml
Request to be added as milestone maintainer for 1.17 release.
/cc @alenkacz
> Add droslean as a milestone maintainer for 1.17

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1307 
fixes #1312 
fixes #1322 
fixes #1324 
fixes #1325 
fixes #1326 
> Add members 2019-10-22

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Signed-off-by: Chuck Ha <chuckh@vmware.com>
> Adds chuckha to cluster-api-maintainers list

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1330
Fixes https://github.com/kubernetes/org/issues/1331
Fixes https://github.com/kubernetes/org/issues/1332
> Add members 2019-10-24

- config/kubernetes/org.yaml
> Add dvonthenen (myself 😃) to vsphere admins

- config/kubernetes/org.yaml
ref: https://github.com/kubernetes/community/pull/4195
> Update code-of-conduct gh team

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1335
Fixes https://github.com/kubernetes/org/issues/1337
Fixes https://github.com/kubernetes/org/issues/1339
Fixes https://github.com/kubernetes/org/issues/1340
> Add members 2019-10-25

- config/kubernetes-sigs/org.yaml
Added my account to the members list, as discussed with @jeefy 
Thanks!
cc. @jeefy  @mrbobbytables
> added cartyc to member list

- config/kubernetes/sig-release/teams.yaml
> Add 1.17 docs lead to milestone maintainers

- config/kubernetes/org.yaml
> Add members 2019-10-28

- config/kubernetes-incubator/org.yaml
> Remove GitHub team for spartakus

- config/kubernetes-sigs/org.yaml
Note: I am already a Kubernetes org member
Fixes https://github.com/kubernetes/org/issues/1348
> Add jiatongw to kubernetes-sigs org

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1350 
fixes #1351 
fixes #1357 
fixes #1360 
fixes #1361 
> Add members 2019-10-30

- config/kubernetes-sigs/org.yaml
Note: I am already a Kubernetes org member
> add aramase to kubernetes-sigs org

- config/kubernetes/org.yaml
Updates the kompose teams outdated admin and maintainers.
> Updates kompose teams

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
> Add members 2019-10-31

- config/kubernetes/sig-instrumentation/teams.yaml
> Add serathius to SIG instrumentation

- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
> Add members 2019-11-04

- config/kubernetes-sigs/org.yaml
> Give janetkuo admin access to the application repo

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1387 
fixes #1390 
fixes #1399 
> Add members 2019-11-07

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1403 
fixes #1406 
fixes #1407 
fixes #1409 
fixes #1410 
fixes #1412 
fixes #1413 
> Add members 2019-11-13

- config/kubernetes-sigs/org.yaml
Note: I am already a Kubernetes org member.
> add kkmsft to kubernetes-sigs org

- config/kubernetes/org.yaml
```
{"client":"github","component":"peribolos","file":"external/io_k8s_test_infra/prow/github/client.go:522","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateOrgMembership(kubernetes, ellenkorbes, false)","time":"2019-11-15T21:30:56Z"}
```
> Remove ellenkorbes

- config/kubernetes/org.yaml
Fixes #1416
Fixes #1417
Fixes #1419
> Add members 2019-11-16

- config/kubernetes-sigs/org.yaml
descehduler -> descheduler 🤦‍♂ 
> Correct descheduler-maintainers team name.

- config/kubernetes/org.yaml
Fixes #1408
Fixes #1426
Fixes #1427
> Add members 2019-11-19

- config/kubernetes/org.yaml
> Add members 2019-11-21

- config/kubernetes-sigs/org.yaml
Fixes #1438 
/area github-membershio
> Add members 2019-11-24

- config/kubernetes-client/org.yaml
I am already a part of `kubernetes` org.
Contributions to kubernetes-client
---
https://github.com/kubernetes-client/gen/issues/133
https://github.com/kubernetes-client/gen/pull/134
https://github.com/kubernetes-client/python/issues/952
https://github.com/kubernetes-client/python/issues/976
https://github.com/kubernetes-client/python/issues/994
https://github.com/kubernetes-client/python/pull/978
https://github.com/kubernetes-client/python-base/issues/118
https://github.com/kubernetes-client/python-base/pull/172
https://github.com/kubernetes-client/python-base/pull/173
/cc @roycaihw
> Add palnabarun to kubernetes-client org

- config/kubernetes/org.yaml
> Add members 2019-11-27

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1445
Fixes #1446
Fixes #1450
Fixes #1451
Fixes #1452
> Add members 2019-12-03

- config/kubernetes/sig-docs/teams.yaml
Add owners and reviewers for RU transaltion team.
Related to kubernetes/website#16404
> Add sig-docs-ru members

- config/kubernetes/sig-docs/teams.yaml
I forgot to replace some members in this PR(#1425)
> Update ja l10n member

- config/kubernetes/sig-docs/teams.yaml
This PR adds write permissions to @daminisatya as docs release lead for 1.17.
/assign @jimangel @Bradamant3
> Add write permissions to 1.17 docs release lead

- config/kubernetes/sig-docs/teams.yaml
#1418 describes why I have permissions, but I lost access due to the #1375 update
please let me know if I'm wrong.
> Update access to xichengliudui

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1469
Fixes #1464
Fixes #1463
Fixes #1470
> Add members 2019-12-08

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Rename bclau to claudiubelu

- config/config_test.go
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/org.yaml
- config/kubernetes-retired/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Set billing e-mails on orgs to GH admin team

- config/kubernetes/sig-docs/teams.yaml
/assign @zacharysarah @jimangel
> add fabriziopandini as website.it approver

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1457 
fixes #1460 
fixes #1466
fixes #1476
fixes #1477
fixes #1478
fixes #1480
> Add members 2019-12-16

- config/kubernetes-sigs/org.yaml
Am already a member of kubernetes.
Context: https://github.com/kubernetes/org/issues/1491
> Add jefftree to kubernetes-sigs

- config/kubernetes/org.yaml
/cc @maciaszczykm @floreks @jeefy
> Sync dashboard-maintainers with OWNERS_ALIASES

- config/kubernetes-sigs/org.yaml
Refers to https://github.com/kubernetes/org/issues/1484
cc @Random-Liu @feiskyer @mrunalp @nikhita
> Grant saschagrunert access to cri-tools

- config/kubernetes/org.yaml
Fixes #1494
Fixes #1487
Fixes #1475
> Add members 2019-12-18

- config/kubernetes-incubator/org.yaml
ref https://github.com/kubernetes/org/issues/1488
> Remove rktlet teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-12-23

- config/kubernetes/org.yaml
> Add members 2019-12-24

- config/kubernetes/org.yaml
> Add members 2019-12-29

- config/kubernetes-sigs/org.yaml
> Add hasbro17 to kubernetes-sigs org.

- config/kubernetes/sig-docs/teams.yaml
Add @ysyukr to sig-docs-ko-reviewes.
related with kubernetes/website#18209
> Add member to sig-docs-ko-reviews.

- config/kubernetes-sigs/sig-vmware/teams.yaml
This PR adds new members to the OWNERS file.
> Modify vsphere-csi-driver OWNERS file

- config/kubernetes/sig-docs/teams.yaml
Signed-off-by: Brad Topol <btopol@us.ibm.com>
> I am a chair shadow

- config/kubernetes/sig-docs/teams.yaml
I will be part of the 1.18 docs release team. Having milestone permissions will help me in maintaining milestones with ease.
Signed-off-by: vineeth <vineethpothulapati@outlook.com>
@zacharysarah
> Requesting for website milestone maintainers permissions

- config/kubernetes-sigs/org.yaml
Add youngnick to the kubernetes-sigs org so that I can work on https://github.com/kubernetes-sigs/service-apis.
@bowei can confirm I need it 😄
> Add youngnick to kubernetes-sigs org

- config/kubernetes/org.yaml
fixes #1527 
fixes #1532
fixes #1533
fixes #1534
fixes #1538 
fixes #1539 
fixes #1540 
fixes #1542
fixes #1543
> Add members 2020-01-10

- config/kubernetes/sig-release/teams.yaml
Adding @helayoty @kikisdeliveryservice and @johnbelamaric as 1.18 RT Enhancement Shadows to milestone maintainers for the 1.18 release. Also updated @palnabarun from 1.17 -> 1.18 
🎊 
Signed-off-by: Jeremy Rickard <rickardj@vmware.com>
> Add 1.18 enhancement shadows

- config/kubernetes/sig-release/teams.yaml
@jpreese and @hrishin are now k8s members.
> Update ci-signal team's members

- config/kubernetes/sig-docs/teams.yaml
Updates k/org based on:
- https://github.com/kubernetes/website/pull/18501
- https://github.com/kubernetes/website/pull/18398
> Update SIG Docs team membership

- config/kubernetes/sig-docs/teams.yaml
This PR is related to https://github.com/kubernetes/website/pull/18419
> Add Polish localization team

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1536
Fixes #1547
Fixes #1549
Fixes #1551
Fixes #1552
Fixes #1553
Fixes #1557
> Add members 2019-01-13

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/sig-scheduling/teams.yaml
> Update teams for cluster-capacity

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1550
Fixes #1555
Fixes #1556
Fixes #1558
Fixes #1560
Fixes #1562
Fixes #1567
> Add members 2020-01-16

- config/kubernetes-sigs/org.yaml
> Add vishakha to kubernetes-sig

- config/kubernetes/sig-docs/teams.yaml
Giving the release lead, Vineeth, write permissions on k/website.
> giving release lead write access

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2019-01-20

- config/kubernetes/sig-docs/teams.yaml
> remove me from teams.yaml

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1554
Fixes https://github.com/kubernetes/org/issues/1576
Fixes https://github.com/kubernetes/org/issues/1575
Fixes https://github.com/kubernetes/org/issues/1568
Fixes https://github.com/kubernetes/org/issues/1580
Fixes https://github.com/kubernetes/org/issues/1581
Fixes https://github.com/kubernetes/org/issues/1587
Fixes https://github.com/kubernetes/org/issues/1588
Fixes https://github.com/kubernetes/org/issues/1589
> Add members 2020-01-23

- config/kubernetes-sigs/provider-azure/teams.yaml
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/OWNERS_ALIASES#L23
cc @justaugustus
> Add CecileRobertMichon in cluster-api-provider-azure-admins

- config/kubernetes/sig-release/teams.yaml
xref: kubernetes/sig-release#933
Signed-off-by: alejandrox1 <alarcj137@gmail.com>
> Updated RT lead shadows

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/sig-instrumentation/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1597
> Migrate teams for custom-metrics-apiserver

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1583
> Rename teams for cluster-addons

- config/kubernetes-client/OWNERS
- config/kubernetes-client/org.yaml
- config/kubernetes-csi/OWNERS
- config/kubernetes-csi/org.yaml
- config/kubernetes-incubator/OWNERS
- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/OWNERS
- config/kubernetes/OWNERS
Implements https://github.com/kubernetes/community/pull/4463
/hold
until https://github.com/kubernetes/community/pull/4463 and https://github.com/kubernetes/community/pull/4462 merge
/cc @kubernetes/owners @justaugustus @nzoueidi @idealhack
> Grant approval privileges to NMCs for active orgs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes https://github.com/kubernetes/org/issues/1595
fixes https://github.com/kubernetes/org/issues/1579
fixes https://github.com/kubernetes/org/issues/1596
fixes https://github.com/kubernetes/org/issues/1604
fixes https://github.com/kubernetes/org/issues/1606
> github-membership: add members 2020-01-30

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1565
fixes #1607 
fixes #1610 
fixes #1611
fixes #1612
> Add members 2020-02-04

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
I'll be using this to tag the repo.
/assign @timothysc
> Add codenrhoden to image-builder-maintainers

- config/kubernetes/org.yaml
- config/kubernetes/sig-docs/teams.yaml
2019-03-13 20:43:29 -0700   21) - a1h8
2019-07-12 18:06:17 -0400  461) - JamieRachel
2018-06-21 10:12:51 -0700 1066) - xvello
2019-08-11 22:32:31 -0400  826) - ptone
2019-10-28 22:13:26 -0400  258) - devaips
2018-06-21 10:12:51 -0700  895) - ryanmcginnis
> Remove stale invites for kubernetes

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1614 
fixes #1615 
fixes #1616 
fixes #1618 
fixes #1623 
> Add members 2020-02-10

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
I need these additional permissions to cut releases, add tags, etc.
/assign @cheftako 
cc @Jefftree
> add caesarxuchao to apiserver network proxy admin

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1636
Fixes https://github.com/kubernetes/org/issues/1635
Fixes https://github.com/kubernetes/org/issues/1634
Fixes https://github.com/kubernetes/org/issues/1633
Fixes https://github.com/kubernetes/org/issues/1625
> New members (2020-02-18)

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
Signed-off-by: Vince Prignano <vincepri@vmware.com>
/assign @DirectXMan12
> Add vincepri to controller-runtime maintainers

- config/kubernetes-sigs/sig-auth/teams.yaml
> Add teams for kubernetes-sigs/secrets-store-csi-driver

- config/kubernetes/sig-instrumentation/teams.yaml
Welcome, all of you:
- @dashpole 
- @lilic
- @s-urbaniak
- @RainbowMango 
- @tariq1890
> Add sig-instrumentation members

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1624  
fixes #1637 
fixes #1640 
fixes #1641 
fixes #1642 
fixes #1646 
fixes #1649 
> Add members 2020-02-21

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
> Add vincepri as controller-tools maintainer

- config/kubernetes/sig-docs/teams.yaml
Update SIG Docs file with onlydole user, for reviews.
> Add onlydole to EN sections

- config/kubernetes-sigs/sig-windows/teams.yaml
> Add benmoss to sig-windows-tools maintainers

- config/kubernetes-client/org.yaml
2019-11-04 19:00:11 -0500  37) - guoshimin
This should be the last one to close #1627
> Remove stale invites for kubernetes-client

- config/kubernetes/sig-instrumentation/teams.yaml
I have been a part of the sig for a while and am looking for more day-to-day interaction
> add coffeepac to several of the sig-inst lists

- OWNERS_ALIASES
Removing @piosz, and adding myself and @logicalhan.
/cc @brancz 
See
- https://groups.google.com/d/msg/kubernetes-sig-instrumentation/IZWt4loyx7M/svIYpz0kCwAJ
- https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit
> Update SIG Instrumentation leads

- config/kubernetes-sigs/org.yaml
I'm already a member of the kubernetes org and this PR is to request membership to the kubernetes-sigs org
> Add rajansandeep to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1690 
fixes #1694 
fixes #1695 
fixes #1698 
fixes #1699 
fixes #1702
> Add members 2020-03-11

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1703 
fixes #1707 
fixes #1709 
fixes #1711 
fixes #1712
fixes #1713 
fixes #1719 
> Add members 2020-03-16

- config/kubernetes/sig-release/teams.yaml
> Add serathius as milestone maintainer for sig instrumentation

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
> Remove alvaroaleman fro cluster-api-provider-digitalocean-maintainers

- config/kubernetes-client/org.yaml
Adds teams to the kubernetes-client/c repo
ref: #1700 
> Add teams for the kubernetes-client/c repo

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes: #1714 
fixes: #1724 
fixes: #1726 
fixes: #1729 
fixes: #1730 
fixes: #1732 
> Add members 2020-03-24

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
ref: https://github.com/kubernetes/org/issues/1716
> Add teams for cloud-provider-baiducloud repo

- config/kubernetes-sigs/sig-storage/OWNERS
- config/kubernetes-sigs/sig-storage/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1744, https://github.com/kubernetes/org/issues/1743
> Add GitHub teams for sig-storage repos

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1746
Fixes https://github.com/kubernetes/org/issues/1757
Fixes https://github.com/kubernetes/org/issues/1756
Fixes https://github.com/kubernetes/org/issues/1755
Fixes https://github.com/kubernetes/org/issues/1753
Fixes https://github.com/kubernetes/org/issues/1752
Fixes https://github.com/kubernetes/org/issues/1751
> Add members 2020-03-29

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
> Add GitHub teams for kubebuilder-release-tools

- OWNERS_ALIASES
- config/kubernetes/sig-docs/teams.yaml
- add @sftim
follows on from https://github.com/kubernetes/community/pull/4561
> Update SIG Docs tech leads

- config/kubernetes-csi/org.yaml
I have been maintaining external-resizer and I am one of the authors of resizing feature in k8s.
Adding myself as external-resizer maintainer. I 
/assign @jsafrane @msau42
> Add gnufied as external-resizer maintainer

- config/kubernetes/org.yaml
> Add members 2020-04-03

- config/kubernetes-client/org.yaml
/cc @brendandburns 
for managing milestones/wiki/branches
> Add yue to kubernetes java client admin

- config/kubernetes/sig-docs/teams.yaml
Add @ysyukr to sig-docs-ko-approver.
related with kubernetes/website#20094
> Add member to sig-docs-ko-approver

- config/kubernetes/sig-docs/teams.yaml
Adding myself as additional reviewers for Indonesian localization.
/cc @girikuncoro
> add wahyuoi to sig-docs-id-reviews

- config/kubernetes/org.yaml
Follow-up on https://github.com/kubernetes/kubernetes/pull/89587
> Remove apelisse from dep approvers

- config/kubernetes-sigs/org.yaml
> Add members 2020-04-09

- config/kubernetes/sig-release/teams.yaml
Requesting access to be milestone maintainer as per my involvement with the testing commons sub-project of sig testing.
Signed-off-by: alejandrox1 <alarcj137@gmail.com>
> Added alejandrox1 as milestone maintainer for SIG testing

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-testing/OWNERS
- config/kubernetes-sigs/sig-testing/teams.yaml
ref: https://github.com/kubernetes/org/issues/1783
> Add teams for kubernetes-sigs/boskos

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1689
Fixes https://github.com/kubernetes/org/issues/1780
Fixes https://github.com/kubernetes/org/issues/1784
Fixes https://github.com/kubernetes/org/issues/1787
> Add members 2020-04-14

- config/kubernetes-sigs/sig-multicluster/teams.yaml
...in order to perform kubefed releases.
> Add hectorj2f to kubefed-admins team

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1795
Fixes #1803
Fixes #1804
Fixes #1806
> Add members 2019-04-20

- OWNERS_ALIASES
- config/kubernetes/org.yaml
Ref: https://github.com/kubernetes/steering/pull/157
/hold
until https://github.com/kubernetes/steering/pull/157 is merged
> steering: switch timothysc for lachie83

- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/sig-network/teams.yaml
ref: https://github.com/kubernetes/org/issues/1823
> Migrate teams for kubernetes-incubator/cluster-proportional* repos

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1809 
fixes #1811 
fixes #1817 
fixes #1820
fixes #1821 
fixes #1825 
fixes #1826 
fixes #1830 
fixes #1831 
fixes #1832 
fixes #1833
fixes #1834 
fixes #1835 
> Add members 2020-04-23

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #1530
Fixes #1829
Fixes #1841
Fixes #1843
Fixes #1845
Fixes #1849
> Add members 2019-05-02

- config/kubernetes/sig-release/teams.yaml
Reference: https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release_team.md
/cc @onlydole @mrbobbytables @jeremyrickard 
> Add 1.19 Release Enhancements team members

- config/kubernetes/sig-release/teams.yaml
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
/cc @hkamel @RobertKielty @sayanchowdhury @VineethReddy02
> Add 1.19 CI Signal shadows to milestone maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1838 
fixes #1844 
fixes #1847 
fixes #1855 
fixes #1857 
fixes #1858 
fixes #1861 
fixes #1862 
fixes #1865 
> Add members 2020-05-09

- config/kubernetes-sigs/sig-windows/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1853
> Add GitHub teams for sig-windows-samples

- config/kubernetes-sigs/sig-windows/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1853
s/examples/samples :woman_facepalming: 
> Fix team name for sig-windows-samples

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes https://github.com/kubernetes/org/issues/1851
fixes https://github.com/kubernetes/org/issues/1863
fixes https://github.com/kubernetes/org/issues/1864
fixes https://github.com/kubernetes/org/issues/1868
fixes https://github.com/kubernetes/org/issues/1869
> github-membership: add members 2020-05-13

- config/kubernetes/org.yaml
fixes #1792 
fixes #1878 
fixes #1879 
fixes #1880 
fixes #1882 
fixes  #1884 
> Add members 2020-05-19

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1797 
fixes #1885 
fixes #1889 
fixes #1891
fixes #1893 
> Add members 2020-05-26

- config/kubernetes/sig-docs/teams.yaml
As 1.19 release docs lead, it will be helpful to have permissions to add milestones to issues/PRs :)
cc: @zacharysarah @jimangel
> Requesting permissions to add milestone

- config/kubernetes-sigs/org.yaml
Fixes: https://github.com/kubernetes/org/issues/1897
> Add pohly to the kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1877
Fixes https://github.com/kubernetes/org/issues/1898
Fixes https://github.com/kubernetes/org/issues/1899
> Add members 2020-05-28

- config/kubernetes/sig-release/teams.yaml
> Add bai as a milestone maintainer

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1905
Fixes https://github.com/kubernetes/org/issues/1913
> Add members 2020-06-02

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1890
Fixes https://github.com/kubernetes/org/issues/1915
> Add members 2020-06-04

- config/kubernetes/sig-cloud-provider/teams.yaml
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>
cc @justinsb @nckturner
> add cloud-provider-aws admin/maintainers teams for k8s.io/cloud-provider-aws

- OWNERS_ALIASES
- config/kubernetes/sig-release/teams.yaml
> update sig testing

- config/kubernetes/sig-release/teams.yaml
> Add kbruner as milestone maintainer

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/6c11ec8f0e0030819adfd8ebf669aa72cefe9024/OWNERS_ALIASES#L23
> CAPZ: add reviewers to cluster-api-provider-azure-pms

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1916
> Add members 2020-06-11

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/1927
/assign @roycaihw
> Add roycaihw to kubernetes-sigs

- config/kubernetes/sig-docs/teams.yaml
> Add reviewers and owners for website Ukrainian localization

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1926
> Add members 2020-06-15

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1936
> Add chizhg to kubernetes org

- README.md
Ref: https://github.com/kubernetes/community/pull/4864
Related: https://github.com/kubernetes/community/pull/4868
> Update slack channel and mailing list in README

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1929
> Add alonyb to kubernetes org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1946
Fixes https://github.com/kubernetes/org/issues/1947
> Add members 2020-06-24

- config/kubernetes-sigs/org.yaml
> Add gianarb to kubernetes-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-aws/teams.yaml
Adding myself to ebs csi driver maintainer list.
> Add gnufied to ebs CSI driver

- config/kubernetes/org.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
- config/kubernetes/sig-testing/teams.yaml
There are some stale invites for folks that removed themselves from the kubernetes org
> Remove stale invites

- config/kubernetes-sigs/org.yaml
> Add members 2020-06-25

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1908
Fixes https://github.com/kubernetes/org/issues/1955
Fixes https://github.com/kubernetes/org/issues/1959
> Add members 2020-06-26

- config/kubernetes-sigs/org.yaml
Signed-off-by: knight42 <anonymousknight96@gmail.com>
cc @nikhita PTAL
> Add knight42 to the kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
I'm a member of kubernetes org and would like to join kubernetes-sigs org too.  Thank you.
> Add yuanchen8911 to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #1930 
fixes #1965 
fixes #1967 
> Add members 2020-06-30

- config/kubernetes-sigs/sig-testing/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1977
> Add GitHub teams for kubetest2

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1966
Fixes https://github.com/kubernetes/org/issues/1973
Fixes https://github.com/kubernetes/org/issues/1975
> Add members 2020-07-02

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
ref: https://github.com/kubernetes/org/issues/1971
> Add members and teams for contributor-tweets repo

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/1985
/assign @hakman 
for lgtm
> Add hakman to kubernetes-sigs

- config/kubernetes-sigs/sig-aws/teams.yaml
Adding self to ebs, efs, and fsx repos.
Unsure if this is sufficient for permissions to write releases but that is the goal here. Otherwise there is only 1 active maintainer @leakingtapan making releases.
/cc @jsafrane 
/cc @leakingtapan
> Add wongma7 to ebs, efs, and fsx maintainers

- config/kubernetes/sig-docs/teams.yaml
/cc @jimangel 
/cc @zacharysarah
> Add celestehorgan to sig-docs-en-owners, reviewers, website-milestone-maintainers

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1990
> Add emedina to the kubernetes org

- config/kubernetes/sig-docs/teams.yaml
@emedina, welcome to the Spanish localization team!
> Add emedina as spanish team reviewer

- config/kubernetes/org.yaml
See the current official membership here:
https://github.com/kubernetes/security/blob/master/OWNERS_ALIASES
> Update PSC to match current membership

- config/kubernetes-sigs/org.yaml
Fixes #2006 
/cc @zacharysarah 
/cc @tengqm
> Add onlydole to kubernetes-sigs

- config/kubernetes/sig-cluster-lifecycle/teams.yaml
Adding myself to the sig-cluster-lifecycle team per email: https://groups.google.com/forum/#!msg/kubernetes-sig-cluster-lifecycle/OZPzQ5Niofc/oWHWDp7iBQAJ
/cc @neolit123
> add cpanato to the sig-cluster-lifecycle team

- config/kubernetes/org.yaml
> Add members 2020-07-09

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
> Add randomvariable as a CAPV maintainer

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- Add @devigned and @nader-ziada as maintainers and admins 👏 
- Add @cpanato as reviewer 🎉 
- Remove @rbitia as PM 😢 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/OWNERS_ALIASES
> Update CAPZ maintainers and PMs

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/2016
Fixes https://github.com/kubernetes/org/issues/2017
> Add members 2020-07-14

- config/kubernetes-sigs/sig-testing/teams.yaml
ref: https://github.com/kubernetes/org/issues/2026
/cc @BenTheElder @spiffxp
> Add GitHub teams for secret-sync-rotation

- config/kubernetes/sig-docs/teams.yaml
Cleaning up team repo based on k/website OWNERS file and current approver status.
Removing:
- Rajakavitha1
- daminisatya
- stewart-yu
- jaredbhatti
- bradamant3
- any release leads with write access
@onlydole, I removed you but let me know if you require write-level access for any reason.
Thanks!
/cc @zacharysarah @kbarnard10
> updating permissions

- config/kubernetes-sigs/provider-azure/teams.yaml
/assign @feiskyer @justaugustus
thanks
> add andyzhangx to cloud-provider-azure-admins

- config/kubernetes-sigs/sig-service-catalog/teams.yaml
Fixes #2019 
/assign @carolynvs
> Create GitHub team for minibroker repo

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes: #2033 
fixes: #2034 
fixes: #2035 
> Add members 2020-07-16

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2040
Fixes https://github.com/kubernetes/org/issues/2042
Fixes https://github.com/kubernetes/org/issues/2028
(this might need your PR to have the script re-run to fix rebase conflicts :/)
> Add members 2020-07-20

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2043
> Add mattcary to kubernetes org

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2054
> Add b01901143 to kubernetes, kubernetes-sigs

- config/kubernetes-sigs/sig-storage/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2039
> Add GitHub teams for COSI repos

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2058
Fixes https://github.com/kubernetes/org/issues/2059
> Add members 2020-07-24

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
> Add members 2020-08-01

- config/kubernetes-sigs/sig-vmware/teams.yaml
adding myself as admin user for vsphere-csi-driver
I need admin access to help configure webhook on this repository to help our end to end test team.
@codenrhoden @frapposelli Can you help approve this PR?
cc: @andrewsykim @xing-yang
> adding admin user for vsphere-csi-driver

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2068
Fixes https://github.com/kubernetes/org/issues/2078
Fixes https://github.com/kubernetes/org/issues/2083
Fixes https://github.com/kubernetes/org/issues/2084
> Add members 2020-08-06

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2087
> Add michaelkolber to kubernetes org

- config/kubernetes-sigs/sig-release/teams.yaml
Fixes https://github.com/kubernetes/org/issues/1875
/assign @saschagrunert
> Add GitHub teams for mdtoc

- config/kubernetes-client/org.yaml
- config/kubernetes-incubator/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
- config/kubernetes/sig-multicluster/teams.yaml
- config/kubernetes/sig-node/teams.yaml
- config/kubernetes/sig-testing/teams.yaml
ref: #2076 
This was generated with the same script used for the previous clean up in #2047
/assign @cblecker @nikhita 
/hold
> Remove inactive members - August

- config/kubernetes-sigs/sig-service-catalog/teams.yaml
Ref: https://github.com/kubernetes/org/issues/1970
/assign @idvoretskyi 
for lgtm
> Add GitHub team for mcs-api

- config/kubernetes-csi/org.yaml
Ref: https://github.com/kubernetes/org/issues/1350
> Add ZeroMagic to kubernetes-csi

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 2020-09-12

- config/kubernetes-sigs/org.yaml
Hi. I'm adding myself to the k/sigs org to streamline the release notes publishing process.
Thanks !
> Add @puerco to kubernetes-sigs org

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2070
Fixes https://github.com/kubernetes/org/issues/2097
Fixes https://github.com/kubernetes/org/issues/2103
Fixes https://github.com/kubernetes/org/issues/2105
cc: @mrbobbytables @nikhita
> Add members 08-14-2020

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes: https://github.com/kubernetes/org/issues/2093
fixes: https://github.com/kubernetes/org/issues/2107
fixes: https://github.com/kubernetes/org/issues/2111
fixes: https://github.com/kubernetes/org/issues/2112
/assign @mrbobbytables @nikhita
> Add members 08 17 2020

- config/kubernetes/sig-release/teams.yaml
Add myself, remove @piosz 
/cc @logicalhan @dashpole @mrbobbytables
> Update Instrumentation milestone setters

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2116 
/assign @mrbobbytables @nikhita 
> Addmembers 08-23-2020

- config/kubernetes-sigs/org.yaml
My contributions to service-catalog SIG:
- https://github.com/kubernetes-sigs/service-catalog/pull/2829
- https://github.com/kubernetes-sigs/go-open-service-broker-client/pull/163
- https://github.com/kubernetes-sigs/go-open-service-broker-client/pull/164
- https://github.com/kubernetes-sigs/minibroker/pull/104
- https://github.com/kubernetes-sigs/minibroker/issues/79
- https://github.com/kubernetes-sigs/go-open-service-broker-client/issues/165
> Add jhvhs as a member of kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Fixes https://github.com/kubernetes/org/issues/2133
> Add thebsdbox as admin/maintainer for capp

- config/kubernetes-sigs/org.yaml
fixes #2128
fixes #2130 
/hold
(holding for closing more requests in a batch)
> Add member 2020-08-24

- config/kubernetes-sigs/sig-release/teams.yaml
ref: https://github.com/kubernetes/org/issues/2131
> Add GitHub teams for downloadkubernetes

- config/kubernetes/sig-release/teams.yaml
> Add sig-storage TLs to milestone maintainers

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2144
(Didn't notice any other eligible requests while I was doing this)
> Add e-blackwelder to kubernetes org

- config/kubernetes-sigs/org.yaml
Fixes #2146 
Fixes #2149 
/hold
(holding for closing more requests in a batch)
> Addmembers 08-28-2020 

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2147
Fixes #2150 
Fixes #2151
Fixes #2153
> Add members 09-01-2020

- config/kubernetes/org.yaml
Fixes #2135 
Fixes #2157 
Fixes #2159 
cc: @palnabarun @ameukam 
/assign @nikhita @mrbobbytables
> Add Members 09 01 2020

- config/kubernetes-sigs/provider-azure/teams.yaml
/assign @feiskyer @justaugustus thank you very much!
> add nilo19 to cloud-provider-azure admin

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Signed-off-by: Vince Prignano <vincepri@vmware.com>
> Add fabriziopandini to cluster-api-maintainers group / milestone access

- config/kubernetes/org.yaml
> Add members 2020-09-03

- config/kubernetes-client/org.yaml
Fixes https://github.com/kubernetes/org/issues/2169
for lgtm
> Remove mbohlool from java-admins

- config/kubernetes/org.yaml
> add answer1991 to kubernetes/kubernetes member

- config/kubernetes-sigs/sig-release/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2172
> Add GitHub teams for zeitgeist

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 09-11-2020

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Adding myself as an additional admin/maintainer for cluster-api-provider-packet
/assign @deitch @thebsdbox
> Add detiber to cluster-api-provider-packet-{admins|maintainers}

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
> Add teams for apiserver-runtime repo

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
**Description**
- Add @gabbifish and @camilamacedo86 as maintainers for controller-tools, controller-runtime and kubebuilder.
> add gabbifish and camilamacedo86 as maintainers

- config/kubernetes-sigs/org.yaml
Fixes #2194 
Fixes #2173 
Fixes #2186 
/hold for accommodating more requests 
/assign @nikhita @mrbobbytables
> Add members 09-18-2020

- config/kubernetes/sig-release/teams.yaml
/cc @kubernetes/release-team-leads 
/cc @bai 
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>
> adding droslean as a milestone maintainer

- config/kubernetes/org.yaml
Fixes #2200 
Fixes #2201 
Fixes #2199 
Fixes #2204 
Fixes #2205 
/hold 
cc: @ameukam @palnabarun
> Add members 09-22-2020

- config/kubernetes/org.yaml
> Add members 2020-09-23

- config/kubernetes/org.yaml
fixes #2211
fixes #2212
fixes #2215
> Add members 2020-09-23 Part 2

- config/kubernetes/sig-release/teams.yaml
/cc @kubernetes/release-team-leads
/cc @bai
> Adding erismaster as a milestone maintainer

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add members 09-23-2020 part 3

- config/kubernetes/org.yaml
Fixes #2220 
/hold
(Wait for few hours to group org requests)
> Add members 09-24-2020

- config/kubernetes/sig-release/teams.yaml
/cc @kubernetes/release-team-leads
/cc @bai
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
> Add sayanchowdhury as the milestone maintainer

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-docs/teams.yaml
> membership: Add irvifa to reference-docs-maintainers

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2224 
Fixes #2229
Fixes #2234
Fixes #2236
> Add members 10 02 2020

- config/kubernetes-sigs/org.yaml
> Add rikatz to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
> Add members 10-06-2020

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2247
/assign @neolit123
> Add GitHub teams for cluster-api-provider-nested

- config/kubernetes/org.yaml
fixes #2248 
fixes #2252 
/cc @savitharaghunathan @ameukam 
/assign @mrbobbytables @nikhita
> Add members 2020-10-10

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2250 
fixes #2254
fixes #2255 
/cc @savitharaghunathan @ameukam 
/assign @nikhita @mrbobbytables 
/hold
(for a few more in the batch)
> Add members 2020-10-13

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2259 
fixes #2261
/cc @savitharaghunathan @ameukam 
/assign @mrbobbytables @nikhita
> Add members 2020-10-14

- config/kubernetes-sigs/org.yaml
fixes #2264
fixes #2266
/cc @savitharaghunathan @ameukam 
/assign @nikhita @mrbobbytables
> Add members 2020-10-14 Part 2

- config/kubernetes-csi/org.yaml
I am already approver of these two repos
> add andyzhangx as admin of nfs and csi-proxy repos

- config/kubernetes-sigs/sig-windows/teams.yaml
Helping out @benmoss with maintenance and releases.
cc: @marosset @michmike
> Add jsturtevant to sig-windows-tools-maintainers

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2251 
Fixes #2265 
Fixes #2189 
/hold (for adding more requests for the day)
cc: @palnabarun @ameukam 
/assign @nikhita @mrbobbytables
> Add members 10-16-2020

- config/kubernetes/sig-cloud-provider/teams.yaml
update sig-cloud-provider-alibaba-admins
> add gujingit to sig-cloud-provider-alibaba-admins

- config/kubernetes-sigs/sig-testing/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2271
/assign @spiffxp
> Add GitHub teams for e2e-framework

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2269 
Fixes #2274
Fixes #2275
> Add members 10-21-2020

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-service-catalog/teams.yaml
- config/kubernetes/sig-service-catalog/teams.yaml
Mateusz is leaving the project. We've selected Konstantin as the new co-chair
@mszostok 
@jhvhs
> replace mszostok with jhvhs as sig-service-catalog chair

- config/kubernetes-sigs/sig-storage/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2289
for lgtm
> Add GitHub teams for cosi-api repo

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2284 
Fixes #2283 
Fixes #2282 
cc: @ameukam @palnabarun
> Add members 10-27-2020

- config/kubernetes-sigs/sig-cli/teams.yaml
> Add Phani to as maintainer to kustomize and cli-utils

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2290
fixes #2295
fixes #2297
fixes #2306
fixes #2307
> Add members 2020-11-04

- config/kubernetes/org.yaml
Fixes #2313
Fixes #2294
Fixes #2309
> Add members 11 06 2020

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2317 
Fixes #2318 
/hold for adding more org membership requests
cc: @ameukam @palnabarun
> Add members 11-09-2020

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
> Add Members 11-11-2020

- config/kubernetes-sigs/sig-windows/teams.yaml
- Replacing PatrickLack with marosset for admin groups
- Adding jsturtevant to maintainers groups
> Updating admins/maintainers for sig-windows repos

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2340 
Fixes #2341 
Fixes #2339 
Fixes #2338 
> Add Members 11-24-2020 - Batch 1

- OWNERS_ALIASES
- config/kubernetes/sig-release/teams.yaml
ref: https://github.com/kubernetes/community/pull/5322
Following https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md#leadership-changes
> Add eddiezane to sig-cli-leads

- config/kubernetes-sigs/org.yaml
I am working on scheduler-plugins, I would like to be a member to help me send PRs more conveniently.
#2335
> Add lianghao as a member of kubernetes-sigs

- config/kubernetes/org.yaml
I think this is accurate at this point 🙃
xref: https://github.com/kubernetes/org/issues/2332#issuecomment-729681652 https://github.com/kubernetes/org/pull/2330
> Add bentheelder to Kubernetes maintainers team.

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2353 
Fixes #2355 
Fixes #2356 
Fixes #2358 
> Add Members 12-03-2020

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2365
Fixes https://github.com/kubernetes/org/issues/2354
Fixes https://github.com/kubernetes/org/issues/2352
> Add members 12-04-2020

- config/kubernetes/sig-docs/teams.yaml
Temporary adding myself to the `website-maintainers` team for write access to k/website repo for the release preparation/release day.
/assign @jimangel @irvifa @kbarnard10
> Add annajung to website-maintainers team for 1.20 release

- config/kubernetes-sigs/org.yaml
> Add tallclair to kubernetes-sigs

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
> Add alvaroaleman to controller-runtime maintainers

- config/kubernetes-sigs/sig-node/teams.yaml
Add ArangoGutierrez as NFD_operator maintainer
> Add ArangoGutierrez to  NFD_operator maintainers

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
> cluster-api: ncdc stepping down from maintainership

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2381 
Fixes #2379 
Fixes #2378
Fixes #2376 
Fixes #2373 
Fixes #2369 
Fixes #2362 
Fixes #2333 
> Add Members 12-14-2020

- config/kubernetes/sig-docs/teams.yaml
Add @habibrosyad to sig-docs-id-reviews
> Add habibrosyad to sig-docs-id-reviews

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2331 
Fixes #2383 
Fixes #2386 
Fixes #2388 
Fixes #2392 
> Add Members 12-18-2020

- OWNERS_ALIASES
- config/kubernetes-sigs/sig-security/OWNERS
- config/kubernetes-sigs/sig-security/teams.yaml
- config/kubernetes/sig-security/OWNERS
- config/kubernetes/sig-security/teams.yaml
added sig-security OWNERS and teams and corrected capitalization of my own GitHub username
> add sig-security OWNERS and teams

- config/kubernetes/org.yaml
fixes #2391 
fixes #2396 
fixes #2398 
> Add members 2021-01-04

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2404
Fixes https://github.com/kubernetes/org/issues/2406
Fixes https://github.com/kubernetes/org/issues/2408
Fixes https://github.com/kubernetes/org/issues/2409
Fixes https://github.com/kubernetes/org/issues/2397
Fixes https://github.com/kubernetes/org/issues/2403
Fixes https://github.com/kubernetes/org/issues/2402
> Add members 2021-01-13

- config/kubernetes/org.yaml
Fixes #2370 
Fixes #2413 
Fixes #2418 
/hold until EOD 
> Add Members 01-14-2021

- config/kubernetes-sigs/sig-windows/teams.yaml
- config/kubernetes/sig-release/teams.yaml
- config/kubernetes/sig-windows/teams.yaml
as per kubernetes/community#5386, i am stepping down from sig-windows chair.
updating with the new chairs and TLs for sig-windows
Signed-off-by: Michael Michael michmike@cs.stanford.edu
> michmike vacating sig-windows chair position

- config/kubernetes/org.yaml
Fixes #2426 
Fixes #2424 
Fixes #2422 
Fixes #2421 
/hold until EOD for any more requests
cc: @ameukam @palnabarun
> Add Members 01-15-2021

- config/kubernetes/org.yaml
Fixes #2428 
Fixes #2429 
Fixes #2420 
Fixes #2432 
/hold until EOD for adding more org requests
>  Add Members 01-16-2021

- config/kubernetes/sig-docs/teams.yaml
ref: https://github.com/kubernetes/website/issues/24170
> cleanup docs teams

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2430
Fixes https://github.com/kubernetes/org/issues/2431
Fixes https://github.com/kubernetes/org/issues/2434
Fixes https://github.com/kubernetes/org/issues/2435
> Add members 2021-01-19

- config/kubernetes/org.yaml
Fixes #2440 
Fixes #2436 
Fixes #2444
/hold until EOD for adding more requests
> Add Members 01-19-2021 - Batch 2

- config/kubernetes/sig-cluster-lifecycle/teams.yaml
Add myself to kops-maintainers as I am already an approver of k8s/kops.
> Add olemarkus to kops-maintainers

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-cli/teams.yaml
To address #2447
@pwittrock for +1, please and thankyou!
> Add natasha41575 to kubernetes-sigs/sig-cli

- config/kubernetes/org.yaml
Fixes #2446
Fixes #2454
Fixes #2455 
Fixes #2459
/hold
/assign
/area github-management
> Add members 2021-01-25

- OWNERS_ALIASES
- config/kubernetes/sig-contributor-experience/teams.yaml
Ref: https://github.com/kubernetes/community/issues/5442
/hold
until https://github.com/kubernetes/community/pull/5443 merges
/cc @alisondy @castrojo @mrbobbytables
> sig-contribex: add alisondy to OWNERS and teams

- config/kubernetes-client/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-api-machinery/teams.yaml
- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
- config/kubernetes/org.yaml
- config/kubernetes/provider-openstack/teams.yaml
- config/kubernetes/sig-api-machinery/teams.yaml
- config/kubernetes/sig-auth/teams.yaml
- config/kubernetes/sig-cloud-provider/teams.yaml
- config/kubernetes/sig-docs/teams.yaml
- config/kubernetes/sig-multicluster/teams.yaml
- config/kubernetes/sig-scalability/teams.yaml
- config/kubernetes/sig-scheduling/teams.yaml
- config/kubernetes/sig-storage/teams.yaml
- config/kubernetes/sig-testing/teams.yaml
These members have had no activity since July 1st 2019
/github-membership
/hold
ref #2456
> Remove inactive members - Jan 2021

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2463
Fixes https://github.com/kubernetes/org/issues/2467
Fixes https://github.com/kubernetes/org/issues/2474
Fixes https://github.com/kubernetes/org/issues/2475
Fixes https://github.com/kubernetes/org/issues/2478
> Add members 2021-02-02

- config/kubernetes/org.yaml
Fixes #2472 
Fixes #2480 
Fixes #2481 
Fixes #2483 
/cc @savitharaghunathan @ameukam
> Add members 2021-02-08

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2485 
Fixes #2486 
Fixes #2488 
Fixes #2489 
Fixes #2493 
Fixes #2494 
Fixes #2495 
> Add Members 02-11-2021

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
> kubernetes-sigs/sig-api-machinery: add estroz to kubebuilder-admins

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/1995
Fixes https://github.com/kubernetes/org/issues/2498
Fixes https://github.com/kubernetes/org/issues/2500
Fixes https://github.com/kubernetes/org/issues/2496
Fixes https://github.com/kubernetes/org/issues/2501
> Add members 2021-02-16

- config/kubernetes/org.yaml
> Remove dankohn from Kubernetes org

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2511
Fixes https://github.com/kubernetes/org/issues/2508
Fixes https://github.com/kubernetes/org/issues/2507
Fixes https://github.com/kubernetes/org/issues/2505
Fixes https://github.com/kubernetes/org/issues/2512
> Add members 2021-02-19

- config/kubernetes-sigs/sig-auth/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2516
for lgtm
> Add GitHub teams for hierarchical-namespaces

- config/kubernetes-sigs/org.yaml
Add instrumentation members k8s-sigs.
> add members to k8s-sigs

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2519
Fixes https://github.com/kubernetes/org/issues/2515
Fixes https://github.com/kubernetes/org/issues/2514
Fixes https://github.com/kubernetes/org/issues/2520
> Add members 2021-02-26

- config/kubernetes-sigs/wg-policy/teams.yaml
Update membership to match: https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/OWNERS
> Add rficcaglia to wg-policy-prototypes members

- config/kubernetes/sig-testing/teams.yaml
Adding myself to test-infra-admins for oncall
> Add mpherman2 to test-infra-admins

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/2528
Fixes https://github.com/kubernetes/org/issues/2533
Fixes https://github.com/kubernetes/org/issues/2534
> Add members 2021-03-03

- config/kubernetes-sigs/sig-release/teams.yaml
> Add teams for release-sdk, release-utils repos

- config/kubernetes-sigs/sig-contributor-experience/teams.yaml
- config/kubernetes/sig-contributor-experience/teams.yaml
ref: https://github.com/kubernetes/org/issues/2544
> Migrate contributor-site teams from kubernetes-sigs to kubernetes org

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2536
> Add tanjing2020 to kubernetes org

- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/2542
Fixes https://github.com/kubernetes/org/issues/2547
> Add members 2021-03-09

- config/kubernetes-client/org.yaml
/cc @brendandburns 
for managing/publishing images for the code-generator base..
> Adding yue to gen admins

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2551
fixes #2552 
fixes #2553  
fixes #2554  
fixes #2555  
fixes #2556 
fixes #2557
fixes #2558
fixes #2560
fixes #2561
fixes #2562
/area github-management
/cc @ameukam @savitharaghunathan
> Add members 2021-03-11

- config/kubernetes-sigs/sig-instrumentation/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2566
> Add GitHub team for k-sigs/instrumentation repo

- config/kubernetes-sigs/sig-api-machinery/teams.yaml
> kubernetes-sigs/sig-api-machinery: Add Adirio as maintainer for kubebuilder and kubebuilder-release-tools

- config/kubernetes-csi/org.yaml
Ref: https://github.com/kubernetes/org/issues/2568
> Remove GitHub teams for k-csi/drivers repo

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2565
Fixes https://github.com/kubernetes/org/issues/2569
Fixes https://github.com/kubernetes/org/issues/2576
Fixes https://github.com/kubernetes/org/issues/2577
> Add members 2021-03-16

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2487 
Fixes #2572
Fixes #2573
Fixes #2574
Fixes #2582
Fixes #2584
Fixes #2586
cc: @palnabarun @nikhita @mrbobbytables
> Add Members 03-23-2021

- config/kubernetes-sigs/sig-cli/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2461
/assign @starpit
> Add GitHub teams for kui repo

- config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml
Match recent updates to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/OWNERS_ALIASES
/assign @nader-ziada @devigned
> Update cluster-api-provider-azure teams

- config/kubernetes-sigs/sig-aws/teams.yaml
Since d-nishi is inactive, add self to replace.
> Add self to aws-ebs-csi-driver-admins and remove inactives

- config/kubernetes-sigs/sig-instrumentation/teams.yaml
> Add dgrisonnet to custom-metrics-apiserver and prometheus-adapter maintainers

- OWNERS_ALIASES
- config/kubernetes/sig-windows/teams.yaml
- Adds specific group for leads
- Updates OWNERS_ALIASES
> Update SIG Windows Leads

- config/kubernetes/org.yaml
cc @cheftako @jpbetz 
Ask for maintainers access to version the repo (via tagging/branching).
> Add cheftako, cici37, jpbetz to cloud-provider-gcp-maintainers

- config/kubernetes-csi/org.yaml
Ref: https://github.com/kubernetes/org/issues/2592, https://github.com/kubernetes/org/issues/2591
> Add GitHub teams for volume-populator subproject repos

- config/kubernetes/org.yaml
Ref: https://github.com/kubernetes/org/issues/1499
> Remove GitHub teams for cluster-registry

- config/kubernetes/org.yaml
> Update kube-state-metrics maintainer list

- config/kubernetes/org.yaml
updating CoCC member list with new member names
> Update Kubernetes Code of Conduct Committee names

- config/kubernetes/sig-cluster-lifecycle/teams.yaml
- config/kubernetes/sig-release/teams.yaml
Thanks to the help of all the friends in the k8s community, I am now a member of [kubeadm OWNERS](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/OWNERS).
I hope to join these teams for better cooperation.
/cc @nikhita @neolit123 @fabriziopandini
> Add SataQiu into kubeadm-maintainers and milestone-maintainers teams

- config/kubernetes-sigs/sig-aws/teams.yaml
Add self as aws-ebs-csi-driver maintainer .
> add self as maintainer for aws-ebs-csi-driver

- config/kubernetes/org.yaml
/hold
Wait for https://github.com/kubernetes/security/pull/124 to merge.
> Promote Tabitha to full PSC member

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2585
Fixes #2593
Fixes #2608
Fixes #2610
Fixes #2613
cc: @ameukam @palnabarun 
> Add Members 04-05-2021 

- config/kubernetes-sigs/sig-multicluster/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2609
> Add GitHub team for about-api

- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2588
> Add yangjunmyfm192085 to kubernetes

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2632
Fixes https://github.com/kubernetes/org/issues/2630
Fixes https://github.com/kubernetes/org/issues/2629
Fixes https://github.com/kubernetes/org/issues/2628
Fixes https://github.com/kubernetes/org/issues/2627
Fixes https://github.com/kubernetes/org/issues/2622
Fixes https://github.com/kubernetes/org/issues/2617
Fixes https://github.com/kubernetes/org/issues/2615
> Add members 2021-04-14

- config/kubernetes-sigs/org.yaml
Adding @vladimirvivien to Kubernetes-SIG
> Adding Vladimir Vivien as member

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2641
Fixes https://github.com/kubernetes/org/issues/2644
Fixes https://github.com/kubernetes/org/issues/2642
> Add members 2021-04-16

- config/kubernetes-sigs/sig-storage/teams.yaml
Oops :) 
Ref: https://github.com/kubernetes/org/pull/2647#discussion_r614836653
> Fix typo in cosi-driver-minio-maintainers team name

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2653
Fixes https://github.com/kubernetes/org/issues/2651
Fixes https://github.com/kubernetes/org/issues/2650
Fixes https://github.com/kubernetes/org/issues/2648
Fixes https://github.com/kubernetes/org/issues/2605
> Add members 2021-04-22

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2663 
Fixes #2662 
Fixes #2661 
Fixes #2660 
Fixes #2659 
Fixes #2658 
Fixes #2652 
/cc @ameukam @palnabarun
> Add Members 04-27-2021

- config/kubernetes/org.yaml
fixes #2665 
fixes #2668 
fixes #2670 
fixes #2672 
fixes #2673 
fixes #2674 
fixes #2675 
fixes #2676
fixes #2667
> Add members 2021-04-21

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2679
fixes #2680
/assign @savitharaghunathan
> Add members 2021-04-30

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2683
fixes #2685
fixes #2688
> Add Members 2021-05-06

- config/kubernetes/sig-architecture/teams.yaml
/assign @johnbelamaric @dims @derekwaynecarr 
This is so people can @ the team instead of all four of us individually.
> Add PRR team to GitHub teams

- config/kubernetes-sigs/sig-cloud-provider/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2639
> Add GitHub team for provider-aws-test-infra

- config/kubernetes-sigs/org.yaml
Signed-off-by: JunYang <yang.jun22@zte.com.cn>
Adding myself as member for kubernetes-sigs org as discussed with @serathius @dgrisonnet.
> Add yangjunmyfm192085 to kubernetes-sigs org

- config/kubernetes-sigs/org.yaml
I'm [already a member of the main org](https://github.com/kubernetes/org/blob/bd784529c3bd5cdfbfc11dc9b6ae27a4b3561c5c/config/kubernetes/org.yaml#L95), just adding myself to the `kubernetes-sigs` org too.
> Add myself to members list

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2656 
fixes #2689 
fixes #2691 
fixes #2699 
fixes #2702 
fixes #2703 
fixes #2705
> Add Members 2021-05-12

- config/kubernetes-sigs/sig-storage/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2701
> Add GitHub teams for cosi-driver-sample

- config/kubernetes/org.yaml
This PR adds myself as an admin to the [kubectl GitHub repo](https://github.com/kubernetes/kubectl). Requesting this as sig cli co-chair to make issue cleanup easier.
> Add eddiezane to kubectl-admins and prune

- config/kubernetes/sig-release/teams.yaml
Add missing 1.22 RT members to RT group and milestone maintainers list
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @hasheddan
/cc @annajung @divya-mohan0209 @erismaster @kikisdeliveryservice
> Add missing 1.22 RT members to RT group and milestone maintainers list

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2712 
fixes #2717 
fixes #2718 
fixes #2719
> Add members 2021-05-23

- config/kubernetes/sig-instrumentation/teams.yaml
Signed-off-by: JunYang <yang.jun22@zte.com.cn>
I am working on metrics-server now, and also want to work on  WG Structured Logging. 
So I want to join SIG Instrumentation and continue to work on it.
> Add yangjunmyfm192085 to sig-instrumentation team

- OWNERS_ALIASES
- config/kubernetes/wg-structured-logging/OWNERS
- config/kubernetes/wg-structured-logging/teams.yaml
/cc @shubheksha
New WG https://github.com/kubernetes/community/tree/master/wg-structured-logging
Creating team so we organize members and reviewers for structured logging migration.
> Add wg structured logging teams

- config/kubernetes/org.yaml
/assign bowei@
/cc prameshj swetharepakula
> Add prameshj and swetharepakula into ingress-gce maintainer

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2732
Fixes https://github.com/kubernetes/org/issues/2729
Fixes https://github.com/kubernetes/org/issues/2715
> Add members 2021-05-26

- config/kubernetes/wg-structured-logging/teams.yaml
Signed-off-by: JunYang <yang.jun22@zte.com.cn>
> Adding yangjunmyfm192085 to wg structured logging

- config/kubernetes/wg-structured-logging/teams.yaml
The PR adds `Priyankasaggu11929` as a member under the `wg-structured-logging`.
---
Signed-off-by: Priyanka Saggu <priyankasaggu11929@gmail.com>
> add Priyankasaggu11929 to wg-structured-logging

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
fixes #2704 
fixes #2735 
fixes #2736 
fixes #2740
> Add Members 2021-05-28

- config/kubernetes/wg-structured-logging/teams.yaml
> Add WG stuctured logging leads to members and reviewers

- config/kubernetes/wg-structured-logging/teams.yaml
This PR adds `MadhavJivrajani` to the wg-structured-logging members list
> Add MadhavJivrajani to structured logging members list

- config/kubernetes/wg-structured-logging/teams.yaml
> Add navidshaikh to wg structured logging

- config/kubernetes/wg-structured-logging/teams.yaml
I would like to be an reviewer for structured logging
/cc @serathius @shubheksha
> Add yuzhiquan to wg structured logging

- config/kubernetes/org.yaml
Adding myself as ingress-nginx admin to create the branch necessary for v1 migration.
> Add myself as ingress-nginx admin

- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
Fixes https://github.com/kubernetes/org/issues/2754
Fixes https://github.com/kubernetes/org/issues/2752
> Add members 2021-06-03

- config/kubernetes-sigs/org.yaml
- config/kubernetes-sigs/sig-windows/teams.yaml
Ref: https://github.com/kubernetes/org/issues/2721
/assign @sladyn98
> Add GitHub team for sig-windows-dev-tools

- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes https://github.com/kubernetes/org/issues/2761
Fixes https://github.com/kubernetes/org/issues/2760
Fixes https://github.com/kubernetes/org/issues/2756
Fixes https://github.com/kubernetes/org/issues/2755
Fixes https://github.com/kubernetes/org/issues/2751
> Add members 2021-06-04

- config/kubernetes-sigs/sig-cli/teams.yaml
See https://github.com/kubernetes-sigs/kustomize/blob/master/OWNERS_ALIASES
> Update kustomize teams to match in-repo lists.

- OWNERS_ALIASES
Replace inactive owners in provider-aws
> Replace inactive owners

- config/kubernetes-sigs/org.yaml
https://github.com/kubernetes/org/issues/2771
> add pacoxu to kubernetes-sigs org

- config/kubernetes-sigs/sig-storage/teams.yaml
The repo is being archived: https://github.com/kubernetes/org/issues/2687
> Remove cosi-driver-minio GitHub teams

- config/kubernetes-client/org.yaml
- config/kubernetes-csi/org.yaml
- config/kubernetes-sigs/org.yaml
- config/kubernetes/org.yaml
Fixes #2763 
Fixes #2768 
Fixes #2770 
Fixes #2774 
Fixes #2775 
Fixes #2776 
/cc @ameukam @palnabarun
> Add Members 06-14-2021 
